"""
OPA Policy Generator -- konwertuje reguły z DuckDB na poprawne Rego policies dla OPA.

Zgodnie z aa3fvcx.txt:
- OPA (Open Policy Agent) jako deklaratywny silnik reguł (CNCF)
- DuckDB jako RuleStore (trwały magazyn parametrów i definicji reguł)

Architektura:
  DuckDB (RuleStore) -> Policy Generator -> Rego Policy -> OPA -> Verdict

Poprawna składnia Rego:
  - decide = <value> { <condition> }  -- kompletna reguła
  - Brak łańcuchowania .field = value po zamknięciu nawiasu
  - OR przez wiele reguł z tą samą głową (nie przez ;)
  - Pierwsza pasująca reguła (first-match-wins) przez else chain

Usage:
    generator = OpaPolicyGenerator()
    rego_code = generator.generate_policy(rules_from_duckdb)
    data = generator.generate_data(rules_from_duckdb)
"""

from __future__ import annotations

import json
import re
from datetime import UTC
from typing import Any

from structlog import get_logger

logger = get_logger("nexus.opa.policy_generator")


class OpaPolicyGenerator:
    """Generates poprawne Rego policies z DuckDB tax rules.

    Konwertuje temporalne reguły podatkowe z DuckDB na:
    1. Rego policy (kod źródłowy) -- poprawna składnia Rego z else chain
    2. OPA data document (JSON) -- konkretne reguły jako data.tax.rules

    First-match-wins: else chain w Rego zapewnia deterministyczne
    dopasowanie pierwszej reguły według priorytetu.
    """
    __slots__ = ()


    @staticmethod
    def generate_policy(
        rules: list[dict[str, Any]],
        *,
        package: str = "tax.rules",
        include_comments: bool = True,
    ) -> str:
        """Generate a complete Rego policy from DuckDB rules.

        Używa else chain dla first-match-wins według priorytetu.
        Zgodnie ze składnią Rego:
          - decide = <value> { <cond> }
          - else = <value> { <cond> }  (brak nowej linii między else a poprzednim })

        Args:
            rules: List of rule dicts from DuckDB.
            package: Rego package name.
            include_comments: Whether to include detailed comments.

        Returns:
            Complete Rego source code ready to load into OPA.
        """
        from datetime import datetime

        timestamp = datetime.now(UTC).isoformat()
        rule_count = len(rules)
        rule_sets = sorted(
            set(r.get("rule_set_id", "") for r in rules if r.get("rule_set_id"))
        ) or ["default"]

        lines: list[str] = []

        lines.append(f"package {package}")
        lines.append("")

        if include_comments:
            lines.append(f"# Auto-generated by OpaPolicyGenerator at {timestamp}")
            lines.append(f"# Rules: {rule_count}, Sets: {', '.join(rule_sets)}")
            lines.append("")

        # Default: no match
        lines.append('default decide = {"matched": false, "error": "NO_MATCHING_RULE"}')
        lines.append("")

        # Group rules by priority, then generate else chain
        priorities = sorted(set(r.get("priority", 100) for r in rules))

        # Build the else-chain as one continuous logical rule
        # W Rego, else musi być bezpośrednio po } poprzedniej reguły (bez nowej linii)
        chain_parts: list[str] = []

        for pi, priority in enumerate(priorities):
            priority_rules = [r for r in rules if r.get("priority", 100) == priority]

            for ri, rule in enumerate(priority_rules):
                rule_id = rule.get("rule_id", "unknown")
                condition_sql = rule.get("condition_sql", "true")
                action = OpaPolicyGenerator._parse_action(rule.get("action_json", "{}"))

                # Build Rego condition
                rego_condition = OpaPolicyGenerator._sql_to_rego(condition_sql)

                # Build verdict dict literals
                vat_rate = action.get("vat_rate", "0.23")
                rounding = action.get("rounding_level", "position")
                income_tax = action.get("income_tax_qualification", "deductible_full")
                gtu_code = action.get("gtu_code")
                procedure = action.get("procedure", "")
                routing = action.get("_routing", "")
                routing_reason = action.get("_routing_reason", "")

                # Build the verdict as a proper Rego object
                verdict_parts = [
                    '"matched": true',
                    f'"rule_id": "{rule_id}"',
                    f'"priority": {priority}',
                    f'"vat_rate": "{vat_rate}"',
                    f'"rounding_level": "{rounding}"',
                    f'"income_tax_qualification": "{income_tax}"',
                ]
                if gtu_code:
                    verdict_parts.append(f'"gtu_code": "{gtu_code}"')
                if procedure:
                    verdict_parts.append(f'"procedure": "{procedure}"')
                if routing:
                    verdict_parts.append(f'"_routing": "{routing}"')
                if routing_reason:
                    escaped = routing_reason.replace('"', '\\"')
                    verdict_parts.append(f'"_routing_reason": "{escaped}"')

                verdict_body = ",\n        ".join(verdict_parts)
                condition_line = f"    {rego_condition}" if rego_condition != "true" else "    true"

                is_first = pi == 0 and ri == 0

                if is_first:
                    # First rule in chain: decide = <value> { <condition> }
                    chain_parts.append(
                        f"decide = {{\n        {verdict_body}\n    }} {{\n        {condition_line}\n    }}"
                    )
                else:
                    # Subsequent rules: else = <value> { <condition> }
                    # BRAK nowej linii przed else -- musi być bezpośrednio po }
                    chain_parts.append(
                        f"else = {{\n        {verdict_body}\n    }} {{\n        {condition_line}\n    }}"
                    )

        # Połącz cały else-chain bez newline między kolejnymi regułami
        # w Rego, else = kontynuuje poprzednią regułę (nie może być przerwy)
        if chain_parts:
            # Pierwsza reguła to decide = ...
            # Potem każda kolejna to else = ... na końcu poprzedniej
            full_chain = chain_parts[0]
            for part in chain_parts[1:]:
                full_chain += " " + part
            lines.append(full_chain)

        lines.append("")
        return "\n".join(lines)

    @staticmethod
    def generate_data(rules: list[dict[str, Any]]) -> dict[str, Any]:
        """Generate OPA data document from DuckDB rules.

        Args:
            rules: List of rule dicts from DuckDB.

        Returns:
            Dict ready for OPA data API:
            {"rules": {"list": [...], "count": N, "sets": [...]}}
        """
        rule_list: list[dict[str, Any]] = []
        for rule in rules:
            action = OpaPolicyGenerator._parse_action(rule.get("action_json", "{}"))
            entry: dict[str, Any] = {
                "rule_id": rule.get("rule_id", ""),
                "condition": rule.get("condition_sql", "true"),
                "action": action,
                "priority": rule.get("priority", 100),
                "valid_from": str(rule.get("valid_from", "")),
            }
            vt = rule.get("valid_to")
            if vt is not None:
                entry["valid_to"] = str(vt)
            rule_set = rule.get("rule_set_id", "")
            if rule_set:
                entry["rule_set_id"] = rule_set
            rule_list.append(entry)

        rule_sets = sorted(set(r.get("rule_set_id", "") for r in rules if r.get("rule_set_id")))

        return {
            "rules": {
                "list": rule_list,
                "count": len(rule_list),
                "sets": rule_sets,
            },
        }

    @staticmethod
    def _parse_action(action_json: str | dict[str, Any]) -> dict[str, Any]:
        """Parse action JSON from rule store."""
        if isinstance(action_json, dict):
            return action_json
        try:
            return json.loads(action_json)
        except (json.JSONDecodeError, TypeError):
            logger.warning("[OPA-POLICY] Failed to parse action_json: %s", str(action_json)[:100])
            return {"vat_rate": "0.23", "rounding_level": "position"}

    @staticmethod
    def _sql_to_rego(sql: str) -> str:
        """Convert SQL condition to Rego expression.

        Poprawna konwersja:
          - AND -> , (Rego conjunction)
          - OR -> ; (Rego soft OR -- działa jako OR w ciele reguły)
          - = -> ==
          - IN -> array membership with in keyword
          - IS NULL -> not has()/not object.keys()
          - IS NOT NULL -> has()/object.keys()
          - 'value' -> "value"

        Args:
            sql: SQL condition string.

        Returns:
            Rego-compatible expression string.
        """
        expr = sql.strip()

        # Empty or always-true conditions
        if not expr or expr.lower() == "true" or expr == "1=1":
            return "true"

        # Split on OR first (these become separate rule bodies)
        # For Rego, OR is expressed by multiple rules with same head,
        # but we can also use ; within a rule body for soft OR

        # Handle IN clauses first: "field IN ('a', 'b')"
        # Convert to: input.field == "a"; input.field == "b" (OR)
        def _replace_in(m: re.Match) -> str:
            field = m.group(1).strip()
            values_str = m.group(2)
            values = [v.strip().strip("'\"") for v in values_str.split(",")]
            # IN becomes multiple == conditions joined by ;
            alternatives = [f'{_field_ref(field)} == "{v}"' for v in values]
            return "; ".join(alternatives)

        expr = re.sub(
            r"(\w+(?:\.\w+)?)\s+IN\s*\(([^)]+)\)",
            _replace_in,
            expr,
            flags=re.IGNORECASE,
        )

        # Handle NOT IN: "field NOT IN ('a', 'b')"
        def _replace_not_in(m: re.Match) -> str:
            field = m.group(1).strip()
            values_str = m.group(2)
            values = [v.strip().strip("'\"") for v in values_str.split(",")]
            # NOT IN becomes multiple != conditions joined by ;
            alternatives = [f'{_field_ref(field)} != "{v}"' for v in values]
            return "; ".join(alternatives)

        expr = re.sub(
            r"(\w+(?:\.\w+)?)\s+NOT\s+IN\s*\(([^)]+)\)",
            _replace_not_in,
            expr,
            flags=re.IGNORECASE,
        )

        # Handle IS NULL
        expr = re.sub(
            r"(\w+(?:\.\w+)?)\s+IS\s+NULL",
            r"not has(\1)",
            expr,
            flags=re.IGNORECASE,
        )

        # Handle IS NOT NULL
        expr = re.sub(
            r"(\w+(?:\.\w+)?)\s+IS\s+NOT\s+NULL",
            r"has(\1)",
            expr,
            flags=re.IGNORECASE,
        )

        # Handle LIKE: 'value%' -> startswith, '%value' -> endswith, '%value%' -> contains
        expr = re.sub(
            r"(\w+)\s+LIKE\s+'([^']*)%'",
            lambda m: f'startswith({_field_ref(m.group(1))}, "{m.group(2)}")',
            expr,
            flags=re.IGNORECASE,
        )
        expr = re.sub(
            r"(\w+)\s+LIKE\s+'%([^']*)'",
            lambda m: f'endswith({_field_ref(m.group(1))}, "{m.group(2)}")',
            expr,
            flags=re.IGNORECASE,
        )
        expr = re.sub(
            r"(\w+)\s+LIKE\s+'%([^']*)%'",
            lambda m: f'contains({_field_ref(m.group(1))}, "{m.group(2)}")',
            expr,
            flags=re.IGNORECASE,
        )

        # Replace field references in comparisons: field = 'value'
        # Only replace standalone words, not strings or keywords
        def _replace_field_ref(m: re.Match) -> str:
            word = m.group(1)
            if word.upper() in (
                "AND",
                "OR",
                "NOT",
                "IN",
                "IS",
                "NULL",
                "TRUE",
                "FALSE",
                "LIKE",
                "BETWEEN",
                "HAS",
            ):
                return word
            return _field_ref(word)

        # Replace field names before operators
        expr = re.sub(
            r'(?<![".\w])(\w+)(?=\s*(?:==?|!=|<[=>]?|>[=]?)\s*(?:"(?:[^"\\]|\\.)*"|\'(?:[^\'\\]|\\.)*\'|[\d.]+))',
            _replace_field_ref,
            expr,
        )

        # Replace = with == (for Rego comparison), but not <=, >=, !=
        expr = re.sub(r"(?<![!<>])=(?!=)", " == ", expr)

        # Replace AND with , (Rego conjunction in rule body)
        # But don't replace AND inside strings
        expr = re.sub(r"\s+AND\s+", ", ", expr, flags=re.IGNORECASE)

        # Replace OR with ; (Rego soft disjunction)
        expr = re.sub(r"\s+OR\s+", "; ", expr, flags=re.IGNORECASE)

        # Replace SQL string delimiters: 'value' -> "value"
        expr = re.sub(r"'([^']*)'", r'"\1"', expr)

        # Clean up extra spaces
        expr = re.sub(r"\s+", " ", expr).strip()

        return expr


def _field_ref(field: str) -> str:
    """Convert a field name to a Rego input reference."""
    if field.startswith("input.") or field.startswith("data."):
        return field
    if field.upper() in ("TRUE", "FALSE", "NULL", "HAS"):
        return field.lower()
    return f"input.{field}"
