# ═══════════════════════════════════════════════════════════════════════════════
# nexus_crypto — Python type stubs (.pyi)
# ═══════════════════════════════════════════════════════════════════════════════
#
# Manual type stubs for the nexus_crypto package (Rust + PyO3 bridge).
# These stubs provide full type information for mypy and IDE autocomplete,
# eliminating the need for ``type: ignore[import-untyped]`` comments.
#
# ═══════════════════════════════════════════════════════════════════════════════

from __future__ import annotations

from typing import Any

# ── Custom exceptions ───────────────────────────────────────────────────────

class CryptoError(Exception):
    """Base exception for all nexus-crypto errors."""
class KeyLengthError(CryptoError):
    """Raised when key is not exactly 32 bytes."""
class DecryptionError(CryptoError):
    """Raised when decryption fails."""
class EncryptionError(CryptoError):
    """Raised when encryption fails."""
class IntegrityError(CryptoError):
    """Raised when AEAD integrity verification fails."""
class HashError(CryptoError):
    """Raised when a hashing operation fails."""

# ── Sha256Hasher (Rust-native when available) ────────────────────────────────

class Sha256Hasher:
    """Streaming SHA-256 hasher (Rust-native + Python fallback)."""
    def __init__(self) -> None: ...
    def update(self, data: bytes) -> None: ...
    def hexdigest(self) -> str: ...
    def digest(self) -> bytes: ...
    def copy(self) -> Sha256Hasher: ...

# ── Crypto primitives ───────────────────────────────────────────────────────

def encrypt(key: bytes, plaintext: bytes) -> bytes: ...
def decrypt(key: bytes, data: bytes) -> bytes: ...
def hash_password(password: str) -> str: ...
def verify_password(password: str, hash_str: str) -> bool: ...
def sha256(data: bytes) -> str: ...
def hmac_sha256(key: bytes, data: bytes) -> bytes: ...
def blake2b(data: bytes, digest_size: int = 64) -> bytes: ...
def generate_key() -> bytes: ...
def derive_key(password: str, salt: bytes | None = None) -> tuple[bytes, bytes]: ...

# ── Tax Math Engine (Rust-native when available) ────────────────────────────

def to_grosze(amount: str) -> int: ...
def to_zlotowki(grosze: int) -> str: ...
def multiply_net_by_vat(net_grosze: int, vat_rate: str) -> int: ...
def add_tax(net_grosze: int, vat_grosze: int) -> int: ...
def calculate_vat_by_policy(positions: list, vat_rate: str, rounding_level: str) -> int: ...
def validate_invariants(positions: list, summary: Any) -> Any: ...

class InvoicePositions:
    """A single invoice line item in grosze."""
    net_grosze: int
    vat_rate: str
    def __init__(self, net_grosze: int, vat_rate: str) -> None: ...
    def vat_grosze(self) -> int: ...
    def __repr__(self) -> str: ...

class InvoiceSummary:
    """Invoice totals in grosze."""
    netto_grosze: int
    vat_grosze: int
    brutto_grosze: int
    def __init__(self, netto_grosze: int, vat_grosze: int, brutto_grosze: int) -> None: ...
    def __repr__(self) -> str: ...

class ValidationResult:
    """Result of invariant validation."""
    is_valid: bool
    error_message: str
    def __init__(self, is_valid: bool, error_message: str = "") -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class RoundingPolicy:
    """Rounding strategy constants and logic."""
    POSITION: str = "position"
    TOTAL: str = "total"
    @staticmethod
    def calculate(positions: list, vat_rate: str, rounding_level: str) -> int: ...

class TaxMathEngine:
    """Infallible tax math — integer-only, ROUND_HALF_UP, no floats."""
    @staticmethod
    def to_grosze(amount: str) -> int: ...
    @staticmethod
    def to_zlotowki(grosze: int) -> str: ...
    @staticmethod
    def multiply_net_by_vat(net_grosze: int, vat_rate: str) -> int: ...
    @staticmethod
    def add_tax(net_grosze: int, vat_grosze: int) -> int: ...
    @staticmethod
    def calculate_vat_by_policy(positions: list, vat_rate: str, rounding_level: str) -> int: ...
    @staticmethod
    def validate_invariants(positions: list, summary: Any) -> Any: ...

# ── JWT verification (Rust-native when available) ────────────────────────────

def verify_jwt(
    token: str,
    secret: str,
    required_issuer: str | None = None,
    required_audience: str | None = None,
) -> dict | None: ...
def decode_jwt_header(token: str) -> dict | None: ...


