# ═══════════════════════════════════════════════════════════════════════════════
# nexus_crypto._core — Native Rust module type stubs (.pyi)
# ═══════════════════════════════════════════════════════════════════════════════
#
# Type stubs for the native Rust+PyO3 module (nexus_crypto._core).
# These provide type information for direct imports from the native layer.
#
# ═══════════════════════════════════════════════════════════════════════════════

from __future__ import annotations

from typing import Any

# ── Custom exceptions (PyO3 native) ─────────────────────────────────────────

class CryptoError(Exception): ...
class KeyLengthError(CryptoError): ...
class DecryptionError(CryptoError): ...
class EncryptionError(CryptoError): ...
class IntegrityError(CryptoError): ...
class HashError(CryptoError): ...

# ── Crypto primitives ───────────────────────────────────────────────────────

def encrypt(key: bytes, plaintext: bytes) -> bytes: ...
def decrypt(key: bytes, data: bytes) -> bytes: ...
def hash_password(password: str) -> str: ...
def verify_password(password: str, hash_str: str) -> bool: ...
def sha256(data: bytes) -> str: ...
def hmac_sha256(key: bytes, data: bytes) -> bytes: ...
def blake2b(data: bytes, digest_size: int = 64) -> bytes: ...
def generate_key() -> bytes: ...
def derive_key(password: str, salt: bytes | None = None) -> tuple[bytes, bytes]: ...

class Sha256Hasher:
    def __init__(self) -> None: ...
    def update(self, data: bytes) -> None: ...
    def hexdigest(self) -> str: ...
    def digest(self) -> bytes: ...
    def copy(self) -> Sha256Hasher: ...

# ── Tax Math Engine (Rust native) ───────────────────────────────────────────

def parse_rate(rate_str: str) -> str: ...
def to_grosze(amount: str) -> int: ...
def to_zlotowki(grosze: int) -> str: ...
def multiply_net_by_vat(net_grosze: int, vat_rate: str) -> int: ...
def add_tax(net_grosze: int, vat_grosze: int) -> int: ...
def calculate_vat_by_policy(positions: list, vat_rate: str, rounding_level: str) -> int: ...
def validate_invariants(positions: list, summary: Any) -> Any: ...

class Money:
    amount_cents: int
    currency: str
    def __init__(self, amount_cents: int, currency: str = "PLN") -> None: ...
    def amount(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __add__(self, other: Money) -> Money: ...
    def __sub__(self, other: Money) -> Money: ...
    def __eq__(self, other: object) -> bool: ...
    @staticmethod
    def zero(currency: str = "PLN") -> Money: ...

class InvoicePositions:
    net_grosze: int
    vat_rate: str
    def __init__(self, net_grosze: int, vat_rate: str) -> None: ...
    def vat_grosze(self) -> int: ...
    def __repr__(self) -> str: ...

class InvoiceSummary:
    netto_grosze: int
    vat_grosze: int
    brutto_grosze: int
    def __init__(self, netto_grosze: int, vat_grosze: int, brutto_grosze: int) -> None: ...
    def __repr__(self) -> str: ...

class ValidationResult:
    is_valid: bool
    error_message: str
    def __init__(self, is_valid: bool, error_message: str = "") -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class TaxMathEngine:
    @staticmethod
    def parse_rate(rate_str: str) -> str: ...
    @staticmethod
    def to_grosze(amount: str) -> int: ...
    @staticmethod
    def to_zlotowki(grosze: int) -> str: ...
    @staticmethod
    def multiply_net_by_vat(net_grosze: int, vat_rate: str) -> int: ...
    @staticmethod
    def add_tax(net_grosze: int, vat_grosze: int) -> int: ...
    @staticmethod
    def calculate_vat_by_policy(positions: list, vat_rate: str, rounding_level: str) -> int: ...
    @staticmethod
    def validate_invariants(positions: list, summary: Any) -> Any: ...

# ── JWT verification (Rust native) ──────────────────────────────────────────

def verify_jwt(
    token: str,
    secret: str,
    required_issuer: str | None = None,
    required_audience: str | None = None,
) -> dict | None: ...
def decode_jwt_header(token: str) -> dict | None: ...
