# -*- coding: utf-8 -*-
"""Parts P53-P60: repair wave 2 — temporal, KSeF, ZUS, VAT/PIT details, data ingest, observability, security, docs."""
PARTS = [

dict(code="P53", slug="TEMPORALNOSC_DOMKNIECIE", title="TEMPORALNOŚĆ NA GRANICACH — DAY-0 NOWELIZACJI I TIME-TRAVEL BEZ WĄTPLIWOŚCI",
role="specjalistą od wersjonowania prawa w czasie (retroactivity, przejścia nowelizacji) w systemach policy-as-code",
expertise="okna temporalne, przełączenia day-0, time-travel replays, dane historyczne, kursy, limity roczne",
mission=[
"Zweryfikuj temporalność end-to-end: które reguły/parametry mają okna (valid_from/valid_to), które przy przełączeniu day-0 (nowela wchodzi 1.01) mają testy graniczne (31.12 stare / 1.01 nowe), czy time-travel (replay decyzji historycznych) odtwarza STAN PRAWA z daty zdarzenia (reguły + parametry + kursy + limity narastające) czy tylko parametry. Luka temporalna = błędna deklaracja za przeszły okres — jedyna kategoria błędów, która nie naprawia się sama przy nowej wersji (stare deklaracje zostają błędne).",
"Wygeneruj rejestr granic: wszystkie daty przełączeń (nowelizacje w KALENDARZ_ZMIAN_PRAWNYCH + daty w thresholds_data) z testami day-1/day-0/day+1 i generatorem automatycznym. Zaprojektuj formalny kontrakt time-travel: „deklaracja z dnia D replikowana grosz w grosz” jako test w CI na próbie danych historycznych. Przeprować głęboką analizę: które przepisy mają zasady przejściowe (prawa nabyte, okresy przejściowe) i czy silnik je modeluje (często pomijane!).",
],
subparts=[
dict(name="Mapa okien temporalnych",
goal="które reguły/parametry mają/potrzebują okien",
questions=[
"Które reguły zależne od daty NIE mają okien (valid_from/valid_to) — lista z powodem (stale? zawsze-aktualne?)?",
"Które parametry w thresholds_data mają okna, a które (stawki roczne!) nie — luka P46/P05?",
"Które okna nachodzą na siebie albo mają dziury (przerwa między valid_to starej i valid_from nowej)?",
"Które reguły mają zakodowane daty w warunkach (hardcode dat = luka P46) zamiast okien parametrów?",
]),
dict(name="Przełączenia day-0",
goal="granice nowelizacji przetestowane",
questions=[
"Które przełączenia (KALENDARZ_ZMIAN_PRAWNYCH) mają testy day-1/day-0/day+1 — a które nie?",
"Czy generator (P36) tworzy testy przełączeń automatycznie z okien parametrów (bez ręcznej pracy)?",
"Czy testy sprawdzą też KONIEC obowiązywania (akt wygasł → NEEDS_ADVICE, nie stare zasady)?",
"Czy limity narastające (zwolnienie 200k) mają testy przejścia roku (licznik resetuje się 1.01 — zgodnie z prawem)?",
]),
dict(name="Time-travel i prawa nabyte",
goal="replay przeszłości grosz w grosz",
questions=[
"Czy replay deklaracji historycznej odtwarza: reguły (bundle version), parametry (historia), kursy (data), limit narastający (stan na datę)?",
"Czy bundle historyczne są dostępne (WORM P42) i testowane w replay (restore + eval)?",
"Które przepisy mają zasady przejściowe (prawa nabyte: mały ZUS+ kontynuacja, preferencyjny start) i czy silnik je modeluje?",
"Czy test time-travel jest w CI (próba danych historycznych co PR/nightly) czy tylko ręczny?",
]),
dict(name="Ścieżki temporalne awaryjne",
goal="prawo zmienia się w toku pracy",
questions=[
"Co z decyzjami w toku przy wejściu noweli w połowie miesiąca (input na 31.12, decyzja 2.01) — która wersja prawa?",
"Czy są reguły „przełączonej epoki” (input date → routing do właściwej wersji pakietu) — czy routing P02 jest temporalny?",
"Czy Law Radar (P08) wyzwala przygotowanie nowej wersji PRZED datą wejścia (pre-provisioning), nie po?",
"Czy istnieje tryb „prawo przyszłe” (symulacja na noweli przed wejściem — planowanie, wyraźnie oznaczony)?",
]),
],
file_groups=[
dict(name="Dane temporalne i kontrola", files=[
    ("Progi i stawki (dane z oknami)", "JDG/bundles/thresholds_data.json"),
    ("Kalendarz zmian prawnych", "JDG/docs/KALENDARZ_ZMIAN_PRAWNYCH.md"),
    ("Test kontrol temporalnych", "JDG/tests/test_core_guards_temporal_thresholds.py"),
    ("Dokument kontrol temporalnych", "JDG/docs/CORE_GUARDS_TEMPORAL_THRESHOLDS.md"),
    ("Detektor dryfu temporalnego", "JDG/tools/temporal_drift_detector.py"),
    ("Brama interwałów temporalnych", "JDG/tools/temporal_interval_gate.py"),
    ("Test temporal validity", "JDG/tests/test_temporal_validity.py"),
    ("Test temporal manager", "JDG/tests/test_temporal_manager.py"),
]),
dict(name="Time-travel i replay", files=[
    ("Złote orzeczenia", "JDG/bundles/golden_verdicts.json"),
    ("Test infrastruktury control plane", "JDG/tests/test_control_plane_infrastructure.py"),
    ("Rejestr wdrożeń (historia bundle)", "JDG/bundles/deployments.json"),
    ("WORM storage", "JDG/tools/worm_storage.py"),
    ("Zrzuty DR (katalog)", "JDG/bundles/dr_snapshots"),
    ("Test native lifecycle manager", "JDG/tests/rego/test_native_lifecycle_manager_enterprise.rego"),
]),
dict(name="Domeny temporalne krytyczne", files=[
    ("Test natywny micro ZUS (ulgi roczne)", "JDG/tests/rego/micro/test_native_micro_zus.rego"),
    ("Test natywny ryczałt micro (stawki)", "JDG/tests/rego/micro/test_native_micro_ryczalt.rego"),
    ("Test natywny PCC v3", "JDG/tests/rego/test_native_pcc_v3_10.rego"),
    ("Test tax rules", "JDG/tests/test_tax_rules.py"),
    ("Silnik stawek VAT", "JDG/tools/vat_rate_engine.py"),
    ("Śledzacz okresów preferencyjnych", "JDG/tools/preferential_period_tracker.py"),
]),
],
legal=[
"Ordynacja podatkowa — art. 24b (prawo właściwe w czasie: tekst na datę powstania obowiązku podatkowego).",
"Ordynacja podatkowa — art. 24c (zasady przejściowe nowelizacji obowiązków podatkowych).",
"Ustawa VAT — art. 109e ust. 4 (ewidencja podatkowa): poprawność na datę zdarzenia gospodarczego.",
"Ustawa o PIT — art. 9a ust. 3 (zaokrąglenia i kursy na datę zdarzenia), art. 12 ust. 4 (roczne rozliczenie).",
"Ustawa o ZUS — art. 18d ust. 2 (roczna podstawa: limit roczny — reset kalendarzowy), art. 18ab (mały ZUS+ kontynuacja).",
"Ustawa o rachunkowości — art. 5 (porównywalność okresów: replay musi odtwarzać stan na datę).",
"KKS — art. 53 §1 (przedawnienie liczone od daty — wymaga odtworzenia stanu prawnego z daty).",
"Rozporządzenie VAT (kursy, art. 31a) — tabela NBP z konkretną datą jako dane temporalne.",
],
innovations=[
("Temporal coverage gate", "bramka: reguła zależna od daty bez okna (valid_from/valid_to) albo parametr bez okna = BLOCKER przy PR."),
("Day-0 test auto-generation", "generator: z każdego okna parametru automatyczne testy (dzień przed/po/granica) — zero ręcznych testów przełączeń."),
("Retroactive replay contract", "formalny test: deklaracja historyczna replikowana grosz w grosz (reguły+parametry+kursy) — w CI na próbie danych z 3 lat."),
("Transitional rules register", "rejestr zasad przejściowych (prawa nabyte, okresy przejściowe) per nowela — modelowane jawnie w regułach, nie w głowie księgowego."),
("Temporal routing in orchestrator", "routing P02 bierze pod uwagę datę zdarzenia (input) — wybór wersji pakietu temporalny, nie globalny."),
("Gap/overlap interval validator", "walidator okien: dziury i nachodzenia między valid_from/valid_to = BLOCKER (auto-scan w CI)."),
("Future law sandbox", "tryb symulacji noweli przed wejściem (wyraźnie oznaczony DRAFT, bez zapisu decyzji) — planowanie zmian bez ryzyka produkcji."),
("Pre-provisioning by Law Radar", "Law Radar planuje nową wersję reguł/parametrów PRZED datą wejścia (SHADOW z datą aktywacji) — zero pustki po 1.01."),
("Year boundary tests", "limity narastające: testy 31.12/1.01 (reset liczników) per limit roczny — klasa testów automatyczna."),
("Historical parameter store", "historia parametrów jako dane (kto, kiedy, jaka wartość, jaki akt) — replay czyta historię, nie „aktualne dane”."),
("Epoch-aware golden replay", "złote orzeczenia etykietowane epoką prawną (data zdarzenia) — replay wybiera epokę automatycznie."),
("Temporal audit trail", "certyfikat decyzji zawiera wersję epoki prawnej (hash okna) — dowód „jaka wersja prawa obowiązywała przy tej decyzji”."),
],
in_contracts=[
"Kontrakt parametrów z P46 — okna temporalne parametrów jako dane; testy day-0 generowane.",
"Kontrakt deploy z P38 — historia bundle dostępna WORM dla replays historycznych.",
],
out_contracts=[
"REJESTR GRANIC TEMPORALNYCH (przełączenia + testy) — wejście do P68 i P08 (Law Radar harmonogram).",
"Kontrakt time-travel (replay grosz w grosz) — wiąże P10 (golden oracle) i P39 (CI).",
"Rejestr zasad przejściowych — wiąże P26 (ZUS), P18 (ryczałt), P41 (dokumentacja).",
],
acceptance_extra=[
"Mapa okien temporalnych z licznikami (z oknem / bez okna / hardcode dat) per domena.",
"Test time-travel zaprojektowany na konkretnym przypadku historycznym (np. replay deklaracji Q4 2025 grosz w grosz).",
]),
dict(code="P54", slug="KSEF_JPK_DOMKNIECIE", title="KSEF 2.0 I JPK — TERMINY, SCHEMATY I KOLEJKI NA POZIOMIE ENTERPRISE",
role="inżynierem integracji e-dokumentacji podatkowej (KSeF, JPK, e-Deklaracje) z doświadczeniem produkcyjnych integracji MF",
expertise="KSeF 2.0 harmonogram, schematy FA(2)/FA(3), JPK_V7M/T, kolejki idempotentne, offline mode, retry",
mission=[
"Zweryfikuj kompletność ścieżki KSeF/JPK: harmonogram KSeF 2.0 (obowiązki 2026 — duzi potem mali podatnicy), schematy FA(3), walidacja przed wysyłką, kolejki (offline/outbox) z idempotencją, retry przy awariach MF, statusy wysyłki (sesje online/batch), UPO/potwierdzenia, e-Doreczenia. Luka tu = realne kary i błędy w przepływie dokumentów — najwyższa stawka operacyjna fortecy.",
"Zaprojektuj brakujące elementy: walidator schematów XSD (wersjonowany), dry-run wysyłki (sandbox MF), monitoring statusów (sesje, błędy, retry z backoff), kalendarz obowiązków KSeF (terminy per typ podatnika), obsługa korekt faktur w KSeF, synchronizacja z ewidencjami (faktura KSeF → od razu ewidencja VAT/PKPiR przez pipeline P32). Wszystko z terminami zgodnymi z rozporządzeniami (weryfikacja w crd.gov.pl i podatki.gov.pl).",
],
subparts=[
dict(name="Harmonogram i obowiązki KSeF 2.0",
goal="terminy i obowiązki per typ podatnika",
questions=[
"Które daty harmonogramu KSeF 2.0 są w regułach/kalendarzu (duzi/mali, tokeny, PRF) — zweryfikuj w crd.gov.pl?",
"Czy kalendarz (P25) ma pozycje KSeF z terminami i odmiennymi datami per typ podatnika?",
"Czy reguły rozróżniają tryby (online, batch, offline QR) i ich terminy przesyłania?",
"Czy są ścieżki dla faktur konsumenckich (PRF) i korekt — obecne w harmonogramie?",
]),
dict(name="Schematy i walidacja",
goal="faktury walidowane przed wysyłką",
questions=[
"Która wersja schematu FA jest w użyciu i jak wersjonowanie schematów jest zarządzane (koniec FA(2), start FA(3))?",
"Czy walidacja XSD uruchamia się przed wysyłką (offline walidator) i w CI (testy kontraktowe schematów)?",
"Czy błędy walidacji mają czytelne mapowanie na poprawkę (pole → działanie)?",
"Czy JPK_V7M/T generowane są zgodnie z rozporządzeniem (pola, zaokrąglenia, walidatory MF)?",
]),
dict(name="Kolejki, retry i idempotencja",
goal="awarie MF nie gubią faktur",
questions=[
"Czy kolejka offline/outbox ma idempotencję (retry nie duplikuje wysyłki)?",
"Czy retry ma backoff i limit (nie spam MF) oraz ścieżkę eskalacji (człowiek po N próbach)?",
"Czy statusy sesji są monitorowane (P37) z alarmami na zaległości terminowe?",
"Czy przy dłuższej awarii pipeline przechodzi w tryb offline zgodny z przepisami (QR, terminy odraczane)?",
]),
dict(name="KSeF → ewidencje sync",
goal="faktura w KSeF = od razu księgowanie",
questions=[
"Czy faktura zaakceptowana w KSeF automatycznie wchodzi do ewidencji VAT/PKPiR (P32) — bez ręcznej pracy?",
"Czy korekty KSeF korygują ewidencje (bez podwójnego księgowania)?",
"Czy sync ma idempotencję (duplikat webhooka nie duplikuje zapisu)?",
"Czy użytkownik widzi w UI (P40) stan faktury end-to-end (wysłana → przyjęta → zaksięgowana → w JPK)?",
]),
],
file_groups=[
dict(name="Narzędzia KSeF/JPK", files=[
    ("Kolejka offline KSeF", "JDG/tools/ksef_offline_queue.py"),
    ("Outbox KSeF", "JDG/tools/ksef_outbox.py"),
    ("Generator KSeF (test)", "JDG/tests/test_ksef_generator.py"),
    ("Generator JPK", "JDG/tools/jpk_generator.py"),
    ("Walidator JPK", "JDG/tools/jpk_validator.py"),
    ("Auto-gen JPK", "JDG/tools/jpk_autogen.py"),
    ("Auditor KSeF/JPK", "JDG/tools/ksef_jpk_edeklaracje_auditor.py"),
    ("Bramka KSeF v3", "JDG/tools/ksef_jpk_v3_gate.py"),
]),
dict(name="Testy KSeF/JPK", files=[
    ("Test KSeF generator", "JDG/tests/test_ksef_generator.py"),
    ("Test KSeF/JPK v3", "JDG/tests/test_ksef_jpk_v3_11.py"),
    ("Test audytu KSeF etap20", "JDG/tests/test_ksef_jpk_etap20_audit.py"),
    ("Test natywny KSeF", "JDG/tests/rego/test_native_ksef.rego"),
    ("Test edelivery gateway", "JDG/tests/rego/test_native_edelivery_gateway_enterprise.rego"),
    ("Test deadline monitor", "JDG/tests/rego/test_native_deadline_monitor_enterprise.rego"),
]),
dict(name="Dokumenty i kontekst prawny", files=[
    ("KSeF/JPK (dokument)", "JDG/docs/KSEF_JPK_EDEKLARACJE_P17.md"),
    ("Kalendarz zmian prawnych", "JDG/docs/KALENDARZ_ZMIAN_PRAWNYCH.md"),
    ("Kalendarz ZUS (tool)", "JDG/tools/zus_calendar.py"),
    ("Dokument automatyzacji", "JDG/docs/AUTOMATYZACJA_KSIEGOWOSCI_P18.md"),
]),
],
legal=[
"Ustawa VAT — art. 106na–106nf (KSeF: obowiązek struktury, terminy przesyłania, tryby) — weryfikacja harmonogramu.",
"Rozporządzenie MF o KSeF (schemat FA(3), tryby offline, sesje) — weryfikacja wersji i dat w crd.gov.pl.",
"Ustawa VAT — art. 99–100s (deklaracje JPK_V7M/T, terminy, korekty) — zgodność pól i terminów.",
"Ustawa VAT — art. 106b ust. 1 pkt 2a (faktury ustrukturyzowane od 2026).",
"Rozporządzenie o JPK_V7 — pola, zaokrąglenia, walidatory (wersjonowanie schematów JPK).",
"Ustawa Ordynacja — art. 128–132 (e-Doreczenia, skutki doręczenia elektronicznego).",
"KKS — art. 57 §2 (błędna faktura JPK w KSeF: ryzyko — walidacja pre-send jako ochrona).",
"Ustawa o ZUS — art. 47–48 (deklaracje składkowe — odrębny kalendarz, spójny w P25).",
],
innovations=[
("KSeF compliance calendar", "automatyczny kalendarz obowiązków KSeF per typ podatnika (duzi/mali, PRF) z alertami terminowymi (spina z P25)."),
("Schema version manager", "zarządzanie wersjami FA(2)/FA(3) i JPK: walidacja XSD w CI, przełączanie wersji na datę (temporalność schematów)."),
("Pre-send dry-run", "każda faktura przechodzi dry-run walidacji (XSD + reguły fortecy) przed wysyłką; błąd = czytelna poprawka dla księgowego."),
("Sandbox replay", "środowisko testowe KSeF (sandbox MF) w CI: ścieżki wysyłki testowane co PR na schematach z mockami MF."),
("Status monitor with SLA", "monitoring sesji: wysłana→przyjęta→UPO z SLA i eskalacją (zaległość terminowa = alarm P0)."),
("Idempotent outbox", "klucz idempotencji (hash faktury + sesja) — retry po awarii nie duplikuje wysyłki; duplikat = wykryty i oznaczony."),
("KSeF-to-books sync", "faktura przyjęta w KSeF automatycznie księgowana (pipeline P32) z idempotencją — zero ręcznego przepisywania."),
("Correction chains", "korekty KSeF (przed/po upływie terminu) z pełną ścieżką: faktura korygująca → ewidencje → JPK — testowana end-to-end."),
("Offline mode compliance", "tryb offline (QR, terminy odraczane) zgodny z rozporządzeniem — ścieżki testowane na awariach (chaos P43)."),
("Error-to-action mapping", "mapowanie błędów MF na czytelne akcje (pole schematu → co poprawić) — księgowy naprawia bez analizy XML."),
("Deadline watchdog", "watchdog: faktura w kolejce >X dni przed terminem → eskalacja (P0 alarm) — zero faktur zgubionych w kolejce."),
("Integration attestation", "certyfikat integracji KSeF: wersje schematów, daty obowiązywania, wyniki sandbox — odświeżany przy zmianie MF."),
],
in_contracts=[
"Kontrakt pipeline z P32 — KSeF ingest jest częścią end-to-end (idempotencja wspólna).",
"Kalendarz z P25 — terminy KSeF w jednym źródle (brak rozjazdu terminów).",
],
out_contracts=[
"Kontrakt integracji KSeF (schematy, tryby, terminy, kolejki) — wiąże P40 (API), P38 (deploy okna) i P68.",
"Monitoring statusów (metryki) — wejście do P37.",
"Mapowanie błędów MF→akcje — wejście do P40 (UI) i P41 (dokumentacja).",
],
acceptance_extra=[
"Kalendarz KSeF 2.0 przedstawiony z datami (zweryfikowanymi) i ścieżkami per typ podatnika.",
"Ścieżka end-to-end faktury (wystawienie→KSeF→ewidencja→JPK) z punktami walidacji i idempotencji — diagram.",
]),
dict(code="P55", slug="ZUS_DOMKNIECIE", title="ZUS DO ZERA — 30-KROTNOŚĆ, ULGI, CHOROBOWE I TERMINY BEZ LUK",
role="inżynierem domen składkowych z głęboką znajomością ustawy o systemie ubezpieczeń społecznych i jej pułapek wyliczeniowych",
expertise="30-krotność, ulgi (start, preferencyjny, mały ZUS+), chorobowe, DRA/RCA, terminy, korekty składek",
mission=[
"Zweryfikuj domenę ZUS end-to-end: podstawa wymiaru (deklarowana, 60% zysku, mały ZUS+), granica 30-krotności (kiedy przekroczona — co ze zdrowotną), ulgi (preferencyjny 24 miesiące, mały ZUS+ warunki i kontynuacja), składka chorobowa (dobrowolna — okresy zasiłkowe!), terminy DRA (10/15), korekty (DRA korygujące), zawieszenie działalności (składki tylko zdrowotna?). Wygeneruj rejestr luk wyliczeniowych z przypadkami testowymi brzegowymi (grosze, daty przejść między ulgami, przekroczenia 30-krotności w połowie roku).",
"Zaprojektuj domknięcie: reguły przejść między ulgami (kiedy przysługuje, kiedy wygasa — z datami), testy graniczne (dzień 24. miesiąca preferencyjnego, warunek przychodu małego ZUS+), chorobowe (okresy zasiłkowe, wstrzymanie działalności a zasiłek), integracja z kalendarzem (terminy DRA) i pipeline'em płatności (P32). Wszystko z pełną temporalnością (stawki roczne, limity roczne — P53).",
],
subparts=[
dict(name="Podstawa wymiaru i 30-krotność",
goal="wyliczenie składki bez wątpliwości",
questions=[
"Które warianty podstawy (deklarowana, 60% zysku, mały ZUS+ 60% prognozy) mają reguły i testy?",
"Czy 30-krotność liczy się narastająco z korektami (korekta wcześniejszego miesiąca może przekroczyć limit)?",
"Co się dzieje przy przekroczeniu 30-krotności (składki społeczne stop → zdrowotna dalej) — reguła i test?",
"Czy przekroczenie limitu w połowie miesiąca dzieli miesiąc (zgodnie z ZUS) — czy to jest obsłużone?",
]),
dict(name="Ulgi i przejścia między nimi",
goal="preferencyjny start, mały ZUS+, wygasanie",
questions=[
"Czy okresy preferencyjnego startu (24 miesiące) mają śledzenie z datami (preferential_period_tracker) i testami końca?",
"Czy mały ZUS+ sprawdza warunki (przychód rok poprzedni, nie generuje więcej) i kontynuację (przy stracie)?",
"Czy przejścia między ulgami (koniec ulgi → pełna podstawa) mają testy day-0 (miesiąc przejścia)?",
"Czy ulgi wygasają automatycznie w silniku (bez cichego liczenia na uldze po wygaśnięciu — fail-closed)?",
]),
dict(name="Chorobowe i zasiłki",
goal="dobrowolna składka i okresy zasiłkowe",
questions=[
"Czy składka chorobowa dobrowolna ma okresy karencji (90 dni) i przerw (wznowienie — nowa karencja)?",
"Czy zasiłek chorobowy wyliczany jest zgodnie (baza, %) i na okresy (obecny zasiłek a zawieszenie)?",
"Czy wstrzymanie/zawieszenie działalności a chorobowe (zasiłek tylko przy pełnym zawieszeniu) jest regułowane?",
"Czy śledzacz trwania choroby (sickness_duration_tracker) respektuje limity (182/270 dni) i testuje granice?",
]),
dict(name="Terminy, DRA i korekty",
goal="składki płatne na czas i korygowane",
questions=[
"Czy terminy DRA (10./15. miesiąca następnego) są w kalendarzu z automatycznym pilnowaniem?",
"Czy DRA korygujące mają ścieżkę (korekta → różnica → odsetki z art. 24 OP?) i testy?",
"Czy płatności ZUS (P32 pipeline) mają priorytet i idempotencję (podwójna płatność wykrywana)?",
"Czy kalendarz ZUS respektuje przeniesienie terminu (święto/weekend — dzień roboczy)?",
]),
],
file_groups=[
dict(name="Narzędzia ZUS", files=[
    ("Kalkulator ZUS", "JDG/tools/zus_calculator.py"),
    ("Kalkulator chorobowy", "JDG/tools/zus_zasilkowa_calculator.py"),
    ("Kalendarz ZUS", "JDG/tools/zus_calendar.py"),
    ("Śledzacz trwania choroby", "JDG/tools/sickness_duration_tracker.py"),
    ("Śledzacz okresów preferencyjnych", "JDG/tools/preferential_period_tracker.py"),
    ("Walidator podstawy składki", "JDG/tools/contribution_base_validator.py"),
    ("Harmonizator health ryczałt-ZUS", "JDG/tools/ryczalt_zus_health_harmonizer.py"),
    ("Silnik tierów zdrowotnej", "JDG/tools/zdrowotna_tier_engine.py"),
]),
dict(name="Testy ZUS", files=[
    ("Test natywny micro ZUS", "JDG/tests/rego/micro/test_native_micro_zus.rego"),
    ("Test audytu ZUS core", "JDG/tests/test_zus_core_etap12_audit.py"),
    ("Test audytu ZUS micro", "JDG/tests/test_zus_micro_etap13_audit.py"),
    ("Test regresji P26", "JDG/tests/p26_regression_test.rego"),
    ("Test macro ZUS", "JDG/tests/test_p08_zus_macro_enterprise.py"),
    ("Test kalendarza ZUS", "JDG/tests/rego/test_native_calendar.rego"),
]),
dict(name="Dokumenty ZUS i linter", files=[
    ("ZUS macro (dokument)", "JDG/docs/ZUS_MACRO_P07.md"),
    ("ZUS micro (dokument)", "JDG/docs/ZUS_MICRO_P08.md"),
    ("Linter atomów ZUS", "JDG/tools/zus_atom_linter.py"),
    ("Silnik kompletności ZUS", "JDG/tools/zus_completeness_engine.py"),
    ("Matryca testów atomów ZUS", "JDG/tools/zus_atom_test_matrix.py"),
    ("Sharding reguł ZUS", "JDG/tools/zus_rule_sharding.py"),
    ("Test natywny lokalnych (kontekst terminów)", "JDG/tests/rego/test_native_local_excise_etap19.rego"),
]),
],
legal=[
"Ustawa o ZUS — art. 12 (dobrowolna chorobowa — ubezpieczenie i karencja 90 dni).",
"Ustawa o ZUS — art. 18a (podstawa: deklarowana, 60% zysku, mały ZUS+), art. 18ab (mały ZUS+ — warunki i kontynuacja).",
"Ustawa o ZUS — art. 18c (preferencyjny start: 24 miesiące, ograniczenia), art. 18d (30-krotność, roczny limit).",
"Ustawa o ZUS — art. 47 (terminy DRA: 10. miesiąca, 15. dla płatników uprzywilejowanych).",
"Ustawa o świadczeniach pieniężnych z ubezpieczenia chorobowego — art. 4 (okresy zasiłkowe 182/270), art. 9 (przerwy).",
"Ustawa o świadczeniach pieniężnych — art. 6 (zasiłek a zawieszenie/wstrzymanie działalności).",
"Ordynacja podatkowa — art. 56 (odsetki od zaległości — kontekst korekt składek).",
"Ustawa o ZUS — art. 50 ust. 2a (zawieszenie działalności: składka zdrowotna — weryfikacja stanu prawnego).",
],
innovations=[
("ZUS lifecycle state machine", "model cyklu: nowy→preferencyjny→mały ZUS+→pełny z datami przejść i egzekwowaniem (silnik ODMOWA pełnej składki na wygasłej uldze — fail-closed)."),
("30-krotność year-to-date engine", "narastające liczniki z korektami w locie: korekta miesiąca może zmienić przekroczenie — engine przelicza kaskadowo z alertem."),
("Mid-month limit split", "obsługa podziału miesiąca przy przekroczeniu limitu (wg ZUS) — klasa przypadków zwykle pomijana, tu egzekwowana testem."),
("Carencia and break tracker", "karencja chorobowa 90 dni + przerwy (wznowienie = nowa karencja) — śledzenie z datami i testami granicznymi."),
("Benefit period counter", "182/270 dni z licznikiem narastającym i testami granicznymi (dzień 182, dzień 183)."),
("DRA deadline watchdog", "terminy DRA w kalendarzu z pilnowaniem i przenoszeniem na dzień roboczy (święta) — automatyczne."),
("DRA correction chain", "korekty DRA z kaskadą (różnica → odsetki → plan płatności) — testowana end-to-end z odsetkami OP art. 56."),
("ZUS payment priority", "składki ZUS z priorytetem w pipeline płatności (P32) — zaległość ZUS blokuje inne automatyczne płatności (bezpieczeństwo prawne)."),
("Sickness-benefit vs suspension", "reguły zasiłek a zawieszenie/wstrzymanie (art. 6 ustawy zasiłkowej) — częsta pustynia prawna, tu domknięta regułą."),
("Annual rate windows", "stawki ZUS (duża/preferencyjna/mała) jako parametry roczne z oknami (P53) — noworoczna zmiana automatyczna z testem day-0."),
("ZUS completeness matrix", "matryca kompletności: warunek ZUS → reguła → test — braki widoczne od razu (narzędzie już jest: zus_atom_test_matrix)."),
("Benefit-eligibility check pre-payment", "przed zaliczką chorobową: weryfikacja uprawnień (karencja, limity, zawieszenie) — payment gate fail-closed."),
],
in_contracts=[
"Kalendarz zbiorczy z P25 — terminy ZUS w jednym źródle z przenoszeniem na dni robocze.",
"Kontrakt temporalności z P53 — stawki/limity roczne z oknami i testami day-0.",
],
out_contracts=[
"REJESTR LUK ZUS (z planami) — wejście do P68.",
"State machine ulg ZUS (model + testy) — wiąże P23 (cykl życia firmy: zawieszenie), P24 (praca/PPK) i P18 (ryczałt harmonizacja).",
"Integracja chorobowe↔płatności — wejście do P32 (pipeline) i P37 (metryki terminowe).",
],
acceptance_extra=[
"Rejestr luk ZUS z przypadkami testowymi brzegowymi (30-krotność mid-month, koniec ulgi, karencja, 182 dni).",
"State machine ulg przedstawiony jako diagram z datami i asercjami fail-closed.",
]),
dict(code="P56", slug="VAT_PIT_SZCZEGOLY", title="VAT I PIT — SZCZEGÓŁY MATERIALNE, KTÓRE DECYDUJĄ O POPRAWNOŚCI",
role="podatnikiem-projektantem reguł z doświadczeniem praktyki KIS, specjalistą od pułapek interpretacyjnych VAT i PIT",
expertise="miejsce świadczenia, GTU/procedury, ryczałt stawki per PKWiU, ulgi PIT (IP Box? ulga na start), klaustule anty-abuzywne",
mission=[
"Zweryfikuj szczegóły materiałne: VAT (miejsce świadczenia art. 28b, tabela GTU, procedury MPP/MOSS, towary wrażliwe, autorów/materiały budowlane z art. 17), PIT (przychody: świadczenia, wartości nieodpłatne; koszty: konkrety art. 22, ulgi: 30c/30f, IP Box, ulga na start/mały ZUS+ interakcje, ryczałt stawki per PKWiU). To poziom szczegółów, gdzie księgowi popełniają błędy codziennie — forteca ma je domknąć regułami z testami.",
"Wygeneruj rejestr szczegółów z kartami: przepis → warunki materiałowe → reguła → test graniczny → interpretacja KIS (jeśli jest — z identyfikatorem). Wskaż pustynie szczegółowe (miejsce świadczenia usług elektronicznych, klauzule ochronne, dotacje) i zaprojektuj domknięcie. Przeprować głęboką analizę interakcji VAT↔PIT (koszt z VAT nieodliczonym, mieszane obroty — proporcje).",
],
subparts=[
dict(name="VAT miejsce świadczenia i cross-border",
goal="art. 28b i powiązane — częsta pustynia",
questions=[
"Czy miejsce świadczenia usług B2B (art. 28b) ma regułę (NIP UE → miejsce kontrahenta) z testami?",
"Czy usługi elektroniczne (art. 28k) i OSS/MOSS mają ścieżki (rejestracja, stawki kontrahenta)?",
"Czy WDT/WNT (art. 42) i swap (art. 42 ust. 10a) mają reguły z testami (progi WDT!)?",
"Czy import usług (art. 28b odwrócone obciążenie) ma ścieżkę z VAT-UE i JPK pól?",
]),
dict(name="VAT GTU, procedury, towary wrażliwe",
goal="tabele specjalne i MPP",
questions=[
"Czy GTU_01–GTU_13 mają klasyfikację regułami (PKWiU → GTU) z testami (zestawy PKWiU zweryfikowane)?",
"Czy procedury (MPP, MPP_B, MPP_U, MPP_PRE, TP, FP, WEW) mają reguły oznaczania pól JPK?",
"Czy towary wrażliwe (materiały budowlane art. 17 ust. 1 pkt 4, złom, elektronika) mają ścieżki MPP obowiązkowego?",
"Czy klasyfikacja PKWiU jest danymi z wersjonowaniem (roczniki PKWiU — temporalność)?",
]),
dict(name="PIT koszty i przychody",
goal="konkrety art. 22 i przychody",
questions=[
"Które kategorie kosztów (art. 22 ust. 1, 2, 3, 5, 9 — reprezentacja! art. 23 wyłączenia) mają reguły?",
"Czy przychody specjalne (nieodpłatne świadczenia art. 14 ust. 2 pkt 8, darowizny otrzymane) mają reguły?",
"Czy zaliczki/rozliczenia międzyokresowe mają ścieżki (koszty okresu — art. 22 ust. 5a)?",
"Czy wynagrodzenia (P24) i dotacje mają ścieżki spójne z pracą i przepływami?",
]),
dict(name="PIT ulgi i interakcje",
goal="ulgi i ich wzajemne relacje",
questions=[
"Czy ulga na start/mały ZUS+ (P55) respektują interakcję z formą opodatkowania (ryczałt a składka zdrowotna)?",
"Czy IP Box (art. 30ca) i ulga B+R (art. 18ea) mają reguły (nawet jako NEEDS_ADVICE z doradcą — fail-closed)?",
"Czy stawki ryczałtu per PKWiU (tabela art. 12) są danymi z wersjonowaniem (P46) i testami per wiersz?",
"Czy interakcje VAT↔PIT (VAT nieodliczony → koszt) mają reguły i testy (mieszane obroty — proporcje art. 90)?",
]),
],
file_groups=[
dict(name="Reguły i narzędzia VAT", files=[
    ("Reguły VAT", "JDG/rules/micro/vat/vat.rego"),
    ("Silnik stawek VAT", "JDG/tools/vat_rate_engine.py"),
    ("Detektor MPP", "JDG/tools/vat_mpp_auto_detector.py"),
    ("Toolkit cross-border", "JDG/tools/p13_crossborder_toolkit.py"),
    ("Heat mapa VAT", "JDG/tools/vat_gap_detector.py"),
    ("Narzędzia innowacji VAT", "JDG/tools/vat_innovation_tools.py"),
    ("Test VAT macro audyt", "JDG/tests/test_vat_macro_audit.py"),
    ("Test VAT micro core audyt", "JDG/tests/test_vat_micro_core_audit.py"),
]),
dict(name="Reguły i narzędzia PIT", files=[
    ("Test PIT macro audyt", "JDG/tests/test_pit_macro_audit.py"),
    ("Test PIT micro ulgi", "JDG/tests/test_pit_micro_reliefs_audit.py"),
    ("Silnik snapshotów temporalnych PIT", "JDG/tools/pit_temporal_snapshot_engine.py"),
    ("Narzędzia innowacji PIT", "JDG/tools/pit_innovation_tools.py"),
    ("Symulator form podatkowych", "JDG/tools/tax_form_whatif_simulator.py"),
    ("Toolkit UoR P12", "JDG/tools/p12_uor_toolkit.py"),
    ("Toolkit UoR księgowość", "JDG/tools/p12_uor_accounting_toolkit.py"),
    ("Dokument PIT macro", "JDG/docs/PIT_MACRO_P05.md"),
]),
dict(name="Dokumenty i testy szczegółów", files=[
    ("Dokument VAT macro", "JDG/docs/VAT_MACRO_P03.md"),
    ("Dokument VAT micro", "JDG/docs/VAT_MICRO_P04.md"),
    ("Dokument PIT micro", "JDG/docs/PIT_MICRO_P06.md"),
    ("Raport audytu VAT", "JDG/docs/VAT_AUDYT_R03.md"),
    ("Raport audytu PIT", "JDG/docs/PIT_AUDYT_R04.md"),
    ("Test PIT enterprise", "JDG/tests/test_p06_pit_macro_enterprise.py"),
    ("Test PIT micro atomic", "JDG/tests/test_p07_pit_micro_atomic.py"),
    ("Test VAT micro atomic", "JDG/tests/test_p05_vat_micro_atomic.py"),
]),
],
legal=[
"Ustawa VAT — art. 28b (miejsce świadczenia B2B), art. 28k (usługi elektroniczne), art. 42 (WDT/WNT, swap).",
"Ustawa VAT — art. 19a ust. 1 pkt 4 (MPP: towary i usługi załącznika 15), art. 109a–109e (GTU, procedury w JPK).",
"Ustawa VAT — art. 17 ust. 1 pkt 4 (materiały budowlane — nabywca płaci), art. 90 (proporcje odliczeń).",
"Ustawa o PIT — art. 14 ust. 2 (przychody: w tym nieodpłatne świadczenia), art. 22 ust. 1–9 (koszty), art. 23 (wyłączenia).",
"Ustawa o PIT — art. 30ca (IP Box), art. 18ea (B+R), art. 30f (ryczałt), art. 9 ust. 1a (UoR).",
"Ustawa o ryczałcie — art. 12 (stawki per PKWiU — tabela jako dane wersjonowane).",
"Ustawa o PIT — art. 45 ust. 3a (proporcja ulg przy mieszanych formach — kontekst).",
"Interpretacje KIS — wskazane w kartach szczegółów (identyfikatory interpretacji jako dowód wykładni).",
],
innovations=[
("Place-of-supply rule pack", "kompletny pakiet reguł art. 28b/28k/42 z testami (kraj, UE, poza UE, elektroniczne) — najczęstsza pustynia VAT domknięta."),
("GTU classification as data", "mapowanie PKWiU→GTU jako dane wersjonowane (roczniki PKWiU) — zmiana tabeli GTU = zmiana danych, nie kodu."),
("Procedure markers engine", "automatyczne oznaczanie pól JPK (MPP/TP/FP/WEW/GTU) na podstawie reguł — zero ręcznego zaznaczania (błąd ludzki wyeliminowany)."),
("KIS interpretation registry", "rejestr interpretacji KIS (identyfikator, data, teza) powiązanych z regułami — wykładnia udokumentowana przy regule."),
("Cost exclusion guard", "reguły art. 23 (wyłączenia: reprezentacja, automobile) z asercją NEEDS_ADVICE przy wątpliwej kategorii — ochrona przed kosztami nieterminowymi."),
("Ryczałt table by PKWiU", "tabela stawek ryczałtu per PKWiU jako dane z oknami rocznymi — test per wiersz tabeli (każda stawka zweryfikowana)."),
("Mixed-sales proportion engine", "proporcje odliczeń VAT (art. 90) z testami granic (obroty zmienne w roku — kwartalne przeliczenia)."),
("Relief interaction matrix", "macierz interakcji ulg (ryczałt↔ZUS↔kwota wolna↔IP Box) z asercjami wzajemnej zgodności — interakcje testowane, nie zakładane."),
("Non-monetary income rules", "reguły przychodów nieodpłatnych (świadczenia, darowizny otrzymane) z wyceną i testami — pustynia PIT domknięta."),
("VAT-non-deductible→cost flow", "przepływ: VAT nieodliczony → koszt podatkowy — spójność VAT↔PIT z testami (mieszane obroty)."),
("Suspicious-pattern advice", "wzorce agresywne (fałszywe faktury, schematy MPP) → NEEDS_ADVICE z podaniem powodu (GAAR art. 119a obrona)."),
("Detail-coverage score VAT/PIT", "wskaźnik pokrycia szczegółów materialnych (karty) per domena — cel 100% dla HIGH-frequency przypadków."),
],
in_contracts=[
"Rejestr pustyni z P51 — szczegóły materialne to główna część pustyni (wspólny rejestr).",
"Kontrakt parametrów z P46 — stawki ryczałtu i tabele GTU jako dane wersjonowane.",
],
out_contracts=[
"Karty szczegółów VAT/PIT (przepis→warunki→reguła→test→interpretacja) — wejście do P41 i P68.",
"GTU/procedure data (PKWiU mapowania) — wiąże P36 (generatory) i P46 (parametry).",
"Macierz interakcji ulg — wiąże P55 (ZUS), P18 (ryczałt) i P14.",
],
acceptance_extra=[
"Karty szczegółów z min. 15 pozycji (miejsce świadczenia, GTU, koszty wyłączone, ulgi interakcje) z testami.",
"Macierz interakcji ulg przedstawiona jako tabela z asercjami wzajemnej zgodności.",
]),
dict(code="P57", slug="INGEST_DANYCH", title="INGEST DANYCH — DOKUMENTY, FAKTY I KOLEJKI BEZ UTRATY I BEZ DUPLIKATÓW",
role="inżynierem danych finansowych (document pipelines), specjalistą od idempotentnych ingestów i normalizacji dokumentów",
expertise="normalizacja inputu, walidacja schematów, deduplikacja, kolejki idempotentne, sląty normalizacyjne, pierwotność dowodów",
mission=[
"Przeanalizuj ścieżkę danych wejściowych: skąd przychodzą dokumenty/fakty (KSeF, e-mail, skan, bank feed, CSV, API), jak są normalizowane, walidowane, deduplikowane i wchodzą do silnika. Wygeneruj rejestr braków: brak walidacji na wejściu (złe typy, ujemne kwoty w nieodpowiednich polach), brak deduplikacji (podwójna faktura = podwójne księgowanie), brak śladu pierwotności (oryginał zapisany? checksuma?), brak ścieżki NEEDS_ADVICE na braki danych.",
"Zaprojektuj kontrakt ingestu: schemat wejściowy (wersjonowany), walidacja na wejściu (fail-closed na złe dane — NIGDY „popraw sobie” bez człowieka), deduplikacja (klucz semantyczny: NIP+data+kwota+numer), ślad pierwotności (oryginał WORM + checksuma), kolejka idempotentna (retry nie duplikuje), statusy (przyjęty→zweryfikowany→zaakceptowany→zaksięgowany). Ingest to granica fortecy: złe dane na wejściu = złe decyzje na wyjściu — walidacja wejścia tak surowa jak walidacja reguł.",
],
subparts=[
dict(name="Kanały i normalizacja",
goal="wszystkie wejścia do jednego formatu",
questions=[
"Które kanały wejściowe są realnie obsługiwane (KSeF, bank, CSV, API) — a które deklarowane bez ścieżki?",
"Czy normalizacja ma schemat (wersjonowany) i walidację typów (kwoty, daty, NIP checksum)?",
"Czy NIPy są walidowane (checksuma NIP) przy ingest — błędny NIP na wejściu = błędna decyzja?",
"Czy kanał bankowy (feed) ma parowanie płatności z fakturami (reconciliation — P32)?",
]),
dict(name="Walidacja wejścia i deduplikacja",
goal="złe dane nie wchodzą",
questions=[
"Czy złe dane (typ, zakres, format) odrzucane są z czytelnym komunikatem (fail-closed, nie „popraw automatycznie”)?",
"Czy deduplikacja działa na klucz semantyczny (NIP+data+kwota+numer) z testami (podwójna faktura)?",
"Czy duplikat jest rejestrowany (rejestr duplikatów do weryfikacji człowieka, nie ciche odrzucenie)?",
"Czy dane wejściowe mają checksumę (integrity) przy zapisie i weryfikację przy odczycie?",
]),
dict(name="Pierwotność i ślad dowodowy",
goal="oryginał zabezpieczony",
questions=[
"Czy oryginał dokumentu (PDF/XML) zapisywany jest WORM (P42) z checksumą przed przetwarzaniem?",
"Czy certyfikat decyzji (P11) odwołuje się do checksumy oryginału (łańcuch dowodów od dokumentu)?",
"Czy eksport dowodowy (P40) zawiera oryginał (odtwarzalność pełna dla kontroli skarbowej)?",
"Czy retencja oryginałów respektuje przepisy (5 lat — P42 retention calculator)?",
]),
dict(name="Kolejki i statusy",
goal="nic nie ginie, nic się nie duplikuje",
questions=[
"Czy kolejka ingestu jest trwała (restart procesu nie gubi dokumentów)?",
"Czy statusy dokumentu (przyjęty→zweryfikowany→zaakceptowany→zaksięgowany) są jawne i w UI (P40)?",
"Czy retry ma idempotencję i limit (spamowanie silnika złymi danymi)?",
"Czy dokument odrzucony ma ścieżkę naprawy (co poprawić, gdzie z powrotem w kolejce)?",
]),
],
file_groups=[
dict(name="Pipeline i agregacja", files=[
    ("Test agregacji faktów (kontrakt)", "JDG/tests/test_facts_aggregator.py"),
    ("Test priorytetów płatności (kontrakt)", "JDG/tests/test_payment_priority_service.py"),
    ("Skanner fraudu grafowego", "JDG/tools/fraud_graph_scanner.py"),
    ("Test silnika ryzyka", "JDG/tests/test_risk_guard.py"),
    ("Test priorytetów (engine)", "JDG/tests/test_priority_engine.py"),
    ("Test strażnika semantycznego", "JDG/tests/test_semantic_guard.py"),
    ("Kolejka offline KSeF", "JDG/tools/ksef_offline_queue.py"),
    ("Outbox KSeF", "JDG/tools/ksef_outbox.py"),
]),
dict(name="Testy ingestu", files=[
    ("Test tax pipeline", "JDG/tests/test_tax_pipeline.py"),
    ("Test fraud graph", "JDG/tests/test_fraud_graph_scanner.py"),
    ("Test KSeF generator", "JDG/tests/test_ksef_generator.py"),
    ("Test facts aggregator (dane)", "JDG/tests/test_facts_aggregator.py"),
    ("Test natywny banking automation", "JDG/tests/rego/test_native_banking_automation_enterprise.rego"),
    ("Test natywny cross-declaration", "JDG/tests/rego/test_native_cross_declaration_validator_enterprise.rego"),
    ("Test risk API", "JDG/tests/test_risk_api.py"),
    ("Test risk guard integration", "JDG/tests/test_risk_guard_integration.py"),
]),
dict(name="Dokumenty pipeline", files=[
    ("Automatyzacja księgowości", "JDG/docs/AUTOMATYZACJA_KSIEGOWOSCI_P18.md"),
    ("Logika biznesowa", "JDG/docs/LOGIKA_BIZNESOWA.md"),
    ("Zgodność dokumenty księgowe", "JDG/docs/ZGODNOSC_DOKUMENTY_KSIEGOWE.md"),
    ("Kontrakt orkiestratora", "JDG/docs/ORCHESTRATOR_DATA_CONTRACT.md"),
    ("Kontrakt danych orkiestratora (test)", "JDG/tests/test_orchestrator_data_contract.py"),
]),
],
legal=[
"Ustawa o rachunkowości — art. 4 ust. 4 (dowody księgowe: rzetelne, prawidłowe, kompletne — ingest to gwarancja).",
"Ustawa o rachunkowości — art. 5 (pierwotne dowody: zapis odzwierciedla rzeczywiste zdarzenie — oryginał + checksuma).",
"Ustawa VAT — art. 106b (faktury: elementy obowiązkowe — walidacja wejścia), art. 109e (ewidencje kompletność).",
"KSeF — schematy FA(3): walidacja struktury przed przyjęciem (ingest KSeF = walidacja schematu).",
"Ustawa o PIT — art. 22 ust. 6b (dokumentacja kosztu: dowody — ingested documents as evidence).",
"Ordynacja podatkowa — art. 193a (weryfikacja: silnik musi móc odtworzyć pierwotne dowody).",
"RODO — art. 5 ust. 1f (integralność i poufność: checksumy, WORM).",
"Ustawa o ZUS — dokumentacja składki (DRA z danych — spójność ingestu).",
],
innovations=[
("Ingest contract schema", "wersjonowany schemat wejścia (typy, zakresy, wymagane pola) walidowany na granicy — zero złych danych w silniku."),
("NIP checksum gate", "walidacja checksumy NIP/NIP-UE na wejściu — błędny identyfikator odrzucany z komunikatem (nie cicha normalizacja)."),
("Semantic dedup key", "deduplikacja na (NIP, data, kwota, numer) z rejestrem duplikatów do przeglądu — podwójna faktura nigdy nie zaksięguje się 2×."),
("Original-first WORM", "oryginał dokumentu zapisany WORM z checksumą PRZED przetwarzaniem — łańcuch dowodów od pierwszego bajta."),
("Status state machine", "jawne statusy (przyjęty→zweryfikowany→zaakceptowany→zaksięgowany→zarchiwizowany) w UI — użytkownik widzi stan każdego dokumentu."),
("Repair path for rejects", "odrzucone dokumenty z czytelną ścieżką naprawy (pole → akcja) i powrotem do kolejki — zero dokumentów zgubionych."),
("Bank reconciliation engine", "parowanie feed bankowy↔faktury z idempotencją (przelew bez faktury → NEEDS_ADVICE z kandydatami)."),
("Ingest chaos suite", "chaos input (złe typy, ujemne kwoty, zduplikowane, braki) — asercja fail-closed na granicy (nic złego nie wchodzi)."),
("Ingest metrics", "metryki: wolumen, odrzucenia (z powodami), duplikaty, czasy przetwarzania — zdrowie ingestu widoczne (P37)."),
("Provenance chain to certificate", "certyfikat decyzji → checksuma oryginału → dokument — pełny łańcuch audytowy (audytor schodzi do dokumentu)."),
("Multi-tenant ingest isolation", "izolacja danych per przedsiębiorca (w przyszłości multi-tenant) — już w schemacie (pole tenant_id)."),
("Ingest rate governor", "limit wolumenu per kanał (ochrona przed spamem/atakiem) z metrykami — granica fortecy ma własny strażnik."),
],
in_contracts=[
"Kontrakt pipeline z P32 — ingest jest pierwszym etapem (wspólne statusy i idempotencja).",
"Kontrakt WORM z P42 — oryginały i checksumy w niezmiennym archiwum.",
],
out_contracts=[
"KONTRAKT INGESTU (schema, walidacja, dedup, statusy) — wiąże P40 (API/UI), P54 (KSeF) i P68.",
"Bank reconciliation engine (kontrakt) — wejście do P32 i P37 (metryki parowania).",
"Ingest chaos suite — wejście do P39 (CI) i P43 (security).",
],
acceptance_extra=[
"Mapa kanałów ingestu (kanał → ścieżka → walidacje → statusy) z identyfikacją luk per kanał.",
"Kontrakt schematu wejściowego przedstawiony z przykładami danych poprawnych i odrzucanych (min. 10).",
]),
dict(code="P58", slug="OBSERWOWALNOSC_DOMKNIECIE", title="OBSERWOWALNOŚĆ FORTHECY — METRYKI DECYZYJNE I ALARMY NA TYM, CO PRAWNIE WRAŻLIWE",
role="inżynierem SRE systemów decyzyjnych finansowych, projektantem metryk wiarygodności decyzji podatkowych",
expertise="SLO decyzji, error budget, metryki pewności, alarmy prawne, runbooki, telemetria NEEDS_ADVICE",
mission=[
"Zweryfikuj metryki: co mierzy P37 (SLO, freshness, NEEDS_ADVICE radar), czego brakuje dla perspektywy PRAWNEJ (wiek weryfikacji ISAP per akt — P47, spadek pokrycia prawego — P51, dryf parametrów — P46, spread NEEDS_ADVICE per domena — P49, drift groszowy — P52). Wygeneruj katalog metryk prawnych z progami i runbookami — alarm ma prowadzić do akcji (nie vanity metrics).",
"Zaprojektuj telemetrię decyzji: każdy AUTO_POST/NEEDS_ADVERAGE/MANUAL_REVIEW z kontekstem (domena, kwota, pewność, epoka prawna P53, wersja reguł) do rejestru telemetrii — analiza wzorców (domeny wysokie ryzyko, godziny problematyczne, kwoty graniczne). Error budget dla SLO dokładności (zgodność z golden replay) i świeżości prawa — wyczerpanie budżetu = zamrożenie wdrożeń (P38). Przeprować głęboką analizę: które alarmy potrzebują czytelnego runbooka (co robić krok po kroku).",
],
subparts=[
dict(name="Metryki prawne",
goal="alarmy na to, co prawnie wrażliwe",
questions=[
"Czy wiek weryfikacji ISAP per akt jest metryką (P47 freshness) z alarmem przekroczenia SLA?",
"Czy spadek pokrycia prawnego (pustynie P51 rosną) generuje alarm (regresja pokrycia = BLOCKER)?",
"Czy spread NEEDS_ADVICE per domena (nagły wzrost) alarmuje (sygnał luki lub awarii danych)?",
"Czy drift groszowy (P52 reconciliation) ma metrykę trendu do zera z alarmem na wzrost?",
]),
dict(name="Telemetria decyzji",
goal="każda decyzja z kontekstem",
questions=[
"Czy certyfikat (P11) jest źródłem telemetrii (bez podwójnej instrumentacji)?",
"Czy telemetria zawiera epokę prawną (P53) i wersję reguł (bundle hash) — analiza historyczna możliwa?",
"Czy analiza wzorców (domeny ryzyka, kwoty graniczne, powtarzalne NEEDS_ADVICE) jest zautomatyzowana?",
"Czy telemetria respektuje RODO (bez danych osobowych — pseudonimizacja per tenant)?",
]),
dict(name="SLO i error budget prawny",
goal="budżet na błędy z zamrożeniem",
questions=[
"Czy SLO dokładności (zgodność z golden) i świeżości (ISAP age) są zdefiniowane z progiem zamrożenia wdrożeń?",
"Czy wyczerpanie budgetu rzeczywiście zamraża (workflow CI odmawia merge — mechanizm, nie procedura)?",
"Czy SLO per domena (VAT może mieć inne progi niż nisze) — czy jest zdefiniowane i mierzone?",
"Czy alarmy mają runbooki (P41) z krokami awaryjnymi (kto robi co w pierwszej godzinie)?",
]),
dict(name="Runbooki i reakcja",
goal="alarm → akcja w minutach",
questions=[
"Czy każdy alarm ma runbook (definicja alarmu → link do runbooka) — jak wymusić (P41)?",
"Czy runbooki są testowane (ćwiczenia, chaos drills P43) — czy tylko dokumenty?",
"Czy eskalacja ma ścieżkę (SRE → prawnik → właściciel) z SLA per poziom?",
"Czy post-mortemy są standardem (incydent → analiza → zmiana kontrol) — czy spotykane ad hoc?",
]),
],
file_groups=[
dict(name="Metryki i dashboardy", files=[
    ("Generator metryk", "JDG/tools/metrics_generator.py"),
    ("Metryki pewności", "JDG/tools/pewnosc_metrics.py"),
    ("Silnik tierów health", "JDG/tools/health_tier_engine.py"),
    ("Dashboard enterprise", "JDG/tools/enterprise_dashboard.py"),
    ("Dashboard pewności", "JDG/tools/confidence_dashboard.py"),
    ("Dashboard dryfu", "JDG/tools/drift_dashboard.py"),
    ("Dokument dashboard pewności", "JDG/docs/PEWNOSC_DASHBOARD.md"),
    ("Dokument pewności (test)", "JDG/tests/test_priority_engine.py"),
]),
dict(name="Źródła telemetrii", files=[
    ("Rejestr certyfikatów decyzji", "JDG/bundles/decision_certificates.json"),
    ("Metryki pewności (dane)", "JDG/bundles/metrics_pewnosci.json"),
    ("Serwis certyfikatów", "JDG/tools/certificate_service.py"),
    ("Stan control plane", "JDG/bundles/control_plane_state.json"),
    ("WORM storage", "JDG/tools/worm_storage.py"),
    ("Legal Twin raport", "JDG/docs/LEGAL_TWIN_RAPORT.md"),
    ("Legal Twin traceability", "JDG/docs/LEGAL_TWIN_TRACEABILITY.md"),
    ("Rejestr wdrożeń", "JDG/bundles/deployments.json"),
]),
dict(name="Kontrakt SLO i runbooki", files=[
    ("Enterprise operating contract (dane)", "JDG/bundles/enterprise_operating_contract.json"),
    ("Test kontraktu enterprise", "JDG/tests/test_enterprise_operating_contract.py"),
    ("Walidacja kontraktu enterprise", "JDG/tools/validate_enterprise_contract.py"),
    ("Chaos runner", "JDG/tools/chaos_runner.py"),
    ("Digital twin simulator", "JDG/tools/digital_twin_simulator.py"),
    ("Podręcznik użytkownika (kontekst runbooków)", "JDG/docs/PODRECZNIK_UZYTKOWNIKA.md"),
]),
],
legal=[
"Ustawa o rachunkowości — art. 4 ust. 1 (rzetelność — telemetria jako dowód starannego procesu).",
"RODO — art. 5 ust. 2 (rozliczalność — telemetria decyzji), art. 32 (bezpieczeństwo: monitoring).",
"Ordynacja podatkowa — art. 119a (GAAR: telemetria ścieżek agresywnych — wczesna detekcja).",
"Ustawa VAT — art. 109e (terminowość — metryki terminowe chronią deklaracje).",
"Ustawa o ZUS — art. 47 (terminy DRA — metryki terminowe).",
"KKS — art. 56 (wczesne wykrywanie błędów redukuje ryzyko czynu zabronionego).",
"AI Act — monitorowanie systemów AI w produkcji (kontekst warstwy AI P33).",
"Ustawa o rachunkowości — art. 74–75 (retencja telemetrii).",
],
innovations=[
("Legal freshness SLA per act", "wiek weryfikacji ISAP per akt z SLA (ACTIVE akty: codziennie) — alarm na przekroczenie, runbook do re-checku."),
("Coverage regression alarm", "spadek pokrycia prawnego (nowe pustynie) = alarm P0 — Law Radar otwiera karty pustyni automatycznie."),
("Advice-spread radar", "spread NEEDS_ADVICE per domena (nagły wzrost = sygnał) z klasterizacją powodów — analityka luki prawnej na żywo."),
("Penny drift telemetry", "rozjazdy groszowe (P52) jako metryka trendu do zera — wzrost = alarm z full trace (które wyliczenie)."),
("Decision telemetry registry", "rejestr telemetrii decyzji (domena, kwota, pewność, epoka, bundle hash) — analiza wzorców riskowych na żywo."),
("Error budget freeze mechanism", "wyczerpanie budgetu → automatyczne zamrożenie wdrożeń reguł (CI odmawia) — mechanizm, nie procedura."),
("Runbook-per-alarm contract", "bramka: każdy alarm zdefiniowany musi mieć runbook (link) — alarm bez runbooka nie wchodzi do produkcji."),
("Post-mortem template", "standard post-mortem (incydent → wpływ → przyczyna → kontrole) z rejestrem zakończonych — uczenie się fortecy."),
("Escalation matrix", "macierz eskalacji (poziom, rola, SLA, kanał) jako dane — eskalacja czytelna i testowana (ćwiczenia)."),
("Risk-pattern mining", "analiza telemetrii: domeny/godziny/kwoty ryzyka — proaktywne wzmocnienie (gdzieAlarmy często → tam reguły słabsze)."),
("Telemetry privacy guard", "pseudonimizacja per tenant w telemetrii (RODO by design) — metryki agregatowe, nie osobowe."),
("SLO per domain", "SLO dokładności/świeżości per domena (VAT surowsze niż nisze) — realistyczne i mierzalne."),
],
in_contracts=[
"Katalog metryk z P37 — rozszerzenie o metryki prawne (bez duplikacji — jedno źródło definicji).",
"Certyfikat decyzji z P11 — telemetria z certyfikatów (bez dodatkowej instrumentacji).",
],
out_contracts=[
"KATALOG METRYK PRAWNYCH (definicje, progi, runbooki) — wejście do P68 i P41.",
"Telemetria decyzji (schema rejestru) — wiąże P11 (certyfikaty) i P40 (API).",
"Mechanizm error budget freeze — wiąże P38 (deploy) i P39 (CI).",
],
acceptance_extra=[
"Katalog metryk prawnych z min. 12 pozycjami (definicja, próg, akcja, runbook) — gotowy do wdrożenia.",
"Runbook przykładu (alarm „wiek ISAP przekroczony”) krok po kroku (pierwsza godzina reakcji).",
]),
dict(code="P59", slug="SECURITY_DOMKNIECIE", title="BEZPIECZEŃSTWO DOMKNIĘCIE — GRANICE ZAUFANIA, SEKRETY I ANTY-MANIPULACJA",
role="inżynierem bezpieczeństwa aplikacji (AppSec) dla systemów finansowych z fokus na policy-as-code",
expertise="threat modeling, RBAC granic, zarządzanie sekretami, integralność reguł, supply chain security, CI hardening",
mission=[
"Zbadaj granice zaufania: kto może zmienić reguły (PR, review, deploy — czy chronione?), sekrety (klucze KSeF/MF, podpisy bundle — gdzie trzymane, rotacja, audyt użycia), CI (czy pipeline może wstrzyknąć regułę? provenance buildów — P38 attestation), zależności (supply chain: biblioteki Python — pinning, skanowanie). Wygeneruj threat model konkretny (wektor → kontrola → test → status) zamykany w bramkach.",
"Zaprojektuj anty-manipulację: każda zmiana reguły z podpisem i 4-eyes (krytyczne), hash chain historii reguł (WORM P42 — edycja historii wykrywalna), detekcja nietypowych zmian (nagła zmiana stawki = alarm), plan na insider threat (podwójna kontrola, rotacja obowiązków). Bezpieczeństwo fortecy nie jest projektem jednorazowym — to ciągły proces z testami (chaos security drills P43) i metrykami (P58).",
],
subparts=[
dict(name="Granice zaufania i uprawnienia",
goal="kto może co — technicznie egzekwowane",
questions=[
"Czy branch protection (chronione branche, wymagane review) jest skonfigurowany (albo plan do wdrożenia)?",
"Czy CODEOWNERS wymusza review prawne dla reguł (pliki rego → właściciel prawny)?",
"Czy deploy wymaga 4-eyes dla reguł krytycznych (mechanizm w CI, nie procedura)?",
"Czy dostęp produkcyjny jest JIT (czasowy, z dowodem) — zero stałych uprawnień admina?",
]),
dict(name="Sekrety i klucze",
goal="klucze nigdy w repo/env",
questions=[
"Gdzie są klucze (KSeF, MF, podpisy bundle) — sejf (secrets manager) czy pliki/env (luka P0)?",
"Czy rotacja kluczy jest zautomatyzowana (harmonogram + dowód rotacji + test starego klucza martwy)?",
"Czy użycie klucza jest audytowane (kto, kiedy, do czego — rejestr WORM)?",
"Czy istnieje ścieżka awaryjna (kompromitacja klucza → odwołanie → odtworzenie w minutach)?",
]),
dict(name="CI i supply chain",
goal="pipeline nie jest ścieżką ataku",
questions=[
"Czy workflow CI (jdg-quality.yml) ma minimalne uprawnienia (permissions: read)?",
"Czy zależności są pinowane (hash) i skanowane (vulnerabilities) — czy plan do wdrożenia?",
"Czy build ma attestation (provenance: commit, który testował — SLSA P38)?",
"Czy PR z obcym forkera może uruchomić sekrety (repozytory secrets w PR z fork — klasyczna luka)?",
]),
dict(name="Anty-manipulacja i insider",
goal="wykrywalność każdej manipulacji",
questions=[
"Czy historia reguł ma hash chain (WORM) — cicha edycja historii wykrywalna (test tamper)?",
"Czy nagłe zmiany krytycznych wartości (stawka/prog) generują alarm (anomaly detection — P58)?",
"Czy 4-eyes jest egzekwowane na zmianach reguł krytycznych (dwaj ludzie, nie dwa konta)?",
"Czy istnieje kanał zgłoszeń i procedura reakcji na podejrzenie manipulacji (insider threat)?",
]),
],
file_groups=[
dict(name="Narzędzia i testy bezpieczeństwa", files=[
    ("Szyfrowanie post-quantum", "JDG/tools/quantum_safe_encryption.py"),
    ("WORM storage", "JDG/tools/worm_storage.py"),
    ("Chaos engineering", "JDG/tools/chaos_engineering.py"),
    ("Chaos runner", "JDG/tools/chaos_runner.py"),
    ("Silnik self-healing", "JDG/tools/self_healing_engine.py"),
    ("Skanner fraudu grafowego", "JDG/tools/fraud_graph_scanner.py"),
    ("Test fraud graph", "JDG/tests/test_fraud_graph_scanner.py"),
    ("Test RODO enterprise", "JDG/tests/test_rodo_enterprise.py"),
]),
dict(name="Workflow i kontrakt bezpieczeństwa", files=[
    ("Workflow jakości JDG", "JDG/.github/workflows/jdg-quality.yml"),
    ("Dokument RODO/AML P16", "JDG/docs/RODO_AML_BEZPIECZENSTWO_P16.md"),
    ("Test AML enterprise", "JDG/tests/test_aml_enterprise.py"),
    ("Dokument zgodności prawnej", "JDG/docs/ZGODNOSC_PRAWNA.md"),
    ("Orkiestrator wdrożeń", "JDG/tools/deployment_orchestrator.py"),
    ("Serwis certyfikatów", "JDG/tools/certificate_service.py"),
]),
dict(name="Dane integralności", files=[
    ("Rejestr wdrożeń", "JDG/bundles/deployments.json"),
    ("Zrzuty DR (katalog)", "JDG/bundles/dr_snapshots"),
    ("Zdrowe wersje", "JDG/bundles/healthy_versions.json"),
    ("Katalog bundle", "JDG/bundles/bundle_catalog.json"),
    ("Test walidacji kontraktu", "JDG/tests/test_enterprise_operating_contract.py"),
    ("Dokument święty 1 (kontekst)", "JDG/docs/ARCHITEKTURA_OPA_ENTERPRISE_TARGET.md"),
]),
],
legal=[
"RODO — art. 32 (bezpieczeństwo: pseudonimizacja, szyfrowanie, odporność systemów, regularne testy).",
"RODO — art. 33–34 (naruszenia: raport 72h do UODO — playbook P43).",
"eIDAS — podpisy/pieczęcie na bundle i certyfikatach (integralność i autentyczność).",
"Ustawa o rachunkowości — art. 74 (ochrona przed zniszczeniem: WORM, DR, anty-manipulacja).",
"KKS — art. 115-1 i nast. (oszustwa komputerowe: ochrona silnika jako systemu informatycznego).",
"Ustawa AML — art. 2, 48 (środki bezpieczeństwa finansowego — kontekst).",
"UKSC (ustawa o krajowym systemie cyberbezpieczeństwa) — obowiązki operatorów (kontekst klasyfikacji).",
"Ustawa o prawach konsumenta/e-doręczenia — integralność komunikacji z organami (kontekst).",
],
innovations=[
("Threat model as data + gates", "wektory zagrożeń w YAML (atak→kontrola→test→status) — bramka wymaga statusu „kontrola istnieje” przed produkcją."),
("Signed rules with 4-eyes", "krytyczne reguły podpisywane przez dwie role (techniczna+prawna) — podpis w metadanych reguły, weryfikowany przy deploy."),
("Rule history hash chain", "zmiany reguł w WORM z hash chain — edycja historii wykrywalna (test tamper w CI)."),
("Rate-change anomaly alarm", "nagła zmiana stawki/progu (diff vs historia) → alarm z zatwierdzeniem 4-eyes — manipulacja parametrem blokowana."),
("Secrets vault contract", "sekrety w sejfie (mechanizm wskazany) z rotacją, audytem użycia (WORM) i ścieżką awaryjną — zero sekretów w repo/env."),
("CI hardening checklist", "permissions: read, pinning zależności z hashami, skanowanie CVE, fork-PR secret isolation — checklist z statusem i planem."),
("Build attestation verification", "certyfikat decyzji weryfikuje attestation bundle (provenance) — decyzja bez potwierdzonego pochodzenia = NEEDS_ADVICE."),
("Insider threat program", "podwójna kontrola, rotacja obowiązków, kanał zgłoszeń, audyt nietypowych dostępów — program, nie slogan."),
("Supply chain SBOM", "SBOM (bill of materials) zależności generowany w CI — przejrzystość łańcucha dostaw (P68 certyfikat)."),
("Security chaos drills", "ćwiczenia: próba wstrzyknięcia reguły, kompromitacja klucza, tamper WORM — raport luk procesowych, kwartalnie."),
("Trust boundary map", "mapa granic zaufania (co wewnątrz/na zewnątrz, kim są aktorzy) — dokument + testy kontrol na granicach."),
("Security score trend", "wskaźnik bezpieczeństwa (kontrole zaimplementowane/wymagane) z trendem — raport do P68."),
],
in_contracts=[
"Kontrakt deploy z P38 (podpisy, attestation) — security warstwy integralności.",
"Kontrakt WORM z P42 — hash chain historii jako podstawa anty-manipulacji.",
],
out_contracts=[
"THREAT MODEL (wektor→kontrola→test→status) — wejście do P68 i P43 (DR).",
"Kontrakt sekretów (sejf, rotacja, audyt) — wiąże P40 (API), P54 (KSeF klucze) i P44.",
"CI hardening checklist (status+plan) — wejście do P39 i P68.",
],
acceptance_extra=[
"Threat model z min. 12 wektorami (w tym: manipulacja regułą, kradzież klucza, wstrzyknięcie przez CI, insider).",
"Status sekretów (gdzie są DZISIAJ — dowód z repo) i plan migracji do sejfu z terminem.",
]),
dict(code="P60", slug="DOKUMENTACJA_DOMKNIECIE", title="DOKUMENTACJA DOMKNIECIE — DOKUMENT MÓWI PRAWDĘ O KODZIE",
role="architektem dokumentacji z praktyką audytów zgodności dokument-kod w systemach regulowanych",
expertise="spójność dokument-kod, generowanie dokumentów z rejestrow, podręczniki rolowe, eksport audytowy, retencja dokumentów",
mission=[
"Przeanalizuj 65 dokumentów pod kątem PRAWDZIWOŚCI: czy opisują dzisiejszy kod (nie historię kampanii)? które liczby (liczba reguł, rule_id, bramek) są zgodne z rejestrami (rule_registry, manifest_v2)? które dokumenty opisują elementy nieistniejące (dokumenty-widma — P50)? Wygeneruj rejestr dokument-widmo i rozjazdów z planem korekty (korekta dokumentu albo usunięcie opisu).",
"Zaprojektuj domknięcie: dokumenty-generowane (liczby z rejestrow automatycznie — zero ręcznych liczb), front-matter z artefaktami (binding dokument↔kod — zmiana kodu bez dokumentacji nie przechodzi bramki), mapy rolowe (developer/operator/audytor/przedsiębiorca — każdy ma ścieżkę czytania), eksport audytowy (pakiet dla kontroli skarbowej: dokumenty+rejestry+checksumy). Dokumentacja fortecy to dowód prawny „system działa jak napisano” — musi być prawdą weryfikowalną.",
],
subparts=[
dict(name="Rejestr rozjazdów dokument-kod",
goal="dokument mówi prawdę albo jest korygowany",
questions=[
"Które dokumenty podają liczby sprzeczne z rejestrami (rule_registry, manifest) — lista par z dowodami?",
"Które dokumenty opisują pliki/reguły nieistniejące (widma — zweryfikuj każde odwołanie)?",
"Które dokumenty opisują PRZESZŁOŚĆ (kampanie) jako STAN (dryf czasowy — oznaczyć jako archiwalne)?",
"Które dokumenty PL/EN są sprzeczne (ARCHITEKTURA.md vs ARCHITECTURE.md) — diff semantyczny?",
]),
dict(name="Dokumenty-generowane",
goal="liczby z rejestrow, nie z głowy",
questions=[
"Które liczby w dokumentach da się generować (snippet z rule_registry) — plan konwersji?",
"Czy generator (P36) produkuje też fragmenty dokumentacji (KATALOG_REGUL z rejestru)?",
"Czy daty „aktualizacji” dokumentów są automatyczne (z git) czy ręczne (dryf)?",
"Czy istnieje walidator (P34 doc_consistency) uruchamiany w CI (blokuje rozjazd)?",
]),
dict(name="Front-matter i binding",
goal="dokument przywiązany do kodu",
questions=[
"Czy dokumenty mają front-matter z listą artefaktów (binding) — jak wymusić (bramka docs P29)?",
"Czy status dokumentu (CURRENT/ARCHIVED/SUPERSEDED) jest jawny — zero kanibalizmu wersji?",
"Czy dokumenty święte mają ochronę (zmiana tylko decyzją człowieka z ADR) — mechanizm (CODEOWNERS)?",
"Czy każdy nowy pakiet reguł MUSI mieć dokument (konwencja + bramka) — czy jest egzekwowane?",
]),
dict(name="Eksport audytowy i retencja",
goal="pakiet dla kontroli gotowy w minuty",
questions=[
"Czy eksport audytowy (dokumenty+rejestry+checksumy+pieczęć) jest zautomatyzowany (P42 WORM)?",
"Czy retencja dokumentów respektuje przepisy (5 lat, archiwizacja wersji)?",
"Czy certyfikat (P68) odwołuje się do wersji dokumentacji (hash) — dowód spójności?",
"Czy jest przewodnik audytora (jak zweryfikować zgodność — ścieżki dowodowe) — kompletny?",
]),
],
file_groups=[
dict(name="Dokumenty główne", files=[
    ("Architektura (PL)", "JDG/docs/ARCHITEKTURA.md"),
    ("Architecture (EN)", "JDG/docs/ARCHITECTURE.md"),
    ("Dokument święty 1", "JDG/docs/ARCHITEKTURA_OPA_ENTERPRISE_TARGET.md"),
    ("Dokument święty 2", "JDG/docs/WIZJA_OPA_ENTERPRISE_V2.md"),
    ("Struktura projektu", "JDG/docs/STRUKTURA_PROJEKTU.md"),
    ("Manifest 2.0", "JDG/docs/MANIFEST_2_0.md"),
    ("Katalog reguł", "JDG/docs/KATALOG_REGUL.md"),
    ("Katalog narzędzi", "JDG/docs/KATALOG_NARZEDZI.md"),
]),
dict(name="Guides i użytkownik", files=[
    ("Developer guide", "JDG/docs/DEVELOPER_GUIDE.md"),
    ("OPA Rego developer guide", "JDG/docs/OPA_REGO_DEVELOPER_GUIDE.md"),
    ("Podręcznik użytkownika", "JDG/docs/PODRECZNIK_UZYTKOWNIKA.md"),
    ("FAQ", "JDG/docs/FAQ.md"),
    ("API referencja", "JDG/docs/API_REFERENCJA.md"),
    ("Dokument api", "JDG/docs/api.md"),
    ("Analiza stanu OPA", "JDG/docs/ANALIZA_STANU_OPA_JAKO_SYSTEM.md"),
    ("UNIFIED_PLAN", "JDG/docs/UNIFIED_PLAN.md"),
]),
dict(name="Walidatory dokumentacji", files=[
    ("Walidator spójności dokumentów", "JDG/tools/doc_consistency_validator.py"),
    ("Generator dokumentacji API", "JDG/tools/api_doc_generator.py"),
    ("Bramka docs", "JDG/tools/docs_quality_v3_20_gate.py"),
    ("Test bramki docs", "JDG/tests/test_docs_quality_v3_20.py"),
    ("Generator manifestu", "JDG/tools/generate_manifest.py"),
    ("Bramka api_ui", "JDG/tools/api_ui_quality_v3_19_gate.py"),
    ("Dokument zgodności prawnej", "JDG/docs/ZGODNOSC_PRAWNA.md"),
    ("Podręcznik (kontekst eksportu)", "JDG/docs/PODRECZNIK_UZYTKOWNIKA.md"),
]),
],
legal=[
"Ustawa o rachunkowości — art. 4 ust. 1–3 (dokumentacja jako element sprawdzalności — eksport audytowy).",
"Ordynacja podatkowa — art. 193a (dokumentacja procesu wspiera weryfikację — dokumenty = dowód staranności).",
"RODO — art. 24 (rozliczalność), art. 30 (rejestr czynności — dokumentacja systemu).",
"AI Act — art. 11 (dokumentacja techniczna systemów — kontekst warstwy AI).",
"Ustawa o rachunkowości — art. 74–75 (retencja dokumentacji 5 lat — wersjonowanie).",
"eIDAS — pieczęcie na eksporcie audytowym (integralność pakietu).",
"KSeF — dokumentacja integracji (schematy, wersje) jako element zgodności.",
"ISAP — cytowania aktów w dokumentach zgodne z konwencją (P47).",
],
innovations=[
("Doc truth audit", "pełny audyt: dokument → liczby → rejestry — rejestr rozjazdów z korektą; dokument mówi prawdę albo jest korygowany."),
("Registry-generated snippets", "liczby w dokumentach generowane z rejestrow (rule_registry, manifest) — zero ręcznych liczb (wykrywalnych przez P34)."),
("Front-matter binding gate", "każdy dokument z front-matter (artefakty, status, właściciel); bramka docs sprawdza istnienie artefaktów — binding egzekwowany."),
("Ghost document register", "rejestr dokumentów-widm (opisują nieistniejące elementy) — korekta albo oznaczenie SUPERSEDED."),
("Role reading maps", "mapy czytania per rola (developer: ścieżka A→B→C; audytor: ścieżka dowodowa; przedsiębiorca: podręcznik) — onboarding w minuty."),
("Audit export pack", "jedna komenda: pakiet (dokumenty, rejestry, checksumy, pieczęć WORM) dla kontroli skarbowej — gotowy w minuty."),
("Doc freshness automation", "daty weryfikacji dokumentów z git (automat) — przejrzystość wieku informacji („świeżość” widoczna)."),
("Holy-docs protection", "dokumenty święte pod CODEOWNERS (zmiana tylko z ADR i review prawnym) — nienaruszalność egzekwowana mechanizmem."),
("Example-as-test", "przykłady w dokumentacji (curl, rego) testowane w CI — zero zepsutych przykładów."),
("Glossary enforcement", "terminy z glosariusza (SLOWNIK_REFERENCJI_PRAWNYCH) użyte spójnie — lint językowy (konsekwencja terminologiczna)."),
("PL/EN semantic parity", "ARCHITEKTURA.md vs ARCHITECTURE.md porównywane semantycznie — drift tłumaczenia = alarm."),
("Doc completeness per role", "metryka: pokrycie roli (developer/operator/audytor/przedsiębiorca) — zero ról bez ścieżki czytania."),
],
in_contracts=[
"Sieć walidacji z P34 — doc_consistency w sieci (L4) z blokadą merge przy rozjeździe.",
"Konwencja cytowań z P47 — dokumentacja używa kanonicznych cytowań aktów.",
],
out_contracts=[
"REJESTR ROZJAZDÓW DOKUMENT-KOD (z korektami) — wejście do P68.",
"Konwencja front-matter + statusów — wiąże P29 (bramka docs) i P36 (generatory).",
"Eksport audytowy (format pakietu) — wejście do P42 (WORM), P68 (certyfikat) i P41.",
],
acceptance_extra=[
"Rejestr rozjazdów dokument-kod z min. 10 pozycjami (dokument → liczba → rzeczywistość → korekta).",
"Mapy rolowe (4 role × ścieżki czytania) przedstawione jako tabele — zero ról bez ścieżki.",
]),
]
