# -*- coding: utf-8 -*-
"""Parts P08-P14: Law Radar, Golden Oracle, Declarative Change + domain wave start (VAT)."""
PARTS = [

dict(code="P08", slug="LAW_RADAR", title="LAW RADAR — PROAKTYWNA ADAPTACJA DO ZMIAN PRAWA (V2/F5)",
role="ekspertem monitoringu legislacyjnego i architektem proaktywnych systemów policy-as-code",
expertise="monitoring projektów ustaw (RCL/Sejm/Senat), pipeline ISAP→produkcja, AI-Reader nowelizacji, lead time reguł",
mission=[
"Zmień paradygmat silnika z REAKCJI (nowelizacja opublikowana → 24 h) na PROAKCJĘ (projekt ustawy → przygotowane reguły przed wejściem w życie) zgodnie z V2/F5. Zbuduj projekt Law Radar: monitoring projektów ustaw i rozporządzeń (RCL, Sejm, Senat, konsultacje), AI-Reader analizujący nowelizację do ustrukturyzowanego diffu prawnego (który akt, artykuł, co się zmienia: stawki/progi/definicje/terminy) z walidacją 4-eyes (drugi model + prawnik).",
"Zaprojektuj pełny pipeline: wykrycie projektu → diff prawny → impact matrix (dotknięte reguły/parametry/decyzje) → przygotowanie reguł SHADOW z wyprzedzeniem (lead time) → gotowość na dzień wejścia w życie → automatyczna aktywacja. Uwzględnij istniejące narzędzia (isap_crawler, isap_rule_update_pipeline, law_radar.py, legal_change_calendar, law_impact_matrix) — rozbuduj, nie duplikuj. Cel SLO z V1: nowelizacja P0 ≤ 4 h od publikacji, rutynowa ≤ 24 h, parametr ≤ 15 min.",
],
subparts=[
dict(name="Źródła prawa i detekcja zmian",
goal="pełna mapa źródeł i mechanizmów wykrywania (opublikowane + projekty)",
questions=[
"Co dziś monitoruje isap_crawler.py i law_radar.py — czy pokrywają projekty ustaw, czy tylko opublikowane akty?",
"Jakie źródła brakuje (konsultacje publiczne, uzasadnienia, stanowiska, komunikaty MF/KIS) i jak je dodać?",
"Jak wykrywać zmiany w rozporządzeniach wykonawczych (stawki, wzory) — one nie zawsze mają „projekt”?",
"Jaka jest częstotliwość crawlowania i czy wspiera wykrywanie zmian w tekstach jednolitych (diff wersji)?",
]),
dict(name="AI-Reader i diff prawny",
goal="automatyczna zamiana nowelizacji na ustrukturyzowany diff z pewnością",
questions=[
"Jaka jest struktura diffu prawnego (akt, jednostka redakcyjna, typ zmiany, stara/nowa treść, daty)?",
"Jak walidować wyjście AI (4-eyes: drugi model + człowiek) i jaką pewność przypisywać?",
"Jak AI-Reader łączy się z LKG (P01): diff → nowe wersje węzłów prawnych → lista dotkniętych reguł?",
"Czy llm_bridge.py jest gotowy do roli AI-Readera — jakie braki (prompting, walidacja, cytowanie)?",
]),
dict(name="Impact matrix i plan adaptacji",
goal="od diffu prawnego do listy zadań z priorytetami",
questions=[
"Czy law_impact_matrix.py i legal_change_impact_analyzer.py mapują diff na reguły/parametry/decyzje?",
"Jak szacować wpływ na portfel decyzji (replay historyczny) przed napisaniem reguł?",
"Jak priorytetyzować (P0/P1/P2) i ustalać lead time (kiedy reguły muszą być w SHADOW)?",
"Jak łączyć to z kalendarzem zmian prawnych (legal_change_calendar) i alertami N dni przed?",
]),
dict(name="Aktywacja i gotowość",
goal="automatyczne wejście w życie i dry run",
questions=[
"Czy reguły z valid_from w przyszłości są testowane wcześniej (dry run na danych bieżących)?",
"Jak wygląda aktywacja w dniu wejścia w życie — automat czy ręczna akcja (jaka awaryjna ścieżka)?",
"Jak weryfikować poprawność wdrożenia (porównanie z uzasadnieniem diffu, golden replay delta)?",
"Jak raportować gotowość („prawo X: przygotowane 14 dni przed terminem / spóźnione”)?",
]),
],
file_groups=[
dict(name="Narzędzia monitoringu prawa", files=[
    ("Crawler ISAP", "JDG/tools/isap_crawler.py"),
    ("Pipeline ISAP→reguły", "JDG/tools/isap_rule_update_pipeline.py"),
    ("Law Radar (narzędzie)", "JDG/tools/law_radar.py"),
    ("Macierz wpływu prawa", "JDG/tools/law_impact_matrix.py"),
    ("Analizator wpływu zmian prawnych", "JDG/tools/legal_change_impact_analyzer.py"),
    ("Kalendarz zmian prawnych", "JDG/tools/legal_change_calendar.py"),
    ("Kalendarz zmian (dane)", "JDG/bundles/legal_change_calendar.json"),
    ("Alarm dryfu ISAP", "JDG/tools/isap_drift_alarm.py"),
    ("Symulator amendacji", "JDG/tools/law_amendment_simulator.py"),
    ("Bridge LLM", "JDG/tools/llm_bridge.py"),
]),
dict(name="Reguły wsparcia adaptacji", files=[
    ("Monitor legislacyjny (reguła)", "JDG/rules/legislative_monitor_enterprise.rego"),
    ("Analizator wpływu legislacyjnego (reguła)", "JDG/rules/legislative_impact_analyzer_enterprise.rego"),
    ("Kalendarz zmian (reguła)", "JDG/rules/calendar_notifier_enterprise.rego"),
    ("Roadmap strategiczna (reguła)", "JDG/rules/strategic_roadmap_enterprise.rego"),
]),
dict(name="Dokumenty adaptacyjne", files=[
    ("Kalendarz zmian prawnych (dokument)", "JDG/docs/KALENDARZ_ZMIAN_PRAWNYCH.md"),
    ("Analiza stanu (luka adaptacji)", "JDG/docs/ANALIZA_STANU_OPA_JAKO_SYSTEM.md"),
    ("Kampania etapy (kontekst)", "JDG/docs/KAMPANIA_GLM52_ETAPY_10_28.md"),
]),
dict(name="Testy pipeline prawa", files=[
    ("Test monitora legislacyjnego", "JDG/tests/rego/test_native_legislative_monitor_enterprise.rego"),
    ("Test lifecycle reguł", "JDG/tests/test_control_plane_lifecycle.py"),
]),
],
focus=[
"Porównaj implementację isap_rule_update_pipeline.py z pipeline V1 §4 (ingest→analiza→generacja→walidacja→wdrożenie) — tabela różnic.",
"Zaprojektuj schemat diffu prawnego (JSON) zgodny z LKG (legal_node_id z P01) i zarazem użyteczny dla reguł.",
"Zaprojektuj scoring pewności AI-Reader i jego granice: co zawsze wymaga człowieka (zmiany definicji, nowe podatki).",
"Zbuduj przykładowy end-to-end: hipotetyczna nowelizacja limitu VAT 200k → diff → impact → SHADOW → dry run → aktywacja.",
"Zaprojektuj SLO i telemetrię pipeline (czas wykrycia→produkcja) oraz alarmy naruszeń SLO.",
"Oceń integrację z lifecycle (P07): pipeline musi tworzyć reguły od razu w SHADOW z lead time.",
"Zaprojektuj obsługę kilku scenariuszy jednocześnie (konkurujące projekty ustaw) i unieważniania (projekt upadł).",
"Zaplanuj kanały prawne z niską latencją (feed Dz.U., RCL webhook) i średnią (konsultacje) — priorytety crawlowania.",
"Oceń, jak Law Radar współpracuje z P09 (formularz zmiany) — projekt → gotowy wniosek zmiany do zatwierdzenia.",
"Wskaż, które domeny (P10–P36) mają najwyższy ryzyko zmienności prawa i wymagają najszybszego pipeline'u.",
"Zaprojektuj test pipeline na fikcyjnej nowelizacji (test end-to-end z mock feedem).",
"Zaprojektuj raport gotowości prawnej tygodniowy (co się zmienia w 30/60/90 dni, status przygotowania).",
],
legal=[
"Ustawa o VAT — art. 41, art. 113 (limity/stawki jako częsty obiekt nowelizacji)",
"Ustawa o PIT — art. 27, art. 30c, art. 26 (progi i ulgi jako obiekt nowelizacji)",
"Ustawa o systemie ubezpieczeń społecznych — art. 18a/18c (ulgi składkowe okresowe)",
"Ordynacja podatkowa — art. 14a-14c (interpretacje jako kanał „miękkich” zmian interpretacyjnych)",
"Ustawa o świadczeniach opieki zdrowotnej — art. 81 (progi zdrowotnej — zmiany coroczne)",
"Ustawa – Prawo przedsiębiorców — art. 22–25 (procedury zawieszenia — zmiany epizodyczne)",
"Rozporządzenia MF (JPK_VAT, wzory) jako szybki kanał zmian technicznych",
],
innovations=[
("Draft Law Radar Feed", "monitoring RCL/Sejm/Senat z scoringiem prawdopodobieństwa uchwalenia"),
("AI-Reader 4-Eyes", "LLM diff → walidacja drugim modelem → prawnik; pełny audyt pewności"),
("Pre-Life Shadow Rules", "reguły przyszłych wersji w SHADOW z dry run na bieżących danych"),
("Lead-Time SLA Dashboard", "pomiar lead time per nowelizacja vs deadline (gotowe 30/14/7 dni przed)"),
("Impact Matrix Auto-Builder", "diff → dotknięte reguły/parametry/werdykty z priorytetami i szacunkiem pracy"),
("Legal Change Calendar Sync", "kalendarz z alertami N-dni i integracją z lifecycle (P07) i bundle (P38)"),
("Scenario Versioning", "obsługa kilku alternatywnych projektów jednocześnie z unieważnianiem"),
("Repeal Detector", "wykrywanie uchylenia przepisu → lista reguł do wygaszenia (deprecate)"),
("Low-Latency Legal Feeds", "webhooki/feed Dz.U. z degradacją do polling (SLA wykrycia < 1 h)"),
("Compliance Readiness Report", "tygodniowy raport: co się zmienia i czy silnik jest gotowy"),
("Pipeline E2E Test Rig", "test pełnego pipeline na fikcyjnej nowelizacji (mock feed → produkcja)"),
("Law Radar API", "API statusu adaptacji prawnej dla UI księgowej („prawo X: gotowe / w przygotowaniu”)"),
],
in_contracts=[
"Honoruj model LKG i legal_node_id z V3_P01 — diff prawny mapuje się na wersje węzłów.",
"Honoruj okna temporalne i Snapshot ID z V3_P05 — reguły przyszłe mają poprawne valid_from i dry run.",
"Honoruj lifecycle z V3_P07 — pipeline tworzy reguły w SHADOW z lead time i awansuje automatycznie.",
],
out_contracts=[
"Schemat diffu prawnego — wiąże P01 (LKG), P09 (declarative change), P10 (golden oracle uzasadnienia).",
"Impact matrix — wiąże P06 (parametry) i wszystkie domeny P10–P36 (priorytety adaptacji).",
"SLO adaptacji i telemetria — wiąże P41 (obserwowalność) i P44 (certyfikacja).",
"Kalendarz gotowości prawnej — wejście do UI (P41) i raportów P44.",
],
acceptance_extra=[
"Raport zawiera scenariusz end-to-end hipotetycznej nowelizacji od detekcji do aktywacji.",
"Każde narzędzie istniejące ma ocenę: co zostaje, co się zmienia, co brakuje (bez propozycji duplikatów).",
]),

dict(code="P09", slug="DECLARATIVE_CHANGE", title="DECLARATIVE CHANGE — ZMIANA W JĘZYKU PROSTYM (V2/F6)",
role="architektem systemów Declarative Change i UX dla operacji prawno-technicznych",
expertise="formularze deklaratywne, automatyczna kompilacja deklaracji do reguł/PR, 4-eyes, zero wiedzy eksperckiej wymagane od autora zmiany",
mission=[
"Zbuduj pełny projekt Declarative Change (V2/F6): operator/prawnik opisuje zmianę w formularzu prostym („stawka VAT dla X od 2027-01-01: 23%→8%”, „nowy próg składki zdrowotnej od 2026-01-01: ...”), a SYSTEM sam: mapuje na reguły/parametry, generuje diff, testy, impact, PR, przeprowadza 4-eyes i wdrożenie kanarkowe. Wymóg: człowiek opisuje, maszyna wykonuje; zmiana prawa nie może wymagać wiedzy eksperckiej o kodzie.",
"Zbadaj istniejące narzędzie declarative_change.py i ocenioną integrację: schemat formularza, parser intencji, mapowanie na P06 (parametry) i P07 (lifecycle), walidacje i przewidywanie wpływu. Zaprojektuj katalog wzorców zmian (recipes): typowe typy zmian prawa (zmiana stawki, nowy próg, nowy przepis, uchylenie, zmiana terminu) z gotowymi szablonami generacji.",
],
subparts=[
dict(name="Formularz deklaratywny i schemat deklaracji",
goal="prostota zapisu zmiany bez utraty precyzji",
questions=[
"Jakie pola musi mieć deklaracja zmiany (co, gdzie, od kiedy, podstawa prawna, uzasadnienie)?",
"Jak walidować deklarację (spójność dat, zakresy wartości, istnienie przepisu w LKG)?",
"Jak obsłużyć zmiany złożone (kilka artykułów, kilka aktów) — deklaracja złożona czy kilka prostych?",
"Jak język naturalny mapuje się na schemat (asystent uzupełniania, podpowiedzi z LKG)?",
]),
dict(name="Kompilacja deklaracji do zmian",
goal="deklaracja → diff reguł/parametrów → PR → 4-eyes",
questions=[
"Jak deklaracja „zmiana stawki” kompiluje się do parametru (P06) i/lub wersji reguły (P07)?",
"Jak automat generuje testy (granice, day-1/0/+1, golden delta) dla każdej zmiany?",
"Jak obliczany jest impact (dotknięte decyzje, portfel) przed zatwierdzeniem?",
"Jak wygląda 4-eyes: kto zatwierdza (role), jakie bramki, jak podpisywany jest wynik?",
]),
dict(name="Katalog wzorców zmian (recipes)",
goal="gotowe szablony typowych zmian prawa",
questions=[
"Które typy zmian pokrywają 80% przypadków (stawka, próg, limit, termin, stawka progresji, nowy przepis, uchylenie)?",
"Jak recipe definiuje: parametry do zmiany, reguły do wersjonowania, testy do generacji, ryzyka?",
"Jak dodawać nowe recipes (procedura, walidacja, testy szablonu)?",
"Jak recipe łączy się z Law Radar (P08): projekt ustawy → pre-wypełniona deklaracja?",
]),
dict(name="Bezpieczeństwo i audyt zmian",
goal="każda zmiana odwracalna i udokumentowana",
questions=[
"Czy każda deklaracja i jej wykonanie jest audytowalne (kto, kiedy, co, na jakiej podstawie)?",
"Jak wygląda rollback deklaracji (co się cofa: parametr, reguła, bundle)?",
"Jak blokować deklaracje niebezpieczne (brak podstawy prawnej, konflikt z invariantami P04)?",
"Jak deklaracje współgrają z golden oracle (P10): uzasadniona delta vs nieuzasadniona?",
]),
],
file_groups=[
dict(name="Narzędzie deklaratywnej zmiany", files=[
    ("Declarative change (narzędzie)", "JDG/tools/declarative_change.py"),
    ("Rejestr limitów (parametry)", "JDG/tools/limits_registry.py"),
    ("Data Service (parametry)", "JDG/tools/data_service.py"),
    ("Menedżer lifecycle (wykonanie)", "JDG/tools/rule_lifecycle_manager.py"),
    ("Generator białych list (kontekst)", "JDG/tools/overlay_engine.py"),
    ("Silnik overlay (warianty)", "JDG/tools/overlay_generator.py"),
]),
dict(name="Reguły zmiany i adaptacji", files=[
    ("Lifecycle reguł", "JDG/rules/rule_lifecycle_enterprise.rego"),
    ("Menedżer lifecycle", "JDG/rules/lifecycle_manager_enterprise.rego"),
    ("Monitor legislacyjny", "JDG/rules/legislative_monitor_enterprise.rego"),
    ("Form optimizer (kontekst)", "JDG/rules/form_optimizer_enterprise.rego"),
]),
dict(name="Dokumenty procesowe", files=[
    ("Lifecycle (dokument)", "JDG/docs/RULE_LIFECYCLE.md"),
    ("Control plane (dokument)", "JDG/docs/CONTROL_PLANE_RULE_LIFECYCLE.md"),
    ("Guide dewelopera (proces reguł)", "JDG/docs/DEVELOPER_GUIDE.md"),
    ("Guide Rego (konwencje)", "JDG/docs/OPA_REGO_DEVELOPER_GUIDE.md"),
]),
dict(name="Dane procesowe", files=[
    ("Rejestr reguł", "JDG/bundles/rule_registry.json"),
    ("Dane progów", "JDG/bundles/thresholds_data.json"),
    ("Deploymenty", "JDG/bundles/deployments.json"),
]),
],
focus=[
"Porównaj declarative_change.py z wymogami V2/F6 — tabela: wymóg → status → luka → plan.",
"Zaprojektuj schemat deklaracji (JSON Schema) z walidacją dat, zakresów i podstaw prawnych (P01).",
"Zaprojektuj pipeline generacji: deklaracja → diff → testy → impact → PR → 4-eyes → canary (P07/P38).",
"Zbuduj 6 recipes: zmiana stawki, zmiana progu, nowy limit czasowy, zmiana terminu, uchylenie przepisu, zmiana definicji.",
"Zaprojektuj integrację z P06 (parametry hot-reload) — większość zmian to dane, nie kod.",
"Zaprojektuj integrację z P08 (Law Radar) — pre-wypełnione deklaracje z diffów prawnych.",
"Zdefiniuj granice deklaratywnej zmiany (co NIGDY nie jest deklaratywne: nowe domeny, zmiany invariantów P04).",
"Zaprojektuj tryb awaryjny ręczny (gdy deklaracja niemożliwa) — bez cichego omijania bramek.",
"Zaplanuj telemetrię procesu (czas deklaracji→produkcja, liczba odrzuceń, powody).",
"Zaprojektuj UI/API (P41) dla formularza zmiany z podpowiedziami z LKG.",
"Zbuduj test end-to-end deklaracji zmiany stawki (mock: deklaracja → produkcja → werdykt z nową stawką od daty).",
"Zdefiniuj role i uprawnienia deklaracji (kto może deklarować, zatwierdzać, wdrażać) — spójnie z RBAC P43.",
],
legal=[
"Ustawa o VAT — art. 41 (zmiany stawek — przepis recipe „zmiana stawki”)",
"Ustawa o PIT — art. 27/30c (progi — recipe „zmiana progu”)",
"Ustawa o zryczałtowanym podatku dochodowym — art. 12 (stawki ryczałtu — recipe)",
"Ustawa o systemie ubezpieczeń społecznych — art. 18a/18c (ulgi okresowe — recipe „nowy limit czasowy”)",
"Ustawa o świadczeniach opieki zdrowotnej — art. 81 (progi zdrowotnej — recipe)",
"Ordynacja podatkowa — art. 24a (informacja o zmianie okoliczności jako paradygmat aktualizacji danych)",
],
innovations=[
("Declaration Schema v1", "pełny schemat deklaracji zmiany z walidacją i przykładami"),
("Intent Compiler", "parser deklaracji → precyzyjny plan zmian (parametry/reguły/testy) z wyrokiem pewności"),
("Recipe Library", "katalog wzorców zmian prawa z automatyczną generacją testów i ryzyk"),
("Auto-Test Synthesizer", "generacja testów granicznych i temporalnych dla każdej deklaracji"),
("Impact Preview", "przed zatwierdzeniem: szacunek wpływu na portfel decyzji (replay)"),
("4-Eyes Flow Engine", "techniczne wymuszenie ról i bramek zatwierdzeń z podpisami"),
("Dangerous Change Guard", "blokada deklaracji naruszających invarianty (P04) lub bez podstawy prawnej (P01)"),
("Law Radar Prefill", "deklaracje pre-wypełnione z diffów prawnych (P08) — prawnik potwierdza, nie pisze"),
("Rollback-as-Declaration", "cofnięcie zmiany = nowa deklaracja (pełny audyt, zero ręcznych operacji)"),
("Change Telemetry", "SLO: czas deklaracji→produkcja, odrzucenia z powodami, obciążenie ról"),
("Emergency Manual Mode", "śledzony tryb ręczny z obowiązkiem retro-deklaracji (zero cichych zmian)"),
("Declarative UI Contract", "kontrakt formularza dla UI (P41): pola, walidacje, podpowiedzi LKG"),
],
in_contracts=[
"Honoruj schemat parametrów i hot-reload z V3_P06 — większość deklaracji to zmiany danych.",
"Honoruj lifecycle (SHADOW/CANDIDATE/ACTIVE, 4-eyes) z V3_P07 — deklaracje przechodzą te same bramki.",
"Honoruj diff prawny z V3_P08 — deklaracje pre-wypełnione z pipeline'u prawa.",
],
out_contracts=[
"Schemat deklaracji i recipes — wiąże P38 (deployment) i P41 (UI/API).",
"Granice deklaratywności (co wymaga kodu) — wiąże P44 (certyfikacja procesu).",
"Tryb awaryjny i rollback-as-declaration — wiąże P43 (DR).",
"Telemetria zmian — wiąże P41 (obserwowalność).",
],
acceptance_extra=[
"Raport zawiera 6 kompletnych recipes z przykładami deklaracji i wygenerowanymi artefaktami.",
"Zawiera test end-to-end deklaracji (od formularza do werdyktu na produkcji).",
]),

dict(code="P10", slug="GOLDEN_ORACLE", title="GOLDEN VERDICTS ORACLE I NIEZNISZCZALNOŚĆ PRZESZŁOŚCI (V2/F3)",
role="ekspertem weryfikacji formalnej, regression oracles i systemów z gwarancją niezmienności historycznej",
expertise="golden replay, weryfikacja formalna SMT/Z3, ewaluacja różnicowa, autojustification delt",
mission=[
"Zbuduj pełny projekt Golden Verdicts Repository (V2/F3): złote werdykty z ostatnich 12+ miesięcy jako ORACLE PRZESZŁOŚCI. Każda zmiana reguły/parametru musi WYJAŚNIĆ każdą zmianę werdyktu na golden setcie diffem prawnym — nieuzasadniona delta = blokada merge. Do tego weryfikacja formalna (SMT/Z3) krytycznych podzbiorów reguł (dowód, że niezmienniki P04 nigdy nie zostaną złamane) i ewaluacja różnicowa (≥ 2 węzły, zgodność hashy werdyktów).",
"Zbadaj istniejące narzędzia (golden_replay.py, golden_autojustify.py, golden_baseline_seed.py, smt_z3_verification.py, differential_evaluation.py, bundles/golden_verdicts.json) — oceń, czego brakuje do pełnego oracle. Zaprojektuj pipeline: seed → okresowe re-generacje → delta analysis → auto-justification z diffem prawnym → bramka CI → dashboard oracle health.",
],
subparts=[
dict(name="Golden set: skład i seeding",
goal="reprezentatywny, nietykalny zbiór historycznych decyzji",
questions=[
"Co dziś zawiera bundles/golden_verdicts.json i czy jest reprezentatywny (domeny, granice, edge cases)?",
"Jak seedować golden set (golden_baseline_seed.py): próbka historyczna, syntetyczne granice, oba?",
"Jak golden set rośnie w czasie (12+ miesięcy) i jak jest wersjonowany (immutability)?",
"Jak chronić golden set przed manipulacją (hash, WORM, uprawnienia)?",
]),
dict(name="Delta analysis i auto-justification",
goal="każda zmiana werdyktu ma uzasadnienie prawne",
questions=[
"Czy golden_autojustify.py łączy deltę z diffem prawnym (P08) — czy uzasadnienie jest automatyczne czy ręczne?",
"Co się dzieje z nieuzasadnioną deltą (blokada, eskalacja, audyt) — czy jest egzekwowane w CI?",
"Jak klasyfikować delty (oczekiwane wg nowelizacji, błąd regresji, dryf danych)?",
"Jak mierzyć „zdrowie oracle” (liczba delt, % uzasadnionych, czas analizy)?",
]),
dict(name="Weryfikacja formalna (SMT/Z3)",
goal="dowód niezłamalności niezmienników dla krytycznych reguł",
questions=[
"Co pokrywa smt_z3_verification.py i które domeny są dziś weryfikowalne formalnie?",
"Jak translować Rego → SMT (ograniczenia języka, semantyka else-chain, agregacje)?",
"Jakie niezmienniki P04 da się udowodnić formalnie, a które tylko testami — macierz pokrycia?",
"Jak formalne dowody integrują się z CI (kiedy uruchamiane, co blokują)?",
]),
dict(name="Ewaluacja różnicowa i konsensus",
goal="ten sam input → ten sam hash na każdym węźle",
questions=[
"Czy differential_evaluation.py porównuje węzły/bundle/konfiguracje — jakie rozbieżności wykrywa?",
"Jak wdrożyć konsensus na ≥ 2 węzłach (co robić przy rozbieżności: alarm, blokada, degradacja)?",
"Jak różnicować nie tylko węzły, ale też wersje (stary bundle vs nowy na tym samym inputcie)?",
"Jak konsensus wpływa na certainty_class (P03): rozbieżność = NEEDS_ADVICE?",
]),
],
file_groups=[
dict(name="Narzędzia oracle", files=[
    ("Golden replay (narzędzie)", "JDG/tools/golden_replay.py"),
    ("Autojustification golden", "JDG/tools/golden_autojustify.py"),
    ("Seed golden baseline", "JDG/tools/golden_baseline_seed.py"),
    ("Weryfikacja SMT/Z3", "JDG/tools/smt_z3_verification.py"),
    ("Ewaluacja różnicowa", "JDG/tools/differential_evaluation.py"),
    ("Silnik samonaprawy (kontekst)", "JDG/tools/self_healing_engine.py"),
    ("Monitor jakości decyzji", "JDG/tools/decision_quality_monitor.py"),
]),
dict(name="Dane oracle", files=[
    ("Złote werdykty (bundle)", "JDG/bundles/golden_verdicts.json"),
    ("Kanon pokrycia", "JDG/bundles/coverage_canon.json"),
    ("Metryki pewności", "JDG/bundles/metrics_pewnosci.json"),
    ("Zdrowe wersje", "JDG/bundles/healthy_versions.json"),
]),
dict(name="Reguły jakości i raporty", files=[
    ("Reguła certyfikacji finalnej", "JDG/rules/final_certification_etap28_v1.rego"),
    ("Raport AD01 — canonical coverage", "JDG/raporty_glm52/RAPORT_AD01_CANONICAL_COVERAGE.txt"),
    ("Raport AD02 — LKG domknięcie", "JDG/raporty_glm52/RAPORT_AD02_LKG_DOMKNIECIE.txt"),
]),
dict(name="Testy oracle", files=[
    ("Test certyfikacji finalnej v4", "JDG/tests/test_final_certification_v4.py"),
    ("Test rekonsyliacji inwentarza", "JDG/tests/test_inventory_reconciliation.py"),
    ("Test bramki kampanii v3", "JDG/tests/auto/test_v3_campaign_gate.py"),
]),
],
focus=[
"Oceń reprezentatywność golden set (domeny × typy decyzji × granice) — macierz dziur.",
"Zaprojektuj politykę wersjonowania golden set (immutable wersje, hash, WORM).",
"Zaprojektuj auto-justification: delta → diff prawny (P08) → wyrok (UZASADNIONA/REGRESJA) z audytem.",
"Zaprojektuj bramkę CI: merge zablokowany dopóki każda delta nie ma wyroku.",
"Zbuduj macierz formalizowalności: niezmiennik P04 → metoda dowodu (SMT/property/test) → status.",
"Zaprojektuj pipeline Z3: subset reguł krytycznych → translacja → dowód/niewiadoma → raport per merge.",
"Zaprojektuj konsensus dual-node (hash werdyktu) z reakcją na rozbieżność (degradacja NEEDS_ADVICE).",
"Oceń wpływ golden oracle na lifecycle (P07): delta > próg = brak awansu automatycznego.",
"Zaplanuj metryki oracle: pokrycie decyzji, % uzasadnionych delt, wiek setu, częstotliwość re-gen.",
"Zaprojektuj ochronę przed „self-fulfilling oracle” (set zgodny z błędnymi regułami) — walidacja niezależna.",
"Wskaż domeny o najwyższym ryzyku regresji (P10–P36) — priorytet golden coverage.",
"Zaprojektuj eksport oracle do audytu zewnętrznego (dla KAS/audytora, z podpisami).",
],
legal=[
"Ordynacja podatkowa — art. 187b (utrzymanie mocy prawnej decyzji jako paradygmat nietykalności przeszłości)",
"Ustawa o rachunkowości — art. 4 ust. 6 (ciągłość stosowania zasad — paradygmat golden setu)",
"Ustawa o VAT — art. 86b (korekty wstecz — scenariusze delt uzasadnionych prawem)",
"Ustawa o PIT — art. 9 ust. 2 (forma na cały rok — granice delt temporalnych)",
"Zasada pewności prawa i zaufania do prawa (konstytucja art. 2) jako fundament oracle",
],
innovations=[
("Golden Vault WORM", "złote werdykty w storage niemodyfikowalnym (append-only, hash chain)"),
("Delta Autopsy Pipeline", "każda delta: klasyfikacja → uzasadnienie prawne → wyrok → audyt"),
("Merge Oracle Gate", "CI blokuje merge dopóki delty nie mają wyroków (zero nieuzasadnionych zmian)"),
("Formal Proof Matrix", "niezmiennik → metoda dowodu (SMT/property/fuzz) → status → CI hook"),
("Z3 Translation Harness", "testowalna translacja Rego→SMT z raportem nieweryfikowalnych fragmentów"),
("Dual-Node Consensus", "hash werdyktu na 2 węzłach; rozbieżność = auto-degradacja + alarm"),
("Oracle Health Dashboard", "metriki: pokrycie, % uzasadnionych delt, wiek, częstotliwość re-gen"),
("Independent Oracle Validator", "walidacja golden set niezależnym mechanizmem (anti self-fulfilling)"),
("Golden Coverage Planner", "plan domykania pokrycia golden per domena (priorytety ryzyka)"),
("Retro-Delta Explorer", "przeglądanie delt historycznych z uzasadnieniami (nauka systemu)"),
("Oracle Export & Seal", "eksport do audytu zewnętrznego z podpisem kryptograficznym"),
("Delta Regression Radar", "wczesny sygnał: rosnąca liczba nieuzasadnionych delt = dryf reguł"),
],
in_contracts=[
"Honoruj Snapshot ID i immutability przeszłości z V3_P05 — golden set jest jego audytorem.",
"Honoruj katalog niezmienników z V3_P04 — formalizowalność planujesz per niezmiennik.",
"Honoruj diff prawny z V3_P08 — auto-justification korzysta z tego samego źródła uzasadnień.",
"Honoruj lifecycle z V3_P07 — bramka oracle wchodzi w kryteria awansu.",
],
out_contracts=[
"Format golden setu i polityka wersjonowania — wiąże P39 (testy/CI) i P44.",
"Pipeline auto-justification — wiąże P07 (awans) i P38 (deploy).",
"Macierz formalizowalności — wiąże P04 (invarianty) i P44 (certyfikacja).",
"Konsensus dual-node — wiąże P38 (deployment) i P43 (DR).",
],
acceptance_extra=[
"Raport zawiera przykład end-to-end: zmiana reguły → delta golden → wyrok UZASADNIONA/REGRESJA.",
"Macierz formalizowalności obejmuje min. 15 niezmienników z metodą dowodu i statusem.",
]),

dict(code="P11", slug="DECISION_CERTIFICATE", title="DECISION CERTIFICATE — DOWÓD DECYZJI DLA PRZEDSIĘBIORCY (V2/F4)",
role="ekspertem podpisów kryptograficznych, dokumentacji dowodowej i UX zaufania w systemach finansowych",
expertise="certyfikaty decyzyjne (PDF ludzki + pieczęć kryptograficzna), Merkle/HSM, weryfikacja offline, klasy pewności",
mission=[
"Zbuduj pełny projekt Decision Certificate (V2/F4): każdy werdykt generuje certyfikat w dwóch warstwach — ludzkiej (PDF po polsku: podstawa prawna z cytatem przepisu w wersji z dnia transakcji, daty, progi, wersje reguł, wyjaśnienie decyzji prostym językiem) i kryptograficznej (SHA-256 → Merkle → podpis HSM/KMS) weryfikowalnej OFFLINE przez lata (retencja 50 lat audytowych).",
"Zbadaj istniejące narzędzia (decision_certificate.py, certificate_service.py, worm_storage.py, blockchain_audit_trail.py) — oceń gotowość. Zaprojektuj cykl życia certyfikatu: generacja → podpis → przechowywanie WORM → weryfikacja offline → eksport dla KAS/audytora → unieważnienie/korekta (certyfikat korekty wiąże się z oryginałem).",
],
subparts=[
dict(name="Warstwa ludzka certyfikatu",
goal="PDF zrozumiały dla przedsiębiorcy i księgowej",
questions=[
"Co dokładnie musi zawierać PDF (sekcje, cytaty prawne, progi, wyjaśnienia, QR do weryfikacji)?",
"Jak przedstawić klasę pewności i jej konsekwencje (CERTAIN = możliwe AUTO_POST; NEEDS_ADVICE = pytanie)?",
"Jak cytować przepis w wersji z dnia transakcji (dowód z P01/P05)?",
"Jak wyjaśniać decyzje prosto bez fałszowania złożoności (warstwy: krótko → szczegółowo → pełny dowód)?",
]),
dict(name="Warstwa kryptograficzna",
goal="pieczęć weryfikowalna offline przez dekady",
questions=[
"Czy certificate_service.py podpisuje (jakim kluczem, jakim algorytmem) i jak weryfikacja offline działa?",
"Jak zbudować Merkle tree per okres (dzień/miesiąc) i gdzie publikować root (transparencja)?",
"Czy worm_storage.py daje append-only i retencję 50 lat — jakie braki (szyfrowanie, replikacja, DR)?",
"Jak podpisywać kluczami HSM/KMS i jak zarządzać rotacją kluczy z zachowaniem weryfikowalności starych certyfikatów?",
]),
dict(name="Cykl życia i korekty",
goal="certyfikat żyje, koryguje się i archiwizuje",
questions=[
"Czy korekta decyzji tworzy certyfikat korekty powiązany z oryginałem (łańcuch wersji)?",
"Jak wygląda unieważnienie certyfikatu (CRL/manifest unieważnień) i kto może je wykonać?",
"Jak eksportować certyfikaty dla KAS/audytora (format, podpis, kompletność)?",
"Jak certyfikat łączy się z golden oracle (P10) — czy decyzja na golden secie ma swój certyfikat?",
]),
dict(name="Weryfikacja offline i UX zaufania",
goal="weryfikowalność bez dostępu do systemu",
questions=[
"Jak zbudować weryfikator offline (narzędzie/plik + instrukcja) dla przedsiębiorcy i audytora?",
"Co weryfikuje się offline: podpis, merkle root, legal refs hash, kompletność kontraktu?",
"Jak UI pokazuje status weryfikacji (zielony/żółty/czerwony) i prowadzi użytkownika przy błędzie?",
"Jak testować weryfikację offline (test: certyfikat sprzed 2 lat weryfikuje się dziś bez sieci)?",
]),
],
file_groups=[
dict(name="Narzędzia certyfikatów", files=[
    ("Decision certificate (narzędzie)", "JDG/tools/decision_certificate.py"),
    ("Certificate service", "JDG/tools/certificate_service.py"),
    ("WORM storage", "JDG/tools/worm_storage.py"),
    ("Audit trail (blockchain-style)", "JDG/tools/blockchain_audit_trail.py"),
    ("Kalkulator odsetek (kontekst danych)", "JDG/rules/exit_tax_interest_calculator.rego"),
    ("Metryki pewności", "JDG/tools/pewnosc_metrics.py"),
    ("Dashboard pewności", "JDG/tools/confidence_dashboard.py"),
]),
dict(name="Reguły provenance", files=[
    ("Provenance werdyktów", "JDG/rules/provenance.rego"),
    ("Scoring decyzji", "JDG/rules/decision_scoring_enterprise.rego"),
    ("Kompozytor decyzji", "JDG/rules/decision_composer_enterprise.rego"),
]),
dict(name="Dokumenty zaufania", files=[
    ("Dashboard pewności (dokument)", "JDG/docs/PEWNOSC_DASHBOARD.md"),
    ("Legal Twin (dokument)", "JDG/docs/LEGAL_TWIN_RAPORT.md"),
    ("Migracja 003 — legal twin", "JDG/migrations/003_jdg_v8_legal_twin.sql"),
]),
dict(name="Testy certyfikatów", files=[
    ("Test certyfikacji finalnej", "JDG/tests/test_final_certification_v4.py"),
    ("Test operating contract", "JDG/tests/test_enterprise_operating_contract.py"),
]),
],
focus=[
"Porównaj decision_certificate.py + certificate_service.py z V2/F4 — tabela wymóg→status→luka.",
"Zaprojektuj schemat certyfikatu (JSON) i jego reprezentację PDF (szablon sekcji).",
"Zaprojektuj Merkle architecture: per-werdykt hash → drzewo dziennie → root miesięczny → publikacja root.",
"Zaprojektuj HSM/KMS: klucz podpisujący, rotacja kwartalna, klucze offline DR, weryfikacja starych podpisów.",
"Zaprojektuj łańcuch korekt: oryginał → korekta 1 → korekta 2 (każdy podpisany, poprzedni nietykalny).",
"Zaprojektuj weryfikator offline (CLI/narzędzie) i test dekady (certyfikat sprzed lat weryfikuje się).",
"Zaprojektuj eksport dla KAS (paczka: certyfikaty + merkle root + legal snapshots z P01/P05).",
"Oceń spójność z provenance werdyktu (P03): certyfikat = superset pól werdyktu (zero informacji w PDF, których nie ma w JSON).",
"Zaplanuj retencję i DR (P43): replikacja WORM, testy odtworzenia, RPO/RTO dla archiwum.",
"Zaprojektuj UI zaufania (P41): status weryfikacji, historia decyzji, przycisk „pokaż dowód”.",
"Oceń wpływ na wydajność (podpis per werdykt vs batch) i zaprojektuj buforowanie/batching.",
"Zaprojektuj testy tamper-proof: modyfikacja certyfikatu → weryfikacja offline MUSI nie przejść.",
],
legal=[
"Ustawa o rachunkowości — art. 74 (retencja 5 lat dokumentów — i dłużej audytowo; paradygmat przechowywania)",
"Ustawa o PIT — art. 86 § 3 Ordynacji (obowiązek przechowywania dowodów — retencja)",
"Ordynacja podatkowa — art. 86 § 1 (obowiązek przechowywania dokumentacji, retencja jako wymóg)",
"Ustawa o VAT — art. 106b (faktura jako dowód — paradygmat dokumentu z kompletnymi danymi)",
"Rozporządzenie MF o kasach/dowodach (paradygmat wydruku fiskalnego jako dowód dla podatnika)",
"eIDAS / podpis kwalifikowany jako paradygmat prawnego znaczenia podpisu (kontekst UE)",
],
innovations=[
("Certificate Schema v1", "pełny schemat certyfikatu (JSON) z wiążącym odwzorowaniem PDF"),
("Merkle Daily Tree", "drzewa dziennie + root miesięczny + publiczny rejestr rootów (transparencja)"),
("Offline Verifier CLI", "samodzielny weryfikator (bez sieci) dla przedsiębiorcy i audytora"),
("Correction Chain", "łańcuch korekt podpisanych, nietykalnych wstecz"),
("Revocation Manifest", "podpisany manifest unieważnień rozpowszechniany z certyfikatami"),
("KAS Export Bundle", "paczka dla organu: certyfikaty + merkle + snapshoty przepisów (P01/P05)"),
("HSM Key Ceremony", "procedura inicjalizacji i rotacji kluczy z audytem ceremonii"),
("Trust UI Pattern", "wzorce UX zaufania: status weryfikacji, „pokaż dowód”, wyjaśnienie warstwowe"),
("Tamper Test Suite", "testy manipulacji: zmiana pola → weryfikacja MUSI zawieść"),
("Batch Signing", "podpisywanie batchowe z budżetem latencji (zero degeneracji SLO)"),
("Long-Term Validation", "LTV: znaczniki czasu i algorytmy odporne na dekady (sztuka inżynierii)"),
("Certificate Golden Link", "decyzje golden setu mają certyfikaty — dowód spójności oracle (P10)"),
],
in_contracts=[
"Honoruj kontrakt werdyktu i certainty_class z V3_P03 — certyfikat jest nadzbiorem werdyktu.",
"Honoruj legal refs i dowody przepisu z V3_P01/P05 — PDF cytuje przepis w wersji z dnia transakcji.",
"Honoruj oracle z V3_P10 — decyzje golden mają certyfikaty (spójność dowodowa).",
],
out_contracts=[
"Schemat certyfikatu i format PDF — wiąże P41 (UI/API) i P44 (certyfikacja finalna).",
"Architektura HSM/Merkle/WORM — wiąże P43 (security/DR) i P38 (deployment).",
"Łańcuch korekt i unieważnień — wiąże P36 (kalendarz/procesy) i P44.",
"Eksport KAS — wejście do P44 (definicja sukcesu: dowód dla organów).",
],
acceptance_extra=[
"Raport zawiera przykładowy certyfikat (JSON + zarys PDF) dla jednej decyzji end-to-end.",
"Zawiera projekt weryfikatora offline i test dekady.",
]),

dict(code="P12", slug="VAT_STAWKI_ZWOLNIENIA", title="VAT — STAWKI, ZWOLNIENIA I KLASYFIKACJA (MACRO + MICRO)",
role="najwyższej klasy ekspertem podatku VAT w Polsce i audytorem reguł Rego",
expertise="art. 41-43 VAT (stawki/zwolnienia), art. 113 (limit podmiotowy), GTU, WIS, klasyfikacja PKWiU/CN, obniżone stawki z rozporządzeń",
mission=[
"Przeprowadź pełny audyt reguł VAT w warstwach macro (rules/vat/*) i micro (rules/micro/vat/*): stawki 23/8/5/0/NP, zwolnienia przedmiotowe (art. 43) i podmiotowe (art. 113), załączniki (zał. 10 obniżone, zał. 15 MPP — kontekst), GTU auto-klasyfikacja, WIS. Dla KAŻDEGO przepisu materiałnego: reguła → test → status (PEŁNE/CZĘŚCIOWE/BRAK) → ryzyko. Zestawiaj z dokumentem źródeł prawnych (JDG/docs/Bbb) i weryfikuj w ISAP.",
"Zaprojektuj docelowy model stawek jako DANYCH (z P06): tabele stawek/zwolnień wersjonowane z datami obowiązywania, walidacja zakresów, golden dataset. Wykryj wszystkie wartości hardcoded w regułach VAT i zaprojektuj migrację. Zapewnij fail-closed: niejednoznaczna klasyfikacja → NEEDS_ADVICE, nigdy cichy wybór stawki.",
],
subparts=[
dict(name="Stawki i tabela klasyfikacyjna",
goal="kompletna macierz towar/usługa → stawka → warunek → przepis",
questions=[
"Czy reguły pokrywają wszystkie stawki (23/8/5/0/NP) i przejścia między nimi (korekty stawek)?",
"Czy załącznik 10 (obniżone stawki) jest reprezentowany jako dane czy hardcode — jak ewidencjonować wersje?",
"Jak obsłużone są zwolnienia częściowe (art. 43 ust. 2 vs ust. 3) — wykrywalne konflikty?",
"Czy limit art. 113 (200 000 zł) jest parametrem z valid_from i śledzeniem przekroczenia (naruszenie w trakcie roku)?",
]),
dict(name="Zwolnienia przedmiotowe art. 43",
goal="kompletność katalogu zwolnień z warunkami",
questions=[
"Które zwolnienia z art. 43 (lit. a-z) mają reguły — tabela: zwolnienie → warunki → reguła → test?",
"Czy warunki zwolnień (np. art. 43 ust. 1 pkt 7: powierzchnia < 80 m2 itd.) są kompletne i parametryzowane?",
"Jak obsłużona jest rezygnacja ze zwolnienia (art. 44) i powrót — temporalność?",
"Czy są reguły dla zwolnień sektorowych (rolnictwo art. 43 ust. 1 lit. f, finanse lit. g-h) — jak głębokie?",
]),
dict(name="GTU, WIS i klasyfikacja",
goal="auto-klasyfikacja towarów i usług bez błędów",
questions=[
"Czy GTU_01-GTU_13 (zał. 15) mają reguły auto-klasyfikacji — tabela kody→reguła→test?",
"Czy WIS (wspólny indywidualny system) jest obsługiwany dla elektroniki — warunki, monitoring limitów?",
"Jak klasyfikacja PKWiU/CN mapuje się na stawki/GTU — czy mapa jest danem, czy hardcode?",
"Czy niejednoznaczna klasyfikacja prowadzi do NEEDS_ADVICE (fail-closed) czy cichego wyboru?",
]),
dict(name="Spójność macro/micro i luki",
goal="jedna prawda VAT w dwóch warstwach",
questions=[
"Gdzie macro i micro (micro/vat/vat.rego ~571 reguł) się dublują lub rozjeżdżają — tabela konfliktów?",
"Które przepisy VAT z Bbb nie mają ŻADNEJ reguły (pustynia pokrycia VAT)?",
"Które reguły VAT nie mają testów natywnych Rego — lista do P39?",
"Jak VAT kontraktuje się z KSeF/JPK (P16), cross-border (P15), ryczałtem (P14) — czy pola są zgodne?",
]),
],
file_groups=[
dict(name="VAT macro (rules/vat)", files=[
    ("Substantive VAT", "JDG/rules/vat/substantive.rego"),
    ("Plan42 reduced rates", "JDG/rules/vat/plan42_reduced_rates.rego"),
    ("Plan23 detailed", "JDG/rules/vat/plan23_detailed.rego"),
    ("Plan26 critical", "JDG/rules/vat/plan26_critical.rego"),
    ("Place of supply", "JDG/rules/vat/place_of_supply.rego"),
    ("VAT enterprise zero doubt", "JDG/rules/vat/vat_enterprise_zero_doubt.rego"),
    ("Enterprise VAT bridge", "JDG/rules/vat/enterprise_vat_bridge.rego"),
]),
dict(name="VAT micro (rules/micro/vat)", files=[
    ("VAT micro rdzeń", "JDG/rules/micro/vat/vat.rego"),
    ("WDT/eksport/import", "JDG/rules/micro/vat/wdt_export_import.rego"),
    ("Place of supply micro", "JDG/rules/micro/vat/place_of_supply_micro.rego"),
    ("Proporcja VAT", "JDG/rules/micro/vat/proportion_vat.rego"),
    ("Schemat marży", "JDG/rules/micro/vat/margin_scheme_micro.rego"),
    ("KSeF micro", "JDG/rules/micro/vat/ksef_micro.rego"),
    ("R03 VAT artykuły", "JDG/rules/micro/vat/r03_vat_micro_articles.rego"),
]),
dict(name="VAT enterprise i audyt stawek", files=[
    ("VAT substantive complete", "JDG/rules/vat_substantive_complete_enterprise.rego"),
    ("Audyt stawek/zwolnień", "JDG/rules/vat_rates_exemptions_audit_enterprise.rego"),
    ("Innowacje VAT macro", "JDG/rules/p04_vat_macro_enterprise_v9.rego"),
    ("Innowacje VAT micro atomic", "JDG/rules/p05_vat_micro_atomic_v9.rego"),
    ("Plan33 VAT", "JDG/rules/micro/plan33_vat.rego"),
    ("Plan34 VAT", "JDG/rules/micro/plan34_vat.rego"),
]),
dict(name="Dane, progi i dokumenty", files=[
    ("Dane progów", "JDG/bundles/thresholds_data.json"),
    ("Progi centralne", "JDG/rules/thresholds_jdg.rego"),
    ("Pokrycie prawne (dokument)", "JDG/docs/LEGAL_COVERAGE.md"),
    ("Raport VAT audytu (dokument)", "JDG/docs/VAT_AUDYT_R03.md"),
    ("Audyt VAT macro (narzędzie)", "JDG/tools/vat_macro_audit.py"),
    ("Audyt VAT micro", "JDG/tools/vat_micro_core_audit.py"),
    ("Inwentarz VAT micro", "JDG/tools/vat_micro_inventory.py"),
]),
dict(name="Testy VAT", files=[
    ("Test VAT enterprise", "JDG/tests/test_vat_enterprise.py"),
    ("Test VAT macro audytu", "JDG/tests/test_vat_macro_audit.py"),
    ("Test VAT micro core", "JDG/tests/test_vat_micro_core_audit.py"),
    ("Test VAT micro special", "JDG/tests/test_vat_micro_special_audit.py"),
    ("Test natywny VAT macro", "JDG/tests/rego/test_p03_vat_macro_enterprise.rego"),
    ("Test natywny VAT micro", "JDG/tests/rego/test_p04_vat_micro_enterprise.rego"),
    ("Test natywny VAT", "JDG/tests/rego/test_native_vat_micro.rego"),
]),
],
focus=[
"Zbuduj macierz art. 41/43/113 → reguła → test → status — dla KAŻDEGO materiałnego przepisu z Bbb.",
"Wypisz wszystkie hardcoded stawki/limity w regułach VAT (tabele) i zaprojektuj migrację do danych (P06).",
"Zaprojektuj tabelę stawek jako wersjonowane dane (valid_from/valid_to, źródło: rozporządzenie) — spójnie z P06.",
"Zaprojektuj GTU classifier jako dane+reguły (mapa kodów, walidacja PKWiU/CN) z NEEDS_ADVICE przy niepewności.",
"Zbadaj przejścia stawek w czasie (korekta po zmianie stawki — art. 90/91 kontekst) i ich pokrycie.",
"Zaprojektuj granice testów: 199 999,99 / 200 000,00 (limit 113), granice groszy, zero, waluty.",
"Oceń integrację WIS z limitami elektroniki (monitoring, autorequest — P13 cross-border kontekst).",
"Wypisz pustynie pokrycia VAT (przepisy bez reguł) z priorytetami i ryzykiem finansowym.",
"Zaprojektuj spójność macro↔micro: mechanizm wykrywania rozjazdów (single source of truth per przepis).",
"Zaprojektuj testy property: stawka ∈ {0,5,8,23,NP}; suma podatku ≥ 0; VAT należny − naliczony = spójne pola JPK.",
"Sprawdź zgodność pól VAT z kontraktem werdyktu (P03) i JPK_V7 (P16).",
"Wyznacz 10 największych ryzyk błędnej decyzji VAT (kwotowo) i zaprojektuj dla nich invarianty (P04).",
],
legal=[
"Ustawa o VAT — art. 41 (stawki podstawowe i obniżone)",
"Ustawa o VAT — art. 43 (zwolnienia przedmiotowe, ust. 1 lit. a-z, ust. 2-3)",
"Ustawa o VAT — art. 113 (zwolnienie podmiotowe 200 000 zł)",
"Ustawa o VAT — art. 109 (ewidencja VAT)",
"Ustawa o VAT — zał. 10 (towary/usługi stawkami obniżonymi), zał. 15 (GTU + MPP)",
"Rozporządzenie MF z 4.12.2024 (obniżone stawki VAT) — zweryfikować w ISAP",
"Rozporządzenie MF z 15.7.2025 (JPK_VAT z deklaracją) — struktura GTU w JPK",
],
innovations=[
("Rates-as-Data VAT Engine", "tabele stawek/zwolnień wersjonowane z datami i źródłami (ISAP link)"),
("Exemption Matrix Complete", "pełna macierz art. 43 (lit. a-z) z warunkami parametryzowanymi i testami"),
("GTU Semantic Classifier", "klasyfikacja GTU z mapy PKWiU/CN jako dane + NEEDS_ADVICE przy niepewności"),
("Limit 113 Sentinel", "monitoring przekroczenia limitu 200k w trakcie roku (alarm przed przekroczeniem)"),
("VAT Rate Golden Set", "golden dataset stawek granicznych (199 999,99 / 200 000 / 200 000,01)"),
("Macro-Micro Consistency Gate", "CI: brak sprzecznych odpowiedzi macro vs micro na tym samym inputcie"),
("VAT Coverage Desert Map", "mapa przepisów bez reguł z planem zasiedlenia priorytetyzowanym kwotowo"),
("Simplified vs Normal Advisor", "doradca: czy podatnik powinien być na VAT-O (symulator korzyści)"),
("Rate Change Corrector", "korekta faktur po zmianie stawki (art. 90/91 kontekst) z automatyzacją"),
("VAT Invariants Pack", "pack niezmienników VAT dla P04 (stawka∈set, VAT≥0, spójność JPK)"),
("Exemption Waiver Tracker", "śledzenie rezygnacji/powrotu ze zwolnienia (art. 44) z temporalnością"),
("Classification Confidence", "każda klasyfikacja niesie pewność; niska pewność = NEEDS_ADVICE (fail-closed)"),
],
in_contracts=[
"Honoruj schemat parametrów z V3_P06 — stawki/limity VAT to dane, nie hardcode.",
"Honoruj katalog niezmienników z V3_P04 — propozycje VAT dodawaj jako rozszerzenia, nie duplikaty.",
"Honoruj kontrakt werdyktu z V3_P03 — klasyfikacja niesie certainty_class.",
"Honoruj legal_node_id z V3_P01 — każda reguła VAT podpięta pod węzeł przepisu.",
],
out_contracts=[
"Macierz pokrycia VAT (art. → reguła → test) — wiąże P16 (JPK/KSeF) i P44.",
"Tabela stawek jako dane — wiąże P06 i P14 (ryczałt progi).",
"Lista invariantów VAT — wejście do P04/P39.",
"Lista pustyn pokrycia VAT — wejście do P44 (plan domknięcia).",
],
acceptance_extra=[
"Macierz obejmuje wszystkie przepisy VAT wymienione w Bbb (art. 41/43/113 minimum) ze statusem i ryzykiem.",
"Każda propozycja stawki/zwolnienia ma cytat przepisu i status weryfikacji ISAP.",
]),

dict(code="P13", slug="VAT_ODLICZENIA_MPP", title="VAT — ODLICZENIA, PROPORCJE, KOREKTY, MPP/SPLIT PAYMENT I FRAUD",
role="najwyższej klasy ekspertem rozliczeń VAT, mechanizmu podzielonej płatności i wykrywania fraudu",
expertise="art. 86-96 VAT (odliczenia, proporcje, korekty art. 89-91, złe długi art. 89a), art. 108a-108f (MPP), Biała Lista art. 96b, solidarne odpowiedzialności art. 106a",
mission=[
"Audytuj pełen cykl odliczeń VAT: prawo do odliczenia (art. 86), moment (art. 86b), ograniczenia (art. 88, auta art. 88 ust. 2-4), proporcja (art. 90-91), korekty (art. 89/89a/89b/91), prefinansowanie (art. 86b ust. 2). Dla każdej ścieżki: reguła → test → status → ryzyko. Zaprojektuj granice groszowe i property testy (suma odliczeń ≤ należny).",
"Audytuj MPP (art. 108a-108d): lista zał. 15, próg 15 000 zł, obowiązkowy rachunek VAT, skutki braku MPP (sanctions art. 108d). Zaprojektuj auto-detekcję MPP (P13 narzędzie istnieje — vat_mpp_auto_detector.py, mpp_monitor.py) i fraud detection (vat_fraud_detection_enterprise.rego, fraud_graph_scanner.py): puste faktury, karuzele, scoring ryzyka kontrahenta (Biała Lista art. 96b) — zawsze jako SYGNAŁ z human review, nigdy automatyczna wina.",
],
subparts=[
dict(name="Prawo do odliczenia i moment",
goal="art. 86-87 kompletnie i fail-closed",
questions=[
"Czy reguły pokrywają warunki art. 86 ust. 1 (związek z czynnościami opodatkowanymi)?",
"Czy moment odliczenia (art. 86b: miesiąc/3 miesiące, prefinansowanie) jest regułowany z datami?",
"Czy auta (art. 88 ust. 2: 50%/0%, użycie mieszane) mają reguły z proporcją?",
"Czy ograniczenia art. 88 (usługi hotelowe, gastronomia itd.) są kompletne — tabela?",
]),
dict(name="Proporcja i korekty",
goal="art. 90-91 wieloletnie i art. 89-89b",
questions=[
"Czy proporcja (art. 90) jest liczona jako reguła z danymi (obroty) i zaokrągleniami do 1%?",
"Czy korekty wieloletnie (art. 91: nieruchomości 10 lat, inne 5 lat) mają pełny harmonogram roczny?",
"Czy złe długi (art. 89a: 90 dni, wiek należności) mają reguły z datami i monitoringiem?",
"Czy korekty in plus/in minus są symetryczne i testowane na granicach okresów?",
]),
dict(name="MPP / split payment",
goal="art. 108a-108d kompletnie z auto-detekcją",
questions=[
"Czy lista zał. 15 jest danem (wersjonowana) czy hardcode — jak ewidencjonować zmiany?",
"Czy próg 15 000 zł (z dopiskami: netto z VAT? per faktura?) jest regułowany poprawnie i parametryzowany?",
"Czy brak MPP generuje sankcje art. 108d (dopłata 30%/100%) w regułach i alertach?",
"Czy vat_mpp_auto_detector.py i mpp_monitor.py są zintegrowane z regułami (alerty, tracking)?",
]),
dict(name="Fraud, Biała Lista i ochrona",
goal="sygnały ryzyka z human review",
questions=[
"Czy fraud_graph_scanner.py wykrywa wzorce karuzel (graf transakcji) — jakie sygnały, jakie progi?",
"Czy Biała Lista (art. 96b: weryfikacja przed przelewem > 15k) jest regułą z integracją API MF (fallback)?",
"Czy solidarna odpowiedzialność (art. 106a) ma reguły (kontekst w VAT_AUDYT_R03.md)?",
"Czy scoring fraudu prowadzi do NEEDS_ADVICE/blokady płatności (fail-closed) czy tylko do flagi?",
]),
],
file_groups=[
dict(name="VAT odliczenia (macro)", files=[
    ("Deductions VAT", "JDG/rules/vat/deductions.rego"),
    ("Procedures VAT", "JDG/rules/vat/procedures.rego"),
    ("Plan23 detailed", "JDG/rules/vat/plan23_detailed.rego"),
    ("Plan26 critical", "JDG/rules/vat/plan26_critical.rego"),
]),
dict(name="VAT odliczenia (enterprise)", files=[
    ("Deductions corrections", "JDG/rules/vat_deductions_corrections_enterprise.rego"),
    ("MPP split payment", "JDG/rules/vat_mpp_split_payment_enterprise.rego"),
    ("Fraud detection", "JDG/rules/vat_fraud_detection_enterprise.rego"),
    ("Solidarne odpowiedzialności", "JDG/rules/solidarity_auto_calc_enterprise.rego"),
    ("Korekty (rdzeń)", "JDG/rules/corrections.rego"),
    ("Zegar przedawnienia (kontekst)", "JDG/rules/statute_of_limitations.rego"),
]),
dict(name="Narzędzia MPP, fraud i monitoringu", files=[
    ("Auto-detektor MPP", "JDG/tools/vat_mpp_auto_detector.py"),
    ("Monitor MPP", "JDG/tools/mpp_monitor.py"),
    ("Weryfikacja MPP", "JDG/tools/verify_vat_mpp.py"),
    ("Skanner grafu fraudu", "JDG/tools/fraud_graph_scanner.py"),
    ("Monitor limitu 2M (kontekst)", "JDG/tools/limit_2m_monitor.py"),
    ("Audyt VAT micro", "JDG/tools/vat_micro_special_audit.py"),
]),
dict(name="Dokumenty i testy", files=[
    ("Raport VAT audytu (dokument)", "JDG/docs/VAT_AUDYT_R03.md"),
    ("Test VAT enterprise", "JDG/tests/test_vat_enterprise.py"),
    ("Test VAT MPP natywny", "JDG/tests/rego/test_native_vat_mpp.rego"),
    ("Test VAT A113 tracker", "JDG/tests/rego/test_native_vat_a113_tracker.rego"),
    ("Test VAT deductions natywny", "JDG/tests/rego/test_native_vat_deductions_enterprise.rego"),
    ("Test VAT fraud natywny", "JDG/tests/rego/test_native_vat_fraud_enterprise.rego"),
    ("Test korekt (rdzeń)", "JDG/tests/auto/test_auto_block_corrections.py"),
]),
],
focus=[
"Zbuduj macierz art. 86/88/89a/90/91/108a → reguła → test → status → ryzyko (każdy przepis materiałny).",
"Zaprojektuj harmonogram korekt wieloletnich (art. 91) jako dane (rok korekty → %) z testami granicznymi lat.",
"Zaprojektuj listę zał. 15 jako wersjonowane dane z walidacją (PKWiU/CN) i historią zmian.",
"Zaprojektuj auto-detekcję MPP end-to-end (faktura → wykrycie → flaga → alert → tracking płatności MPP).",
"Zaprojektuj granice: 14 999,99 / 15 000,00 / 15 000,01 (MPP), dzień 90/91 (złe długi), 1% proporcji.",
"Zaprojektuj property tests: suma odliczeń ≤ VAT należny (przed zwolnieniem), proporcja ∈ [0,100]%.",
"Oceń integrację Biała Lista: API MF, cache TTL, fallback offline (degradacja NEEDS_ADVICE), audit weryfikacji.",
"Zaprojektuj fraud scoring jako sygnał: próg → NEEDS_ADVICE, extreme → MANUAL_REVIEW — nigdy automatyczna wina.",
"Zaprojektuj invarianty VAT: MPP obowiązkowy → faktura MPP (BLOCKER bez), odliczenie tylko dla VAT-O.",
"Wskaż pustynie pokrycia odliczeń (art. bez reguł) i priorytetyzuj kwotowo.",
"Zaprojektuj scenariusze stress: 1000 faktur MPP jednocześnie, korekta wieloletnia masowa, fraud łańcuchowy.",
"Sprawdź spójność z P12 (stawki) i P16 (JPK_V7 pola MPP/GTU) — kontrakty pól.",
],
legal=[
"Ustawa o VAT — art. 86-87 (prawo do odliczenia i moment)",
"Ustawa o VAT — art. 88 (wyłączenia odliczeń, auta 50%)",
"Ustawa o VAT — art. 89, 89a, 89b (korekty, złe długi: 90 dni)",
"Ustawa o VAT — art. 90-91 (proporcja, korekty: nieruchomości 10 lat, inne 5)",
"Ustawa o VAT — art. 108a-108d (MPP: zał. 15, 15 000 zł, sankcje)",
"Ustawa o VAT — art. 96b (Biała Lista: weryfikacja > 15 000 zł)",
"Ustawa o VAT — art. 105a-106a (odpowiedzialność solidarnej i specustawa)",
],
innovations=[
("Deduction Rights Engine", "pełny silnik art. 86: warunki → moment → ograniczenia z datami"),
("Multi-Year Correction Planner", "harmonogram art. 91 (5/10 lat) z automatycznymi korektami rocznymi"),
("Bad Debt Radar", "monitoring 90 dni (art. 89a) z alertami i automatyczną korektą in minus"),
("MPP Obligation Detector", "auto-detekcja MPP (lista+próg) z trackingiem płatności i sankcji 108d"),
("Annex 15 as Versioned Data", "lista towarów MPP jako dane z historią i walidacją"),
("White List Gate", "integracja Białej Listy: weryfikacja przed przelewem, cache, fallback NEEDS_ADVICE"),
("Fraud Signal Framework", "graf transakcji → sygnały (karuzele, puste faktury) → human review (nigdy wina)"),
("Proportion Precision Engine", "proporcja art. 90 z groszówką, testami 1% i granicami obrotów"),
("VAT Balance Invariants", "odliczenia ≤ należny; symetria korekt; spójność JPK (do P04)"),
("VAT Stress Lab", "scenariusze 1000 faktur, masowe korekty, fraud chains — testy wydajności i poprawności"),
("Correction Symmetry Guard", "korekta in minus/in plus zawsze symetryczna i audytowalna"),
("Payment Safe-Pay Advisor", "doradca płatności: kontrahent + MPP + Biała Lista → „bezpiecznie zapłać tak”"),
],
in_contracts=[
"Honoruj tabelę stawek jako dane z V3_P12 — listy (zał. 15) dołączają do tego samego wzorca.",
"Honoruj invariants z V3_P04 — VAT Balance Invariants jako rozszerzenia katalogu.",
"Honoruj kontrakt werdyktu z V3_P03 — fraud scoring wpływa na certainty_class, nie na winę.",
],
out_contracts=[
"Harmonogram korekt art. 91 — wiąże P16 (JPK korekty) i P14 (ryczałt korekty).",
"MPP tracking — wiąże P16 (pola JPK_V7 MPP) i P41 (UI płatności).",
"Fraud signals — wiąże P36 (procesy) i P41 (UI review).",
"Lista pustyn odliczeń — wejście do P44.",
],
acceptance_extra=[
"Macierz obejmuje art. 86, 88, 89a, 90, 91, 108a-108d, 96b ze statusem i ryzykiem.",
"Każdy granica kwotowa (15k, 90 dni, 1%) ma test graniczny zaprojektowany w planie testów.",
]),

dict(code="P14", slug="PIT_ULGI_OPTYMALIZACJA", title="PIT — FORMY OPODATKOWANIA, ULGI I OPTYMALIZACJA",
role="najwyższej klasy ekspertem podatku dochodowego od osób fizycznych JDG i optymalizacji legalnej",
expertise="art. 9a/27/30c PIT (formy), art. 26/26e/26eb/26gb/26h/30ca (ulgi), art. 21 ust. 1 pkt 148/152/153/154 (zwolnienia), art. 44 (zaliczki), art. 22-23 (KUP)",
mission=[
"Audytuj komplet ulg PIT dla JDG: B+R (art. 26e), prototyp (26eb), robotyzacja (26gb), termomodernizacja (26h, limit 53 000 zł), IP Box (30ca, 5%), ekspansja (26ec), rehabilitacyjna (26), sowie optymalizację między ulgami (cross_relief_optimizer). Dla każdej ulgi: definicja ustawowa → warunki → reguła → test → limit → status. Zestawiaj z Bbb (lista ulg jest tam kompletna) i weryfikuj w ISAP.",
"Audytuj formy opodatkowania: skala (art. 27: 12%/32%, kwota zmniejszająca), liniowy (30c: 19%), ryczałt (P14), karta (art. 30). Zaprojektuj form transition intelligence (tax_form_transition_intelligence.rego, form_transition_simulator, form_simulator.py): symulator porównania form na danych historycznych, proaktywny doradca zmiany (do 20 dnia lutego, art. 9 ust. 2 — na kolejny rok). Zaliczki (art. 44): harmonogram, metoda uproszczona, granice kwotowe, kwota wolna 30 000 zł (skala).",
],
subparts=[
dict(name="Ulgi inwestycyjne i innowacyjne",
goal="komplet ulg z warunkami i limitami",
questions=[
"Czy B+R (26e: 100% koszty, 200% personalne) ma reguły z definicją działalności B+R (dokumentacja)?",
"Czy IP Box (30ca: 5%, nexus ratio) ma reguły kwalifikacji (jakie przychody, jakie koszty)?",
"Czy termomodernizacja (26h: limit 53 000 zł, lista przedsięwzięć) jest kompletna — kto weryfikuje listę?",
"Czy prototyp (26eb: 30%), robotyzacja (26gb: 50%), ekspansja (26ec) mają reguły z warunkami i limitem czasowym (ulgi inwestycyjne)?",
]),
dict(name="Ulgi społeczne i zwolnienia",
goal="art. 21 zwolnienia i art. 26 rehabilitacja",
questions=[
"Czy Ulga dla młodych (21 ust. 1 pkt 148: do 85 528 zł, do 26 lat) ma reguły z granicą wieku i kwotą?",
"Czy powrót (152: 4 lata), rodziny 4+ (153), pracujący emeryci (154) są kompletne z warunkami?",
"Czy rehabilitacyjna (26 ust. 1 pkt 6: lista wydatków, limit 2 280 zł samochód) ma katalog wydatków jako dane?",
"Jak zwolnienia składają się z pozostałymi ulgami (kolejność odliczeń — invariant: suma ≤ dochód)?",
]),
dict(name="Formy opodatkowania i zaliczki",
goal="wybór formy i harmonogram zaliczek",
questions=[
"Czy skala (27: 12%/32% + 3600 kwota zmniejszająca) jest parametryzowana z valid_from (roczne progi)?",
"Czy liniowy (30c: 19%) i przejścia skala↔liniowy (ograniczenia 9 ust. 2) są regułowane?",
"Czy zaliczki (44: miesięczne/kwartalne, metoda uproszczona 20%/50% r/r) mają harmonogramy z datami?",
"Czy kwota wolna 30 000 (skala) jest uwzględniona w zaliczkach i rocznym — granice testów?",
]),
dict(name="Optymalizacja i doradca formy",
goal="legalna optymalizacja z wyjaśnieniem",
questions=[
"Czy cross_relief_optimizer.rego optymalizuje kolejność/odliczenia (invariants) — czy jest testowany?",
"Czy form_transition_simulator porównuje formy na danych historycznych (12 miesięcy) z założeniami przyszłości?",
"Czy doradca zmiany formy działa proaktywnie (deadline art. 9 ust. 2 — do 20.02) z alertami?",
"Czy optymalizacja daje wyjaśnienie (dlaczego ta forma) i pewność (NEEDS_ADVICE przy niepewności)?",
]),
],
file_groups=[
dict(name="PIT core (rules/pit)", files=[
    ("KUP PIT", "JDG/rules/pit/kup.rego"),
    ("Exemptions PIT", "JDG/rules/pit/exemptions.rego"),
    ("Advances and returns", "JDG/rules/pit/advances_returns.rego"),
    ("Transitions form", "JDG/rules/pit/transitions.rego"),
    ("Forms PIT", "JDG/rules/pit/forms.rego"),
    ("Plan26 detailed", "JDG/rules/pit/plan26_detailed.rego"),
    ("Plan23 exemptions", "JDG/rules/pit/plan23_exemptions.rego"),
]),
dict(name="Ulgi enterprise", files=[
    ("Art. 21 exemptions", "JDG/rules/pit/art21_exemptions_enterprise.rego"),
    ("Termomodernizacja", "JDG/rules/pit/thermo_relief_enterprise.rego"),
    ("B+R", "JDG/rules/pit/rd_relief_enterprise.rego"),
    ("IP Box", "JDG/rules/pit/ipbox_enterprise.rego"),
    ("Donation", "JDG/rules/pit/donation_relief_enterprise.rego"),
    ("Cross relief optimizer", "JDG/rules/pit/cross_relief_optimizer_enterprise.rego"),
    ("Tax loss harvesting", "JDG/rules/pit/tax_loss_harvesting_enterprise.rego"),
    ("Family Estonian", "JDG/rules/pit/family_estonian_enterprise.rego"),
    ("Missing reliefs", "JDG/rules/pit/missing_reliefs_enterprise.rego"),
    ("KUP extended", "JDG/rules/pit/kup_extended.rego"),
    ("E-learning", "JDG/rules/pit/elearning.rego"),
]),
dict(name="Formy i symulatory", files=[
    ("Form transition intelligence", "JDG/rules/pit/tax_form_transition_intelligence.rego"),
    ("Form transition simulator", "JDG/rules/form_transition_simulator_enterprise.rego"),
    ("Annual declaration", "JDG/rules/annual_declaration_enterprise.rego"),
    ("Plan23 tax form change", "JDG/rules/pit/plan23_tax_form_change.rego"),
    ("Plan26 PIT critical", "JDG/rules/pit/plan26_pit_critical.rego"),
    ("Enterprise zero doubt", "JDG/rules/pit/pit_enterprise_zero_doubt.rego"),
    ("Declaration extensions", "JDG/rules/pit/declaration_extensions_enterprise.rego"),
]),
dict(name="Narzędzia PIT i testy", files=[
    ("Optimizer ulg PIT", "JDG/tools/pit_reliefs_optimizer.py"),
    ("Symulator form", "JDG/tools/form_simulator.py"),
    ("Silnik roczny PIT", "JDG/tools/pit_annual_engine.py"),
    ("Audyt PIT macro", "JDG/tools/pit_macro_audit.py"),
    ("Audyt ulg micro", "JDG/tools/pit_micro_reliefs_audit.py"),
    ("Test PIT enterprise", "JDG/tests/auto/test_p05_pit_macro_enterprise_glm52.py"),
    ("Test ulgi", "JDG/tests/auto/test_p07_ulgi_enterprise_glm52.py"),
    ("Test natywny PIT kup", "JDG/tests/rego/test_native_pit_kup.rego"),
    ("Test natywny reliefs", "JDG/tests/rego/test_native_reliefs.rego"),
    ("Test PIT audyt R04", "JDG/tests/auto/test_pit_audyt_r04_enterprise.py"),
]),
],
focus=[
"Zbuduj macierz ulg: ulga → przepis → warunki → limit → reguła → test → status (każda ulga z Bbb).",
"Zaprojektuj limity jako dane (53 000 termo, 85 528 młodych, 2 280 auto) z valid_from (zmiany roczne).",
"Zaprojektuj invariant: suma odliczeń ≤ dochód (P04) z testem property na ulgach.",
"Zaprojektuj IP Box nexus ratio (koszty B+R / koszty) z testami granicznymi i dokumentacją wymogów.",
"Zaprojektuj harmonogram zaliczek (44) z granicami: 20. miesiąca, kwartalna do 20., metoda uproszczona.",
"Zaprojektuj kwota wolna 30 000 (skala): granice 29 999,99/30 000/30 000,01 i wpływ na zaliczki.",
"Zaprojektuj doradca formy end-to-end: dane 12 mies. → symulacja → raport (skala vs liniowy vs ryczałt) → deadline alert.",
"Oceń tax loss harvesting (art. 9 ust. 3: 50% straty, 5 lat) — czy reguły mają harmonogram 5-letni?",
"Sprawdź spójność z P14 (ryczałt) i P28 (księgowość) — kontrakty pól przychodów/kosztów.",
"Wskaż pustynie pokrycia ulg (ulga bez reguły) i priorytetyzuj kwotowo (typowa oszczędność).",
"Zaprojektuj testy: przekroczenie limitu termo (odrzucenie nadwyżki), wiek 25/26 (młodych), granice progów 120k.",
"Zaprojektuj risk policy: optymalizacja agresywna (np. IP Box bez dokumentacji) → NEEDS_ADVICE + checklist.",
],
legal=[
"Ustawa o PIT — art. 26 (ulgi: e. B+R; eb. prototyp; gb. robotyzacja; h. termomodernizacja 53 000 zł; rehabilitacyjna)",
"Ustawa o PIT — art. 30ca (IP Box 5%), art. 30c (liniowy 19%), art. 27 (skala 12%/32%, kwota wolna 30 000)",
"Ustawa o PIT — art. 21 ust. 1 pkt 148 (młodych 85 528/do 26 lat), 152 (powrót), 153 (4+), 154 (emeryci)",
"Ustawa o PIT — art. 44 (zaliczki), art. 45 (zeznanie), art. 9 ust. 2/3 (forma, strata 50%/5 lat)",
"Ustawa o PIT — art. 22-23 (KUP/NKUP — kontekst dla P28)",
"Rozporządzenie MF o metodach zaliczek (uproszczona) — zweryfikować aktualność w ISAP",
],
innovations=[
("Reliefs Matrix Complete", "pełna macierz ulg PIT z warunkami/limitami i testami granicznymi"),
("Limit-as-Data Engine", "limity ulg (53k/85k/2280) jako dane roczne z walidacją"),
("Nexus Ratio Auditor", "IP Box: obliczanie nexus ratio + checklist dokumentacyjna + NEEDS_ADVICE"),
("Relief Order Optimizer", "optymalna kolejność odliczeń pod invariant „suma ≤ dochód”"),
("Form Changer Proactive", "doradca formy z deadline alertem (art. 9 ust. 2 — 20.02) i raportem PDF"),
("12-Month Simulator", "symulator form na danych historycznych z założeniami przyszłości (scenariusze)"),
("Loss Harvesting Planner", "plan wykorzystania straty (50%/5 lat) z monitoringiem okien"),
("Relief Documentation Pack", "generator checklist dokumentacyjnych per ulga (dowody dla KAS)"),
("Relief Expiry Sentinel", "alarmy wygasania ulg czasowych (inwestycyjne, powrót 4 lata)"),
("Relief Golden Set", "golden decyzje ulgowe z granicami limitów i wieku"),
("Multi-Relief Conflict Detector", "wykrywanie kolizji ulg (te same koszty w dwóch ulgach) — BLOCKER"),
("Relief Explanation Engine", "wyjaśnienie decyzji ulgowej prostym językiem (PDF do certyfikatu P11)"),
],
in_contracts=[
"Honoruj parametry-as-data z V3_P06 — limity ulg to dane roczne.",
"Honoruj invariants z V3_P04 — „suma odliczeń ≤ dochód” jest konstytucją silnika PIT.",
"Honoruj certainty_class z V3_P03 — optymalizacja agresywna = niższa klasa pewności + checklist.",
"Honoruj macierz pustyn pokrycia z V3_P12/P01 — ulgi bez reguł to kolejna warstwa tej samej mapy.",
],
out_contracts=[
"Macierz ulg PIT — wiąże P28 (księgowość: koszty ulg) i P44.",
"Harmonogram zaliczek — wiąże P36 (kalendarz terminów) i P16 (deklaracje).",
"Doradca formy — wiąże P14 (ryczałt) i P41 (UI doradcy).",
"Lista kolizji ulg — wejście do P04 (invariants) i P44.",
],
acceptance_extra=[
"Macierz obejmuje wszystkie ulgi wymienione w Bbb (26e/h/30ca/21 ust. 1 pkt 148 minimum).",
"Symulator formy zawiera przykład end-to-end na przykładowych danych 12-miesięcznych.",
]),

dict(code="P15", slug="CROSSBORDER_TP", title="CROSS-BORDER, WDT/WNT, TP/MDR/CFC I WALUTY",
role="ekspertem prawa podatkowego międzynarodowego i transakcji transgranicznych JDG",
expertise="VAT UE (WDT/WNT, place of supply 28a-28o, OSS), PIT zagraniczne (residency, unikanie podwójnego), TP (CIT 11a-11e kontekst), MDR (DAC6), CFC, exit tax, kursy NBP",
mission=[
"Audytuj warstwę transgraniczną JDG: WDT/WNT (art. 42/138 VAT), place of supply usług (art. 28a-28o), OSS/IOSS (kontekst), post-Brexit, rejestr VAT UE. PIT: ograniczony/nieograniczony obowiązek (art. 3), unikanie podwójnego opodatkowania (metoda wyłączenia/zaliczki — art. 24 UPGW), pracy zdalnej za granicą. TP: dokumentacja (próg 2M/10M PLN — kontekst CIT), MDR (schematy — DAC6, hallmarks), CFC (income shift), exit tax.",
"Zaprojektuj walutowy silnik kursów NBP (kursy dzienne/miesięczne, przeliczenia groszowe, kursy historyczne dla ewidencji) i kontrakt z księgowością (P28). Zbadaj narzędzia (fx_rate_engine.py, crossborder_auditor.py, tp_documentation_engine.py, mdr_scorer.py, cfc_classifier.py, exit_tax_*). Każda ścieżka: reguła → test → status → ryzyko, z listą pustyn pokrycia i fail-closed na niepewności rezydencji.",
],
subparts=[
dict(name="VAT transgraniczny (WDT/WNT/OSS)",
goal="przepływy UE z odwzorowaniem miejsc świadczenia",
questions=[
"Czy WDT (art. 42: przemieszczenie własnych towarów, zgłoszenie VAT-UE) ma reguły z rejestracyjnym kontekstem?",
"Czy WNT (art. 138) i nabycie wewnątrzwspólnotowe są kompletne (stawka kraju docelowego jako dane?)",
"Czy place of supply usług (28a-28o: B2B miejsce nabywcy, B2C miejscowa, nieruchomości, kultura) ma macierz ścieżek?",
"Czy OSS (art. 28k-28m kontekst) jest w ogóle w zasięgu JDG — czy jest decyzja architektoniczna?",
]),
dict(name="PIT transgraniczny i rezydencja",
goal="rezydencja, unikanie podwójnego, praca zdalna",
questions=[
"Czy reguły rozróżniają rezydencję (art. 3 PIT: centrum interesów/183 dni) i czy prowadzą do NEEDS_ADVICE?",
"Czy metoda wyłączenia z progresją i zaliczki (art. 24 UPGW) są regułowane — jak z umowami o unikaniu?",
"Czy praca zdalna za granicą (konsekwencje ZUS/PIT) ma ścieżki decyzyjne — jakie ryzyka sygnalizuje?",
"Czy exit tax (art. 24cg PIT) i CFC mają reguły (exit_tax_cfc_complete.rego) z progami i wyłączeniami?",
]),
dict(name="TP, MDR i schematy",
goal="dokumentacja i raportowanie schematów",
questions=[
"Czy próg TP (2M PLN transakcje jednorodne) ma monitoring (tp_documentation_engine.py) — czy egzekwuje checklist?",
"Czy MDR (hallmarks DAC6) ma scoring (mdr_scorer.py) i auto-raport — czy human review jest wymuszony?",
"Czy MDR po polsku (mdr_enterprise.rego, plan44/45_mdr) pokrywa terminy (30 dni od zdarzenia)?",
"Czy JDG w ogóle podpada (próg MDR dla JDG — czy jest decyzja architektoniczna z uzasadnieniem)?",
]),
dict(name="Waluty i kursy NBP",
goal="przeliczenia bez błędów groszowych",
questions=[
"Czy fx_rate_engine.py ściąga kursy NBP (dzienny/miesięczny) — jakie cache, fallback, audit źródła?",
"Czy kursy historyczne dla ewidencji są wersjonowane (kurs z dnia poprzedzającego — reguła)?",
"Czy przeliczenia groszowe mają testy (0,005 round-half-up?) i invarianty walutowe?",
"Czy kursy kontraktują się z księgowością (P28) — te same kursy dla VAT i PKPiR?",
]),
],
file_groups=[
dict(name="Cross-border reguły", files=[
    ("Crossborder plan23 UE", "JDG/rules/crossborder/plan23_ue.rego"),
    ("Post-Brexit", "JDG/rules/crossborder/post_brexit.rego"),
    ("Exit tax i CFC", "JDG/rules/crossborder/exit_tax_cfc_complete.rego"),
    ("V3_08 enterprise", "JDG/rules/crossborder/v3_08_enterprise.rego"),
    ("Micro crossborder", "JDG/rules/micro/crossborder/crossborder.rego"),
    ("Plan33 CB", "JDG/rules/micro/plan33_cb.rego"),
    ("Plan34 crossborder", "JDG/rules/micro/plan34_ord.rego"),
]),
dict(name="MDS i międzynarodowe", files=[
    ("MDR enterprise", "JDG/rules/mdr/mdr_enterprise.rego"),
    ("MDR hallmarks", "JDG/rules/mdr/mdr_hallmarks.rego"),
    ("MDR DAC6", "JDG/rules/mdr_dac6_enterprise.rego"),
    ("Exit tax MDR", "JDG/rules/exit_tax_mdr_enterprise.rego"),
    ("WIS API", "JDG/rules/wis_api_enterprise.rego"),
    ("International expanded", "JDG/rules/international_expanded.rego"),
    ("Cross jurisdiction ruling", "JDG/rules/cross_jurisdiction_ruling_enterprise.rego"),
    ("Residency plan44", "JDG/rules/residency/plan44_residency.rego"),
    ("Residency plan45", "JDG/rules/residency/plan45_residency.rego"),
]),
dict(name="Narzędzia cross-border", files=[
    ("Silnik kursów FX", "JDG/tools/fx_rate_engine.py"),
    ("Audyt cross-border", "JDG/tools/crossborder_auditor.py"),
    ("Dokumentacja TP", "JDG/tools/tp_documentation_engine.py"),
    ("Scorer MDR", "JDG/tools/mdr_scorer.py"),
    ("Klasyfikator CFC", "JDG/tools/cfc_classifier.py"),
    ("Klasyfikator PKWiU (kontekst)", "JDG/tools/pkwiu_classifier.py"),
    ("MDS auto generator", "JDG/rules/mdr_auto_generator.rego"),
    ("WDT document tracker", "JDG/rules/wdt_document_tracker.rego"),
]),
dict(name="Dokumenty i testy", files=[
    ("Crossborder (dokument P12)", "JDG/docs/CROSSBORDER_P12.md"),
    ("Test cross-border enterprise", "JDG/tests/test_crossborder_enterprise.py"),
    ("Test cross-border v3", "JDG/tests/test_crossborder_v3_08.py"),
    ("Test natywny crossborder", "JDG/tests/rego/test_native_crossborder.rego"),
    ("Test cross-border etap", "JDG/tests/rego/test_native_crossborder_etap17.rego"),
    ("Audyt cross-border etap", "JDG/tests/test_crossborder_etap17_audit.py"),
]),
],
focus=[
"Zbuduj macierz ścieżek place of supply (28a-28o): usługa → kontrahent → kraj → reguła → status.",
"Zaprojektuj tabele stawek VAT UE jako dane (kraj → stawka) z walidacją i źródłem (komisja UE).",
"Zaprojektuj rezydencję jako determinator NEEDS_ADVICE (niepewna rezydencja = nie automatyczna decyzja).",
"Zaprojektuj kursy NBP: API, cache, kursy z D-1, invarianty walutowe (suma PLN = suma walut × kurs groszowo).",
"Zbuduj macierz MDR: hallmarks → wskaźniki → scoring → raport (terminy 30 dni) z human review.",
"Oceń exit tax i CFC: progi (2M PLN?), wyłączenia, monitoring — czy JDG w ogóle (decyzja architektoniczna).",
"Zaprojektuj granice testów: 183 dni rezydencji, 2M/10M TP, groszowe przeliczenia, kursy D-1.",
"Zaprojektuj invarianty cross-border: WDT zawsze z kontrahentem UE-VAT, kurs z D-1 dla ewidencji.",
"Wskaż pustynie pokrycia cross-border (ścieżki bez reguł) i priorytetyzuj ryzykiem sankcyjnym.",
"Zaprojektuj integrację z P12 (stawki VAT) i P13 (odliczenia — import usług art. 28b samooratkowanie).",
"Zaprojektuj scenariusze stress: kursy weekendowe (brak notowania — D-1 z piątku), masowe faktury UE.",
"Sprawdź kontrakty z P16 (JPK_V7 pola WDT/WNT/UE) — zgodność pól raportowania.",
],
legal=[
"Ustawa o VAT — art. 42 (WDT), art. 138 (WNT), art. 28a-28o (miejsce świadczenia usług)",
"Ustawa o VAT — art. 28b (import usług), art. 97a/99 (deklaracje UE, VAT-UE)",
"Ustawa o PIT — art. 3 (rezydencja: 183 dni/centrum interesów), art. 24cg (exit tax)",
"Ustawa o PIT — art. 30c1-30c3 (CFC — kontekst; dla JDG decyzja architektoniczna)",
"Ustawa o wymianie informacji podatkowych (MDR/DAC6 — schematy, terminy)",
"Umowy o unikaniu podwójnego opodatkowania (paradygmat metody wyłączenia/zaliczki)",
"Ustawa o CIT — art. 11a-11e (TP — kontekst progu 2M/10M dla dokumentacji)",
],
innovations=[
("Place-of-Supply Matrix", "pełna macierz 28a-28o z ścieżkami decyzyjnymi i testami"),
("EU VAT Rates Feed", "stawki UE jako dane z feedem komisji (walidacja per kraj, valid_from)"),
("Residency Advisor", "kwestionariusz rezydencji → NEEDS_ADVICE + checklist dokumentów (certyfikat rezydencji)"),
("FX Precision Engine", "kursy NBP z D-1, cache, invarianty walutowe, testy groszowe"),
("TP Threshold Sentinel", "monitoring progu TP (2M) z alertami dokumentacyjnymi"),
("MDR Hallmark Scorer", "scoring schematów z human review i terminy 30 dni (auto-raport)"),
("Exit Tax Early Warning", "wczesne wykrywanie zdarzeń exit tax (przeniesienie majątku)"),
("Cross-Border Golden Set", "decyzje transgraniczne graniczne (D-1 kursy, 183 dni) w oracle"),
("OSS Decision Advisor", "decyzja: czy JDG powinno być na OSS (progi, korzyści) z symulatorem"),
("Distance Selling Tracker", "monitoring progów sprzedaży wysyłkowej (alarms)"),
("Cross-Border Invariants", "WDT↔VAT-UE spójność, kursy D-1, samonależenie import usług (P04)"),
("Currency Consistency Gate", "CI: te same kursy dla VAT i PKPiR na tym samym inputcie (kontrakt z P28)"),
],
in_contracts=[
"Honoruj stawki jako dane z V3_P12 — stawki UE dołączają do tej samej warstwy.",
"Honoruj kursy i waluty jako dane kontekstowe P06 — fx engine pod tym samym wzorcem.",
"Honoruj invariants z V3_P04 — Cross-Border Invariants jako rozszerzenia.",
],
out_contracts=[
"Macierz place of supply — wiąże P12 (stawki) i P16 (JPK pola UE).",
"Silnik kursów — wiąże P28 (księgowość) i P16 (JPK waluty).",
"MDR/TP monitoring — wiąże P36 (kalendarz terminów) i P44.",
"Lista pustyn cross-border — wejście do P44.",
],
acceptance_extra=[
"Macierz obejmuje art. 42, 138, 28a-28o (minimum) ze statusem i ryzykiem.",
"Silnik kursów ma zaprojektowany test groszowy (przykład: EUR 1234,56 × kurs z D-1).",
]),

dict(code="P16", slug="KSEF_JPK", title="KSeF 2.0, JPK_V7, DEKLARACJE I E-DOREĄCZENIA",
role="ekspertem integracji fiskalnych (KSeF, JPK) i architektą resilience dla systemów raportowania",
expertise="KSeF 2.0 (obowiązkowy 2026), struktury FA(3)?, JPK_V7M/K, JPK_PKPIR, edeklaracje, UPO, offline queue, sandbox, terminy (25./20. dnia)",
mission=[
"Audytuj kompletny cykl raportowania fiskalnego: KSeF (wystawianie, schematy XSD, sesje, offline 2026, UPO, kary), JPK_V7M/K (struktura, GTU, MPP pola, korekty — DOK/JPK), JPK_PKPIR (struktura pliku, terminy), PIT deklaracje (PIT-36/36L/28: terminy 30.04, e-deklaracje), VAT deklaracje (VAT-7/7K: termin 25./20.?). Zaprojektuj pełny kalendarz terminów z invariantami (termin ≠ cisza: brak deklaracji = alarm).",
"Zbadaj rozbudowaną infrastrukturę KSeF (ksef_* reguły i narzędzia: offline queue, firewall, sandbox, UPO tracker, receipt digest, sanction monitor) i JPK (jpk_generator, jpk_validator, jpk_autogen, jpk_v7_autogen). Zaprojektuj resilience: KSeF niedostępny (kolejka offline, retry, degradacja), JPK walidacja przed wysyłką, UPO tracking z retry. Wszystko fail-closed: nieudana wysyłka = alarm, nigdy cisza.",
],
subparts=[
dict(name="KSeF 2.0 kompletność",
goal="obowiązkowy 2026: sesje, offline, UPO, kary",
questions=[
"Czy reguły KSeF pokrywają sesje online/offline (batch), uwierzytelnianie, sesje zbiorcze?",
"Czy offline queue (ksef_offline_queue) obsługuje awarię KSeF (retry, priorytety, degradacja) z gwarancją braku utraty faktury?",
"Czy UPO tracker (ksef_upo_tracker) monitoruje potwierdzenia (timeout → alarm → retry) — jakie SLO?",
"Czy kary KSeF (sanction monitor) są regułowane (progresywność kar 2026 — zweryfikować w ISAP)?",
]),
dict(name="JPK_V7 i JPK_PKPIR",
goal="struktury, terminy, korekty",
questions=[
"Czy generator JPK_V7 (jpk_v7_autogen) produkuje pola zgodne ze schematem MF (GTU, MPP, WDT/WNT) — walidacja XSD?",
"Czy JPK_PKPIR (PKPiR→JPK) generuje poprawny plik (ewidencja → struktura 7) — co z remanentem (P28)?",
"Czy terminy (VAT 25./20. dnia? PIT 30.04?) są kalendarzem z invariantami (brak = alarm) i wersjonowane (changes)?",
"Czy korekty JPK (jpk_corrections_workflow) są idempotentne i audytowalne (DOK, identyfikatory)?",
]),
dict(name="E-deklaracje i PIT",
goal="zesłania PIT i e-UPO",
questions=[
"Czy annual_declaration_enterprise generuje PIT-36/36L/28 zgodnie ze schematami MF (walidacja schematów)?",
"Czy e-doręczenia (edelivery_gateway) mają ścieżki: wysyłka → status → UPO → archiwum — zero ciszy?",
"Czy terminy PIT (30.04, 45. dnia przy kwartale?) są kalendarzem z alertami N-dni?",
"Czy integracja z certyfikatami (podpisy e-deklaracji) jest zaprojektowana (podpis podmiotowy)?",
]),
dict(name="Resilience i testy",
goal="KSeF niedostępny, sandbox, chaos",
questions=[
"Czy ksef_sandbox_harness pozwala testować na sandboxie MF (retry, awarie) — jak często uruchamiany?",
"Czy ksef_firewall blokuje błędne dane przed wysyłką (walidacja schemat + semantyka) — zero śmieci do MF?",
"Czy jest chaos test (KSeF down 72h — kolejkowanie offline, zero utraty) — jak mierzony (RPO/RTO)?",
"Czy integracja KSeF/JPK kontraktuje się z decyzjami VAT (P12/P13: GTU, MPP) — te same pola?",
]),
],
file_groups=[
dict(name="KSeF reguły", files=[
    ("KSeF innovations", "JDG/rules/ksef_innovations_enterprise.rego"),
    ("KSeF UPO tracker", "JDG/rules/ksef_upo_tracker_enterprise.rego"),
    ("KSeF sanction monitor", "JDG/rules/ksef_sanction_monitor_enterprise.rego"),
    ("KSeF outbox", "JDG/rules/ksef_outbox_enterprise.rego"),
    ("KSeF offline queue", "JDG/rules/ksef_offline_queue_enterprise.rego"),
    ("KSeF firewall", "JDG/rules/ksef_firewall_enterprise.rego"),
    ("KSeF sandbox harness", "JDG/rules/ksef_sandbox_harness_enterprise.rego"),
    ("KSeF receipt digest", "JDG/rules/ksef_receipt_digest_enterprise.rego"),
    ("KSeF resilience", "JDG/rules/ksef_resilience_enterprise.rego"),
    ("KSeF/JPK v3_11", "JDG/rules/ksef_jpk/v3_11_enterprise.rego"),
    ("KSeF micro", "JDG/rules/micro/vat/ksef_micro.rego"),
    ("KSeF JPK etap20", "JDG/rules/ksef_jpk_etap20_v1.rego"),
]),
dict(name="JPK reguły", files=[
    ("JPK V7 autogen", "JDG/rules/jpk_v7_autogen_enterprise.rego"),
    ("JPK KR ST generator", "JDG/rules/jpk_kr_st_generator_enterprise.rego"),
    ("JPK corrections workflow", "JDG/rules/jpk_corrections_workflow_enterprise.rego"),
    ("JPK deadlines", "JDG/rules/jpk/plan26_deadlines.rego"),
    ("JPK micro", "JDG/rules/micro/jpk/jpk.rego"),
    ("Plan33 JPK", "JDG/rules/micro/plan33_jpk.rego"),
    ("JPK CIT", "JDG/rules/jpk_cit.rego"),
    ("KSeF/JPK etap20 (kontekst)", "JDG/rules/ksef_jpk_etap20_v1.rego"),
]),
dict(name="Narzędzia KSeF/JPK", files=[
    ("Generator JPK", "JDG/tools/jpk_generator.py"),
    ("Walidator JPK", "JDG/tools/jpk_validator.py"),
    ("JPK autogen", "JDG/tools/jpk_autogen.py"),
    ("KSeF outbox", "JDG/tools/ksef_outbox.py"),
    ("KSeF offline queue", "JDG/tools/ksef_offline_queue.py"),
    ("Bramka KSeF/JPK v3", "JDG/tools/ksef_jpk_v3_gate.py"),
    ("Audyt KSeF/JPK edeklaracje", "JDG/tools/ksef_jpk_edeklaracje_auditor.py"),
]),
dict(name="E-doręczenia i terminy", files=[
    ("E-delivery gateway", "JDG/rules/edelivery_gateway_enterprise.rego"),
    ("E-delivery gateway v2", "JDG/rules/edelivery_gateway_v2_enterprise.rego"),
    ("E-delivery monitor (narzędzie)", "JDG/tools/edelivery_monitor.py"),
    ("E-delivery plan44", "JDG/rules/edelivery/plan44_edelivery.rego"),
    ("E-delivery plan45", "JDG/rules/edelivery/plan45_edelivery.rego"),
    ("ePUAP enterprise", "JDG/rules/epuap_enterprise.rego"),
]),
dict(name="Dokumenty i testy", files=[
    ("KSeF/JPK (dokument P17)", "JDG/docs/KSEF_JPK_EDEKLARACJE_P17.md"),
    ("Test KSeF generator", "JDG/tests/test_ksef_generator.py"),
    ("Test generatora KSeF (odporność)", "JDG/tests/test_ksef_generator.py"),
    ("Test KSeF JPK v3", "JDG/tests/test_ksef_jpk_v3_11.py"),
    ("Test JPK etap20 audyt", "JDG/tests/test_ksef_jpk_etap20_audit.py"),
    ("Test natywny KSeF", "JDG/tests/rego/test_native_ksef.rego"),
    ("Test natywny JPK", "JDG/tests/rego/test_native_jpk.rego"),
]),
],
focus=[
"Zbuduj macierz ścieżek KSeF: faktura → walidacja → sesja → wysyłka → UPO → archiwum, z punktami awarii.",
"Zaprojektuj offline queue: kolejność, priorytety, retry z backoff, RPO/RTO, zero utraty (idempotency keys).",
"Zaprojektuj UPO tracking: timeout (24h?) → alarm → retry → eskalacja — zero ciszy (terminy kar).",
"Zbuduj kalendarz terminów (VAT 25./20., PIT 30.04, ZUS 15./20., JPK) z invariantami (brak deklaracji = alarm).",
"Zaprojektuj walidację przed wysyłką (firewall): schemat XSD + semantyka (P12/P13 kontrakty pól).",
"Zaprojektuj korekty JPK idempotentne (retry nie dubluje korekty) — identyfikatory zdarzeń.",
"Zbuduj granice testów: 25. dnia (weekend/holiday shift — czy przenosi?), 30.04 PIT, terminy 7-dniowe.",
"Oceń integrację certyfikatów podpisu e-deklaracji (podpis podmiotowy, klucze — P11 kontrakt).",
"Zaprojektuj sandbox pipeline (CI: cotygodniowy test na sandboxie MF z raportem).",
"Wskaż pustynie KSeF/JPK (ścieżki bez reguł — np. faktura konsumencka B2C KSeF?) i priorytetyzuj.",
"Zaprojektuj invarianty: faktura ≠ wysłana bez UPO; JPK ≠ złożony bez potwierdzenia (zero ciszy).",
"Zaprojektuj chaos drill: KSeF down 72h → kolejka offline → zero utraty → odzyskanie (test tabletop).",
],
legal=[
"Ustawa o VAT — art. 106ka-106m (KSeF: obowiązek, sesje, kary) — zweryfikować status 2026 w ISAP",
"Ustawa o VAT — art. 99 (terminy JPK: 25./20. dnia)",
"Ustawa o VAT — art. 109 (ewidencja JPK)",
"Ustawa o PIT — art. 45 (terminy zeznań 30.04/45. dnia?)",
"Rozporządzenie MF z 15.7.2025 (JPK_VAT z deklaracją) — struktury i terminy",
"Rozporządzenie MF z 5.10.2025 (wzór faktury ustrukturyzowanej KSeF) — schemat XSD",
"Ustawa o doręczeniach elektronicznych (e-Doręczenia — adresy, skutki doręczenia)",
],
innovations=[
("KSeF Session Orchestrator", "pełny orchestrator sesji (online/batch/offline) z idempotencją i retry"),
("Zero-Loss Offline Queue", "kolejka offline z RPO=0 (identyfikatory, WAL, replikacja)"),
("UPO Sentinel", "monitoring potwierdzeń z timeout→alarm→retry→eskalacja"),
("Pre-Send Firewall", "walidacja XSD+semantyka przed wysyłką (zero śmieci do MF)"),
("Deadline Constitution", "terminy jako konstytucja (invarianty: brak deklaracji = alarm, przeniesienia weekendowe)"),
("JPK Field Contract", "pola JPK_V7 jako kontrakt (P12/P13) — walidacja krzyżowa przed generacją"),
("Idempotent Corrections", "korekty JPK idempotentne (identyfikatory zdarzeń, retry-proof)"),
("Sandbox CI Rig", "cotygodniowy test na sandboxie MF z raportem i trendami"),
("Chaos KSeF Drill", "test tabletop: KSeF down 72h → zero utraty (pomiar RPO/RTO)"),
("E-Delivery Chain", "wysyłka → status → UPO → archiwum z zero ciszy"),
("Penalty Exposure Monitor", "monitoring narażenia na kary KSeF (progresywność — symulacja)"),
("KSeF/JPK Golden Set", "golden faktury/JPK z walidacją schematową (oracle)"),
],
in_contracts=[
"Honoruj pola VAT z V3_P12/P13 (GTU, MPP) — JPK generuje z tych samych kontraktów.",
"Honoruj certyfikaty z V3_P11 — UPO i potwierdzenia archiwizowane jako dowody.",
"Honoruj kalendarz z V3_P36 (jeśli wcześniej) — terminy jednego źródła.",
"Honoruj invariants z V3_P04 — zero ciszy (faktura ≠ wysłana bez UPO) jako konstytucja.",
],
out_contracts=[
"Kalendarz terminów fiskalnych — wiąże P36 (kalendarz) i P41 (UI).",
"Offline queue design — wiąże P43 (DR/BCP) i P38 (deployment).",
"Pola JPK kontrakty — wiąże P28 (PKPiR→JPK) i P44.",
"Lista pustyn KSeF/JPK — wejście do P44.",
],
acceptance_extra=[
"Macierz ścieżek KSeF zawiera punkty awarii i mechanizmy odtworzenia.",
"Kalendarz terminów zawiera scenariusze weekendowe i świąteczne (przeniesienia).",
]),

dict(code="P17", slug="ORDYNACJA_OBRONA", title="ORDYNACJA PODATKOWA — OBRONA, ODSETKI, PRZEDAWNIENIE I PROWADZENIE SPRAW",
role="ekspertem Ordynacji podatkowej i strategii obrony podatnika w sporach z KAS",
expertise="odsetki (art. 56), przedawnienie (art. 70-72), klauzule GAAR (art. 119a), interpretacje, audyt podatkowy, obrona (art. 187-234), kary KKS (kontekst P29)",
mission=[
"Audytuj warstwę obronną silnika: odsetki (art. 56: stawki, kapitalizacja miesięczna, granice groszowe — exit_tax_interest_calculator, interest_calculator), przedawnienie (art. 70: 5 lat, termin kończy się z upływem... interwencje — limitations_calendar, statute_of_limitations, kks_limitations_calendar), GAAR (art. 119a: gaar_shield_enterprise — scoring ochronny, NIE automatyczna wina), zawieszenie bieg (art. 71).",
"Audytuj procedury prowadzenia spraw: korekty deklaracji (korekta czynna/uzupełniająca — art. 81), czynności sprawdzające, postępowanie (terminy 7/14/30 dni), interpreacje KIS (tax_ruling_autodrafter — wnioski), audyt podatkowy (AUD — dobrowolne ujawnienie), czynności beganiste. Zaprojektuj procedury obrony: apelacja (30 dni), skarga do WSA (30 dni), zwolnienie z odpowiedzialności (art. 30a) — kalendarz z zero ciszy.",
],
subparts=[
dict(name="Odsetki i kapitalizacja",
goal="art. 56 z groszową precyzją",
questions=[
"Czy stawki odsetek (podatkowe/od zaległości celnych) są danem z valid_from (zmiany RWPS/MF)?",
"Czy kapitalizacja miesięczna (art. 56 ust. 1) jest regułowana (ostatni dzień miesiąca) i testowana?",
"Czy granice groszowe (zaokrąglenia, 0,005) mają testy (0,01 różnice)?",
"Czy odsetki od zaliczek wstecz (retroaktywność) są śledzone z temporalnością (P05)?",
]),
dict(name="Przedawnienie i zawieszenia",
goal="art. 70-72 z harmonogramem interwencji",
questions=[
"Czy 5-letni okres (koniec roku kalendarzowego + 5) jest liczony poprawnie (granice 31.12)?",
"Czy zawieszenia (art. 71: postępowanie, odroczenie, etapy) mają kalendarz interwencji?",
"Czy kalendarz przedawnienia (limitations_calendar) jest dane + reguła z alertami N-dni?",
"Czy interwencje przerywające (wezwanie, decyzja) mają ścieżki (bieg → nowy termin) i audyt?",
]),
dict(name="GAAR i klauzule",
goal="art. 119a jako ochrona, nie wina",
questions=[
"Czy gaar_shield_enterprise ocenia ryzyko (przedmiotowe: ukrycie, korzyść < 1M?) jako SYGNAŁ z checklistą?",
"Czy scoring GAAR prowadzi do NEEDS_ADVICE + dokumentacji (wartość dodana, uzasadnienie biznesowe)?",
"Czy MAE (korzyść < 1M zł wyłączenie) jest parametryzowany i testowany na granicy?",
"Czy ścieżki interpretacji (wniosek o interpretację — tax_ruling_autodrafter) integrują się z scoringiem?",
]),
dict(name="Procedury i obrona",
goal="korekty, terminy, apelacje — zero ciszy",
questions=[
"Czy korekta czynna (art. 81: przed wszczęciem) i uzupełniająca (po) są regułowane z konsekwencjami?",
"Czy terminy postępowania (7 dni stanowisko, 14 apelacja, 30 skarga WSA) są kalendarzem z alertami?",
"Czy AUD (dobrowolne ujawnienie art. 30a/30b) ma ścieżki (korzyści: kara 12%/0%?) z monitoringiem?",
"Czy procedura_tracker (proceeding_tracker_enterprise) śledzi sprawy (statusy, terminy) z zero ciszy?",
]),
],
file_groups=[
dict(name="Ordynacja reguły", files=[
    ("Micro ordynacja", "JDG/rules/micro/ord/ord.rego"),
    ("Plan33 ordynacja", "JDG/rules/micro/plan33_ord.rego"),
    ("Plan34 ordynacja", "JDG/rules/micro/plan34_ord.rego"),
    ("Ordynacja innovations", "JDG/rules/ord/ord_innovations_v8.rego"),
    ("Ordynacja supplements", "JDG/rules/ord_supplements_enterprise.rego"),
    ("Ordynacja obrona R08", "JDG/rules/r08_ordynacja_obrona_innovations_v9.rego"),
    ("Ordynacja innovations v9", "JDG/rules/p11_ordynacja_podatkowa_innovations_v9.rego"),
]),
dict(name="Odsetki, przedawnienie, GAAR", files=[
    ("Odsetki (kalkulator)", "JDG/rules/exit_tax_interest_calculator.rego"),
    ("Odsetki enterprise", "JDG/rules/interest_calculator_enterprise.rego"),
    ("Przedawnienie", "JDG/rules/statute_of_limitations.rego"),
    ("Statute plan26", "JDG/rules/statute/plan26_detailed.rego"),
    ("GAAR shield", "JDG/rules/gaar_shield_enterprise.rego"),
    ("Kalendarz przedawnienia (narzędzie)", "JDG/tools/limitations_calendar.py"),
    ("Kalendarz KKS przedawnienia", "JDG/tools/kks_limitations_calendar.py"),
]),
dict(name="Obrona i interakcja z KAS", files=[
    ("Tax authority interaction", "JDG/rules/tax_authority_interaction_enterprise.rego"),
    ("Proceeding tracker", "JDG/rules/proceeding_tracker_enterprise.rego"),
    ("Tax ruling autodrafter", "JDG/rules/tax_ruling_autodrafter_enterprise.rego"),
    ("Defense builder", "JDG/rules/defense_builder_enterprise.rego"),
    ("Defense packet builder (narzędzie)", "JDG/tools/defense_packet_builder.py"),
    ("Correspondence generator", "JDG/tools/correspondence_generator.py"),
    ("Penalty AI", "JDG/rules/penalty_ai_enterprise.rego"),
    ("Kalkulator sankcji (narzędzie)", "JDG/tools/sanction_calculator.py"),
    ("Audyt Ordynacji (narzędzie)", "JDG/tools/ordpu_auditor.py"),
    ("Judicial trend", "JDG/rules/judicial_trend_enterprise.rego"),
    ("Audit defense", "JDG/rules/audit_defense_enterprise.rego"),
    ("Judicial interpretations", "JDG/rules/judicial_interpretations_enterprise.rego"),
]),
dict(name="Dokumenty i testy", files=[
    ("Ordynacja (dokument P11)", "JDG/docs/ORDYNACJA_PODATKOWA_P11.md"),
    ("Test Ordynacji etap16 audyt", "JDG/tests/test_kks_ord_etap16_audit.py"),
    ("Test natywny ord", "JDG/tests/rego/test_native_ord.rego"),
    ("Test natywny ordynacja", "JDG/tests/rego/test_native_jdg_ord.rego"),
    ("Test R08 obrona", "JDG/tests/auto/test_r08_ordynacja_obrona_enterprise.py"),
    ("Test natywny R08", "JDG/tests/rego/test_r08_ordynacja_obrona_enterprise.rego"),
]),
],
focus=[
"Zbuduj macierz art. 56/70/71/81/119a → reguła → test → status → ryzyko (każdy materiałny przepis).",
"Zaprojektuj odsetki z groszową precyzją: stawki jako dane (valid_from), kapitalizacja ostatni dzień miesiąca, granice 0,01.",
"Zaprojektuj kalendarz przedawnienia (art. 70: 31.12+5) z zawieszeniami (art. 71) i alertami N-dni.",
"Zaprojektuj GAAR scoring jako ochronę: checklist wartość dodana, MAE granica 1M, ścieżka interpretacji.",
"Zbuduj kalendarz proceduralny (7/14/30 dni) z zero ciszy (brak reakcji = alarm + eskalacja).",
"Zaprojektuj korekty czynna/uzupełniająca z konsekwencjami (kary redukcja — art. 56c kontekst) i testami granicznymi.",
"Zaprojektuj AUD ścieżki (dobrowolne ujawnienie) z benefitem redukcji kary i monitoringiem warunków.",
"Oceń tax_ruling_autodrafter: wniosek KIS (poprawność formalna, opis sprawy) — jakość generacji, 4-eyes.",
"Zaprojektuj invarianty: odsetki ≥ 0, przedawnienie nie wcześniej niż koniec 5. roku, korekta zawsze audytowana.",
"Wskaż pustynie Ordynacji (art. bez reguł: np. czynności beganiste) i priorytetyzuj ryzykiem finansowym.",
"Zaprojektuj scenariusze stress: odsetki 10 lat, przedawnienie z 3 zawieszeniami, apelacja w ostatnim dniu.",
"Sprawdź spójność z P29 (KKS kary) i P36 (kalendarz) — jeden kalendarz proceduralny.",
],
legal=[
"Ordynacja podatkowa — art. 56 (odsetki od zaległości i zwrotów, kapitalizacja miesięczna)",
"Ordynacja podatkowa — art. 70-72 (przedawnienie 5 lat, zawieszenie bieg, interwencje)",
"Ordynacja podatkowa — art. 81 (korekty deklaracji czynne/uzupełniające)",
"Ordynacja podatkowa — art. 119a (GAAR, klauzula przeciwdziałania unikaniu opodatkowania)",
"Ordynacja podatkowa — art. 30a/30b (AUD: dobrowolne ujawnienie, redukcja kary)",
"Ordynacja podatkowa — art. 187-234 (postępowanie: terminy, apelacja 14 dni, skarga 30 dni)",
"Ustawa o NSA — art. 3 § 3 (termin skargi 30 dni — kontekst)",
],
innovations=[
("Interest Precision Engine", "odsetki groszowe z kapitalizacją i testami 0,01 (art. 56)"),
("Limitation Sentinel", "kalendarz przedawnienia z zawieszeniami i alertami 90/60/30 dni"),
("GAAR Shield Framework", "scoring ochronny: checklist, MAE granica, ścieżka interpretacji (nie wina)"),
("Procedural Deadline Constitution", "kalendarz 7/14/30 dni z zero ciszy (brak reakcji = alarm)"),
("Active Correction Advisor", "doradca korekty czynnej (przed wszczęciem — benefity kar) z terminami"),
("AUD Benefit Tracker", "śledzenie warunków AUD (redukcja 12%→0%) i monitoring naruszeń"),
("Ruling Autodrafter 4-Eyes", "generator wniosków KIS z review prawnika (jakość formalna)"),
("Proceeding Timeline", "timeline sprawy (czynności→postępowanie→apelacja→WSA) z terminami i dowodami"),
("Defense Packet Generator", "paczka obronna (odpowiedzi, dokumenty, dowody) z checklistą"),
("Interpretation Library", "baza interpretacji KIS per przepis (powiązanie z LKG P01) z datami ważności"),
("ORD Invariants Pack", "odsetki ≥ 0, przedawnienie ≥ koniec 5. roku, korekta audytowana (P04)"),
("Litigation Stress Lab", "symulatory: odsetki 10 lat, wielokrotne zawieszenia, granice terminów"),
],
in_contracts=[
"Honoruj invariants z V3_P04 — ORD Invariants Pack jako rozszerzenia katalogu.",
"Honoruj kalendarz z V3_P36 (terminy jedenego źródła) i P16 (terminy fiskalne).",
"Honoruj LKG z V3_P01 — interpretacje KIS podpięte pod węzły przepisów.",
"Honoruj certainty_class z V3_P03 — scoring GAAR wpływa na klasę, nie na winę.",
],
out_contracts=[
"Kalendarz proceduralny — wiąże P36 (kalendarz) i P41 (UI spraw).",
"Odsetki silnik — wiąże P36 (płatności) i P44.",
"GAAR scoring — wiąże P12/P13 (decyzje VAT) i P44.",
"Lista pustyn Ordynacji — wejście do P44.",
],
acceptance_extra=[
"Macierz obejmuje art. 56, 70, 71, 81, 119a (minimum) ze statusem i ryzykiem.",
"Odsetki mają test graniczny groszowy (przykład: kapitalizacja ostatni dzień miesiąca, 0,01 różnice).",
]),
]
