# -*- coding: utf-8 -*-
"""Parts P45-P52: repair wave 1 — stubs, hardcode, legal basis, mirror, fail-closed, dead code, legal deserts, grosz boundaries."""
PARTS = [

dict(code="P45", slug="STUB_KILLER", title="ELIMINACJA STUBÓW I FASAD — ZERO REGUŁ UDĄJĄCYCH POKRYCIE",
role="głównym egzekutorem jakości reguł, specjalistą od wykrywania i usuwania stubów, tautologii i fasad w systemach policy-as-code",
expertise="detekcja reguł typu true=>..., konwersja stubów na reguły warunkowe, mutation testing, audyt testów zawsze-zielonych",
mission=[
"Wykonaj pełną INWENTARYZACJĘ STUBÓW w JDG/rules: reguły z warunkiem zawsze prawdziwym, reguły-zapchajdziury bez treści prawnej, else-chain z twardym `true`, reguły skopiowane z szablonu z pustymi _legal_basis. Narzędzia (convert_true_to_conditions, tautology_guard, else_chain_dead_code_detector) istnieją — zweryfikuj, czy je URUCHOMIONO na wszystkich pakietach, i wygeneruj pełny rejestr stubów z priorytetami: które reguły udają pokrycie VAT/PIT/ZUS/KKS (najgroźniejsze — wywołują błędne AUTO_POST).",
"Zaprojektuj program ELIMINACJI: dla każdego stubu — z którego przepisu ma powstać realna reguła (akt+art+ust), jakie granice testowe ją dowiodą, kto weryfikuje merytorycznie, termin. Reguła bez treści prawnej ma zostać USUNIĘTA albo UZUPEŁNIONA — zero stanu pośredniego „udajemy pokrycie”. Forteca nie ma elementów dekoracyjnych. Przeprować głęboką analizę: jak stuby weszły do repo (generator bez walidacji? kopiowanie?) i jak zablokować tą ścieżkę na przyszłość.",
],
subparts=[
dict(name="Inwentaryzacja stubów w regułach",
goal="pełny rejestr reguł-fasad z dowodami linia po linii",
questions=[
"Które reguły mają warunek zawsze prawdziwy (wynik narzędzi + ręczna weryfikacja najgroźniejszych)?",
"Które reguły mają puste/miejsce-zapełnione _legal_basis (brak aktu lub art.)?",
"Które else-chain kończą się `true => ...` zamiast jawnego NEEDS_ADVICE?",
"Ile stubów jest w micro vs macro vs enterprise — która warstwa jest najbardziej fasadowa?",
]),
dict(name="Konwersja stubów na reguły warunkowe",
goal="każdy stub → realna reguła albo usunięcie",
questions=[
"Które stuby da się skonwertować automatycznie (narzędzie) a które wymagają treści prawnej człowieka?",
"Jak wygląda wzorzec konwersji (warunek z input + prog z data.thresholds + else fail-closed)?",
"Które stuby są poza zakresem silnika (do usunięcia z rejestrem przyczyny)?",
"Jak test po konwersji dowodzi, że reguła NIE jest stubem (asercja na konkretny przypadek)?",
]),
dict(name="Zablokowanie ścieżki powstawania stubów",
goal="żaden nowy stub nie wejdzie do repo",
questions=[
"Który generator produkował stuby (plan33? plan50?) i jak go zabezpieczyć?",
"Jak dodać bramkę CI odrzucającą PR z regułą-stubem (jaki detektor, jaki test)?",
"Czy rule_registry ma pole lifecycle wykrywające reguły bez dowodu testowego (SHADOW z terminem)?",
"Jak procesu awansu CANDIDATE→ACTIVE zakazać przyjmowania reguł bez pełnego dowodu (P07)?",
]),
dict(name="Mutation testing jako dowód nie-fasadowości",
goal="testy łapią celowe uszkodzenia reguł",
questions=[
"Które pakiety przejdą mutation testing (mutacja progu → test musi paść) — gdzie są luki?",
"Jak zautomatyzować mutacje (zestaw operatorów: zmiana progu, odwrócenie warunku, usunięcie else)?",
"Jaki próg „mutation score” jest akceptowalny dla reguł krytycznych (VAT/PIT/ZUS)?",
"Gdzie mutation testing wykryje, że testy testują nazwy, nie semantykę?",
]),
],
file_groups=[
dict(name="Narzędzia detekcji i konwersji stubów", files=[
    ("Konwerter true→warunki", "JDG/tools/convert_true_to_conditions.py"),
    ("Detektor tautologii", "JDG/tools/tautology_guard.py"),
    ("Detektor dead code else-chain", "JDG/tools/else_chain_dead_code_detector.py"),
    ("Detektor dead rules", "JDG/tools/dead_rule_detector.py"),
    ("Debug konwerter", "JDG/tools/debug_converter.py"),
    ("Linter rego", "JDG/tools/lint_rego_rules.py"),
    ("Walidator reguł", "JDG/tools/validate_rules.py"),
    ("Audyt hardcode", "JDG/tools/hardcoded_audit.py"),
]),
dict(name="Bramki jakości i ich testy", files=[
    ("Bramka micro", "JDG/tools/micro_quality_v3_13_gate.py"),
    ("Bramka enterprise", "JDG/tools/enterprise_quality_v3_15_gate.py"),
    ("Test bramki micro", "JDG/tests/test_micro_quality_v3_13.py"),
    ("Test bramki enterprise", "JDG/tests/test_enterprise_quality_v3_15.py"),
    ("Test natywny menedżera lifecycle", "JDG/tests/rego/test_native_lifecycle_manager_enterprise.rego"),
    ("Test kontraktu enterprise", "JDG/tests/test_enterprise_operating_contract.py"),
]),
dict(name="Rejestry i cykl życia", files=[
    ("Rejestr reguł", "JDG/bundles/rule_registry.json"),
    ("Pustynie pokrycia", "JDG/bundles/coverage_deserts.json"),
    ("Kanon pokrycia (dane)", "JDG/bundles/coverage_canon.json"),
    ("Menedżer lifecycle", "JDG/tools/rule_lifecycle_manager.py"),
    ("Dokument rule lifecycle", "JDG/docs/RULE_LIFECYCLE.md"),
    ("Dokument control plane", "JDG/docs/CONTROL_PLANE_RULE_LIFECYCLE.md"),
]),
],
legal=[
"Ordynacja podatkowa — art. 119a: reguła-stub może niezamierzenie uchwycić konstrukcję sztuczną (brak warunków materiałnych).",
"Ustawa VAT — art. 41, 43, 108: stawki i zwolnienia MUSZĄ mieć realne warunki materiałowe (stub = błędna stawka).",
"Ustawa o PIT — art. 22, 27, 30c: koszty i formy opodatkowania z pełnymi przesłankami (stub = błędny podatek).",
"Ustawa o ZUS — art. 18a–18e: podstawa wymiaru i ulgi z pełnymi przesłankami.",
"KKS — art. 56: stub generujący błędną deklarację = ryzyko czynu zabronionego po stronie użytkownika.",
"Ustawa o rachunkowości — art. 4 ust. 1: reguła-fasada narusza rzetelność wyliczeń.",
"Ustawa o rachunkowości — art. 5: zapisy ewidencji muszą odpowiadać rzeczywistym zdarzeniom.",
"Ordynacja podatkowa — art. 21 §1: organ stosuje prawo materialne — silnik musi odtwarzać przesłanki, nie symulować.",
],
innovations=[
("Stub register with SLA", "rejestr każdego stubu (rule_id, plik, powód powstania, plan naprawy, deadline, właściciel); bramka CI raportuje trend spadkowy — zero stubów do daty P68."),
("Stub forensics", "analiza git blame + logów generatorów: jak stub wszedł (commit, prompt, plan) — zamyka ścieżkę powstawania."),
("Auto-convert pipeline", "konwersja automatyczna z dry-run → diff → walidacja P34 → golden replay → 4-eyes; rejestrowana w migration ledger P36."),
("Negative assertion generator", "dla każdej skonwertowanej reguły generator tworzy test negatywny (brak przesłanki → NEEDS_ADVICE) — dowód, że reguła warunkowa."),
("Mutation score gate", "próg mutation score per domena (np. VAT ≥90%) w bramce; spadek = BLOCKER."),
("Stub-free badge per package", "etykieta pakietu „stub-free” z datą dowodu i checksumą skanu — widoczna w rule_registry i certyfikacie."),
("Template rule policy", "każdy nowy szablon reguły (template) wymaga wypełnienia treści materiałowej PRZED dodaniem; template bez treści = PR odrzucony."),
("Reguły-zapchajdziury w testach", "wykrywanie testów, które przechodzą na stubach (test zawsze-zielony na regule fasadowej) — para stub+test do naprawy."),
("Provenance of truth", "reguła bez pełnego łańcucha (akt→art→reguła→test) nie może opuścić SHADOW — egzekwowane przez lifecycle manager."),
("Stub census report", "automatyczny cotygodniowy raport: liczba stubów per domena, trend, TOP-10 do naprawy — do dashboardu P37."),
("Legal-empty detector", "detekcja reguł, których _legal_basis jest puste albo zawiera placeholder („TODO”, „N/A”, „—”) — rejestr z priorytetem."),
("Parity with ISAP text", "dla skonwertowanych reguł: cytat przepisu z ISAP obok kodu reguły w raporcie — człowiek weryfikuje zgodność merytoryczną."),
],
in_contracts=[
"Kanon artefaktów z P00 — rejestr stubów wbudowany w mapę kanoniczną (liczby zgodne).",
"Sieć walidacji z P34 — konwersje kończą się pełną walidacją L1–L5.",
],
out_contracts=[
"REJESTR STUBÓW (pełny, z SLA) — wejście do P46 (hardcode), P47 (legal basis) i P68 (re-certyfikacja).",
"Stub-free badge (kryteria + mechanizm) — wiąże P07 (lifecycle) i P29 (bramki).",
"Mutation score gate (progi per domena) — wejście do P39 (CI) i P45-followup.",
],
acceptance_extra=[
"Rejestr stubów z liczbą per domena i per warstwa (macro/micro/enterprise) — liczniki z dowodami.",
"Min. 5 przykładowych konwersji stub→reguła warunkowa z pełnym cyklem (diff, test, replay) jako wzorzec.",
]),
dict(code="P46", slug="HARDCODE_ELIMINACJA", title="ELIMINACJA HARDCODE — WSZYSTKIE PROGI, STAWKI I LIMITY DO DATA.THRESHOLDS.*",
role="refaktoryzatorem systemów regułowych, specjalistą od zewnętrznego warstwowania parametrów (parametry-as-data) i migracji konfiguracji",
expertise="hardcode audit, migracja wartości do data documents, hot-reload, walidacja parametrów, temporalne okna parametrów",
mission=[
"Wykonaj pełny audyt hardcode: wszystkie liczby w kodzie Rego (stawki VAT, progi MPP, ryczałty, składki ZUS, kwoty wolne, limity 30-krotności, odsetki, sankcje) porównaj z JDG/bundles/thresholds_data.json. Każda wartość w kodzie a nie w danych = luka ADR-002 (BLOCKER wg dokumentów świętych: zmiana prawa ma być zmianą DANYCH, nie deployem kodu). Wygeneruj migrację wartość-po-wartości z mapowaniem: reguła → parametr → ścieżka w thresholds_data → okno temporalne → test regresji.",
"Zaprojektuj zarządzanie parametrami: walidacja struktury thresholds_data (schema), podpisy i checksuma (integralność), hot-reload bez utraty decyzji w locie (graceful switch), historia zmian parametrów (kto, kiedy, dlaczego — bo zmiana stawki to decyzja po nowelizacji), test graniczny day-0 dla każdego przełączenia. Parametr bez daty obowiązywania = luka temporalna (P05). Przeprować głęboką analizę: które wartości są zmienne prawnie (roczne stawki ZUS) a które strukturalne (procent zaokrąglenia) — różne ścieżki zarządzania.",
],
subparts=[
dict(name="Audyt hardcode wartości prawnych",
goal="pełna lista liczb w kodzie poza thresholds_data",
questions=[
"Które reguły mają stawki/progi/limity inline (wynik hardcoded_audit + ręczne skanowanie wzorców liczbowych)?",
"Które wartości w thresholds_data są duplikowane w kodzie (rozjazd = już dziś błąd gdzieś)?",
"Które wartości są zmienne rocznie (ZUS, kwota wolna) i nie mają okien temporalnych?",
"Które liczby są strukturalne (zaokrąglenia, konwersje) i mogą zostać w kodzie jako stałe inżynierskie?",
]),
dict(name="Migracja wartości do danych",
goal="każda wartość prawna w data.thresholds.*",
questions=[
"Jak wygląda mapowanie migracji (reguła → ścieżka w thresholds_data → walidacja → test)?",
"Które reguły potrzebują prefiksu domeny w ścieżce (vat./pit./zus.) i jaki standard nazw parametrów?",
"Jak test regresji dowodzi, że po migracji wyliczenia są IDENTYCZNE (golden replay)?",
"Które migracje wymagają aktualizacji dokumentacji (P41) i kontraktów (P03)?",
]),
dict(name="Zarządzanie i integralność danych",
goal="parametry jako podpisany, wersjonowany dokument",
questions=[
"Czy thresholds_data ma schemat walidowany w CI (kto pilnuje struktury)?",
"Czy dokument ma checksumę/podpis i jest archiwizowany WORM (dowód stanu parametrów na datę decyzji)?",
"Czy historia zmian (diff wersji) jest śledzona z powiązaniem do nowelizacji (Law Radar P08)?",
"Jak hot-reload respektuje decyzje w locie (decyzja na parametrach z chwili odczytu inputu)?",
]),
dict(name="Testy graniczne parametrów",
goal="day-0 przełączeń i granice wartości",
questions=[
"Czy każdy parametr temporalny ma test day-1/day-0/day+1 (P05)?",
"Czy testy obejmują skrajne wartości (limit osiągnięty dokładnie, przekroczony o grosz)?",
"Czy testy pilnują jednostek (PLN vs % vs mnożnik) — błąd jednostki = katastrofa?",
"Czy fuzzing parametrów wykrywa reguły, które psują się przy wartościach skrajnych?",
]),
],
file_groups=[
dict(name="Dane parametrów i narzędzia audytu", files=[
    ("Progi i stawki (dane)", "JDG/bundles/thresholds_data.json"),
    ("Audyt hardcode", "JDG/tools/hardcoded_audit.py"),
    ("Fix p07 thresholds (migracja)", "JDG/tools/fix_p07_thresholds.py"),
    ("Walidator reguł", "JDG/tools/validate_rules.py"),
    ("Linter rego", "JDG/tools/lint_rego_rules.py"),
    ("Manifest bundle v2", "JDG/bundles/manifest_v2.json"),
    ("Rejestr reguł", "JDG/bundles/rule_registry.json"),
    ("Generator manifestu", "JDG/tools/generate_manifest.py"),
]),
dict(name="Reguły z ryzykiem hardcode (domeny krytyczne)", files=[
    ("Reguły VAT (katalog)", "JDG/rules/micro/vat/vat.rego"),
    ("Progi święte (dokument)", "JDG/rules/thresholds_jdg.rego"),
    ("Test natywny micro ZUS", "JDG/tests/rego/micro/test_native_micro_zus.rego"),
    ("Test natywny ryczałt micro", "JDG/tests/rego/micro/test_native_micro_ryczalt.rego"),
    ("Test kontrol temporalnych", "JDG/tests/test_core_guards_temporal_thresholds.py"),
    ("Test natywny PCC v3", "JDG/tests/rego/test_native_pcc_v3_10.rego"),
]),
dict(name="Deploy i wersjonowanie parametrów", files=[
    ("Skrypt budowy bundle", "JDG/bundles/bundle.sh"),
    ("Rejestr wdrożeń", "JDG/bundles/deployments.json"),
    ("Dokument kontrol temporalnych", "JDG/docs/CORE_GUARDS_TEMPORAL_THRESHOLDS.md"),
    ("Migracja 009 core guards", "JDG/migrations/009_jdg_v14_core_guards.sql"),
    ("WORM storage", "JDG/tools/worm_storage.py"),
    ("Test weryfikatora inwariantów", "JDG/tools/verify_verdict_invariants.py"),
]),
],
legal=[
"Ordynacja podatkowa — art. 12, 13: obowiązku podatkowego na datę zdarzenia — parametry muszą mieć daty obowiązywania.",
"Ustawa VAT — art. 41 ust. 1–13 (stawki), art. 113 (zwolnienie podmiotowe do limitu) — wartości roczne zmienne.",
"Ustawa o PIT — art. 27 ust. 1 (skala), art. 30c (19%), art. 30f (ryczałty tabela) — stawki i progi roczne.",
"Ustawa o ZUS — art. 18d (roczna podstawa), art. 18ab (mały ZUS+) — limity 30-krotności i progi zysku.",
"Ustawa o ryczałcie — załącznik (stawki ryczałtu per PKWiU) — tabela jako dane, nie kod.",
"Ordynacja podatkowa — art. 56 (odsetki), art. 119 (MPP próg 15 000 zł) — wartości weryfikowalne w ISAP.",
"KKS — art. 57 (kwoty sankcji) — parametry sankcji jako dane.",
"ISAP/RCL — każda wartość przeniesiona do danych cytowana z Dz.U. i datą wejścia w życie.",
],
innovations=[
("Parameter registry", "rejestr każdego parametru: ścieżka, wartość bieżąca, historia wartości, akt źródłowy, okno temporalne, właściciel — zapytywalny."),
("Value provenance chain", "parametr → akt → art. → nowela → data → zmiana (diff) — pełne DNA wartości (rozszerzenie P42 DNA reguł o dane)."),
("Temporal parameter gate", "bramka CI: parametr bez valid_from/valid_to przy wartości zmiennej prawnie = BLOCKER."),
("Schema validation for thresholds", "JSON-schema dla thresholds_data walidowana w CI (typ, jednostka, zakres) — błąd jednostki niewykrywalny kodem reguł zostanie złapany w danych."),
("Signed parameter bundles", "bundle parametrów podpisany jak kod (P38) — integralność wartości równa integralności reguł."),
("Day-0 test generation", "generator (P36) tworzy testy przełączenia dla każdego parametru z oknem (dzień przed/po) — automatycznie."),
("Parameter change workflow", "procedura zmiany parametru: PR z cytatem nowelizacji → walidacja → testy day-0 → deploy parametrów bez deployu reguł (szybka adaptacja do prawa)."),
("Unit semantics", "jednostka parametru (% vs PLN vs mnożnik) jawnie w schemacie; reguły walidują jednostkę przy odczycie (defense in depth)."),
("Parameter drift alarm", "porównanie wartości w thresholds_data z wartościami wytropianymi w ISAP (crawler P34) — rozjazd = alarm do Law Radar."),
("Legacy value sweeper", "po migracji: skan kodu w poszukiwaniu „osieroconych” wartości prawnych (liczby wyglądające jak stawki/progi) — rejestr do weryfikacji."),
("Golden replay per parameter change", "każda zmiana parametru uruchamia replay złotych orzeczeń z parametrami OLD i NEW — czytelny diff skutków."),
("Parameter documentation anchor", "każdy parametr ma anchor w dokumentacji (co znaczy, skąd się wziął, kiedy wygasa) — zero magicznych kluczy w danych."),
],
in_contracts=[
"ADR-002 z dokumentów świętych — parametry wyłącznie w data.thresholds.* (nadrzędne nad konwencjami lokalnymi).",
"Rejestr stubów z P45 — reguły skonwertowane ze stubów nie mogą dostawać hardcode w trakcie konwersji.",
],
out_contracts=[
"MAPA MIGRACJI HARDCODE (reguła → parametr → ścieżka → test) — wejście do P36 (generatory) i P68.",
"Parameter registry (format, standard nazw) — wiąże P06 (parametry-as-data) i P41 (dokumentacja).",
"Schema thresholds_data (walidowana) — wejście do P39 (CI) i P38 (bundle).",
],
acceptance_extra=[
"Lista wartości prawnych w kodzie poza thresholds_data — min. 10 pozycji z dowodami (plik+linia) i planem migracji.",
"Standard nazewnictwa parametrów przedstawiony z pełnym przykładem dla VAT, PIT, ZUS.",
]),
dict(code="P47", slug="LEGAL_BASIS_WERYFIKACJA", title="WERYFIKACJA PODSTAW PRAWNYCH — ZERO FIKCJI, KAŻDY CYTAT W ISAP",
role="prawnik-projektantem systemów AI dla prawa, specjalistą od weryfikacji źródeł i budowy rejestru legal basis klasy audytowej",
expertise="weryfikacja aktów w ISAP/RCL, formaty cytowań, śledzenie nowelizacji, rejestr źródeł, mediacje rozbieżności",
mission=[
"Wykonaj pełny audyt _legal_basis w regułach: każdy akt/art./ust./Dz.U./data zweryfikuj co do istnienia i treści (ISAP/RCL/MF). Wygeneruj trzy listy: (1) PODSTAWY ZWERYFIKOWANE OK (złącz z LEGAL_SOURCE_REGISTRY), (2) NIEZWERYFIKOWANE (brak dostępu w sesji — tag + plan), (3) PODEJRZANE/BŁĘDNE (niemożliwe numery pozycji, daty przed ustawą, artykuły spoza zakresu) — lista 3 z priorytetem BLOCKER: fikcyjna podstawa prawna w fortecce to rak. Dokument JDG/docs/Bbb traktuj jako katalog twierdzeń do weryfikacji, nie dowód.",
"Zaprojektuj trwały proces: rejestr źródeł jako dane (akty z identyfikatorem ISAP, datami obowiązywania, URL), walidacja formatu cytowania przy PR (linter prawny), automatyczny re-check aktualności (crawler ISAP cyklicznie, Law Radar P08), procedura mediacji rozbieżności (reguła mówi X, ISAP mówi Y — kto rozstrzyga, jak najszybciej). Zero podstaw [NIEZWERYFIKOWANE] w regułach aktywnych (ACTIVE) — aktywna reguła z fikcyjną podstawą to najgorszy możliwy defekt fortecy.",
],
subparts=[
dict(name="Audyt podstaw w regułach",
goal="każde _legal_basis sprawdzone albo oznaczone",
questions=[
"Które reguły mają _legal_basis puste, placeholder lub nieczytelne (format niezgodny z konwencją)?",
"Które cytowania mają niemożliwe elementy (rok, pozycja, data) — lista podejrzanych z powodem?",
"Które reguły ACTIVE mają podstawy spoza rejestru LEGAL_SOURCE_REGISTRY (duplikaty, warianty)?",
"Jak wygląda rejestr mediacji: reguła vs ISAP rozbieżne — kto ma rozstrzygnąć i do kiedy?",
]),
dict(name="Rejestr źródeł jako dane",
goal="akty z identyfikatorami ISAP i oknami obowiązywania",
questions=[
"Czy LEGAL_SOURCE_REGISTRY pokrywa wszystkie akty użyte w regułach (liczby porównaj z licznikiem reguł)?",
"Czy każdy wpis ma: identyfikator ISAP, tytuł, Dz.U., daty (ogłoszenie/obowiązywanie), status, URL?",
"Czy rejestr obejmuje też rozporządzenia wykonawcze (PKPiR, JPK, KSeF schematy)?",
"Czy wpisy mają okna temporalne (wersja aktu obowiązywała w okresie X) — time-travel P05?",
]),
dict(name="Walidacja formatu i proces PR",
goal="linter prawny na wejściu",
questions=[
"Jaki jest kanoniczny format cytowania (akt, art., ust., pkt, Dz.U. rok poz.) — zdefiniuj z przykładami?",
"Jak linter prawny odrzuca cytowania niezgodne z formatem (blok merge)?",
"Czy PR dodający regułę wymaga pola „weryfikacja ISAP” z datą i osobą (4-eyes prawne)?",
"Jak proces radzi sobie z aktami niepublicznymi/konsolidacjami w toku (wersje robocze)?",
]),
dict(name="Cyclic re-check i mediacje",
goal="aktualność po nowelizacjach",
questions=[
"Czy crawler ISAP (P34) jest uruchamiany cyklicznie (harmonogram, który zakres aktów)?",
"Jak wykrywać zmianę treści aktu (diff konsolidacji) → oznaczenie reguł do przeglądu (Law Radar)?",
"Jaki SLA mediacji (reguła vs ISAP) — czas do rozstrzygnięcia, co z decyzjami w toku?",
"Czy proces ma fail-closed: akt zmieniony → reguły dotknięte automatycznie do SHADOW do przeglądu?",
]),
],
file_groups=[
dict(name="Rejestry i dokumenty prawne", files=[
    ("Rejestr źródeł prawnych (dokument)", "JDG/docs/LEGAL_SOURCE_REGISTRY.md"),
    ("Rejestr źródeł prawnych (narzędzie)", "JDG/tests/test_legal_source_registry.py"),
    ("Legal reference acts", "JDG/docs/LEGAL_REFERENCE_ACTS.md"),
    ("Słownik referencji prawnych", "JDG/docs/SLOWNIK_REFERENCJI_PRAWNYCH.md"),
    ("Audit podstaw prawnych", "JDG/docs/AUDYT_PODSTAW_PRAWNYCH.md"),
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
    ("Remediacja podstaw P00", "JDG/docs/P00_REMEDIACJA_PODSTAW_PRAWNYCH.md"),
    ("Kalendarz zmian prawnych", "JDG/docs/KALENDARZ_ZMIAN_PRAWNYCH.md"),
]),
dict(name="Narzędzia weryfikacji", files=[
    ("Walidacja podstaw prawnych", "JDG/tools/validate_legal_basis.py"),
    ("Walidacja podstaw prawnych v2", "JDG/tools/validate_legal_basis_v2.py"),
    ("Crawler ISAP", "JDG/tools/isap_crawler.py"),
    ("Pipeline aktualizacji ISAP", "JDG/tools/isap_rule_update_pipeline.py"),
    ("Alarm dryfu ISAP", "JDG/tools/isap_drift_alarm.py"),
    ("Walidacja P24", "JDG/tools/validate_p24_legal_basis.py"),
    ("Analizator wpływu zmiany prawnej", "JDG/tools/legal_change_impact_analyzer.py"),
    ("Fix hyper legal basis", "JDG/tools/fix_hyper_legal_basis.py"),
]),
dict(name="Testy rejestru i zgodności", files=[
    ("Test rejestru źródeł", "JDG/tests/test_legal_source_registry.py"),
    ("Test legal twin traceability", "JDG/tests/test_legal_twin_traceability.py"),
    ("Test infrastruktury legal twin", "JDG/tests/test_legal_twin_infrastructure.py"),
    ("Legal Twin traceability (dokument)", "JDG/docs/LEGAL_TWIN_TRACEABILITY.md"),
    ("Zgodność prawna (dokument)", "JDG/docs/ZGODNOSC_PRAWNA.md"),
    ("Graf prawny (LKG)", "JDG/bundles/legal_graph.json"),
]),
],
legal=[
"Zasada pisania prawa — ISAP jako jedyny publikator tekstów ujednoliconych (konstytucyjny wymóg promulgacji).",
"Ordynacja podatkowa — art. 24b–24e (prawo właściwe w czasie: obowiązuje tekst na datę zdarzenia).",
"Ordynacja podatkowa — art. 189a–189e (interpretacje ogólne i CLZ jako źródło praktyki stosowania).",
"Ustawa o trybunale konstytucyjnym — wyroki TK jako źródło wykładni (kontekst).",
"Ustawa VAT/PIT/ZUS — weryfikacja wszystkich artykułów cytowanych w regułach (lista z sekcji 8 części V3).",
"Regulamin Sejmu — proces legislacyjny (legislacja.gov.pl) jako źródło dat wejścia w życie.",
"AI Act — systemy wspierające decyzje prawne: wymóg identyfikowalności źródeł (kontekst, weryfikacja statusu).",
"KKS — fikcyjna podstawa w deklaracji = ryzyko czynu zabronionego (najwyższy priorytet eliminacji).",
],
innovations=[
("Legal basis census", "pełny spis: liczba reguł per akt, liczba podstaw zweryfikowanych/niezweryfikowanych/podejrzanych — jedna metryka zdrowia prawnego fortecy."),
("Citation linter", "walidator formatu cytowań (kanon z raportu) w bramce PR — zero nowych podstaw w złym formacie."),
("ISAP anchor for every act", "każdy wpis rejestru z URL ISAP i identyfikatorem — klik z raportu prosto do konsolidacji."),
("Temporal act versions", "rejestr trzyma WERSJE aktów (konsolidacja obowiązywała od–do) — time-travel P05 działa na wersjach prawa, nie tylko parametrów."),
("Auto re-check scheduler", "harmonogram re-checku aktów (crawler) z priorytetem: akty reguł ACTIVE codziennie, CANDIDATE co tydzień."),
("Discrepancy mediation workflow", "rozbieżność reguła↔ISAP tworzy ticket z SLA, blokuje awans CANDIDATE→ACTIVE i oznacza ACTIVE do przeglądu (fail-closed prawny)."),
("Fictional basis blocker", "tryb awaryjny: podstawa oznaczona BŁĄD_PODSTAWY_PRAWNEJ → reguła automatycznie SHADOW + wszystkie decyzje na niej get RE-EXAMINE flag."),
("Legal basis completeness score", "wskaźnik: % reguł z pełnym łańcuchem (akt→art→ust→pkt) — cel 100% dla ACTIVE, trend w P37."),
("ISAP diff watch", "monitoring konsolidacji: zmiana treści artykułu → lista reguł dotkniętych (impact analyzer) → automatyczne SHADOW."),
("Human verification stamp", "pole „zweryfikował człowiek” z datą w rejestrze — weryfikacja AI nie zastępuje człowieka (4-eyes prawne)."),
("Acts coverage heatmap", "mapa cieplna: które akty mają pełne pokrycie regułami, które są pustyniami (spina z P51)."),
("Citation style guide", "dokument konwencji cytowań z przykładami poprawnych/niepoprawnych — część dokumentacji P41."),
],
in_contracts=[
"Dokumenty święte — obowiązek weryfikacji źródeł (Bbb = twierdzenia) jest nadrzędny wobec konwencji lokalnych.",
"Rejestr stubów z P45 — reguły bez treści prawnej i reguły z fikcyjną podstawą to wspólny rejestr defektów prawnych.",
],
out_contracts=[
"AUDYT PODSTAW (3 listy: OK/NIEZWERYFIKOWANE/PODEJRZANE) — wejście do P51 (pustynie) i P68.",
"Kanon cytowań (format + przykłady) — wiąże P41 (dokumentacja) i P36 (generatory).",
"Proces mediacji rozbieżności (SLA, fail-closed) — wiąże P08 (Law Radar) i P07 (lifecycle).",
],
acceptance_extra=[
"Trzy listy podstaw (OK/NIEZWERYFIKOWANE/PODEJRZANE) z licznikami i dowodami — kompletne dla zakresu.",
"Min. 10 podstaw podejrzanych z analizą dlaczego (niemożliwa data/pozycja) i propozycją korekty.",
]),
dict(code="P48", slug="MIRROR_SYNC", title="SYNCHRONIZACJA MIRROR POLICIES — ZERO DRYFU CANONICAL↔MIRROR",
role="inżynierem repozytoriów z replikacją kodu (canonical ↔ mirror), specjalistą od wykrywania i eliminowania dryfu semantycznego",
expertise="semantic diff rego, parowanie AST, synchronizacja automatyczna, bramki drift, git workflows",
mission=[
"Porównaj JDG/rules z policies/ (573 pliki): plik-po-pliku, czy treść jest semantycznie identyczna. Dryf mirror to cichy zabójca zgodności: build może użyć mirror, testy canonical — wyniki różnią się bez alarmu. Wygeneruj pełną mapę dryfu (plik → różnica → ryzyko → akcja) i program synchronizacji: mirror jako artefakt generowany z canonical (nie ręcznie utrzymywany), sync w tej samej transakcji co zmiana canonical (P36), bramka CI wykrywająca dryf semantyczny (AST diff, nie nazwa pliku).",
"Zaprojektuj architekturę: jedno źródło prawdy (JDG/rules), mirror jako build output (policies/ generowany) albo jawny overlay (jeśli mirror ma celowo inne zachowanie — dokumentowane). Każde rozwiązanie z pełną ścieżką migracji istniejącego dryfu. Przeprować głęboką analizę: który z mirrorów (jdg, tax, vat) dryfuje najbardziej i dlaczego (proces? narzędzie? człowiek?).",
],
subparts=[
dict(name="Mapa dryfu canonical↔mirror",
goal="pełna lista rozjazdów z semantyką",
questions=[
"Które pliki istnieją tylko w canonical albo tylko w mirror (duplikaty połowe — luka synchronizacji)?",
"Które pliki różnią się treścią (diff tekstowy) i które różnice są SEMANTYCZNE (AST, wartości, warunki)?",
"Które różnice są celowe (overlay, komentarze, nagłówki) a które przypadkowe (dryf procesu)?",
"Które bundle/manifest w mirror wskazują na inne wersje niż canonical (dryf danych)?",
]),
dict(name="Architektura synchronizacji",
goal="jedno źródło prawdy",
questions=[
"Jaki model wybrać: mirror jako build output (generowany) czy overlay z deklaracją różnic?",
"Jak synchronizować w tej samej PR co canonical (brak osobnych commitów — dryf czasowy)?",
"Jak bramka CI wykrywa dryf (AST diff + walidacja overlay) i blokuje merge przy rozjeździe?",
"Co z historią git mirror (gdy mirror staje się build output — archiwizacja starej struktury)?",
]),
dict(name="Testy i walidacja mirror",
goal="mirror testowany równie surowo",
questions=[
"Czy testy natywne rego uruchamiają się na mirror (te same wyniki)?",
"Czy golden replay (P10) uruchamiany jest na mirror bundle (zgodność decyzji)?",
"Czy dryf mirror wykrywany jest też po deploy (kontrola post-deploy P38)?",
"Kto odpowiada za mirror (właściciel w rejestru) — czy procedura reakcji istnieje?",
]),
dict(name="Case study dryfu",
goal="głęboka analiza najgorszego przypadku",
questions=[
"Który pakiet ma największy dryf i jak do tego doszło (historia git)?",
"Jaki byłby skutek prawny użycia dryfującej wersji (błędna decyzja AUTO_POST)?",
"Jak procesy (PR, review, deploy) przeoczyły dryf — gdzie wzmocnić kontrole?",
"Jak szybko domknąć ten przypadek (plan naprawy z terminem i właścicielem)?",
]),
],
file_groups=[
dict(name="Mirror policies — struktura", files=[
    ("Mirror jdg (katalog)", "policies/jdg"),
    ("Mirror tax (katalog)", "policies/tax"),
    ("Mirror VAT (katalog)", "policies/tax/vat"),
    ("Skrypt budowy bundle mirror", "policies/jdg/bundles/bundle.sh"),
    ("Manifest bazowy mirror", "policies/jdg/bundles/base/manifest.json"),
    ("Overlay v2026 mirror", "policies/jdg/bundles/overlays/v2026/manifest.json"),
]),
dict(name="Canonical — punkty odniesienia", files=[
    ("Reguły canonical (katalog)", "JDG/rules"),
    ("Reguły VAT canonical", "JDG/rules/micro/vat/vat.rego"),
    ("Bramka synchronizacji mirror", "JDG/tools/policies_mirror_report22_gate.py"),
    ("Audyt synchronizacji mirror", "JDG/tools/policies_mirror_sync_etap26_audit.py"),
    ("Test synchronizacji mirror", "JDG/tests/test_policies_mirror_sync_etap26_audit.py"),
    ("Detektor konfliktów między pakietami", "JDG/tools/cross_package_conflict_detector.py"),
    ("Walidator spójności dokumentów", "JDG/tools/doc_consistency_validator.py"),
]),
dict(name="Deploy i bundle w obu światach", files=[
    ("Skrypt budowy bundle canonical", "JDG/bundles/bundle.sh"),
    ("Katalog bundle", "JDG/bundles/bundle_catalog.json"),
    ("Rejestr wdrożeń", "JDG/bundles/deployments.json"),
    ("Test walidatora JPK (mirror-agnostyczny)", "JDG/tools/jpk_validator.py"),
    ("Dokument struktury projektu", "JDG/docs/STRUKTURA_PROJEKTU.md"),
]),
],
legal=[
"Ordynacja podatkowa — art. 24b: silnik musi stosować tekst obowiązujący na datę zdarzenia — dwie wersje reguł = dwie interpretacje prawa.",
"Ustawa VAT — art. 106b–109e: ewidencje muszą być spójne — mirror i canonical muszą dawać ten sam JPK.",
"Ustawa o rachunkowości — art. 4 ust. 1: sprawdzalność — dowód musi być jeden (która wersja jest prawdziwa?).",
"Ustawa o ZUS — art. 47–48: deklaracje składkowe spójne — rozjazd mirror = rozjazd deklaracji.",
"RODO — art. 5 ust. 1d (prawidłowość): przetwarzanie na dwóch wersjach reguł narusza prawidłowość.",
"Ustawa o rachunkowości — art. 5: zapisy odzwierciedlają rzeczywisty stan — reguła użyta do zapisu musi być ta sama.",
"KSeF — schematy wykonawcze: mirror i canonical muszą obsługiwać tę samą wersję schematu.",
"AI Act — wersjonowanie systemu z rozróżnieniem canonical/deployed (kontekst audytowy).",
],
innovations=[
("Mirror as build output", "policies/ generowany z JDG/rules jednym poleceniem; PR nie może edytować mirror ręcznie (CODEOWNERS + bramka) — dryf strukturalnie niemożliwy."),
("Semantic AST diff gate", "bramka: AST canonical vs mirror identyczne albo overlay zadeklarowany — tekstowy diff ignorowany, semantyczny blokuje."),
("Sync-in-PR rule", "zmiana canonical bez synchronicznego mirror (albo bez deklaracji overlay) = odrzucenie PR."),
("Drift heatmap", "mapa cieplna dryfu per pakiet (0 = idealna sync) z trendem; cel 0 dla wszystkich pakietów."),
("Overlay declaration file", "jeśli mirror ma celowo inne zachowanie: plik OVERLAY.md w pakiecie z powodem, zakresem, właścicielem i terminem przeglądu — jawne, nie ukryte."),
("Mirror test parity", "testy natywne uruchamiane na canonical i mirror w jednym job; wyniki porównywane (diff = BLOCKER)."),
("Golden replay on mirror", "złote orzeczenia odtwarzane na mirror bundle przed deploy — zgodność decyzji wymuszona."),
("Mirror ownership register", "każdy pakiet mirror ma właściciela i częstotliwość przeglądu — zero pakietów osieroconych."),
("Post-deploy mirror check", "po deploy: kontrola, że bundle zbudowany z canonical (checksum match) — wykrycie deploy z dryfującego źródła."),
("Case-study template", "wzorzec analizy dryfu (przypadek → przyczyna → skutek → naprawa → kontrola) — standard dla kampanii przyszłych."),
("Mirror lifecycle alignment", "mirror dziedziczy lifecycle z canonical (SHADOW w canonical = SHADOW w mirror) — zero rozjazdu statusów."),
("One-truth attestation", "certyfikat decyzji zawiera hash reguły użytej (nie tylko rule_id) — dowód, która wersja wyliczyła."),
],
in_contracts=[
"Kanon artefaktów z P00 — mapa dryfu spójna z inwentaryzacją (liczby plików canonical/mirror).",
"Sieć walidacji z P34 — AST diff jako narzędzie sieci (L4: spójność).",
],
out_contracts=[
"MAPA DRYFU (pełna, z semantyką) — wejście do P68 (re-certyfikacja) i P36 (sync-in-PR).",
"Architektura mirror (model + ścieżka migracji) — wiąże P38 (bundle: skąd build) i P41 (dokumentacja struktury).",
"Bramka AST diff (konfiguracja) — wejście do P29 (bramki) i P39 (CI).",
],
acceptance_extra=[
"Mapa dryfu z licznikami (identyczne / tekstowo-różne / semantycznie-różne / jednostronne) — per pakiet.",
"Case study najgorszego dryfu z pełną analizą (przyczyna, skutek, plan naprawy, kontrola zapobiegawcza).",
]),
dict(code="P49", slug="FAIL_CLOSED_DOMKNIECIE", title="DOMKNIĘCIE FAIL-CLOSED — ZERO CICHYCH AUTO_POST, KAŻDA NIEPEWNOŚĆ MA ŚCIEŻKĘ",
role="specjalistą od architektury fail-safe w systemach decyzyjnych, projektantem ścieżek awaryjnych i domyślnych bezpiecznych",
expertise="default-deny, ścieżki NEEDS_ADVICE/MANUAL_REVIEW, invarianty runtime, testy negatywne, analiza ścieżek decyzyjnych",
mission=[
"Przeanalizuj WSZYSTKIE ścieżki decyzyjne reguł pod kątem fail-open: czy przy braku pola, braku danych, konflikcie pakietów, wartości spoza zakresu, niepewności prawnej — reguła domyślnie IDZIE DO NEEDS_ADVICE/MANUAL_REVIEW, czy cicho liczy/AUTO_POSTuje? Wygeneruj rejestr ścieżek fail-open (najgroźniejsza klasa defektów fortecy) i program domknięcia: każda reguła z else-chain kończącą jawnym NEEDS_ADVICE, brak pola → NEEDS_ADVICE, konflikt → MANUAL_REVIEW, nigdy ciche „true => AUTO_POST”.",
"Zaprojektuj egzekucję architektoniczną: invariant runtime (P04) odrzucający werdykt AUTO_POST bez pełnego łańcucha dowodów (kontrakt werdyktu P03 — pola obowiązkowe), testy negatywne systematyczne (generator: dla każdej reguły przypadki „brak pola X” → asercja NEEDS_ADVICE), chaos input (mutacje input z asercją fail-closed), audyt runtime (probe decyzyjne: co by było gdyby...). Forteca domyślnie broni przedsiębiorcy: wątpliwość = człowiek.",
],
subparts=[
dict(name="Audyt ścieżek fail-open",
goal="rejestr cichych auto-postów",
questions=[
"Które reguły zwracają AUTO_POST bez sprawdzenia kompletności inputu (brak pól obowiązkowych)?",
"Które else-chain domyślnie „lbiną” na wersję najkorzystniejszą dla podatnika (ryzyko prawne)?",
"Które reguły przy konflikcie z innym pakietem wybierają wartość bez MANUAL_REVIEW?",
"Które pola werdyktu (P03) są wypełniane domyślnie bez prawdziwego dowodu (fasadowa pewność)?",
]),
dict(name="Invariant runtime jako ostateczna linia",
goal="warstwa konstytucyjna egzekwuje fail-closed",
questions=[
"Czy invarianty P04 odrzucają AUTO_POST przy braku pól obowiązkowych (test na live bundle)?",
"Czy istnieje „circuit breaker”: seria NEEDS_ADVICE z jednej domeny → tryb awaryjny domeny?",
"Czy decyzje AUTO_POST mają kwotowy limit automatyczny (ponad limit → człowiek) — jako dane (P46)?",
"Czy invarianty są testowane po każdym deploy (smoke test fail-closed)?",
]),
dict(name="Systematyczne testy negatywne",
goal="generator przypadków brakujących danych",
questions=[
"Czy każda reguła ma test „brak pola X → NEEDS_ADVICE” (jak wygenerować systematycznie z kontraktu P03)?",
"Czy testy obejmują wartości brzegowe puste (null, 0, pusty string, brak klucza — różne braki)?",
"Czy chaos input (mutacje) testuje kombinacje braków (pole A brak + pole B skrajne)?",
"Czy testy pilnują, że NEEDS_ADVICE ma POWÓD (nie pusty powód — fasada fail-closed)?",
]),
dict(name="Audyt ścieżek awaryjnych",
goal="co się dzieje, gdy awaria przerwie ścieżkę",
questions=[
"Czy przy awarii OPA/narzędzia pipeline wchodzi w tryb kolejki (nie gubi dokumentów — P32)?",
"Czy dostęp awaryjny do decyzji (eksport certyfikatów) działa bez pełnej platformy (DR P43)?",
"Czy NEEDS_ADVICE ma SLA i właściciela (kolejka nie może rosnąć w nieskończoność — P37 metryka)?",
"Czy użytkownik widzi stan NEEDS_ADVICE w UI z jasną akcją (P40) — fail-closed też musi być użyteczny?",
]),
],
file_groups=[
dict(name="Narzędzia fail-closed i invarianty", files=[
    ("Test weryfikatora inwariantów", "JDG/tools/verify_verdict_invariants.py"),
    ("Walidacja kontraktu enterprise", "JDG/tools/validate_enterprise_contract.py"),
    ("Strażnik semantyczny (test)", "JDG/tests/test_semantic_guard.py"),
    ("Silnik ryzyka (test)", "JDG/tests/test_risk_guard.py"),
    ("Test integracji silnika ryzyka", "JDG/tests/test_risk_guard_integration.py"),
    ("Test kontrol temporalnych", "JDG/tests/test_core_guards_temporal_thresholds.py"),
    ("Dokument kontrol temporalnych", "JDG/docs/CORE_GUARDS_TEMPORAL_THRESHOLDS.md"),
    ("Chaos engineering", "JDG/tools/chaos_engineering.py"),
    ("Chaos runner", "JDG/tools/chaos_runner.py"),
]),
dict(name="Kontrakt werdyktu i kompozycja", files=[
    ("Kompozycja decyzji (reguła)", "JDG/rules/decision_composer_enterprise.rego"),
    ("Kompletność decision core", "JDG/rules/decision_core_completeness_enterprise.rego"),
    ("Scoring decyzji", "JDG/rules/decision_scoring_enterprise.rego"),
    ("Innowacje decision core", "JDG/rules/p02_decision_core_innovations_v9.rego"),
    ("Dokument DECISION_CORE_P02", "JDG/docs/DECISION_CORE_P02.md"),
    ("Dokument orkiestrator kontraktu", "JDG/docs/ORCHESTRATOR_DATA_CONTRACT.md"),
]),
dict(name="Testy negatywne i chaos", files=[
    ("Test edge cases enterprise", "JDG/tests/test_edge_cases_enterprise.py"),
    ("Test konfliktów enterprise", "JDG/tests/test_conflicts_enterprise.py"),
    ("Test natywny edge cases", "JDG/tests/rego/test_native_edge_cases_enterprise.rego"),
    ("Test natywny kompozytora decyzji", "JDG/tests/rego/test_native_decision_composer_enterprise.rego"),
    ("Test natywny GAAR shield", "JDG/tests/rego/test_native_gaar_shield_enterprise.rego"),
    ("Test natywny cross-declaration", "JDG/tests/rego/test_native_cross_declaration_validator_enterprise.rego"),
]),
],
legal=[
"Ordynacja podatkowa — art. 21 §1: organ stosuje prawo materialne — silnik nie może cicho przyjmować interpretacji korzystnych.",
"Ordynacja podatkowa — art. 119a: klauzula GAAR wymaga analizy — cichy AUTO_POST agresywnej konstrukcji = ryzyko",
"Ustawa VAT — art. 108: nieprawidłowa stawka — fail-open na stawce = podatnik płaci błędnie (i sankcje).",
"Ustawa o PIT — art. 45 (obowiązek rocznego zeznania) — błędne ciche wyliczenia kaskadą błędów w zeznaniu.",
"Ustawa o ZUS — art. 47–48 (deklaracje): ciche błędne składki → zaległości i odsetki.",
"KKS — art. 56–57: cichy błąd w deklaracji = ryzyko czynu zabronionego (fail-closed jako ochrona prawna).",
"RODO — art. 22 (decyzje zautomatyzowane): człowiek musi mieć wpływ — NEEDS_ADVICE jako mechanizm prawny.",
"Ustawa o rachunkowości — art. 4 ust. 1: rzetelność — ciche wartości domyślne naruszają rzetelność.",
],
innovations=[
("Fail-closed invariant pack", "zbiór invariantów runtime (kompletność pól, spójność podpisów, zakresy) uruchamiany przed każdym AUTO_POST — odmowa bez pełnego łańcucha."),
("Default-deny decision core", "decyzja CORE domyślnie NEEDS_ADVICE; AUTO_POST wymaga pozytywnego dowodu WSZYSTKICH przesłanek (whitelist dowodów, nie blacklist braków)."),
("Missing-field generator", "narzędzie: dla każdej reguły generuje przypadki z brakiem każdego pola obowiązkowego (systematyczny negatywny test) — 100% pokrycie ścieżek braku."),
("Chaos input suite", "mutacje input (braki, skrajne wartości, złe typy, waluty) z asercją NEEDS_ADVICE/MANUAL_REVIEW — property-based fail-closed."),
("Circuit breaker per domain", "seria N decyzji NEEDS_ADVICE z domeny w oknie T → domena w tryb REVIEW (temporarily all MANUAL) z raportem przyczyny."),
("Amount ceiling as data", "limit kwotowy AUTO_POST jako parametr (P46): powyżej — człowiek (nawet przy pełnym dowodzie, decyzja wielka = 4-eyes)."),
("Reason completeness check", "NEEDS_ADVICE bez czytelnego powodu (pusty/krótki) = defekt (linter ścieżek NEEDS_ADVICE) — fail-closed nie może być fasadą."),
("Emergency export path", "ścieżka awaryjna eksportu certyfikatów i stanu (DR P43) — dostępna bez pełnej platformy."),
("Decision trail replay audit", "cotygodniowy audyt: replay decyzji AUTO_POST z tygodnia na obecnych regułach — decyzje, które dziś byłyby NEEDS_ADVICE → lista do rewizji."),
("Fail-closed score", "metryka: % ścieżek reguł jawnie fail-closed (else → NEEDS_ADVICE) — cel 100%, trend w P37."),
("Silent-post canary", "probe decyzyjny: syntetyczne inputy z brakami wprowadzane cyklicznie do produkcji (test z ukrycia) — asercja fail-closed na żywo."),
("User-visible safety", "UI (P40): NEEDS_ADVICE zawsze z akcją („co muszę uzupełnić”), AUTO_POST z dowodem do pobrania — bezpieczeństwo = użyteczność."),
],
in_contracts=[
"Kontrakt werdyktu z P03 — pola obowiązkowe i NEEDS_ADVICE/MANUAL_REVIEW zgodne z ADR-004.",
"Invarianty z P04 — warstwa konstytucyjna nadrzędna nad regułami domen (fail-closed egzekwowany centralnie).",
],
out_contracts=[
"REJESTR ŚCIEŻEK FAIL-OPEN (pełny) — wejście do P45 (stuby często współistnieją) i P68.",
"Invariant pack fail-closed (lista + testy) — wiąże P04 (invarianty) i P39 (CI smoke).",
"Generator brakujących pól (narzędzie) — wejście do P36 (generatory) i P39 (testy).",
],
acceptance_extra=[
"Rejestr ścieżek fail-open z priorytetami (która ścieżka może wywołać błędny AUTO_POST na dużych kwotach).",
"Chaos suite przedstawiony z min. 10 scenariuszami mutacji input i oczekiwanymi wynikami fail-closed.",
]),
dict(code="P50", slug="DEAD_CODE_DUPLIKATY", title="DEAD CODE I DUPLIKATY — UNIKALNOŚĆ RULE_ID, JEDNO ŹRÓDŁO PRAWDY PER ZASADA",
role="refaktoryzatorem dużych baz reguł, specjalistą od deduplikacji semantycznej i porządkowania repozytoriów policy-as-code",
expertise="deduplikacja reguł, unikalność rule_id, wykrywanie martwego kodu, konsolidacja wariantów, rejestr źródeł prawdy",
mission=[
"Wykonaj pełny spis: reguły zduplikowane (ta sama zasada prawna w macro, micro i enterprise bez rejestru, która jest źródłem prawdy), rule_id kolidujące (ten sam identyfikator w różnych pakietach albo w canonical i mirror), martwe reguły (nigdy nie wywołane przez orkiestrator — dead_rule_detector), martwe narzędzia (nikt nie importuje/uruchamia), martwe dane w bundle (klucze nieużywane przez reguły). Duplikat bez rejestru = ryzyko sprzecznych decyzji w tym samym dniu.",
"Zaprojektuj konsolidację: dla każdej zasady prawnej JEDNO źródło prawdy (pakiet + rule_id), inne warianty jako jawne view/referencje albo usunięte; globalna unikalność rule_id egzekwowana (bramka); pakietowy routing (P02) jako jedyny punkt wywołania (martwe = niepodpięte → usunąć lub podpiąć). Rejestr duplikatów z decyzją per para (konsoliduj/usuń/deklaruj celowe warianty z powodem). Przeprować głęboką analizę: skąd wzięły się duplikaty (generatory z planów? kopie kampanii?) i jak temu zapobiec.",
],
subparts=[
dict(name="Spis duplikatów semantycznych",
goal="ta sama zasada w wielu miejscach",
questions=[
"Które pary reguł (różne rule_id) implementują tę samą zasadę (porównanie semantyczne warunków i skutków)?",
"Które duplikaty dają SPRZECZNE wyniki na tym samym input (najgroźniejsze — decyzja losowa)?",
"Które duplikaty mają różne daty obowiązywania (celowe wersje temporalne czy nieporządek)?",
"Które duplikaty mają różne podstawy prawne (jedna poprawna, druga nie — rejestr P47)?",
]),
dict(name="Unikalność rule_id i routing",
goal="identyfikator = tożsamość reguły",
questions=[
"Które rule_id się powtarzają (globalnie, między pakietami, między canonical i mirror)?",
"Które reguły nie są osiągalne z routingu orkiestratora (martwe — dead_rule_detector)?",
"Które reguły są osiągalne z wielu ścieżek (routing konfliktowy — pierwszeństwo niezdefiniowane)?",
"Jak wygląda standard rule_id (konwencja) i jak bramka egzekwuje unikalność przy PR?",
]),
dict(name="Martwe narzędzia i dane",
goal="repo bez zbędnych elementów",
questions=[
"Które narzędzia nie są importowane przez nic i nie mają testów (martwe)?",
"Które klucze w thresholds_data i bundle JSON nie są odczytywane przez reguły (martwe dane)?",
"Które dokumenty opisują elementy nieistniejące (dokumenty-widma)?",
"Jaka jest procedura bezpiecznego usunięcia (archiwum zamiast twardego delete, rejestry, rollback)?",
]),
dict(name="Konsolidacja i zapobieganie",
goal="jedno źródło prawdy i ścieżka do niego",
questions=[
"Jak wygląda plan konsolidacji per duplikat (który wariant zostaje, jak migrują odwołania, co z historią)?",
"Czy „celowe warianty” (np. ryczałt 2025 vs 2026) mają jawną deklarację (overlay P48) z powodem?",
"Jak generatory (P36) zapobiegną tworzeniu duplikatów (crossref przy generacji)?",
"Jak rejestry (rule_registry) mają wykrywać duplikaty semantyczne (hash warunków)?",
]),
],
file_groups=[
dict(name="Narzędzia deduplikacji i dead code", files=[
    ("Dedup micro plan33", "JDG/tools/dedup_micro_plan33.py"),
    ("Fix p00 duplicates", "JDG/tools/fix_p00_duplicates.py"),
    ("Fix plan34 duplicates", "JDG/tools/fix_plan34_duplicates.py"),
    ("Detektor dead rules", "JDG/tools/dead_rule_detector.py"),
    ("Detektor konfliktów między pakietami", "JDG/tools/cross_package_conflict_detector.py"),
    ("Detektor dead code else-chain", "JDG/tools/else_chain_dead_code_detector.py"),
    ("Symulator wpływu reguł", "JDG/tools/rule_impact_simulator.py"),
    ("Crossref plan50", "JDG/tools/crossref_plan50.py"),
]),
dict(name="Rejestry tożsamości reguł", files=[
    ("Rejestr reguł", "JDG/bundles/rule_registry.json"),
    ("Katalog bundle", "JDG/bundles/bundle_catalog.json"),
    ("Manifest bundle v2", "JDG/bundles/manifest_v2.json"),
    ("Enterprise registry", "JDG/bundles/enterprise_v3_registry.json"),
    ("Menedżer lifecycle", "JDG/tools/rule_lifecycle_manager.py"),
    ("Migrator rule_id VAT", "JDG/tools/vat_ruleid_migrator.py"),
    ("Katalog reguł (dokument)", "JDG/docs/KATALOG_REGUL.md"),
    ("Inwentaryzacja plików", "JDG/docs/INWENTARYZACJA_PLIKOW.md"),
]),
dict(name="Routing i orkiestrator", files=[
    ("Dokument orkiestrator", "JDG/docs/DECISION_CORE_P02.md"),
    ("Kontrakt danych orkiestratora", "JDG/docs/ORCHESTRATOR_DATA_CONTRACT.md"),
    ("Dokument OPA jako system", "JDG/docs/OPA_JAKO_SYSTEM_P21.md"),
    ("Test natywny cross-domain intelligence", "JDG/tests/rego/test_native_cross_domain_intelligence_enterprise.rego"),
    ("Test kontraktu danych orkiestratora", "JDG/tests/test_orchestrator_data_contract.py"),
]),
],
legal=[
"Ordynacja podatkowa — art. 24b: jedna interpretacja prawa na datę zdarzenia — duplikaty dają dwie interpretacje.",
"Ustawa VAT — art. 41/43: jedna stawka/zwolnienie dla towaru — duplikat z różną stawką = decyzja losowa.",
"Ustawa o PIT — art. 22–30: jedna zasada kosztu — duplikaty z różnymi warunkami = ryzyko sporu.",
"Ustawa o ZUS — art. 18a: jedna podstawa wymiaru — duplikaty = rozjazd składek.",
"Ustawa o rachunkowości — art. 4 ust. 1: sprawdzalność — reguła użyta do zapisu musi być jedyna i identyfikowalna.",
"KKS — art. 56: rozjazd duplikatów = nieświadome błędne deklaracje.",
"Ordynacja podatkowa — art. 199a–199c (CLZ): stabilność interpretacji wymaga spójności implementacji.",
"RODO — art. 5 ust. 1c: minimalizacja — martwe dane w bundle to zbędne przetwarzanie.",
],
innovations=[
("Semantic duplicate detector", "hash warunków (AST) + porównanie skutków: pary reguł z identyczną semantyką — rejestr do konsolidacji, niezależnie od nazw."),
("Contradiction check", "sub-zbiór detektora: duplikaty dające różne wyniki na tym samym input — najwyższy priorytet (BLOCKER)."),
("Global rule_id uniqueness gate", "bramka CI: rule_id musi być globalnie unikalny (canonical+mirror+rejestry) — zero kolizji od teraz."),
("Single-source-of-truth register", "rejestr: zasada prawna → pakiet źródłowy → rule_id → warianty (jawne, z powodem) — zapytywalny."),
("Dead tool archive", "procedura: narzędzie martwe → archiwizacja (katalog archive/ z README powodu) → usunięcie po 2 cyklach bez sprzeciwu."),
("Orphan data sweeper", "skaner kluczy data.* nieodczytywanych przez reguły — rejestr (usunąć/podpiąć/dokumentować)."),
("Ghost doc detector", "dokumenty odwołujące się do nieistniejących plików/reguł — rejestr z korektą (P41)."),
("Duplication prevention in generators", "generatory (P36) przed dodaniem reguły sprawdzają hash semantyczny (duplikat = fail-fast z linkiem do istniejącej)."),
("Consolidation ledger", "dziennik konsolidacji: co scalono, gdzie migrowały odwołania, wynik golden replay — pełna historia."),
("Intentful variants", "celowe warianty (temporalne/domenowe) jako zadeklarowane overlaye (P48) — przestają być duplikatami, stają się architekturą."),
("Rule reachability map", "mapa: routing → reguły osiągalne → ścieżki wywołania — zero reguł bez punktu wejścia."),
("Duplicate burden metric", "wskaźnik: % reguł będących duplikatami — cel 0%, trend w P37."),
],
in_contracts=[
"Kanon artefaktów z P00 — spis duplikatów spójny z inwentaryzacją (rule_id, pakiety).",
"Mapa dryfu z P48 — duplikaty canonical↔mirror to wspólny rejestr (rozwiązywane razem).",
],
out_contracts=[
"REJESTR DUPLIKATÓW (z decyzjami) — wejście do P68 i P36 (zapobieganie w generatorach).",
"Standard unikalności rule_id (konwencja + bramka) — wiąże P00 (kanon) i P29 (bramki).",
"Procedura archiwizacji martwych elementów — wiąże P41 (dokumentacja) i P43 (DR: archiwum).",
],
acceptance_extra=[
"Spis duplikatów z klasyfikacją (identyczne / sprzeczne / temporalne-warianty) i decyzją per para.",
"Mapa osiągalności reguł (routing) z listą reguł martwych i planem (podpiąć/usunąć).",
]),
dict(code="P51", slug="PUSTYNIE_PRAWNE", title="PUSTYNIE PRAWNE — DOMKNIĘCIE LUK POKRYCIA AKT→REGUŁY",
role="projektantem pokrycia regulacyjnego w systemach policy-as-code, specjalistą od priorytetyzacji luk prawnych",
expertise="macierz akt→art→reguła→test, heat mapy pokrycia, plan domknięcia pustynni, priorytetyzacja ryzyka prawnego",
mission=[
"Przeanalizuj coverage_deserts.json, coverage_canon.json, LEGAL_COVERAGE_GAP_RAPORT.md i macierz PRAWO↔REGUŁA↔TEST wszystkich części V3. Wygeneruj KOMPLETNY rejestr pustyni prawnych: przepisy materiałne w zakresie JDG (VAT, PIT, ZUS, ryczałt, Ordynacja, KKS, KSeF, PCC, BDO, RODO/AML, prawo przedsiębiorców, praca, cross-border) bez reguły albo z regułą bez testu albo z testem bez reguły. Priorytetyzuj wg ryzyka księgowego: co może wywołać błędne AUTO_POST lub przymknąć ważną ulgę.",
"Zaprojektuj program domknięcia: per pustynia — przepis (zweryfikowany w ISAP), propozycja reguły (warunki materiałne z treści przepisu), wymagane testy (granice, temporalne), koszt wdrożenia, kolejność. Cel kwantyfikowany: % aktów z pełnym łańcuchem (akt→art→reguła→test) — definition of done kampanii. Uwzględnij pustynie SYSTEMOWE: odsetki, przedawnienie, ulgi specjalne, KSeF terminy, waluty — często pomijane, a wpływające na codzienne księgowanie.",
],
subparts=[
dict(name="Spis pustyni per domena",
goal="kompletna mapa luk materiałnych",
questions=[
"Które artykuły VAT (41–43, 86–109e, 113, 119) nie mają reguł albo mają reguły bez testów?",
"Które artykuły PIT (22–30c, 45) i ryczałtu (tabela stawek) są pustyniami?",
"Które elementy ZUS (18a–18e, ulgi, chorobowe) mają luki implementacyjne?",
"Które przepisy Ordynacji (odsetki, przedawnienie, 119a) i KKS (56–57) są niepokryte?",
]),
dict(name="Pustynie systemowe (przekrojowe)",
goal="przepisy wpływające na wszystkie domeny",
questions=[
"Które zasady wspólne (moment obowiązku, korekty, odsetki, przedawnienie) nie mają reguł przekrojowych?",
"Które waluty i kursy (NBP) nie mają reguł (przeliczenia — częsta luka)?",
"Które terminy (kalendarz P25) nie mają reguł pilnujących (przypominających, blokujących)?",
"Które korekty i przeniesienia (miesiące, deklaracje korygujące) są bez ścieżek?",
]),
dict(name="Priorytetyzacja wg ryzyka",
goal="kolejność domknięcia z uzasadnieniem",
questions=[
"Które pustynie mogą wywołać błędny AUTO_POST wysokiej kwoty (priorytet P0)?",
"Które pustynie przestają użytkownikowi ulgi (strata realna, mniejsza pilność — P1)?",
"Które pustynie dotyczą zdarzeń rzadkich (P2/P3) — do domknięcia w V4?",
"Jak mierzyć ryzyko pustyni (częstość zdarzenia × kwota × niepewność prawna) — metodologia?",
]),
dict(name="Plan domknięcia",
goal="recepta per pustynia",
questions=[
"Jak wygląda karta pustyni: przepis → warunki materiałne → propozycja reguły → testy → koszt?",
"Które pustynie domknie generator (P36) z treści przepisu (semi-automatyzacja z walidacją człowieka)?",
"Jaki jest cel kwantyfikowany kampanii (np. 90% aktów z pełnym łańcuchem do P68) i jak go mierzyć?",
"Jak Law Radar (P08) pilnuje, że nowe nowelizacje nie tworzą nowych pustyni (proces ciągły)?",
]),
],
file_groups=[
dict(name="Dane i dokumenty pokrycia", files=[
    ("Pustynie pokrycia (dane)", "JDG/bundles/coverage_deserts.json"),
    ("Kanon pokrycia (dane)", "JDG/bundles/coverage_canon.json"),
    ("Dokument kanonu pokrycia", "JDG/docs/COVERAGE_CANON.md"),
    ("Raport luk pokrycia", "JDG/docs/LEGAL_COVERAGE_GAP_RAPORT.md"),
    ("Dokument pokrycia prawnego", "JDG/docs/LEGAL_COVERAGE.md"),
    ("Raport pokrycia", "JDG/COVERAGE_REPORT.md"),
    ("Heat mapa pokrycia prawnego", "JDG/tools/legal_coverage_heatmap.py"),
    ("Unifier pokrycia", "JDG/tools/coverage_unifier.py"),
    ("Test unifiera pokrycia", "JDG/tests/test_coverage_unifier.py"),
]),
dict(name="Narzędzia planu i generacji", files=[
    ("Plan pokrycia 95%", "JDG/tools/coverage_95_plan.py"),
    ("Generator brakujących reguł", "JDG/generate_missing_rules.py"),
    ("Parser plan33 i generator", "JDG/tools/parse_plan33_and_generate.py"),
    ("Generator z plan50", "JDG/tools/generate_from_plan50.py"),
    ("Analizator wpływu zmiany prawnej", "JDG/tools/legal_change_impact_analyzer.py"),
    ("Matryca traceability", "JDG/tools/traceability_matrix.py"),
    ("Matryca traceability VAT", "JDG/tools/vat_traceability_matrix.py"),
    ("Plan unifikacyjny v8", "JDG/unified_plan_v8.yaml"),
]),
dict(name="Rejestry prawne źródła", files=[
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
    ("Rejestr źródeł prawnych", "JDG/docs/LEGAL_SOURCE_REGISTRY.md"),
    ("Legal reference acts", "JDG/docs/LEGAL_REFERENCE_ACTS.md"),
    ("Kalendarz zmian prawnych", "JDG/docs/KALENDARZ_ZMIAN_PRAWNYCH.md"),
    ("Graf prawny (LKG)", "JDG/bundles/legal_graph.json"),
]),
],
legal=[
"Ustawa VAT — pełny zakres art. 5–113 (przedmiot, miejsce świadczenia, stawki, odliczenia, ewidencja) jako mapa pokrycia.",
"Ustawa o PIT — art. 9–45c (formy, koszty, ulgi, terminy) jako mapa pokrycia.",
"Ustawa o ryczałcie — tabela stawek i zasady (art. 6–12) jako mapa pokrycia.",
"Ustawa o ZUS — art. 13–25 (podmioty), art. 18a–18f (wymiar), ulgi (start, mały ZUS+, preferencyjny) jako mapa.",
"Ordynacja podatkowa — art. 12–13 (obowiązek), art. 51–67 (terminy), art. 56 (odsetki), art. 70–71 (przedawnienie), art. 119a.",
"KKS — art. 48–58 (czyny zabronione, sankcje, dobrowolne ujawnienie).",
"Ustawa o rachunkowości — art. 4–7 (ewidencja i wycena) jako mapa kontekstu księgowego.",
"Rozporządzenia wykonawcze (PKPiR, JPK, KSeF) — jako warstwa szczegółów pokrycia.",
],
innovations=[
("Desert register with SLA", "rejestr pustyni: przepis, ryzyko, plan, deadline, właściciel; trend spadkowy w P37 — pustynie znikają, nie gromadzą się."),
("Risk-weighted prioritization", "scoring pustyni (częstość zdarzenia × typowa kwota × niepewność wykładni) — kolejność domknięcia z uzasadnieniem liczbowym."),
("Desert card template", "karta pustyni (przepis → warunki → reguła propozycja → testy → koszt) jako standard raportu — gotowa do wdrożenia."),
("Coverage chain metric", "metryka: % aktów z pełnym łańcuchem akt→art→reguła→test (nie tylko „jest plik”) — cel kwantyfikowany kampanii."),
("Semi-auto rule drafting", "generator szkicu reguły z treści przepisu (struktura warunków) + człowiek wypełnia merytorykę — przyspieszenie 3–5×."),
("Cross-domain desert sweep", "osobny przebieg dla przepisów przekrojowych (waluty, terminy, korekty) — pustynie systemowe łatwo przeoczyć w podziale domenowym."),
("Coverage regression block", "bramka: nowy akt prawny (Law Radar) bez planu reguły → ticket z SLA; zmiana prawa nie może tworzyć pustyni bez alarmu."),
("Desert heatmap by money impact", "mapa cieplna pustyni ważona przepływem kwot (jakie kwoty przechodzą przez obszar bez reguły) — ryzyko widoczne liczbowo."),
("Testless rule sweep", "osobna klasa pustyni: reguła istnieje, test brak — generator testów (P36) domyka szybciej niż pisanie reguł."),
("Quarterly coverage goal", "cel kwartalny pokrycia zależny od domeny (VAT 95%, nisze 70%) — realistyczny, mierzalny."),
("Desert→vacancy mapping", "połączenie pustyni z rejestrem stubów (P45): reguła-fasada jest pustynią prawdziwą (brak treści) — jeden rejestr ryzyka."),
("Legal coverage attestation", "w certyfikacie (P68): deklaracja pokrycia z liczbami i licznikiem zastrzeżeń — enterprises widzą dokładnie, co silnik wie."),
],
in_contracts=[
"Kanon pokrycia z P00 — liczby pustyni spójne z mapą kanoniczną (coverage_canon.json jako baza).",
"Audyt podstaw z P47 — pustynia z podstawą podejrzaną = podwójna luka (priorytet wzrasta).",
],
out_contracts=[
"REJESTR PUSTYNI (kompletny, z priorytetami) — wejście do P36 (generatory), P52 (testy) i P68.",
"Karta pustyni (template) — wiąże P41 (dokumentacja) i kampanie przyszłe.",
"Metodologia scoringu ryzyka pustyni — wiąże P37 (metryki) i P68 (certyfikacja).",
],
acceptance_extra=[
"Rejestr pustyni z licznikami per domena i per klasa (brak reguły / reguła bez testu / test bez reguły).",
"TOP-10 pustyni wg ryzyka z pełnymi kartami (przepis, plan, testy, koszt) gotowymi do wdrożenia.",
]),
dict(code="P52", slug="GRANICE_GROSZOWE", title="GRANICE GROSZOWE, WALUTY I ZAOKRĄGLENI — PRECYZJA WYPOWIEDZI FINANSOWEJ",
role="ekspertem od arytmetyki finansowej w systemach księgowych (zaokrąglenia, waluty, granice groszowe) i projektantem testów precyzji",
expertise="arytmetyka dziesiętna, granice zaokrągleń, kursy NBP, testy brzegowe kwot, invarianty finansowe",
mission=[
"Przeanalizuj arytmetykę silnika: gdzie są zaokrąglenia (half-up vs banker's), gdzie przeliczenia walut (kursy NBP — dzień poprzedzający? dzień faktury?), gdzie granice kwotowe (art. 119: 15 000 zł dokładnie? przekroczenie o 0,01?), gdzie sumy częściowe mogą się rozjechać z sumą całkowitą (rozjazd groszowy = różnice w JPK i deklaracjach). Wygeneruj rejestr punktów arytmetycznych wrażliwych z przypadkami testowymi brzegowymi i standard arytmetyki (jeden standard zaokrągleń per kontekst prawny, z cytatami z przepisów wykonawczych).",
"Zaprojektuj testy precyzji: tabela przypadków (0,00 / 0,01 / 0,005 / 999999,99 / ujemne / zero-net), waluty (EUR/USD/GBP z kursami historycznymi — time-travel P05), granice progów (dokładnie 15 000,00 vs 15 000,01), sumy setek pozycji (inwariant sumy = suma invariants), interakcje zaokrągleń w łańcuchach (VAT netto→brutto→sumy). Każdy wynik deklaracji musi być REPRODUKOWALNY grosz po groszu — determinizm arytmetyczny to podstawa audytowalności fortecy.",
],
subparts=[
dict(name="Audyt punktów zaokrągleń",
goal="inwentarz miejsc arytmetycznie wrażliwych",
questions=[
"Gdzie silnik zaokrągla (jakie operacje) i jakim standardem (half-up/banker's)? Które są niespójne?",
"Czy przepisy wykonawcze narzucają standard zaokrągleń (VAT do pełnych groszy — art. 107 Ordynacji?) — zacytować?",
"Gdzie sumy są liczone z pozycji (suma zaokrąglonych) vs z wartości pełnych (zaokrąglenie sumy) — rozjazdy?",
"Czy ujemne kwoty (korekty, nadpłaty) przechodzą przez te same ścieżki zaokrągleń?",
]),
dict(name="Waluty i kursy",
goal="przeliczenia deterministyczne i prawidłowe",
questions=[
"Skąd silnik bierze kursy (NBP tabela A?) i na jaki dzień (obowiązek podatkowy? wystawienia?) — art. 11a ust. 1?",
"Czy kursy są danymi z provenance (data tabeli, źródło, checksuma) czy hardcode (P46)?",
"Czy waluty egzotyczne i brak kursu na datę (weekend/święto) mają ścieżkę fail-closed?",
"Czy time-travel (P05) odtwarza kurs historyczny z daty (replay deklaracji walutowej)?",
]),
dict(name="Granice progów kwotowych",
goal="grosz przy progu decyduje o reżimie",
questions=[
"Czy próg 15 000 zł (art. 119) traktuje „dokładnie 15 000,00” zgodnie z przepisem (włącznie)?",
"Czy limity roczne (zwolnienie podmiotowe 200 000 zł) liczą narastająco z korektami?",
"Czy testy obejmują przekroczenie o 0,01 (zmiana reżimu MPP/ewidencji) — day-of przekroczenia?",
"Czy progi walutowe (equivalent EUR dla transakcji zagranicznych) mają kurs i datę?",
]),
dict(name="Inwarianty arytmetyczne i reprodukcja",
goal="grosz za grosz, zawsze",
questions=[
"Czy suma składników = suma całkowita w wszystkich łańcuchach wyliczeń (inwariant testowany)?",
"Czy deklaracja generowana dwukrotnie z tych samych danych daje identyczne kwoty (determinizm)?",
"Czy replay historyczny (P05) odtwarza kwoty deklaracji sprzed lat grosz w grosz?",
"Czy interakcje VAT netto→VAT→brutto→sumy pozycji są testowane na rozjazd groszowy?",
]),
],
file_groups=[
dict(name="Reguły i narzędzia arytmetyki", files=[
    ("Silnik stawek VAT", "JDG/tools/vat_rate_engine.py"),
    ("Kalkulator ZUS", "JDG/tools/zus_calculator.py"),
    ("Kalkulator chorobowy ZUS", "JDG/tools/zus_zasilkowa_calculator.py"),
    ("Kalkulator sankcji", "JDG/tools/sanction_calculator.py"),
    ("Kalkulator KKS kary", "JDG/tools/kks_penalty_simulator.py"),
    ("Progi święte (dokument)", "JDG/rules/thresholds_jdg.rego"),
    ("Progi i stawki (dane)", "JDG/bundles/thresholds_data.json"),
    ("Symulator form podatkowych", "JDG/tools/tax_form_whatif_simulator.py"),
]),
dict(name="Testy arytmetyczne", files=[
    ("Test reguł podatkowych", "JDG/tests/test_tax_rules.py"),
    ("Test VAT enterprise", "JDG/tests/test_vat_enterprise.py"),
    ("Test PCC/akcyza enterprise", "JDG/tests/test_pcc_excise_enterprise.py"),
    ("Test natywny PCC v3", "JDG/tests/rego/test_native_pcc_v3_10.rego"),
    ("Test natywny micro ZUS", "JDG/tests/rego/micro/test_native_micro_zus.rego"),
    ("Test kontrol temporalnych", "JDG/tests/test_core_guards_temporal_thresholds.py"),
    ("Test edge cases enterprise", "JDG/tests/test_edge_cases_enterprise.py"),
]),
dict(name="Waluty, cross-border i JPK", files=[
    ("Toolkit cross-border P13", "JDG/tools/p13_crossborder_toolkit.py"),
    ("Dokument cross-border P12", "JDG/docs/CROSSBORDER_P12.md"),
    ("Walidator JPK", "JDG/tools/jpk_validator.py"),
    ("Generator JPK", "JDG/tools/jpk_generator.py"),
    ("Test cross-border enterprise", "JDG/tests/test_crossborder_enterprise.py"),
    ("Test natywny crossborder", "JDG/tests/rego/test_native_crossborder.rego"),
]),
],
legal=[
"Ordynacja podatkowa — art. 107 (kwoty zaokrąglane do pełnych groszy: ustawa definiuje standard zaokrągleń podatkowych).",
"Ustawa VAT — art. 119 (próg 15 000 zł MPP: „kwota brutto ... przekracza” — granica włącznie/wyłącznie), art. 113 (limit zwolnienia).",
"Ustawa VAT — art. 31a (kurs walut: dzień poprzedzający obowiązek podatkowy — źródło daty kursu).",
"Ustawa o PIT — art. 11a (kursy walut dla przychodów/kosztów), art. 63 (zaokrąglenia do pełnych groszy).",
"Ustawa o ZUS — art. 18d (podstawa roczna: 30-krotność — granica przekroczenia).",
"Ustawa o rachunkowości — art. 28 ust. 1 pkt 11 (wycena w walutach: kursy), art. 30 (zaokrąglenia).",
"Obwieszczenia NBP (tabela A) — kursy jako dane publiczne z datą (provenance).",
"Rozporządzenie o PKPiR — zaokrąglenia w ewidencji (kontekst spójności deklaracji).",
],
innovations=[
("Arithmetic standards register", "rejestr: operacja → standard zaokrąglenia → przepis (art. 107 OP / art. 63 PIT) → testy — jeden standard per kontekst, z cytatami."),
("Penny boundary test matrix", "generator przypadków: dla każdego progu kwotowego testy {próg, próg±0,01, próg±1%} z oczekiwanym reżimem — automatyczny."),
("Currency rate provenance", "kursy jako dane z datą, źródłem (NBP tabela A) i checksumą; replay walutowy odtwarza kurs historyczny z daty zdarzenia."),
("Weekend/holiday rate path", "brak kursu na datę → ścieżka fail-closed (ostatnia dostępna tabela zgodnie z przepisem albo NEEDS_ADVICE) — z testami na daty świąt 2026–2027."),
("Sum invariants suite", "inwarianty: suma pozycji = suma total (per JPK, per deklaracja), suma netto+VAT=brutto — testowane na setkach pozycji z groszami."),
("Determinism hash", "hash wyliczenia deklaracji (input+parametry+reguły) — dwa razy ten sam wynik = ten sam hash; rozjazd = BLOCKER (test w CI)."),
("Rounding interaction tests", "testy łańcuchów (netto→VAT→brutto→sumy→JPK pola) z walidacją, że zaokrąglenia pośrednie nie tworzą rozjazdów."),
("Negative amount paths", "testy korekt i nadpłat przez te same ścieżki arytmetyczne (ujemne kwoty często odkrywają braki w kodzie zaokrągleń)."),
("Threshold calendar audit", "audyt roczny: kwota narastająca per podatnik vs limity (zwolnienie, 30-krotność) — test granicy przekroczenia z korektami w locie."),
("Penny drift telemetry", "metryka: rozjazdy groszowe wykryte w produkcji (reconciliation) — trend do zera; rozjazd = alarm z full trace."),
("Currency fuzz", "property-based: dowolna kombinacja (kwota, waluta, kurs, data) → inwarianty (kwota≥0, spójność pola JPK) — zero wyjątków bez NEEDS_ADVICE."),
("Arithmetic doomsday suite", "zestaw skrajnych przypadków (max long, min long, overflow, dzielenie przez zero, NaN-like) z asercją fail-closed — silnik nie może się wysypać na arytmetyce."),
],
in_contracts=[
"Kontrakt parametrów z P46 — progi kwotowe w data.thresholds z jednostkami (testy graniczne na danych).",
"Kontrakt temporalności z P05 — kursy walut i limity roczne odtwarzane w time-travel.",
],
out_contracts=[
"Rejestr punktów arytmetycznych (standards register) — wiąże P41 (dokumentacja) i P68.",
"Tabela testów brzegowych (generator) — wejście do P39 (CI) i P36.",
"Inwarianty arytmetyczne (pakiet) — wiąże P49 (fail-closed) i P37 (telemetria driftu groszowego).",
],
acceptance_extra=[
"Rejestr punktów zaokrągleń z cytowaniami przepisów (art. 107 OP, art. 63 PIT) i statusami spójności.",
"Tabela testów brzegowych z min. 20 przypadkami (progi, waluty, sumy, ujemne) i oczekiwanymi wynikami.",
]),
]
