# -*- coding: utf-8 -*-
"""Parts P69-P80: material law wave — daily accountant law closure (crypto, e-commerce, kasa, cars, PPK, korekty, local taxes, najem, dotacje, rolnicy, PPHU, amortyzacja)."""
PARTS = [

dict(code="P69", slug="KRYPTO_WALUTY", title="KRYPTOWALUTY I AKTYWA WIRTUALNE — PIT I VAT NAD AKTYWAMI CYFROWYMI",
role="specjalistą od opodatkowania aktywów cyfrowych (kryptowaluty, NFT, staking) w systemach policy-as-code",
expertise="przychody z walut wirtualnych, koszty nabycia FIFO/ważona, staking i mining, VAT na aktywa cyfrowe, MiCA kontekst",
mission=[
"Przeanalizuj pokrycie aktywów wirtualnych: sprzedaż walut wirtualnych (PIT art. 4 ust. 1 pkt 26a, koszty art. 22b), wymiana krypto-krypto (neutralna w PIT?), staking/mining (przychód z ich odrębnego źródła?), NFT, końcowy podatek (19% bez progów, koszty od niesprzedanych nieodliczalne), ewidencja kursów (krypto-krypto brak, PLN konwersja), formularze (PIT-38, załącznik PIT/ZG — transakcje zagraniczne giełdy). W repo brak DEDYKOWANYCH reguł i narzędzi krypto — to pustynia materialna pierwszej klasy (młodzi podatnicy, kontrola KAS na giełdy).",
"Zaprojektuj domknięcie: rejestr transakcji krypto (schema ingestu P57 rozszerzony), wyliczenie kosztów FIFO/ważona średnia (do wyboru, konsekwentnie), staking jako odrębne źródło (przychód w PLN z kursu dnia otrzymania), VAT (waluta wirtualna = towar? usługa? — status po weryfikacji ISAP), ewidencja dla kontroli (dowody, wyciągi giełdowe). Zasady fail-closed: brak danych giełdowych → NEEDS_ADVICE, kurs niepewny → NEEDS_ADVICE. Przeprować głęboką analizę zgodności z przyszłym MiCA (regulacja UE wdrożona do prawa polskiego — weryfikacja statusu).",
],
subparts=[
dict(name="PIT przychody i koszty krypto",
goal="19% od dochodu z walut wirtualnych — bez pomyłek",
questions=[
"Czy transakcje krypto→krypto są neutralne podatkowo (nie generują przychodu) — reguła i test?",
"Czy koszty nabycia wyliczane są FIFO albo średnią ważoną (wybór podatnika) — obie metody z testami?",
"Czy niesprzedane krypto (nieodliczone koszty w tym roku) mają ścieżkę przeniesienia na kolejny rok?",
"Czy staking/mining jest odrębnym źródłem (art. 10 ust. 1 pkt 11?) — weryfikacja w ISAP i reguła?",
]),
dict(name="Ewidencja i kursy",
goal="dowody dla kontroli KAS",
questions=[
"Czy kurs konwersji (krypto→PLN) jest data-zależny (dzień transakcji) — provenance kursu (P61 standard)?",
"Czy wyciągi giełdowe są ingested (P57) z walidacją i WORM (P42)?",
"Czy ewidencja transakcji jest kompletna (data, ilość, kurs, koszty) — schema i testy?",
"Czy PIT-38 + PIT/ZG (transakcje zagraniczne) generowane są automatycznie (P32 pipeline)?",
]),
dict(name="VAT na aktywa cyfrowe",
goal="status wymiany i usług krypto",
questions=[
"Czy wymiana walut wirtualnych jest zwolniona z VAT (interpretacje MF — świadczenie finansowe) — reguła z cytatem?",
"Czy NFT (aktywa cyfrowe unikatowe) jest towarem/usługą VAT — ścieżka NEEDS_ADVICE z doradcą?",
"Czy usługi giełd/prowizje mają status (B2B od giełdy zagranicznej — odwrócone obciążenie?)?",
"Czy MiCA (rozporządzenie UE) zmieniło status — weryfikacja implementacji polskiej (legislacja.gov.pl)?",
]),
dict(name="Inwestor vs przedsiębiorca",
goal="rozgraniczenie.statusu",
questions=[
"Czy częsta wymiana (day-trading) = działalność gospodarcza (PIT art. 5a pkt 6 — ciągłość) — reguła klasyfikacji z fail-closed?",
"Czy przepływ: krypto w działalności (faktury za krypto — waluta wirtualna jako środek płatniczy) jest obsługiwany?",
"Czy mieszanie portfeli (osobisty + działalność) ma ścieżkę segregacji (NEEDS_ADVICE)?",
"Czy podobne aktywa (tokeny ekosystemowe, airdropy) mają ścieżki (przychód? kiedy? wycena)?",
]),
],
file_groups=[
dict(name="Narzędzia ogólne (kontekst wyliczeń)", files=[
    ("Symulator form podatkowych", "JDG/tools/tax_form_whatif_simulator.py"),
    ("Silnik roczny PIT", "JDG/tools/pit_annual_engine.py"),
    ("Silnik stawek VAT", "JDG/tools/vat_rate_engine.py"),
    ("Toolkit cross-border", "JDG/tools/p13_crossborder_toolkit.py"),
]),
dict(name="Testy kontekstowe", files=[
    ("Test reguł podatkowych", "JDG/tests/test_tax_rules.py"),
    ("Test VAT enterprise", "JDG/tests/test_vat_enterprise.py"),
    ("Test cross-border enterprise", "JDG/tests/test_crossborder_enterprise.py"),
    ("Test natywny crossborder", "JDG/tests/rego/test_native_crossborder.rego"),
]),
dict(name="Dokumenty i rejestry prawne", files=[
    ("Dokument PIT macro", "JDG/docs/PIT_MACRO_P05.md"),
    ("Dokument VAT macro", "JDG/docs/VAT_MACRO_P03.md"),
    ("Kalendarz zmian prawnych", "JDG/docs/KALENDARZ_ZMIAN_PRAWNYCH.md"),
    ("Zgodność prawna", "JDG/docs/ZGODNOSC_PRAWNA.md"),
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
    ("Rejestr źródeł prawnych", "JDG/docs/LEGAL_SOURCE_REGISTRY.md"),
]),
],
legal=[
"Ustawa o PIT — art. 4 ust. 1 pkt 26a (przychody z walut wirtualnych), art. 10 ust. 1 pkt 11 (źródło).",
"Ustawa o PIT — art. 22b (koszty nabycia walut wirtualnych), art. 30f ust. 2 (podatek 19%, koszty nieodliczalne).",
"Ustawa o PIT — art. 45 ust. 3a (PIT-38, termin), rozporządzenie o PIT/ZG (załącznik transakcji zagranicznych).",
"Interpretacje MF o VAT na walutach wirtualnych (zwolnienie — świadczenie finansowe) — weryfikacja w podatki.gov.pl.",
"MiCA (Rozporządzenie UE 2023/1114) — status aktywów krypto, implementacja polska (weryfikacja legislacja.gov.pl).",
"Ustawa o przeciwdziałaniu praniu pieniędzy (AML) — kantory krypto, VASP (kontekst P73/P86).",
"Ordynacja podatkowa — art. 193a (wyciągi giełdowe jako dowody — WORM P42).",
"Ustawa o PIT — art. 14 ust. 2 pkt 8 (przychody z nieodpłatnych świadczeń: airdropy? — ścieżka NEEDS_ADVICE).",
],
innovations=[
("Crypto transaction ledger", "schema ewidencji transakcji (data, kwota, kurs, koszty, giełda) z ingestem giełdowym (CSV/API) i WORM — zero transakcji z głowy."),
("FIFO vs weighted-average engine", "oba algorytki kosztów z testami identycznymi (przykład obliczeniowy end-to-end) i konsekwencją wyboru (jeden na rok, zgodnie z przepisami wykonawczymi)."),
("Staking/mining source classifier", "reguły: staking = odrębne źródło (przychód w PLN z kursu dnia otrzymania) — test na scenariuszach (nagrody co miesiąc, reinwestycja)."),
("Crypto-to-crypto neutrality test", "asercja: wymiana krypto-krypto nie generuje przychodu PIT (reguła z testem); zero cichego liczenia podatkowego na wymianach."),
("VAT status matrix", "macierz: wymiana/prowizje/NFT/usługi → status VAT z cytatem interpretacji; niepewne = NEEDS_ADVICE z doradcą (fail-closed prawny)."),
("Exchange data ingest", "parser wyciągów giełdowych (CSV standardy: Coinbase, Binance, Kraken) z walidacją i normalizacją do ewidencji — deduplikacja (P57)."),
("MiCA readiness check", "analiza zgodności reguł z implementacją MiCA (weryfikacja aktualności; alarm przy nowelizacji — Law Radar P08)."),
("Kurs provenance krypto", "kursy krypto→PLN z datą i źródłem (giełda) z checksumą — replay wyliczenia grosz w grosz (P52 standard)."),
("Air-drop and fork rules", "reguły: airdrop/fork (przychód? wycena? data) — ścieżka NEEDS_ADVICE z doradcą jeśli niepewne, dowód z interpretacją jeśli jest."),
("Day-trading classifier", "reguły klasyfikacji częstotliwości (ciągłość = działalność) z fail-closed (przy wątpliwości NEEDS_ADVICE, nie cicha klasyfikacja)."),
("PIT-38 + PIT/ZG generator", "automatyczne generowanie formularzy z ewidencji (załącznik transakcji zagranicznych) — walidacja przed wysyłką (P54 dry-run standard)."),
("Crypto audit packet", "pakiet dowodowy dla kontroli (ewidencja, wyciągi, kursy, wyliczenie) eksportowany jednym poleceniem (P60 audit export standard)."),
],
in_contracts=[
"Kontrakt ingestu z P57 — dane giełdowe wchodzą przez standardowy ingest (walidacja, dedup, WORM).",
"Kontrakt parametrów z P46 — kursy i stawki (19%) jako dane z provenance.",
],
out_contracts=[
"Crypto transaction ledger (schema) — wejście do P57 (ingest), P42 (WORM) i P68.",
"Koszt engine (FIFO/ważona) — wiąże P80 (amortyzacja: analogiczne wyliczenia) i P68.",
"VAT status matrix krypto — wejście do P70 (e-commerce) i P41 (dokumentacja).",
],
acceptance_extra=[
"Pełny przykład wyliczenia end-to-end (100 transakcji testowych) — PIT-38 kwota odtwarzalna grosz w grosz.",
"Macierz VAT krypto z cytatem każdej pozycji (interpretacja MF) albo jawnym NEEDS_ADVICE.",
]),
dict(code="P70", slug="ECOMMERCE_OSS", title="E-COMMERCE, OSS/IOSS I PLATFORMY VMS — SPRZEDAŻ TRANSGRANICZNA KONSUMENTÓW",
role="specjalistą od VAT transgranicznego B2C (OSS, IOSS, platformy pośredniczące) w silnikach rozliczeniowych",
expertise="OSS/IOSS rejestracje i deklaracje, WSTO i próg 10 000 EUR, platformy VMS (faktura zbiorcza), zwroty i korekty",
mission=[
"Przeanalizuj sprzedaż B2C transgraniczną: WSTO (art. 133a — próg 10 000 EUR łącznie dla UE, wybranie procedury OSS lub lokalna rejestracja), rejestracja VAT-UE (VAT-OSS), deklaracja VAT-UE w JPK (kursy NBP na koniec okresu!), platformy VMS (art. 119a VAT: platforma rozlicza — nabywca przez platformę), IOSS (import do 150 EUR), zwroty (korekta OSS), towary objęte i wyłączone (towary akcyzowe, pojazdy, dzieła sztuki). W repo: cross-border toolkit ma B2B (WDT) — B2C/OSS/VMS to pustynia.",
"Zaprojektuj: reguły progu (przeliczenie EUR na PLN kurs NBP ostatniego dnia roboczego przed początkiem kwartału! — art. 133a ust. 2), WSTO vs krajowa (adres konsumencki — weryfikacja, sygnatury IP jako kontekst, NIE dowód), OSS deklaracja kwartalna (kurs konwersji na ostatni dzień kwartału), platformy VMS (faktura zbiorcza, wystawca = platforma, 7 dni), zwroty (korekta w deklaracji za okres zwrotu). Fail-closed: brak weryfikacji konsumencji → NEEDS_ADVICE. Przeprować głęboką analizę interakcji OSS ↔ JPK_V7 (pola deklaracyjne, dane nagłówkowe VAT-UE).",
],
subparts=[
dict(name="Próg 10 000 EUR i wybór procedury",
goal="próg i decyzja (OSS vs lokalnie) — grosz w przeliczeniu",
questions=[
"Czy próg 10 000 EUR przeliczany jest kursem NBP ostatniego dnia roboczego przed początkiem kwartału (art. 133a ust. 2) — test na granicy?",
"Czy próg liczy się narastająco od początku roku (łącznie wszystkie kraje UE) — test na przekroczeniu w Q3?",
"Czy decyzja OSS vs rejestracja lokalna ma regułę (próg przekroczony → wybór wiążący) z fail-closed (bez decyzji = NEEDS_ADVICE)?",
"Czy wyłączenia z progu (towary akcyzowe, pojazdy) są rozpoznawane (klasyfikacja PKWiU)?",
]),
dict(name="Deklaracja OSS i kursy",
goal="kwartalna deklaracja z kursami",
questions=[
"Czy kursy konwersji (na ostatni dzień kwartału, tabela NBP A) mają provenance (P61) i testy dat (weekendy/święta)?",
"Czy deklaracja VAT-UE (kwartalna) generowana jest z danych WSTO (kraje, stawki kraju konsumpcji) — walidacja przed wysyłką?",
"Czy stawki VAT krajów konsumpcji (np. DE 19%, FR 20%) są danymi z wersjonowaniem (P46) — zmiana stawki kraju = dane?",
"Czy interakcja z JPK_V7 (pole rozliczania OSS) jest testowana (spójność kwot JPK ↔ VAT-UE)?",
]),
dict(name="Platformy VMS (art. 119a)",
goal="platforma rozlicza — nabywca dostaje fakturę zbiorczą",
questions=[
"Czy reguły rozpoznają sprzedaż przez platformę (VMS: baza ue, usługi elektroniczne, towary importowane do 150 EUR) — klasyfikacja?",
"Czy faktura zbiorcza (7 dni po upływie miesiąca, dwie — sprzedaż platforma i usługa pośrednictwa) jest generowana automatycznie?",
"Czy prowizja platformy (usługa z zagranicy — odwrócone obciążenie NP?) ma ścieżkę z VAT-UE?",
"Czy IOSS (import do 150 EUR) ma ścieżkę (rejestracja, deklaracja miesięczna) — czy tylko OSS?",
]),
dict(name="Zwroty i korekty",
goal="zwrot towaru = korekta deklaracji",
questions=[
"Czy zwrot towaru (reklamacja, odstąpienie) generuje korektę WSTO w deklaracji za okres zwrotu (art. 133a ust. 7) — test?",
"Czy korekty są idempotentne (podwójny zwrot nie podwaja korekty — P57 dedup)?",
"Czy spadek obrotu poniżej progu w następnym roku (wybór OSS obowiązuje 2 lata — art. 133a ust. 5) jest pilnowany (kalendarz P25)?",
"Czy anulowane zamówienia (przed wysyłką) mają ścieżkę (bez WSTO — nie wszedł do obrotu)?",
]),
],
file_groups=[
dict(name="Narzędzia cross-border", files=[
    ("Toolkit cross-border", "JDG/tools/p13_crossborder_toolkit.py"),
    ("Auditor cross-border", "JDG/tools/crossborder_auditor.py"),
    ("Jakość cross-border", "JDG/tools/crossborder_quality.py"),
    ("Harmonizator jurysdykcji", "JDG/tools/cross_jurisdiction_harmonizer.py"),
    ("Silnik stawek VAT", "JDG/tools/vat_rate_engine.py"),
    ("Silnik roczny PIT", "JDG/tools/pit_annual_engine.py"),
]),
dict(name="Testy cross-border", files=[
    ("Test cross-border enterprise", "JDG/tests/test_crossborder_enterprise.py"),
    ("Test cross-border v3", "JDG/tests/test_crossborder_v3_08.py"),
    ("Test audytu cross-border etap17", "JDG/tests/test_crossborder_etap17_audit.py"),
    ("Test natywny crossborder", "JDG/tests/rego/test_native_crossborder.rego"),
    ("Test natywny crossborder etap17", "JDG/tests/rego/test_native_crossborder_etap17.rego"),
]),
dict(name="Dokumenty kontekstowe", files=[
    ("Dokument cross-border", "JDG/docs/CROSSBORDER_P12.md"),
    ("Dokument VAT macro", "JDG/docs/VAT_MACRO_P03.md"),
    ("Dokument VAT micro", "JDG/docs/VAT_MICRO_P04.md"),
    ("Kalendarz zmian prawnych", "JDG/docs/KALENDARZ_ZMIAN_PRAWNYCH.md"),
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
]),
],
legal=[
"Ustawa VAT — art. 133a (WSTO: próg 10 000 EUR, kurs NBP ostatniego dnia roboczego przed początkiem kwartału).",
"Ustawa VAT — art. 133b–133g (procedura OSS: rejestracja VAT-UE, deklaracja kwartalna, terminy).",
"Ustawa VAT — art. 119a (platformy VMS: platforma rozlicza VAT, faktura zbiorcza w 7 dni).",
"Ustawa VAT — art. 141–146 (IOSS: import do 150 EUR).",
"Rozporządzenie Implementing Council Directive 2006/112/EC (OSS szczegóły) — weryfikacja w EUR-Lex.",
"Ustawa VAT — art. 31b (kursy na deklarację: ostatni dzień okresu podatkowego).",
"Ustawa o PIT — art. 45 ust. 4 (kwartalne zaliczki przy WSTO — kontekst wybrania procedury).",
"Regulacje platform e-commerce (PSD2, DSA — kontekst operacyjny platform VMS).",
],
innovations=[
("Threshold engine 10k EUR", "przeliczenie progu z kursem NBP (ostatni dzień roboczy przed kwartałem) z testami granic (9999,99 / 10 000,00 / 10 000,01) — zero zgadywania."),
("OSS decision wizard", "reguły wyboru procedury (próg przekroczony → OSS lub rejestracja lokalna; konsekwencja 2 lata) z fail-closed (brak decyzji = NEEDS_ADVICE)."),
("Country rate registry", "stawki VAT krajów konsumpcji jako dane wersjonowane (data obowiązywania) — zmiana stawki kraju = zmiana danych (P46 standard)."),
("Quarterly OSS declaration builder", "generator deklaracji VAT-UE z danych WSTO (kraje, stawki, kursy) + walidacja pre-send + spójność z JPK_V7 (asercja kwot)."),
("VMS platform classifier", "rozpoznawanie sprzedaży przez platformę (baza ue, usługi elektroniczne, import <150 EUR) — automatyczne oznaczanie i faktura zbiorcza."),
("Collective invoice generator", "faktura zbiorcza platformy (dwie: sprzedaż + pośrednictwo) generowana automatycznie w 7 dni — termin pilnowany (P25)."),
("Return-correction chain", "zwrot → korekta WSTO w okresie zwrotu → deklaracja korygująca — idempotentnie (dedup zwrotów) i z pełnym śladem."),
("Consumer verification policy", "weryfikacja statusu nabywcy (adres, dane kontekstowe) z zasadą: dowód wątpliwy = NEEDS_ADVICE (nie cicha klasyfikacja WSTO)."),
("IOSS path", "rejestracja IOSS, deklaracja miesięczna, import <150 EUR — ścieżki z terminami (P25) i testami."),
("OSS-JPK reconciliation", "automatyczna rekonsylacja: kwoty OSS (VAT-UE) ↔ pola JPK_V7 — rozjazd = BLOCKER (bramka CI)."),
("Currency provenance for OSS", "kursy NBP z datą/checksumą per deklaracja — replay kwartalny grosz w grosz (P52/P53 standard)."),
("E-commerce audit pack", "pakiet audytowy: ewidencja WSTO, deklaracje, faktury zbiorcze, zwroty — eksport jednym poleceniem (P60)."),
],
in_contracts=[
"Kontrakt parametrów z P46 — stawki krajów i kursy jako dane z provenance.",
"Kontrakt ingestu z P57 — zamówienia e-commerce przez standardowy ingest (dedup, walidacja).",
],
out_contracts=[
"OSS engine (próg, deklaracja, VMS, zwroty) — wiąże P61 (kursy), P54 (deklaracje terminy) i P68.",
"Country rate registry (format) — wejście do P46 i P41.",
"E-commerce audit pack — wejście do P60 i P68.",
],
acceptance_extra=[
"Przykład kwartalnego rozliczenia OSS end-to-end (10 krajów, zwrot w Q3) — kwoty odtwarzalne grosz w grosz.",
"Macierz VMS (typ platformy → obowiązki → dokumenty) z cytatem art. 119a i ścieżkami.",
]),
dict(code="P71", slug="KASA_FISKALNA", title="KASY FISKALNE, E-PARAGONY I OBOWIĄZKI EWIDENCJI SPRZEDAŻY",
role="specjalistą od ewidencjonowania sprzedaży detalicznej (kasy fiskalne online) w silnikach reguł",
expertise="zwolnienia z kas, obowiązkowe kasy online, raporty kasowe, ROR, e-paragony, kary (KKS art. 62)",
mission=[
"Przeanalizuj ewidencjonowanie sprzedaży detalicznej: kasy fiskalne online (obowiązkowe dla większości), zwolnienia przedmiotowe (usługi medyczne, edukacja — art. 111 ust. 4 VAT) i podmiotowe (obrót do 20 000 zł rocznie — art. 113 ust. 2, wyłączenia), terminy fiskalizacji (w wypadku przekroczenia progu — 2 miesiące do końca roku), raporty dobowe/miesięczne, ROR (raport rozliczeniowy), dane do JPK (ewidencja detaliczna, ptu_23?), e-paragony, kary za nieewidencjonowanie (KKS art. 62 — 30% kwoty, min 468 zł). W repo brak reguł kasowych — pustynia dla JDG usługowych.",
"Zaprojektuj: rejestr zwolnień (usługi → kasa wymagana czy zwolniona — z cytatem), licznik obrotu detalicznego (próg 20k z testami granic), ścieżkę „przekroczony próg → obowiązki i terminy fiskalizacji” (kalendarz P25 z alarmami), integracja raportów kasowych z ewidencją VAT (ROR → JPK), ostrzeżenie o karze (koszt nieewidencjonowania widoczny w UI — motywacja). Fail-closed: sprzedaż detaliczna bez weryfikacji zwolnienia → NEEDS_ADVICE, nie ciche pominięcie kasy.",
],
subparts=[
dict(name="Zwolnienia i obowiązek kasowy",
goal="czy kasa jest wymagana dla tej usługi",
questions=[
"Czy rejestr zwolnień przedmiotowych (usługi medyczne PKWiU 86, edukacja 85, wynajem na cele mieszkaniowe) ma reguły z PKWiU — test per grupa?",
"Czy zwolnienie podmiotowe (obrót detaliczny do 20 000 zł) liczy się narastająco z wyłączeniami (WDT, usługi ubezpieczeniowe — art. 113 ust. 2a) — test?",
"Czy „sprzedaż na rzecz osób prywatnych” rozpoznawana jest (konsumencja) — reguła z weryfikacją (faktura na żądanie)?",
"Czy przekroczenie progu uruchamia ścieżkę (termin fiskalizacji: do końca roku + 2 miesiące?) — kalendarz z alarmami?",
]),
dict(name="Raporty kasowe i ROR",
goal="kasa → ewidencja VAT bez przepisywania",
questions=[
"Czy raporty dobowe/miesięczne kasowe ingested (P57 — plik z kasy) z walidacją (suma, paragony)?",
"Czy ROR generowany jest (kwoty per stawka VAT) i spójny z ewidencją detaliczną w JPK (asercja)?",
"Czy e-paragony (wysyłka e-mail) mają ścieżkę (dane nabywcy, terminy wysyłki)?",
"Czy brak raportu (kasa nie podłączona) = alarm (fail-closed: sprzedaż detaliczna bez raportu = luka)?",
]),
dict(name="Kary i ryzyko",
goal="koszt nieewidencjonowania widoczny",
questions=[
"Czy kara KKS art. 62 (30% kwoty nieewidencjonowanej, min. 468 zł) jest kalkulowana w symulatorze ryzyka (motywacja do zgodności)?",
"Czy kontrola JPK (KAS porównuje zapasy towarów z ewidencją — braki, ruszanie towarem) ma ścieżkę obronną (P84)?",
"Czy terminy fiskalizacji mają watchdog (termin mijący → alarm P0)?",
"Czy przypadki sprzedaży przez internet (kasa dla e-commerce: zwolnienie na wysyłki kurierem — art. 111 ust. 6) mają reguły?",
]),
dict(name="Integracja z ewidencją VAT",
goal="sprzedaż detaliczna w JPK bez luk",
questions=[
"Czy ewidencja detaliczna (per stawka) spójna z sumą raportów kasowych (rekonsylacja)?",
"Czy sprzedaż z fakturą (na firmę) jest oddzielana od detalicznej (bez kasy — faktura zwalnia z obowiązku kasy dla tej transakcji)?",
"Czy paragony z VAT-RR (od rolników — P78) mają ścieżkę odrębną (faktura VAT-RR a kasa)?",
"Czy miesięczne zamykanie kas (raport → ewidencja → JPK) jest częścią pipeline'u zamknięcia miesiąca (P32)?",
]),
],
file_groups=[
dict(name="Narzędzia kontekstowe", files=[
    ("Toolkit księgowości", "JDG/tools/p11_accounting_toolkit.py"),
    ("Test agregacji faktów (kontrakt)", "JDG/tests/test_facts_aggregator.py"),
    ("Generator JPK", "JDG/tools/jpk_generator.py"),
    ("Walidator JPK", "JDG/tools/jpk_validator.py"),
    ("Auto-gen JPK", "JDG/tools/jpk_autogen.py"),
    ("Symulator form podatkowych", "JDG/tools/tax_form_whatif_simulator.py"),
]),
dict(name="Testy pipeline", files=[
    ("Test tax pipeline", "JDG/tests/test_tax_pipeline.py"),
    ("Test VAT enterprise", "JDG/tests/test_vat_enterprise.py"),
    ("Test natywny kalendarza", "JDG/tests/rego/test_native_calendar.rego"),
    ("Test deadline monitor", "JDG/tests/rego/test_native_deadline_monitor_enterprise.rego"),
]),
dict(name="Dokumenty kontekstowe", files=[
    ("Logika biznesowa", "JDG/docs/LOGIKA_BIZNESOWA.md"),
    ("Automatyzacja księgowości", "JDG/docs/AUTOMATYZACJA_KSIEGOWOSCI_P18.md"),
    ("Zgodność dokumenty księgowe", "JDG/docs/ZGODNOSC_DOKUMENTY_KSIEGOWE.md"),
    ("Kalendarz zmian prawnych", "JDG/docs/KALENDARZ_ZMIAN_PRAWNYCH.md"),
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
]),
],
legal=[
"Ustawa VAT — art. 111 (obowiązek posiadania kasy, zwolnienia przedmiotowe i wyjątki).",
"Ustawa VAT — art. 113 ust. 2 (zwolnienie podmiotowe od kas do 20 000 zł obrotu detalicznego) i ust. 2a (wyłączenia).",
"Rozporządzenie MF o kasach fiskalnych online (terminy fiskalizacji, raporty) — weryfikacja w ISAP.",
"Ustawa VAT — art. 109 (ewidencja sprzedaży detalicznej), art. 128 (dane z ewidencji do deklaracji).",
"KKS — art. 62 (nieewidencjonowanie sprzedaży: grzywna do 30% kwoty, min. 468 zł).",
"Ustawa VAT — art. 106b ust. 5 (faktura na żądanie — zwalnia z kasy dla tej transakcji).",
"Ustawa VAT — art. 111 ust. 6 (e-commerce: zwolnienie z kasy przy wysyłkach kurierem/przelewem).",
"Ustawa VAT — art. 114a (korekta przy nieewidencjonowaniu — asercja ryzyka).",
],
innovations=[
("Kasa obligation classifier", "reguły: usługa/towar (PKWiU) + profil nabywcy → kasa wymagana/zwolniona (art. 111) z cytatem — zero zgadywania przy 1. sprzedaży."),
("Retail turnover counter", "narastający licznik obrotu detalicznego (20 000 zł) z wyłączeniami (art. 113 ust. 2a) i testami granic — przekroczenie uruchamia terminy."),
("Fiskalization deadline watchdog", "przekroczony próg → kalendarz obowiązku fiskalizacji (2 miesiące do końca roku) z alarmami (P25) — termin nienaruszalny."),
("ROR auto-integration", "raporty kasowe (dobowe/miesięczne) ingested i spójne z ewidencją detaliczną w JPK — rekonsylacja z asercją, rozjazd = BLOCKER."),
("E-paragon path", "wysyłka e-paragonów (dane, terminy) — ścieżki z testami (brak e-maila → paragon papierowy, nie cisza)."),
("Fine simulator", "kalkulacja ryzyka KKS art. 62 (30% nieewidencjonowanej) w dashboard ryzyka — przedsiębiorca widzi koszt braku kasy."),
("Invoice-exemption rule", "faktura na żądanie → ta transakcja bez kasy (art. 106b ust. 5) — reguła z testem (nie ciche pomijanie)."),
("E-commerce exemption", "sprzedaż wysyłkowa online (kurier, przelew) → zwolnienie z kasy (art. 111 ust. 6) — klasyfikacja z weryfikacją dostawy."),
("VAT-RR separate path", "sprzedaż od rolników (P78) poza ewidencją kasową — odrębna ścieżka z testami (nie mieszanie z detaliczną)."),
("Month-close kasa step", "raport miesięczny kasy jako etap zamknięcia miesiąca (P32) — brak raportu blokuje zamknięcie (fail-closed)."),
("KAS inventory check defense", "ścieżka obronna na kontrolę zapasów (KAS porównuje stany z ewidencją) — pakiet dowodowy (P84) gotowy."),
("Kasa readiness checklist", "przed startem sprzedaży detalicznej: checklist obowiązku (klasyfikacja, próg, terminy) — zapobieganie karze od pierwszego dnia."),
],
in_contracts=[
"Kontrakt pipeline z P32 — raporty kasowe jako etap zamknięcia miesiąca (fail-closed na brak).",
"Kontrakt kalendarza z P25 — terminy fiskalizacji w jednym źródle z alarmami.",
],
out_contracts=[
"Kasa obligation classifier (reguły + dane PKWiU) — wiąże P56 (GTU/VAT szczegóły) i P68.",
"ROR integration contract — wejście do P32 (pipeline), P54 (JPK) i P68.",
"Fine simulator (KKS art. 62) — wejście do P84 (obrona) i P40 (UI ryzyka).",
],
acceptance_extra=[
"Macierz zwolnień kasowych (usługa → zwolniona/wymagana → cytat art. 111) z testami per wiersz.",
"Ścieżka przekroczenia progu 20 000 zł end-to-end (przekroczenie → termin → fiskalizacja → raporty) z datami.",
]),
dict(code="P72", slug="AUTA_PODROZE", title="AUTA W DZIAŁALNOŚCI, KILOMETRÓWKA I DIETY — KOSZTY MOBILNOŚCI BEZ WĄTPLIWOŚCI",
role="specjalistą od kosztów transportu w działalności (auta prywatne/służbowe, diety) w silnikach kosztowych",
expertise="kilometrówka, stawki ryczałtowe, VAT 50% eksploatacja, wyłączenia art. 23, diety krajowe/zagraniczne",
mission=[
"Przeanalizuj koszty mobilności: auto prywatne w działalności (kilometrówka — art. 23 ust. 1 pkt 45a: 135 zł za 1 km? stawki ryczałtowe rozporządzenie, do ewidencji przebiegu, PCC przy przeniesieniu własności), auto służbowe (amortyzacja do limitu 150 000 zł, eksploatacja 75% VAT dla firmowych), wyłączenia (art. 23 ust. 1 pkt 4 — koszty auta >150 000), diety krajowe i zagraniczne (delegacje — rozporządzenie MF, stawki per kraj, ryczałty), VAT od zakupu auta (50%? 100% przy zawężonym użytkowaniu — faktura z ograniczeniem). W repo: deprecation_engine ma podstawy — stawki mobilności i diety to luka.",
"Zaprojektuj: rejestr pojazdów (typ, zakres użytkowania, udokumentowanie), kilometrówka (ewidencja przebiegu, stawka z rozporządzenia, testy), diety (kalkulator delegacji: dni, stawki krajowe/zagraniczne, ryczałt vs rachunki), VAT (50%/100% — reguły z warunkami, korekta przy zmianie użytkowania), wyłączenia art. 23 (auto powyżej limitu — kwota wyłączona automatycznie). Fail-closed: kilometrówka bez ewidencji → NEEDS_ADVICE (nie ciche zaliczenie do kosztów).",
],
subparts=[
dict(name="Auto prywatne i kilometrówka",
goal="koszt ryczałtowy z ewidencją",
questions=[
"Czy stawka kilometrówki (art. 23 ust. 1 pkt 45a — rozporządzenie: 135 zł/km?) jest parametrem z wersjonowaniem (P46) i testem?",
"Czy ewidencja przebiegu (data, trasa, cel, km) jest ingested (P57) i walidowana (suma km × stawka)?",
"Czy PCC (2%) przy przeniesieniu własności auta prywatnego na działalność ma ścieżkę (p15 toolkit)?",
"Czy uwierzytelnienie (art. 22 ust. 6b pkt 5 — ewidencja przebiegu) pilnowane jest (brak ewidencji → NEEDS_ADVICE)?",
]),
dict(name="Auto służbowe i VAT 50%",
goal="eksploatacja i zakup",
questions=[
"Czy 50% VAT od eksploatacji aut firmowych (mieszane użycie) ma regułę z warunkami (art. 86 ust. 12a–12e)?",
"Czy 100% VAT (użytkowanie wyłącznie działalność — zawężenie, korekta) ma ścieżkę z oświadczeniem i testem?",
"Czy zakup auta (VAT 50%, limit amortyzacji 150 000 zł — kwota wyłączona art. 23 ust. 1 pkt 4) ma reguły z testami granic (cena = limit / limit+1)?",
"Czy sprzedaż auta służbowego (korekta VAT, przychód/koszt uor) ma ścieżkę end-to-end (korekta proporcjonalna 60 miesięcy)?",
]),
dict(name="Diety i delegacje",
goal="kalkulator krajowy/zagraniczny",
questions=[
"Czy diety krajowe (rozporządzenie MF — stawka ryczałtowa) i zagraniczne (stawki per kraj) są danymi z wersjonowaniem (P46)?",
"Czy kalkulator delegacji (data wyjazdu/powrotu, dziesiąte godziny → pełna dieta, 50% po 8h) ma testy (min. 10 scenariuszy)?",
"Czy podróże zagraniczne (kursy NBP? nie — stawki w EUR z tabeli) mają reguły (kraj → dieta dziesiąte godziny)?",
"Czy ryczałt za pracę zdalną (P83) i diety delegacyjne nie się dublują (reguła rozróżnienia)?",
]),
dict(name="Wyłączenia i limity",
goal="koszty nieterminowe automatycznie wyłączone",
questions=[
"Czy art. 23 ust. 1 pkt 4 (kwota wyłączenia ponad 150 000) automatycznie wyliczana (koszt pomniejszony) — test?",
"Czy opłaty drogowe, paliwo, serwis mają ścieżki kosztowe (podział na 100%/50% zgodnie z VAT od auta)?",
"Czy ubezpieczenie OC/AC (koszt? wyłączenie z VAT dla części prywatnej?) ma reguły?",
"Czy leasing (rata — koszt, VAT) i najem długoterminowy mają ścieżki (odrębne od własności)?",
]),
],
file_groups=[
dict(name="Narzędzia amortyzacji i UoR", files=[
    ("Silnik amortyzacji", "JDG/tools/deprecation_engine.py"),
    ("Auditor amortyzacji PIT", "JDG/tools/pit_micro_amortization_auditor.py"),
    ("Toolkit UoR P12", "JDG/tools/p12_uor_toolkit.py"),
    ("Toolkit UoR księgowość", "JDG/tools/p12_uor_accounting_toolkit.py"),
    ("Toolkit PCC/lokalne", "JDG/tools/p15_pcc_local_excise_toolkit.py"),
    ("Silnik PCC", "JDG/tools/pcc_engine.py"),
]),
dict(name="Testy kontekstowe", files=[
    ("Test PKPiR/UoR enterprise", "JDG/tests/test_pkpir_uor_enterprise.py"),
    ("Test PCC/akcyza enterprise", "JDG/tests/test_pcc_excise_enterprise.py"),
    ("Test VAT enterprise", "JDG/tests/test_vat_enterprise.py"),
    ("Test edge cases enterprise", "JDG/tests/test_edge_cases_enterprise.py"),
    ("Test natywny amortyzacja", "JDG/tests/rego/test_native_amortyzacja.rego"),
]),
dict(name="Dokumenty kontekstowe", files=[
    ("Dokument PIT macro", "JDG/docs/PIT_MACRO_P05.md"),
    ("Księgowość PKPiR/UoR", "JDG/docs/KSIEGOWOSC_PKPIR_UOR_P09.md"),
    ("Dokument VAT micro", "JDG/docs/VAT_MICRO_P04.md"),
    ("Logika biznesowa", "JDG/docs/LOGIKA_BIZNESOWA.md"),
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
]),
],
legal=[
"Ustawa o PIT — art. 23 ust. 1 pkt 45a (kilometrówka auto prywatne — stawki z rozporządzenia), pkt 45b (ewidencja).",
"Rozporządzenie MF w sprawie ustalenia stawek kilometrówki (aktualna stawka — weryfikacja ISAP).",
"Ustawa o PIT — art. 22 ust. 1e (limit 150 000 zł amortyzacji aut), art. 23 ust. 1 pkt 4 (kwota wyłączona).",
"Ustawa VAT — art. 86 ust. 12a–12e (50% VAT od aut firmowych), art. 86a (100% przy zawężeniu, korekta).",
"Rozporządzenie MF o dietach i ryczałtach (krajowe, zagraniczne per kraj) — weryfikacja ISAP.",
"Ustawa PCC — art. 7 ust. 1 pkt 5 (PCC 2% od auta kupowanego z prywatnego majątku).",
"Ustawa VAT — art. 90b ust. 4 (korekta VAT od aut przy sprzedaży — proporcja 60 miesięcy).",
"Ustawa o PIT — art. 22 ust. 1 pkt 13–15 (koszty eksploatacji pojazdów — kontekst).",
],
innovations=[
("Vehicle registry with usage scope", "rejestr pojazdów (prywatny/służbowy, zakres, data od–do) napędzający wszystkie ścieżki kosztowe/VAT — zero zgadywania per rachunek."),
("Kilometrówka engine", "ewidencja przebiegu → koszt (km × stawka z rozporządzenia jako parametr P46) z walidacją kompletności (brak wpisu → NEEDS_ADVICE)."),
("VAT 50/100 rule pack", "reguły art. 86 z warunkami zawężenia (100%) i korektą przy zmianie — testy na scenariuszach zmiany użytkowania."),
("Limit 150k exclusion engine", "automatyczne wyliczenie kwoty wyłączonej (art. 23 ust. 1 pkt 4) z testem granicznym (dokładnie 150k / 150 000,01)."),
("Per-diem calculator", "delegacje krajowe/zagraniczne: daty, godziny (10. → pełna), stawki per kraj (dane) — min. 10 scenariuszy testowych, brak diety dla 1-dniowej <8h? (zasady z rozporządzenia)."),
("Car sale correction chain", "sprzedaż auta służbowego: korekta VAT proporcjonalna (60 miesięcy) + przychód/koszt UoR + PCC kontrahenta — jedna ścieżka end-to-end."),
("Leasing vs ownership paths", "leasing (rata = koszt, VAT od raty 50%) vs najem długoterminowy vs własność — odrębne ścieżki z testami (błędna ścieżka = błędny koszt)."),
("Private-to-business transfer", "przeniesienie własności auta: PCC 2% (p15 toolkit), wartość początkowa amortyzacji, dokumentacja — ścieżka kompletna."),
("Fuel/service cost routing", "koszty eksploatacji rozdzielane zgodnie z VAT od auta (100% lub 50% część) — automatycznie z rejestru pojazdów."),
("Insurance cost rules", "OC/AC: koszt podatkowy (tak), VAT zależny od reżimu auta — reguły spójne z rejestrem."),
("Per-diem vs remote-work guard", "dieta delegacyjna ≠ ryczałt za pracę zdalną — reguła rozróżnienia (ten sam dzień nie może być w obu)."),
("Mobility audit pack", "pakiet: ewidencje przebiegu, delegacje, rejestry pojazdów — eksport audytowy (P60 standard) dla kontroli."),
],
in_contracts=[
"Kontrakt parametrów z P46 — stawki kilometrówki i diety jako dane wersjonowane z cytatem rozporządzenia.",
"Kontrakt ingestu z P57 — ewidencje przebiegu i delegacje przez standardowy ingest.",
],
out_contracts=[
"Vehicle registry (schema) — wiąże P80 (amortyzacja: służbowe), P73 (PPK: deputat?) i P68.",
"Per-diem calculator — wejście do P83 (praca zdalna rozróżnienie) i P40 (UI).",
"VAT 50/100 pack — wejście do P56 (VAT szczegóły) i P68.",
],
acceptance_extra=[
"Kalkulator delegacji z min. 10 testami (kraje, godziny, półdiety) — wyniki odtwarzalne.",
"Ścieżka VAT 50%↔100% z korektą przy zmianie użytkowania — diagram + testy.",
]),
dict(code="P73", slug="PPK_PFRON", title="PPK, PFRON I DOFINANSOWANIA — OBOWIĄZKI PRACODAWCY JDG Z POZOSTAŁYMI UBEZPIECZONYMI",
role="specjalistą od obowiązków pracodawcy-entrepreneur (PPK, PFRON, zasiłki) w silnikach compliance",
expertise="PPK wpłaty i terminy, PFRON WAG i refundacje, dofinansowanie wynagrodzeń, świadczenia na zatrudnionych",
mission=[
"Przeanalizuj obowiązki JDG jako pracodawcy: PPK (obowiązek przy zatrudnieniu ≥1 zatrudnionego od 21 lat, wpłaty podstawowe 2%+1,5%, dodatkowe do 4%/2,5%, terminy do 15. dnia miesiąca następnego, zwolnienie do 120% — weryfikacja aktualnego stanu prawnego!), PFRON (refundacja wynagrodzeń osób niepełnosprawnych, wskaźnik WAG — 6%, 30, 60 dni), dofinansowanie wynagrodzeń (PFRON eWnioskodawca), zatrudnienie członka rodziny (ZUS art. 6 ust. 4 — zwolnienie z własnego ZUS), świadczenia pracownicze (P81 szczegóły). W repo: hr_swiadczenia_auditor istnieje — PPK/PFRON to luka.",
"Zaprojektuj: kalendarz PPK (terminy wpłat, dokumenty umowne), licznik WAG (kładzie pod uwagę zatrudnionych — wagi), ścieżka refundacji (wniosek, terminy, kwoty), zatrudnienie rodziny (skutki ZUS/PIT — oddzielne od własnych składek!), interakcje z P55 (składki ZUS pracodawcy od wynagrodzeń). Fail-closed: brak wpłaty PPK w terminie → alarm (kary PPK!), brak dokumentów PFRON → NEEDS_ADVICE.",
],
subparts=[
dict(name="PPK obowiązek i wpłaty",
goal="terminy i kwoty bez kar",
questions=[
"Czy obowiązek PPK (zatrudnieni od 21 lat, umowa min. 14 dni?) jest klasyfikowany (kto podlega) — reguła z testem?",
"Czy wpłaty podstawowe (2% pracodawca + 2% pracownik; dodatkowe do 4%/2,5%) i terminy (do 15. dnia) mają reguły i kalendarz?",
"Czy zwolnienie z wpłat (dochód do 120% prognozy — art. 134 ustawy PPK?) ma reguły (próg, dokumentacja)?",
"Czy kary za brak wpłat (5000 zł — art. 20 PPK) są w symulatorze ryzyka (motywacja terminowości)?",
]),
dict(name="PFRON i WAG",
goal="refundacje prawidłowe i terminowe",
questions=[
"Czy WAG (wskaźnik zatrudnienia osób niepełnosprawnych — 6%) liczy się zgodnie z ustawą (wagi 6/30/60 per stopień) — test?",
"Czy refundacja wynagrodzeń (3 500,00 do poziomu 90% minimalnej?) ma reguły z wersjonowaniem (P46)?",
"Czy wniosek eWnioskodawca (termin 3 dni? do końca miesiąca?) ma ścieżkę z terminami (P25)?",
"Czy nadpłaty/zwroty PFRON (zmiana stanu — korekta WAG) mają ścieżki (rekalkulacja)?",
]),
dict(name="Zatrudnienie członka rodziny",
goal="skutki ZUS/PIT jasne",
questions=[
"Czy art. 6 ust. 4 ustawy ZUS (zwolnienie z własnych składek przy zatrudnieniu żony/męża) ma regułę (warunki: dochód, ubezpieczenia)?",
"Czy zatrudnienie członka rodziny respektuje PIT (wynagrodzenie = koszt, składki pracodawcy = koszt) — ścieżka UoR/PKPiR?",
"Czy mix: żona na UoP w firmie + własna JDG ma ścieżkę (interakcje składkowe — dwie podstawy?)?",
"Czy dokumentacja (umowa, składki) jest generowana (kontrakt pracy → dokumenty)?",
]),
dict(name="Świadczenia i integracje",
goal="benefity zpoprawne podatkowo",
questions=[
"Czy świadczenia na zatrudnionych (szkolenia, telefon, auto) mają ścieżki kosztowe/VAT (użytek mieszany — P72)?",
"Czy świadczenia 1:1 (EPI? art. 18 PIT?) i ryczałty (praca zdalna — P83) są rozróżnione (nie dublowanie)?",
"Czy PPK dla członka rodziny (współmałżonek zatrudniony) obowiązują (tak — pracodawca) — reguła?",
"Czy interakcja z P24 (prawo pracy — część V3) jest spójna (kontrakty)?",
]),
],
file_groups=[
dict(name="Narzędzia HR i ZUS", files=[
    ("Auditor świadczeń HR", "JDG/tools/hr_swiadczenia_auditor.py"),
    ("Kalkulator ZUS", "JDG/tools/zus_calculator.py"),
    ("Kalkulator chorobowy ZUS", "JDG/tools/zus_zasilkowa_calculator.py"),
    ("Toolkit cyklu życia firmy", "JDG/tools/p16_business_lifecycle_toolkit.py"),
    ("Silnik tierów zdrowotnej", "JDG/tools/zdrowotna_tier_engine.py"),
    ("Kalendarz ZUS", "JDG/tools/zus_calendar.py"),
]),
dict(name="Testy HR/ZUS", files=[
    ("Test RODO/AML/BDO/HR etap21", "JDG/tests/test_rodo_aml_bdo_hr_etap21_audit.py"),
    ("Test natywny HR świadczenia", "JDG/tests/rego/test_p19_hr_swiadczenia_enterprise.rego"),
    ("Test ZUS macro enterprise", "JDG/tests/test_p08_zus_macro_enterprise.py"),
    ("Test natywny micro ZUS", "JDG/tests/rego/micro/test_native_micro_zus.rego"),
]),
dict(name="Dokumenty HR", files=[
    ("HR świadczenia", "JDG/docs/HR_SWIADCZENIA_P19.md"),
    ("ZUS macro", "JDG/docs/ZUS_MACRO_P07.md"),
    ("RODO/AML/bezpieczeństwo", "JDG/docs/RODO_AML_BEZPIECZENSTWO_P16.md"),
    ("Kalendarz zmian prawnych", "JDG/docs/KALENDARZ_ZMIAN_PRAWNYCH.md"),
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
]),
],
legal=[
"Ustawa o pracowniczych planach kapitałowych — art. 25 (terminy wpłat: do 15. dnia miesiąca), art. 15 (wpłaty 2%/2%).",
"Ustawa o PPK — art. 20 (kary za brak wpłat), art. 134 (zwolnienie od wpłat do 120% prognozy).",
"Ustawa o rehabilitacji zawodowej i społecznej oraz zatrudnianiu osób niepełnosprawnych — art. 25a–26 (WAG, refundacje).",
"Ustawa o rehabilitacji — art. 26a (dofinansowanie wynagrodzeń, terminy wniosków).",
"Ustawa o ZUS — art. 6 ust. 4 (zatrudnienie członka rodziny — zwolnienie z własnych składek).",
"Ustawa o PIT — art. 18 (świadczenia pracownicze), art. 22 ust. 9 (koszty wynagrodzeń).",
"Ustawa o ZUS — art. 18a (podstawa składki pracodawcy od wynagrodzeń — integracja P55).",
"Rozporządzenie MF o kwotach refundacji wynagrodzeń (aktualne kwoty — weryfikacja ISAP).",
],
innovations=[
("PPK deadline engine", "kalendarz PPK (wpłaty do 15., dokumenty umowne) z watchdogiem — kara 5000 zł nie zasługuje na ciszę systemu."),
("PPK eligibility classifier", "kto podlega (21+, umowa 14+ dni, zgoda/rezygnacja) — reguły z dokumentacją zgody (dokumenty generowane)."),
("WAG calculator", "wskaźnik zatrudnienia niepełnosprawnych (wagi 6/30/60) — testy na scenariuszach (zatrudnienie, odejście, stopień)."),
("PFRON refund tracker", "refundacja wynagrodzeń: kwoty (parametry), terminy wniosków, rekalkulacje przy zmianach — ścieżka end-to-end z dowodami."),
("Family-employee rule pack", "art. 6 ust. 4 ZUS: warunki (dochód, ubezpieczenia) + skutki PIT/UoR — jedna ścieżka (nie dwa oddzielne systemy)."),
("Dual-basis guard", "pracownik-rodzina + własna JDG: kontrola podwójnych podstaw (ZUS) — asercja spójności (rozjazd = BLOCKER)."),
("Benefit cost routing", "świadczenia (telefon, auto, szkolenia) → koszt/VAT z rejestrem użytkowania (mix prywatny — P72 spójne)."),
("Penalty simulator HR", "ryzyko kar (PPK 5000, PFRON nadpłaty) w dashboard — motywacja zgodności widoczna liczbowo."),
("PPK document generator", "umowy PPK, informacje do pracowników, zgody — generowane automatycznie (szablony z parametrami)."),
("Employment onboarding flow", "nowy zatrudniony → PPK (30 dni?), składki (P55), PPK wpłaty, benefity — jeden przepływ (zero elementów zapomnianych)."),
("PFRON document pack", "pakiet dla wniosków PFRON (lista płac, ewidencja niepełnosprawności) — eksport jednym poleceniem."),
("HR-ZUS reconciliation", "lista płac ↔ składki ZUS ↔ PPK ↔ PIT zaliczki — rekonsylacja miesiąca z asercjami (rozjazd = BLOCKER)."),
],
in_contracts=[
"Kontrakt kalendarza z P25 — terminy PPK/PFRON w jednym źródle (przenoszenie dni robocze).",
"Kontrakt składek z P55 — składki pracodawcy od wynagrodzeń spójne (nie duplikować wyliczeń).",
],
out_contracts=[
"PPK/PFRON engine — wiąże P24 (prawo pracy V3), P81 (świadczenia szczegóły) i P68.",
"WAG calculator — wejście do P68 (certyfikacja) i P40 (UI HR).",
"HR-ZUS reconciliation — wejście do P32 (pipeline) i P58 (metryki).",
],
acceptance_extra=[
"Kalkulator WAG z min. 5 scenariuszami (zatrudnienia, stopnie, odejścia) — wyniki zgodne z ustawą.",
"Ścieżka PPK od obowiązku do wpłaty (terminy, dokumenty, kary) — diagram z datami.",
]),
dict(code="P74", slug="KOREKTY_NADPLATY", title="KOREKTY DEKLARACJI, NADPŁATY I ZWROTY — PIENIĄDZ WRACAJĄCY NA CZAS",
role="specjalistą od procedur podatkowych (korekty, nadpłaty, zwroty, odsetki) w silnikach rozliczeniowych",
expertise="deklaracje korygujące, nadpłata (art. 72–76 OP), zwrot VAT (art. 87), odsetki od nadpłaty (art. 57), zaliczki",
mission=[
"Przeanalizuj ścieżkę pieniądza wracającego: deklaracje korygujące (Ordynacja art. 81 — korekta przed/gdy trwa kontrola!), nadpłata (art. 72: zwrot 30/40/45 dni od decyzji — zaliczka na zwrot VAT odsetki art. 57a!), zwrot VAT (art. 87: standard 60 dni, 40 jeśli raporty/ewidencje w porządku, 180 przy podejrzeniu — ścieżki), odsetki od nadpłaty (art. 57 — od 45 dni), zaliczki na VAT (korekty w deklaracji), nadpłata na poczet (art. 74 — wybór podatnika). W repo: brak ścieżek korekt i nadpłat — pustynia proceduralna (pieniądze liczą się na odsetkach!).",
"Zaprojektuj: generator deklaracji korygującej (które okresy, kwota, powód — z pełnym śladem), tracker nadpłaty (kwota, data, odsetki narastające — P62 live view), ścieżki zwrotu VAT (terminy per profil: 40/60/180 — warunki z regułami, dokumenty), korekta przed kontrolą vs w trakcie (skutki prawne — art. 81a: nie wolno korygować w trakcie?), nadpłata na poczet (preferencje podatnika jako dane). Fail-closed: korekta bez powodu/dowodu → NEEDS_ADVICE (korekta = deklaracja wiążąca!).",
],
subparts=[
dict(name="Deklaracje korygujące",
goal="korekta z pełnym śladem prawnym",
questions=[
"Czy generator deklaracji korygującej (okres, kwota, powód) ma ścieżkę z walidacją (zgodność z danymi) i WORM (P42)?",
"Czy korekta przed kontrolą (art. 81 §3) vs w trakcie (zakaz — art. 81a?) ma reguły (stan postępowania jako kontekst)?",
"Czy korekta skutkuje odsetkami (zaległość powstała ponownie — art. 56 §3?) — kalkulator odsetek (P62)?",
"Czy korekty JPK_V7 (miesięczne) mają idempotencję (P57) i spójność z ewidencjami (rekonsylacja)?",
]),
dict(name="Nadpłaty i odsetki",
goal="pieniądz z odsetkami pilnowany",
questions=[
"Czy tracker nadpłaty (kwota, data, odsetki art. 57 od 45 dni) ma live view (P62 standard)?",
"Czy terminy zwrotu (30 dni decyzja, 40 od wniosku?, 45 — weryfikacja art. 76) mają watchdogi (termin mijający → eskalacja)?",
"Czy nadpłata na poczet zaległości (art. 74 — wybór podatnika) jest deklarowana (preferencje jako dane)?",
"Czy zaliczki na VAT (nadpłata — art. 76b) mają ścieżkę (zwrot na wniosek w deklaracji)?",
]),
dict(name="Zwroty VAT",
goal="40/60/180 dni — ścieżki i warunki",
questions=[
"Czy profil zwrotu (40 dni: raporty PS_ZD_7 dołączane? 60 standard, 180 wątpliwości) ma reguły z warunkami (art. 87 ust. 1a–3)?",
"Czy raport PS_ZD_7 (asercja zakupów) jest generowany automatycznie (dane z ewidencji)?",
"Czy zwrot 180 dni (podejrzenie) ma ścieżkę obronną (dokumenty, wniosek o przyspieszenie — art. 87 ust. 3a)?",
"Czy zwrot na rachunek VAT (art. 87a — dla dużych?) ma regułę (próg zwolnienia — 3 000,00)?",
]),
dict(name="Integracje i rekonsylacja",
goal="korekty spójne z całością",
questions=[
"Czy korekta deklaracji spójna z korektami ewidencji (JPK ↔ UoR ↔ PKPiR) — rekonsylacja z asercją?",
"Czy odsetki od zaległości (po korekcie) i od nadpłaty w tym samym okresie mają kalkulator wspólny (art. 56 vs art. 57)?",
"Czy nadpłata na VAT vs PIT (dwa systemy!) rozróżniana jest (między rejestrami nie mieszają się)?",
"Czy historii korekt (kto, kiedy, powód) w WORM — audyt pełny (P42)?",
]),
],
file_groups=[
dict(name="Narzędzia proceduralne", files=[
    ("Pakiet obronny (builder)", "JDG/tools/defense_packet_builder.py"),
    ("Kalkulator sankcji", "JDG/tools/sanction_calculator.py"),
    ("Symulator kary KKS", "JDG/tools/kks_penalty_simulator.py"),
    ("Toolkit księgowości", "JDG/tools/p11_accounting_toolkit.py"),
    ("Silnik zamknięcia UoR", "JDG/tools/uor_closing_engine.py"),
    ("WORM storage", "JDG/tools/worm_storage.py"),
]),
dict(name="Testy kontekstowe", files=[
    ("Test PKPiR/UoR enterprise", "JDG/tests/test_pkpir_uor_enterprise.py"),
    ("Test konfliktów enterprise", "JDG/tests/test_conflicts_enterprise.py"),
    ("Test tax audit", "JDG/tests/test_tax_audit.py"),
    ("Test natywny cross-declaration", "JDG/tests/rego/test_native_cross_declaration_validator_enterprise.rego"),
]),
dict(name="Dokumenty proceduralne", files=[
    ("Ordynacja podatkowa", "JDG/docs/ORDYNACJA_PODATKOWA_P11.md"),
    ("Księgowość PKPiR/UoR", "JDG/docs/KSIEGOWOSC_PKPIR_UOR_P09.md"),
    ("Logika biznesowa", "JDG/docs/LOGIKA_BIZNESOWA.md"),
    ("KKS", "JDG/docs/KKS_P10.md"),
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
]),
],
legal=[
"Ordynacja podatkowa — art. 81 (korekta deklaracji: przed trwającą kontrolą — obowiązek), art. 81a (zakaz korekty w trakcie).",
"Ordynacja podatkowa — art. 72–76 (nadpłata: zwrot w 30 dni od decyzji / 40 od wniosku / terminy per przypadek).",
"Ordynacja podatkowa — art. 57 (odsetki od nadpłaty: od 45 dni), art. 57a (odsetki w VAT — od zwrotu).",
"Ordynacja podatkowa — art. 74 (nadpłata na poczet zaległości — wskazanie podatnika), art. 76b (zaliczka na VAT).",
"Ustawa VAT — art. 87 (zwrot: 60 dni standard, 40 z PS_ZD_7?, 180 przy podejrzeniu — weryfikacja wersji), art. 87a (rachunek VAT).",
"Ustawa VAT — art. 76 (zaliczka na VAT — nadpłata z deklaracji).",
"Ordynacja podatkowa — art. 56 §3 (odsetki od zaległości po korekcie — narastająca obowiązek).",
"KKS — art. 57 §1 (zbieg z dopłatą — korekta a sankcje, kontekst P84).",
],
innovations=[
("Correction generator with reason", "deklaracja korygująca: okres, kwota, powód (enum), dokumenty — z walidacją spójności i WORM; zero korekt bez powodu."),
("Control-state guard", "stan postępowania (kontrola trwa?) jako kontekst: korekta w trakcie → BLOCKER prawny (art. 81a) z komunikatem (nie ciche odrzucenie)."),
("Overpayment live tracker", "nadpłata: kwota, data, odsetki art. 57 (od 45 dni) liczone na żywo (P62 standard) — przedsiębiorca widzi koszt zwłoki organu."),
("Refund timeline engine", "profil zwrotu VAT (40/60/180): warunki (raporty, weryfikacje) jako reguły; watchdog na terminy z eskalacją (P25/P37)."),
("PS_ZD_7 auto-report", "raport asercji zakupów generowany z ewidencji (dane, walidacja) — dołączany do deklaracji przy profilu 40 dni."),
("180-day defense path", "zwrot zatrzymany: pakiet dokumentów + wniosek o przyspieszenie (art. 87 ust. 3a) — ścieżka obronna gotowa (P84 spójna)."),
("Preference-driven allocation", "nadpłata na poczet: preferencje podatnika (które zaległości) jako dane — art. 74 egzekwowany zgodnie z wolą."),
("Cross-register reconciliation", "korekta: JPK ↔ ewidencje ↔ UoR — asercje spójności (rozjazd = BLOCKER); odsetki od zaległości i nadpłaty jednym kalkulatorem."),
("Correction history WORM", "pełna historia korekt (kto, kiedy, powód, dokumenty) — audyt niepodważalny (P42 hash chain)."),
("Interest net calculator", "netto odsetek: zaległość po korekcie − nadpłata odsetki — jeden ekran (zero ręcznego liczenia dwóch światów)."),
("VAT vs PIT isolation", "nadpłaty VAT i PIT w odrębnych ścieżkach (nie mieszanie między systemami) — testy izolacji."),
("Correction impact preview", "przed złożeniem: wpływ korekty (podatek, odsetki, ryzyko) — preview z liczbami (P40 UI), decyzja świadoma."),
],
in_contracts=[
"Kontrakt WORM z P42 — historia korekt w niezmiennym archiwum.",
"Kontrakt odsetek z P62 — jeden kalkulator odsetek (zaległości i nadpłaty).",
],
out_contracts=[
"Correction engine (generator + guard) — wiąże P84 (obrona), P32 (pipeline) i P68.",
"Overpayment tracker — wejście do P62 (płatności), P40 (UI) i P68.",
"VAT refund profiles — wejście do P54 (deklaracje) i P25 (terminy).",
],
acceptance_extra=[
"Ścieżka nadpłaty end-to-end (przepłacenie → odsetki → zwrot) z testami terminów (30/40/45).",
"Macierz profili zwrotu VAT (40/60/180) z warunkami i cytatem art. 87 per wiersz.",
]),
dict(code="P75", slug="LOKALNE_OPLATA_SKARBOWA", title="PCC SZCZEGÓŁY, OPŁATA SKARBOWA I PODATKI LOKALNE — ZIEMIA I PAPIERY",
role="specjalistą od PCC szczegółowego, opłaty skarbowej i podatków lokalnych w silnikach reguł",
expertise="PCC od pożyczek (wspólnik art. 9 ust. 10), opłata skarbowa (pełnomocnictwa), podatek od nieruchomości, PCC zwolnienia",
mission=[
"Przeanalizuj szczegóły podatki lokalne: PCC (pożyczki — 0,5%, pożyczka od wspólnika do kwoty zwolnienia art. 9 ust. 10 PCC — limity roczne, PCC od kredytu? nie — czynności bankowe zwolnione), PCC od zakupu auta (P72), nieruchomości (podatek od nieruchomości: działatelność = stawki najwyższe (pomieszczenia gospodarcze?), budynek, grunt — rozporządzenie MF stawki maksymalne), opłata skarbowa (pełnomocnictwa — 17 zł od 2024?, zaświadczenia, zastępstwo procesowe), PCC zwolnienia (art. 9: sprzedaż z tarczą? darowizna w rodzinie I grupy), terminy (14 dni od zdarzenia — sama sposób). W repo: pcc_engine istnieje — szczegóły pożyczek i opłaty skarbowej to luka.",
"Zaprojektuj: rejestr zdarzeń PCC (pożyczki, umowy — data, kwota, podmioty), ścieżka pożyczka od wspólnika (limit zwolnienia — narastający, dokumentacja), kalkulator opłaty skarbowej (pełnomocnictwa — numer, kwota, termin płatności do 14 dni), podatek od nieruchomości (profil działalności → stawka — deklaracja IN-1? roczna, zaliczki), ostrzeżenie o kary (KKS art. 55 — PCC niezapłacona: sankcyjna? nie — odsetki + KKS za niezapłacenie 0,5%?). Fail-closed: zdarzenie PCC bez weryfikacji zwolnienia → NEEDS_ADVICE.",
],
subparts=[
dict(name="PCC pożyczki i zwolnienia",
goal="pożyczka od wspólnika i inne zwolnienia",
questions=[
"Czy pożyczka od wspólnika (art. 9 ust. 10 PCC — zwolnienie do limitu) ma regułę (limit roczny, dokumentacja umowy) z testem granicznym?",
"Czy limit zwolnienia (do 2026: kwota podnoszona?) jest parametrem z wersjonowaniem (P46) i cytatem (nowelizacje)?",
"Czy PCC od pożyczek zewnętrznych (0,5%, 14 dni) ma ścieżkę (termin, płatność PCC-3)?",
"Czy zwolnienia rodzinne (darowizna I grupy — art. 9 ust. 2 pkt 2) i inne (dotacje, pożyczki od rodziców?) mają rejestr z regułami?",
]),
dict(name="Opłata skarbowa",
goal="pełnomocnictwa i zaświadczenia bez pomyłek",
questions=[
"Czy pełnomocnictwa (17 zł od 2024? weryfikacja) mają rejestr (dla kogo, zakres, kwota) i terminy (płatność do 14 dni — P25)?",
"Czy zaświadczenia (o niezaleganiu, o rezydencji) mają ścieżki (opłata, terminy wydania)?",
"Czy opłata skarbowa od zastępstwa procesowego (17 zł, art. 2 ust. 1 pkt 10?) ma reguły (kontekst P84 — obrona)?",
"Czy zwolnienia z opłaty (art. 2 ust. 2: czynności organów podatkowych, wnioski zaliczkowe?) są rozpoznawane?",
]),
dict(name="Podatek od nieruchomości",
goal="działalność = stawki najwyższe",
questions=[
"Czy profil nieruchomości (budynek, pomieszczenie gospodarcze, grunt, działalność) → stawka (rozporządzenie MF maksymalne) ma reguły z wersjonowaniem?",
"Czy deklaracja IN-1 (roczna, zaliczki kwartalne/miesięczne) generowana jest (terminy — 15./14 dni?) z kalendarzem (P25)?",
"Czy zmiana sposobu użytkowania (zamieszkane → działalność — stawka wzrasta) ma ścieżkę (deklaracja IN-2?, korekta)?",
"Czy zwolnienia lokalne (uzgodnione uchwałą — usługi techniczne? zaległości?) mają rejestr (uchwały gminy jako dane)?",
]),
dict(name="Terminy i sankcje",
goal="14 dni — pilnowane",
questions=[
"Czy terminy PCC (14 dni od zdarzenia) i opłaty skarbowej (14 dni) mają watchdogi (P25 — przenoszenie na dni robocze?)?",
"Czy PCC niezapłacona w terminie → odsetki (art. 4 ust. 5a PCC — sankcyjna?) i KKS (niezapłacenie — art. 55) — symulator ryzyka?",
"Czy odsetki od PCC (podatek sankcyjny — art. 4 ust. 5b: odsetki podwójne? weryfikacja) mają kalkulator (P62 spójny)?",
"Czy brak rejestru zdarzeń (PCC przeoczone) wykrywalny (sweep zdarzeń bankowych → kandydaci PCC)?",
]),
],
file_groups=[
dict(name="Narzędzia PCC i lokalne", files=[
    ("Silnik PCC", "JDG/tools/pcc_engine.py"),
    ("Auditor PCC/lokalne/akcyza", "JDG/tools/pcc_local_excise_auditor.py"),
    ("Toolkit PCC/lokalne/akcyza", "JDG/tools/p15_pcc_local_excise_toolkit.py"),
    ("Toolkit podatków lokalnych", "JDG/tools/p15_local_taxes_toolkit.py"),
    ("Kalkulator sankcji", "JDG/tools/sanction_calculator.py"),
    ("Kalendarz ZUS (terminy)", "JDG/tools/zus_calendar.py"),
]),
dict(name="Testy PCC", files=[
    ("Test PCC/akcyza enterprise", "JDG/tests/test_pcc_excise_enterprise.py"),
    ("Test semantyki PCC", "JDG/tests/test_pcc_semantics.py"),
    ("Test PCC v3", "JDG/tests/test_pcc_v3_10.py"),
    ("Test natywny PCC v3", "JDG/tests/rego/test_native_pcc_v3_10.rego"),
]),
dict(name="Dokumenty kontekstowe", files=[
    ("PCC/lokalne/akcyza", "JDG/docs/PCC_LOKALNE_AKCYZA_P14.md"),
    ("Ordynacja podatkowa", "JDG/docs/ORDYNACJA_PODATKOWA_P11.md"),
    ("Kalendarz zmian prawnych", "JDG/docs/KALENDARZ_ZMIAN_PRAWNYCH.md"),
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
    ("Zgodność prawna", "JDG/docs/ZGODNOSC_PRAWNA.md"),
]),
],
legal=[
"Ustawa PCC — art. 1 (czynności: sprzedaż, pożyczka 0,5%, cywilnoprawne), art. 4 (termin 14 dni).",
"Ustawa PCC — art. 9 ust. 10 (pożyczka od wspólnika — zwolnienie do limitu), art. 9 ust. 2 pkt 2 (darowizna I grupy).",
"Ustawa PCC — art. 4 ust. 5a–5b (zapłata w terminie: bez sankcji; po terminie: odsetki i KKS kontekst).",
"Ustawa o podatkach i opłacie lokalnej — art. 5 (podatek od nieruchomości: stawki maksymalne rozporządzenia), art. 6 (deklaracje IN-1/IN-2).",
"Ustawa o opłacie skarbowej — art. 2 (czynności: pełnomocnictwa, zaświadczenia — kwoty aktualne), art. 12 (terminy 14 dni).",
"KKS — art. 55 (niezapłacenie PCC/opłaty — grzywna), art. 57 (zbieg).",
"Rozporządzenie MF o stawkach opłaty skarbowej i podatkach lokalnych — weryfikacja aktualnych kwot w ISAP.",
"Ordynacja podatkowa — art. 24b (prawo właściwe w czasie — stawki lokalne per rok).",
],
innovations=[
("PCC event ledger", "rejestr zdarzeń PCC (pożyczka, sprzedaż, umowa) z datą, kwotą, podmiotami — zero zdarzeń zgubionych (sweep z feedu bankowego — kandydaci)."),
("Partner-loan exemption tracker", "limit zwolnienia pożyczek od wspólnika (narastający rocznie) z testami granic — przekroczenie → PCC automatycznie."),
("Stamp duty register", "pełnomocnictwa/zaświadczenia: numer, kwota (parametry), termin 14 dni z watchdogiem — zero opłat przeoczonych."),
("Property profile engine", "nieruchomości: profil (użytkowanie, działalność) → stawka (dane wersjonowane) → deklaracja IN-1 z zaliczkami — terminy pilnowane."),
("Usage-change detection", "zmiana sposobu użytkowania nieruchomości (zamieszkanie → działalność) → deklaracja korygująca + stawka nowa — ścieżka z testami."),
("Municipal resolution registry", "uchwały gmin (zwolnienia lokalne) jako dane per gmina — reguły sprawdzają uchwałę (nie ciche założenie zwolnienia)."),
("Sankcja simulator PCC", "po terminie: odsetki sankcyjne + ryzyko KKS — symulator (motywacja do terminowości, P62 spójny)."),
("Bank feed PCC sweep", "analiza feedu (przelewy, pożyczki) → kandydaci zdarzeń PCC — przypominajka z kwotami (P61 integracja)."),
("PCC-3 generator", "deklaracja PCC-3 (pożyczka) generowana automatycznie (termin, płatność) — walidacja pre-send (P54 standard)."),
("14-day watchdog unified", "terminy 14-dniowe (PCC, opłata skarbowa, zaliczki lokalne) jednym mechanizmem (przenoszenie na dni robocze — konfigurowalne)."),
("Exemption proof pack", "dla zwolnień (rodzina, wspólnik): pakiet dowodowy (umowa, dokumentacja pokrewieństwa) — gotowy na kontrolę (P84)."),
("Local taxes calendar", "deklaracje lokalne (IN-1, IN-2, PCC-3) w kalendarzu zbiorczym (P25) — zero terminów przeoczonych."),
],
in_contracts=[
"Kontrakt kalendarza z P25 — terminy 14-dniowe i deklaracje lokalne w jednym źródle.",
"Kontrakt odsetek z P62 — sankcje PCC jednym kalkulatorem.",
],
out_contracts=[
"PCC event ledger — wiąże P72 (auta), P74 (korekty) i P68.",
"Property profile engine — wejście do P80 (spis/amortyzacja: budynek), P40 (UI) i P68.",
"Stamp duty register — wejście do P84 (obrona: zastępstwo procesowe) i P41.",
],
acceptance_extra=[
"Rejestr zwolnień PCC (wspólnik, rodzina, inne) z limitami i cytatem art. 9 per wiersz.",
"Ścieżka pożyczki od wspólnika (zwolnienie → limit przekroczony → PCC-3 → płatność) z datami i testami.",
]),
dict(code="P76", slug="NAJEM_DZIERZAWA", title="NAJEM PRYWATNY, KRÓTKOTERMINOWY I DZIERŻAWA — DWA ŚWIATY OPODATKOWANIA",
role="specjalistą od rozróżnienia najmu prywatnego i działalności (ryczałt 8,5%, usługi hotelowe VAT) w silnikach reguł",
expertise="najem prywatny (ryczałt 8,5%/12,5%, brak kosztów), najem krótkoterminowy (usługi hotelowe — VAT!), dzierżawa gruntów",
mission=[
"Przeanalizuj najem w JDG: najem prywatny (ryczałt od przychodów ewidencjonowanych: 8,5% do 100 000 zł, 12,5% powyżej — brak możliwości kosztów!, deklaracja roczna? kwartalna? — art. 6 ust. 4 ryczałtu), najem w działalności (opcja: ryczałt 8,5% lub zasady — koszty), najem krótkoterminowy (Airbnb — usługi hotelowe VAT 8%? jeśli zakwalifikowane — zwolnienie a lokal noclegowy?), dzierżawa gruntów rolnych (ryczałt 2% — art. 12 ust. 7?), podatek od nieruchomości na najem (P75), łączenie najmu z działalnością (proporcje, rejestry oddzielne). W repo: ryczalt_rate_validator — interakcje najmu z działalnością to luka.",
"Zaprojektuj: klasyfikator najmu (prywatny/działalność/krótkoterminowy — reguły z fail-closed), rejestr umów najmu (klient, terminy, kwoty), ścieżka ryczałtu (8,5% do progu → 12,5% — testy graniczne, deklaracje kwartalne art. 12 ust. 4), ścieżka krótkoterminowego (usługi hotelowe: VAT 8%, PKWiU 55.20 — klasyfikacja, ewidencja), dzierżawa gruntów (2% ryczałt, VAT-RR kontrahent — P78). Fail-closed: najem krótkoterminowy bez klasyfikacji VAT → NEEDS_ADVICE (ryzyko błędnej stawki).",
],
subparts=[
dict(name="Klasyfikacja najmu",
goal="prywatny vs działalność vs krótkoterminowy",
questions=[
"Czy klasyfikator (ryczałt prywatny 8,5% vs działalność vs krótkoterminowy hotelowy) ma reguły z fail-closed (wątpliwość → NEEDS_ADVICE)?",
"Czy najem krótkoterminowy (do 29 dni? art. 2a ustawy VAT?) kwalifikuje się jako usługi hotelowe (PKWiU 55.20, VAT 8%) — reguła z cytatem?",
"Czy mix (jedna nieruchomość prywatna + druga w działalności) ma ścieżkę segregacji (rejestry oddzielne)?",
"Czy najem dla pracodawcy (pracownik firma w chacie — świadczenie? P81) ma odrębną ścieżkę?",
]),
dict(name="Ryczałt 8,5%/12,5% i deklaracje",
goal="próg 100 000 zł — grosz w granicy",
questions=[
"Czy próg 100 000 zł (łącznie wszystkie rodzaje przychodów ryczałtowych!) ma regułę z testami granic (99 999,99 / 100 000 / 100 000,01)?",
"Czy 12,5% dotyczy tylko przekroczenia (progresywność) czy całości (art. 12 ust. 1 ust. 2: stawka 12,5% od przekroczenia?) — weryfikacja ISAP i test?",
"Czy deklaracje kwartalne (art. 12 ust. 4 ryczałtu) i roczna (PIT-28) generowane są z terminami (P25)?",
"Czy zaliczka zdrowotna (9%? przy najmie prywatnym — brak? weryfikacja art. 30 PIT od najmu) ma reguły (najem prywatny bez zdrowotnej?)",
]),
dict(name="Najem krótkoterminowy (usługi hotelowe)",
goal="VAT i klasyfikacja",
questions=[
"Czy krótkoterminowy (klient na noc, usługi dodatkowe: sprzątanie, pościel) → usługi hotelowe (VAT 8%) — reguła z weryfikacją (art. 2 pkt 19a?)?",
"Czy rejestracja VAT (przekroczenie 200 000? usługi hotelowe — obowiązek od pierwszej sprzedaży?) ma ścieżkę (terminy)?",
"Czy ewidencja krótkoterminowego (nights, ceny, usługi) jest ingested (P57) i walidowana?",
"Czy świadczenia dodatkowe (śniadania? parking? — odrębne stawki VAT) mają reguły (klasyfikacja per pozycja)?",
]),
dict(name="Dzierżawa gruntów i interakcje",
goal="rolnicy i podatki lokalne",
questions=[
"Czy dzierżawa gruntów rolnych (ryczałt 2% — art. 12 ust. 7?) ma regułę (umowa dzierżawy rolnikowi?) z cytatem?",
"Czy faktura VAT-RR (od rolnika ryczałtowego — P78) przy dzierżawie (rolnik dzierżawi grunt JDG?) ma ścieżkę?",
"Czy podatek od nieruchomości (P75) na najem (działalność → stawka najwyższa) ma integrację (profil nieruchomości)?",
"Czy najem prywatny + działalność (te same koszty: remont?) — segregacja kosztów (ryczałt = brak kosztów!) ma reguły (fail-closed)?",
]),
],
file_groups=[
dict(name="Narzędzia ryczałtu", files=[
    ("Walidator stawek ryczałtu", "JDG/tools/ryczalt_rate_validator.py"),
    ("Auditor lifecycle ryczałtu", "JDG/tools/ryczalt_lifecycle_auditor.py"),
    ("Bramka lifecycle ryczałtu v3", "JDG/tools/ryczalt_lifecycle_v3_gate.py"),
    ("Asystent niezarejestrowanej działalności", "JDG/tools/unregistered_activity_assistant.py"),
    ("Toolkit cyklu życia firmy", "JDG/tools/p16_business_lifecycle_toolkit.py"),
    ("Symulator form podatkowych", "JDG/tools/tax_form_whatif_simulator.py"),
]),
dict(name="Reguły ryczałtu", files=[
    ("Innowacje ryczałt r12", "JDG/rules/r12_ryczalt_cykl_zycia_innovations_v9.rego"),
    ("Innowacje ryczałt p13", "JDG/rules/p13_ryczalt_cykl_zycia_innovations_v9.rego"),
    ("Ryczałt atomic p13", "JDG/rules/micro/ryczalt_cykl_atomic_p13.rego"),
    ("Walidator stawek ryczałtu (dane)", "JDG/tools/ryczalt_rate_validator.py"),
]),
dict(name="Testy i dokumenty", files=[
    ("Test ryczałt v3", "JDG/tests/test_ryczalt_v3_09.py"),
    ("Test natywny ryczałt micro", "JDG/tests/rego/micro/test_native_micro_ryczalt.rego"),
    ("Test PKPiR/UoR enterprise", "JDG/tests/test_pkpir_uor_enterprise.py"),
    ("Ryczałt cykl życia (dokument)", "JDG/docs/RYCZALT_CYKL_ZYCIE_P13.md"),
    ("Dokument PIT macro", "JDG/docs/PIT_MACRO_P05.md"),
    ("Dokument PIT micro", "JDG/docs/PIT_MICRO_P06.md"),
]),
],
legal=[
"Ustawa o PIT — art. 6 ust. 1 pkt 3 i ust. 4–6 (ryczałt od najmu prywatnego), art. 10 ust. 1 pkt 6 (źródło: najem).",
"Ustawa o ryczałcie — art. 12 ust. 1 (stawka 8,5% do 100 000 zł, 12,5% od nadwyżki), art. 12 ust. 4 (deklaracje kwartalne).",
"Ustawa o ryczałcie — art. 9 (najem prywatny: brak kosztów), art. 6 ust. 1 (deklaracja roczna PIT-28 kontekst).",
"Ustawa VAT — art. 2 pkt 19a (usługi hotelowe: nocleg + świadczenia, najem krótkoterminowy — weryfikacja definicji).",
"Ustawa VAT — art. 113 ust. 1 (zwolnienie 200 000 zł — usługi hotelowe od pierwszej sprzedaży? weryfikacja zwolnienia podmiotowego).",
"Ustawa o ryczałcie — art. 12 ust. 7 (dzierżawa gruntów rolnych: 2%?).",
"Ustawa o podatkach i opłacie lokalnej — art. 4 (pomieszczenia gospodarcze na najem — stawki najwyższe).",
"Ustawa o PIT — art. 30a ust. 1 pkt 4? (zdrowotna przy najmie prywatnym — weryfikacja obowiązku składki).",
],
innovations=[
("Rental classifier with fail-closed", "prywatny/działalność/krótkoterminowy: reguły z cytatem (art. 2 pkt 19a VAT) — wątpliwość = NEEDS_ADVICE, nie cicha stawka."),
("Threshold 100k guard", "próg ryczałtu łącznie (najem + działalność ryczałtowa!) — narastający licznik z testami granic; przekroczenie → stawka 12,5% na nadwyżkę (asercja progresywności)."),
("Quarterly declaration builder", "deklaracje kwartalne ryczałtu (art. 12 ust. 4) z terminami (P25) i walidacją — zero deklaracji ręcznych."),
("Short-stay VAT pack", "usługi hotelowe: klasyfikacja (PKWiU 55.20), stawka 8%, ewidencja noclegów, świadczenia dodatkowe — jeden pakiet z testami."),
("VAT registration watchdog", "usługi hotelowe: rejestracja VAT (zwolnienie podmiotowe nie dla hotelowych?) — terminy i ścieżka rejestracji."),
("Lease-land rules", "dzierżawa gruntów rolnych: 2% ryczałt, VAT-RR (P78), umowa dokumentacja — ścieżka kompletna."),
("Cost segregation guard", "najem prywatny (brak kosztów!) vs działalność: koszty nie mogą migrować między światami — asercje segregacji (błędne koszty = korekta)."),
("Health contribution check", "najem prywatny: składka zdrowotna (obowiązek? art. 30a?) — reguła z weryfikacją stanu prawnego (Radar prawny P08 aktualizuje)."),
("Property tax integration", "najem → profil nieruchomości (P75) → stawka podatku od nieruchomości — spójność między podatkami."),
("Mixed-portfolio registry", "portfel (kilka nieruchomości: prywatna + działalność + krótkoterminowa) — rejestry oddzielne z widokiem zbiorczym (P40)."),
("Short-stay seasonal calendar", "sezonowość (lato/zima) — prognozy przychodów i zaliczek (P62 cashflow) dla najmu sezonowego."),
("Rental audit pack", "pakiet audytowy: umowy, ewidencje, deklaracje, klasyfikacje — eksport jednym poleceniem (P60)."),
],
in_contracts=[
"Kontrakt parametrów z P46 — stawki 8,5%/12,5%/2% jako dane wersjonowane.",
"Kontrakt klasyfikacji z P71 — usługi hotelowe vs kasa fiskalna (spójność klasyfikacji PKWiU).",
],
out_contracts=[
"Rental classifier (reguły) — wiąże P56 (VAT szczegóły), P75 (podatek od nieruchomości) i P68.",
"Short-stay VAT pack — wejście do P56, P71 (kasa) i P68.",
"Threshold 100k guard — wejście do P18 (ryczałt V3) i P68.",
],
acceptance_extra=[
"Test progu 100 000 zł (najem + działalność łącznie) z trzema przypadkami granicznymi.",
"Macierz klasyfikacji najmu (typ → PIT stawka → VAT reżim → podatki lokalne) z cytatem per wiersz.",
]),
dict(code="P77", slug="DOTACJE_FUNDUSZE", title="DOTACJE, GRANTY I ŚRODKI UE — PRZYCHÓD CZY NIE, KOSZTY KAPITAŁOWE",
role="specjalistą od rozliczania dotacji i funduszy UE w ewidencjach podatkowych",
expertise="dotacje UE (koszty kwalifikowane), granty (przychód? art. 14 ust. 3?), dopłaty ARiMR, de minimis, amortyzacja z dotacji",
mission=[
"Przeanalizuj dotacje i środki publiczne: dotacje z UE (PFR, fundusze strukturalne — przychód czy nie: PIT art. 14 ust. 3 pkt 3 — dotacje celowe na podnoszenie kompetencji?; rozliczenie inwestycji z dotacji: amortyzacja kwoty nieodliczonej?), granty (Research? konkursy — przychód zwykły?), dopłaty ARiMR (P78 kontekst), de minimis (rejestr SUDOP), dotacje PFRON (P73), świadczenia na start (P24? P55 — ulga na start ≠ dotacja), zwrot dotacji (korekty amortyzacji!). W repo: brak reguł dotacyjnych — pustynia dla startupów (które żyją z grantów).",
"Zaprojektuj: rejestr dotacji (umowa, cel, kwota, okres realizacji), klasyfikator (przychód czy nie — reguła z cytatem art. 14 ust. 3), ścieżka inwestycji (środki trwałe z dotacji: koszt nabycia pomniejszony? amortyzacja? — reguły z testami), ścieżka zwrotu (korekta kosztów, przychód?, odsetki?), de minimis (rejestr, limity 200 000/3 lata). Fail-closed: dotacja bez klasyfikacji → NEEDS_ADVICE (błąd klasyfikacji = błędny podatek).",
],
subparts=[
dict(name="Klasyfikacja przychodu z dotacji",
goal="przychód czy nie — reguła z cytatem",
questions=[
"Czy dotacje (celowe na działalność) mają regułę przychodu (art. 14 ust. 3 pkt 3: dotacje na podnoszenie kompetencji — zwolnione?) — weryfikacja zakresu?",
"Czy granty z konkursów (nie dotacje celowe?) = przychód zwykły (art. 14 ust. 2 pkt 1) — reguła z fail-closed?",
"Czy dopłaty ARiMR (rolnik — P78) i świadczenia UE (IACS?) mają odrębne reguły?",
"Czy zwolnienie z dotacji wpływa na koszty (art. 22 ust. 6g: wydatki z dotacji niekwalifikujące się?) — reguła sprzężenia?",
]),
dict(name="Inwestycje z dotacji",
goal="amortyzacja środków trwałych z dotacji",
questions=[
"Czy środek trwały zakupiony z dotacji (70% dotacji) → amortyzacja od kwoty nieobjętej (30%) — reguła z testem (art. 22 ust. 6g PIT)?",
"Czy dotacja zwolniona (art. 14 ust. 3) a środek trwały — nieodliczenie kosztu (przychód z sprzedaży = pełny?) — asercja sprzężenia?",
"Czy jednorazowa amortyzacja (100 000 zł — degressive?) i dotacja (wykluczenie?) ma reguły (interakcja ulg)?",
"Czy likwidacja/sprzedaż środka z dotacji (przywrócenie kosztów — art. 22 ust. 6h?) ma ścieżkę (korekta)?",
]),
dict(name="Zwroty i korekty dotacji",
goal="zwrot dotacji — co z podatkami",
questions=[
"Czy zwrot dotacji (nieprawidłowe wykorzystanie) = przychód? koszt? korekta amortyzacji — ścieżka kompletna z testami?",
"Czy odsetki od zwrotu (odsetki UE?) mają ścieżkę (koszt? przychód organu?) — NEEDS_ADVOICE z doradcą?",
"Czy korekta w deklaracji za okres zwrotu (nie dotacji!) — reguły okresów (temporalność P53)?",
"Czy podwójne finansowanie (ta sama inwestycja: dotacja + ulga) jest wykrywane (asercja anty-duplikacji)?",
]),
dict(name="Rejestry i de minimis",
goal="kontrola pomocy publicznej",
questions=[
"Czy rejestr de minimis (SUDOP — limit 200 000 zł/3 lata? aktualizacja 2024: sektorowe?) ma ścieżkę (suma, alert zbliżenia limitu)?",
"Czy umowa dotacji (cel, kwoty, okresy) jest ingested (P57) z walidacją (koszty kwalifikowane)?",
"Czy raportowanie dla beneficjenta (dokumenty, faktury kwalifikowane) generowane jest automatycznie?",
"Czy dotacja a VAT (odpłatność — dotacja ≠ odpłatność → bez VAT; wkład własny?) ma reguły?",
]),
],
file_groups=[
dict(name="Narzędzia majątkowe", files=[
    ("Silnik amortyzacji", "JDG/tools/deprecation_engine.py"),
    ("Toolkit UoR księgowość", "JDG/tools/p12_uor_accounting_toolkit.py"),
    ("Toolkit księgowości", "JDG/tools/p11_accounting_toolkit.py"),
    ("Rekonsylacja inwentaryzacji", "JDG/tools/inventory_reconciliation.py"),
    ("Auditor amortyzacji PIT", "JDG/tools/pit_micro_amortization_auditor.py"),
]),
dict(name="Testy kontekstowe", files=[
    ("Test PKPiR/UoR enterprise", "JDG/tests/test_pkpir_uor_enterprise.py"),
    ("Test BDO enterprise", "JDG/tests/test_bdo_enterprise.py"),
    ("Test natywny amortyzacja", "JDG/tests/rego/test_native_amortyzacja.rego"),
    ("Test edge cases enterprise", "JDG/tests/test_edge_cases_enterprise.py"),
]),
dict(name="Dokumenty kontekstowe", files=[
    ("Księgowość PKPiR/UoR", "JDG/docs/KSIEGOWOSC_PKPIR_UOR_P09.md"),
    ("Dokument PIT macro", "JDG/docs/PIT_MACRO_P05.md"),
    ("Logika biznesowa", "JDG/docs/LOGIKA_BIZNESOWA.md"),
    ("Środowisko BDO", "JDG/docs/SRODOWISKO_BDO_P15.md"),
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
]),
],
legal=[
"Ustawa o PIT — art. 14 ust. 3 pkt 3 (dotacje celowe na podnoszenie kompetencji zawodowych — zwolnione z przychodu).",
"Ustawa o PIT — art. 14 ust. 2 pkt 1 (przychody ze źródeł — granty nieobjęte zwolnieniem: przychód).",
"Ustawa o PIT — art. 22 ust. 6g (wydatki z dotacji: koszty nieodliczane w części dotacji).",
"Ustawa o PIT — art. 22 ust. 6h (zwrot dotacji: przywrócenie kosztów — korekta).",
"Ustawa o PIT — art. 22 ust. 6i (amortyzacja: wyłączenie kwoty dotacji — weryfikacja konstrukcji).",
"Rozporządzenie MF o dotacjach (de minimis: rozporządzenie UE 1407/2013 — limity, rejestr SUDOP).",
"Ustawa VAT — art. 29a ust. 2 pkt 7 (dotacje — brak odpłatności → nie podlega VAT; wkład własny od sponsorów?).",
"Regulacje funduszy UE (rozporządzenie 2021/1060 — rozliczanie, koszty kwalifikowane — kontekst).",
],
innovations=[
("Grant classification engine", "dotacja celowa (kompetencje — zwolniona) vs grant (przychód) vs dopłata (rolnik) — reguły z cytatem i fail-closed."),
("Grant-funded asset engine", "środek trwały z dotacji: koszt nabycia pomniejszony o dotację → amortyzacja od różnicy — testy (70/30, 50/50, pełna dotacja)."),
("Spend-correlation assertion", "koszty z dotacji nieodliczane ↔ przychód zwolniony — asercja sprzężenia (jedna strona bez drugiej = BLOCKER)."),
("Refund recovery path", "zwrot dotacji: korekta amortyzacji, przychód/koszt, okres zwrotu — ścieżka kompletna z temporalnością (P53)."),
("De minimis tracker", "rejestr SUDOP (suma pomocy, limit 200 000/3 lata) — alert zbliżenia limitu (90%) z raportem."),
("Qualified-cost ledger", "koszty kwalifikowane (faktury per projekt) ingested i raportowane dla beneficjenta — gotowe na audyt UE."),
("Double-funding detector", "ta sama inwestycja w dwóch źródłach (dotacja + ulga) — asercja anty-duplikacji (BLOCKER)."),
("Grant VAT rules", "dotacja ≠ odpłatność (bez VAT) vs wkład własny/patronackie — reguły VAT z testami."),
("Grant timeline calendar", "okresy realizacji (raporty śródroczne, rozliczenia końcowe) w kalendarzu (P25) — zero terminów z funduszy przeoczonych."),
("Grant audit pack", "pakiet dla audytu UE (umowa, faktury kwalifikowane, rozliczenie) — eksport jednym poleceniem."),
("Disposal recovery engine", "sprzedaż/likwidacja środka z dotacji (art. 22 ust. 6h): przywrócenie kosztów — ścieżka z korektami."),
("Grant-vat-pit consistency", "asercje spójności: klasyfikacja (PIT) ↔ VAT (brak odpłatności) ↔ ewidencja — rozjazd = BLOCKER."),
],
in_contracts=[
"Kontrakt amortyzacji z P80 — silnik amortyzacji wspólny (dotacje jako wyłączenie kwoty).",
"Kontrakt ingestu z P57 — umowy dotacji i faktury kwalifikowane przez standardowy ingest.",
],
out_contracts=[
"Grant classification engine — wiąże P73 (PFRON dotacje), P78 (dopłaty ARiMR) i P68.",
"Grant-funded asset engine — wejście do P80 (amortyzacja), P42 (WORM umów) i P68.",
"De minimis tracker — wejście do P41 (rejestry) i P40 (UI).",
],
acceptance_extra=[
"Ścieżka inwestycji z dotacji (70/30) end-to-end z testami amortyzacji i sprzedaży.",
"Klasyfikator dotacji/grantów/dopłat z cytatem i priorytetem weryfikacji ISAP per kategoria.",
]),
dict(code="P78", slug="ROLNICTWO_RYCZALT", title="SPRZEDAŻ OD ROLNIKÓW RYCZAŁTOWYCH I DZIAŁY SPECJALNE (VAT-RR)",
role="specjalistą od transakcji z rolnikami ryczałtowymi (VAT-RR, flat 7%) i działów specjalnych w silnikach reguł",
expertise="faktura VAT-RR, kwota flat 7%, limity, dzierżawa gruntów rolnych, dział specjalny produkcji rolnej",
mission=[
"Przeanalizuj transakcje z rolnikami: rolnik ryczałtowy (sprzedaż produktów rolnych — nabywca wystawia fakturę VAT-RR, kwota podatku flat 7% do odliczenia — art. 115 VAT), limit (sprzedaż bezpośrednia 100 000 zł — rolnik traci status?), dział specjalny produkcji rolnej (rolnik JDG ryczałt od przychodów ewidencjonowanych — art. 6 ust. 5 PIT), dzierżawa gruntów (P76), kupno od rolnika ( VAT-RR: kto, kwoty, wymagania dokumentacyjne), sprzedaż środków trwałych rolnika (VAT-RR? nie — zwolnienie?), odliczenie flat (jako VAT naliczony). W repo: brak reguł VAT-RR — pustynia dla przetwórstwa i handlu produktami rolnymi.",
"Zaprojektuj: klasyfikator kontrahenta (rolnik ryczałtowy? — oświadczenie, weryfikacja limitu), generator faktury VAT-RR (elementy: data, towary, kwota flat, podpis — art. 116 VAT), ścieżka odliczenia (7% jako naliczony — w JPK), ścieżka działu specjalnego (rolnik-JDG: ryczałt 3%? per dział — tabela art. 8 ryczałtu), interakcje z P76 (dzierżawa gruntów). Fail-closed: transakcja z rolnikiem bez oświadczenia → NEEDS_ADVICE (odliczenie bez dokumentu = ryzyko).",
],
subparts=[
dict(name="Klasyfikacja rolnika ryczałtowego",
goal="kto nim jest — weryfikacja limitu",
questions=[
"Czy oświadczenie rolnika (ryczałtowy, limit 100 000 zł sprzedaży bezpośredniej) jest ingested (P57) i weryfikowane (rejestr)?",
"Czy przekroczenie limitu rolnika (100 000 zł) wykrywane (wyciąg zaświadczenie o rejestracji VAT) — ścieżka (utracony status → faktura VAT zwyczajna)?",
"Czy rejestr rolników (NIP, status, weryfikacja) ma odświeżanie (cykliczna weryfikacja — P61)?",
"Czy kupno od rolnika bez oświadczenia (założenie) ma fail-closed (NEEDS_ADVICE, nie ciche VAT-RR)?",
]),
dict(name="Faktura VAT-RR i flat 7%",
goal="elementy obowiązkowe i odliczenie",
questions=[
"Czy generator faktury VAT-RR (elementy art. 116: data, towary, kwota flat 7%, podpisy) ma walidację kompletności?",
"Czy kwota flat (7% od ceny bez podatku?) jest kalkulowana i odliczana jako VAT naliczony (art. 115 ust. 3?) — test?",
"Czy ewidencja VAT-RR w JPK (pola RR, dokumenty) jest spójna (rekonsylacja P74 standard)?",
"Czy termin wystawienia VAT-RR (data nabycia) pilnowany (P25)?",
]),
dict(name="Dział specjalny produkcji rolnej",
goal="rolnik-JDG na ryczałcie",
questions=[
"Czy dział specjalny (akwakultura, hodowle — art. 2 ust. 15 PIT) klasyfikowany (PKWiU 01.46–01.49?) — reguły?",
"Czy stawki ryczałtu dla działów (art. 8 ust. 1 pkt 3: 3%?) są danymi (P46) i testowane per dział?",
"Czy rolnik-JDG (dział specjalny) + zwykła działalność (mix) ma segregację (rejestry oddzielne, P76 standard)?",
"Czy kupno od takiego rolnika-JDG (nie ryczałtowy VAT) to zwykły VAT (faktura z VAT) — reguła rozróżnienia (nie VAT-RR!)?",
]),
dict(name="Integracje i obrona",
goal="spójność i dokumenty",
questions=[
"Czy VAT-RR ↔ JPK ↔ ewidencje (rekonsylacja) mają asercje (rozjazd = BLOCKER)?",
"Czy dokumentacja (oświadczenia, faktury) archiwizowana WORM (P42) — kontrola skarbowa gotowa (P84)?",
"Czy sprzedaż środków trwałych rolnika (traktor) — VAT-RR czy zwolnienie (rolnik na ryczałcie = brak VAT?) — reguła z cytatem?",
"Czy interakcje z P76 (dzierżawa gruntów od rolnika) i P77 (dopłaty ARiMR rolnika — nie JDG) rozgraniczone?",
]),
],
file_groups=[
dict(name="Narzędzia VAT i ryczałt", files=[
    ("Silnik stawek VAT", "JDG/tools/vat_rate_engine.py"),
    ("Detektor MPP", "JDG/tools/vat_mpp_auto_detector.py"),
    ("Walidator stawek ryczałtu", "JDG/tools/ryczalt_rate_validator.py"),
    ("Generator JPK", "JDG/tools/jpk_generator.py"),
    ("Walidator JPK", "JDG/tools/jpk_validator.py"),
    ("Toolkit PCC/lokalne/akcyza", "JDG/tools/p15_pcc_local_excise_toolkit.py"),
]),
dict(name="Testy kontekstowe", files=[
    ("Test VAT enterprise", "JDG/tests/test_vat_enterprise.py"),
    ("Test VAT micro core audyt", "JDG/tests/test_vat_micro_core_audit.py"),
    ("Test ryczałt v3", "JDG/tests/test_ryczalt_v3_09.py"),
    ("Test natywny PCC v3", "JDG/tests/rego/test_native_pcc_v3_10.rego"),
]),
dict(name="Dokumenty kontekstowe", files=[
    ("Dokument VAT macro", "JDG/docs/VAT_MACRO_P03.md"),
    ("Dokument VAT micro", "JDG/docs/VAT_MICRO_P04.md"),
    ("Ryczałt cykl życia", "JDG/docs/RYCZALT_CYKL_ZYCIE_P13.md"),
    ("Dokument PIT macro", "JDG/docs/PIT_MACRO_P05.md"),
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
]),
],
legal=[
"Ustawa VAT — art. 115 (nabycie od rolnika ryczałtowego: faktura VAT-RR, kwota flat 7%, odliczenie jako naliczony).",
"Ustawa VAT — art. 116 (elementy faktury VAT-RR obowiązkowe), art. 117 (ewidencja).",
"Ustawa VAT — art. 113 ust. 3 (limit 100 000 zł sprzedaży bezpośredniej rolnika — utrata statusu).",
"Ustawa o PIT — art. 2 ust. 15 (dział specjalny produkcji rolnej — definicja, PKWiU).",
"Ustawa o ryczałcie — art. 6 ust. 5? i art. 8 (stawki działów specjalnych — weryfikacja stawek).",
"Ustawa o ryczałcie — art. 12 ust. 7 (dzierżawa gruntów rolnych: 2%).",
"Ustawa o PIT — art. 22 ust. 9c? (koszt: kwota flat od rolnika — zaliczenie do kosztów nabycia).",
"Rozporządzenie MF o PKWiU działów specjalnych — weryfikacja klasyfikacji.",
],
innovations=[
("Farmer classifier with registry", "rejestr rolników (NIP, status, oświadczenia, weryfikacja cykliczna) — status ryczałtowy sprawdzany, nie zakładany."),
("VAT-RR generator", "faktura VAT-RR z walidacją elementów (art. 116) i kwotą flat (7%) — zero faktur niekompletnych."),
("Flat-7 deduction test", "odliczenie 7% jako naliczony (art. 115 ust. 3) z testem kwot (rounding! P52 standard)."),
("Limit watchdog", "przekroczenie 100 000 zł przez rolnika (monitoring rynku? oświadczenie roczne) — alert i ścieżka (faktura VAT zamiast RR)."),
("Special-branch classifier", "działy specjalne (PKWiU) → stawki ryczałtu (dane P46) — testy per dział."),
("RR-JPK reconciliation", "VAT-RR ↔ pola JPK ↔ ewidencje — asercje spójności (rekonsylacja standard P74)."),
("Farmer-JDG vs farmer-ryczałt guard", "od rolnika-JDG (dział specjalny): zwykły VAT, NIE VAT-RR — asercja rozróżnienia (błędny reżim = błędne odliczenie)."),
("Fixed-asset sale rule", "sprzedaż środków trwałych przez rolnika ryczałtowego (bez VAT — zwolnienie podmiotowe?) — reguła z cytatem i NEEDS_ADVICE przy wątpliwości."),
("Oświadczenie WORM", "oświadczenia rolników archiwizowane WORM (P42) — dowód na kontrolę (P84 pack)."),
("Land lease integration", "dzierżawa gruntów (P76: 2%) + VAT-RR (od rolnika-dzierżawcy?) — spójność ścieżek (bez konfliktu reguł)."),
("ARiMR boundary", "dopłaty rolnika (P77) NIE są przychodem JDG kupującego — asercja rozgraniczenia podmiotów."),
("Farm audit pack", "pakiet audytowy transakcji rolnych (oświadczenia, faktury RR, ewidencja) — eksport jednym poleceniem."),
],
in_contracts=[
"Kontrakt parametrów z P46 — flat 7% i stawki działów jako dane wersjonowane.",
"Kontrakt klasyfikatora z P76 — dzierżawa gruntów spójna (jedna klasyfikacja podmiotów).",
],
out_contracts=[
"Farmer registry + VAT-RR pack — wiąże P56 (VAT szczegóły), P84 (obrona) i P68.",
"Special-branch classifier — wejście do P18 (ryczałt) i P68.",
"Farm audit pack — wejście do P60 i P84.",
],
acceptance_extra=[
"Ścieżka VAT-RR end-to-end (oświadczenie → faktura → odliczenie → JPK) z testami kwot flat.",
"Macierz podmiotów rolnych (ryczałtowy / JDG dział specjalny / przetwórca) → reżim VAT/PIT z cytatem.",
]),
dict(code="P79", slug="PPHU_MARZA", title="PPHU, VAT MARŻA I KOMIS — POŚREDNICTWO I TOWARY UŻYWANE",
role="specjalistą od VAT marży (towary używane, dzieła sztuki) i pośrednictwa (PPHU) w silnikach reguł",
expertise="schemat VAT marży (warunki, dokumentacja uproszczona), PPHU (podatnik VAT), komis, import towarów używanych",
mission=[
"Przeanalizuj schemat VAT marży (art. 120 VAT): towary używane, dzieła sztuki, antyki i kolekcje (warunki: nabycie od osoby prywatnej/warunków zwolnienia), dokumentacja uproszczona (faktura marży — bez VAT rozdzielonego, cena = marża + nabycie), obowiązek weryfikacji (podmiot warunków zwolnienia!), VAT od marży (brak odliczenia VAT nabycia!), rejestracja per sztuka?, ewidencja (art. 120 ust. 10). PPHU (podatnik podatku VAT — pośrednik w ustaleniu ceny, zleceniodawca VAT), komis (art. 7 ust. 2: komitent = dostawca, komisant nie na własny rachunek), import towarów używanych (marża!). W repo: vat_rate_engine bez marży — pustynia dla handlu używanym.",
"Zaprojektuj: klasyfikator schematu (towar kwalifikuje? — reguły z warunkami), ścieżka marży (nabycie bez VAT? od prywatnego — dokumentacja), kalkulator marży (cena sprzedaży − cena nabycia → VAT 23% od marży → ewidencja), ścieżka PPHU/komis (kto dostawca, faktura od komitenta, prowizja), import używanych (marża — art. 120 ust. 4 pkt 3?). Fail-closed: schemat bez weryfikacji warunków → NEEDS_ADVICE (schemat błędny = dobra risk!).",
],
subparts=[
dict(name="Warunki schematu VAT marży",
goal="towar kwalifikuje — weryfikacja obowiązkowa",
questions=[
"Czy klasyfikator (towar używany: ruchomość, zdolność do ponownego użycia; dzieło sztuki: definicja art. 120 ust. 3 pkt 6) ma reguły z cytatem?",
"Czy warunki nabycia (od osoby prywatnej bez VAT, od zwolnionego — art. 120 ust. 4) mają reguły (weryfikacja obowiązkowa — fail-closed)?",
"Czy nabycie z VAT (od podatnika — nie kwalifikuje się!) wykrywane (duplikacja VAT = korekta)?",
"Czy import towarów używanych (schemat marży) ma ścieżkę (art. 120 ust. 4 pkt 3? — weryfikacja)?",
]),
dict(name="Ewidencja i faktura marży",
goal="cena i VAT od marży",
questions=[
"Czy faktura marży (bez wyróżnienia VAT, cena = całość) generowana jest zgodnie (art. 120 ust. 10)?",
"Czy ewidencja marży (per sztuka: nabycie, sprzedaż, marża, VAT) ingested (P57) i walidowana?",
"Czy VAT od marży (23% od różnicy: cena sprzedaży minus nabycie) kalkulowany automatycznie z testami (marża 0? ujemna?)",
"Czy ewidencja w JPK (pola marży — kolumna?) spójna (rekonsylacja P74 standard)?",
]),
dict(name="PPHU i komis",
goal="kto dostawca — prawda o łańcuchu",
questions=[
"Czy PPHU (podatnik VAT: pośrednik) rozpoznawany (kontrakt, prowizja) — reguły (faktura od zleceniodawcy, prowizja = usługa)?",
"Czy komis (art. 7 ust. 2: dostawa przez komitenta) ma reguły (komitent dostawca, komisant wystawia?) — weryfikacja konstrukcji",
"Czy prowizja komisanta (usługa dla komitenta — VAT 23%) ma ścieżkę (faktura prowizji)?",
"Czy aktywo powrotne (niesprzedane — zwrot do komitenta, bez dostawy) ma ścieżkę (brak VAT)?",
]),
dict(name="Ryzyka i obrona",
goal="schemat źle użyty = dobra ryzyka",
questions=[
"Czy błędne użycie schematu (nabycie z VAT!) wykrywane (asercja) i korygowane (ścieżka naprawy — P74)?",
"Czy weryfikacja warunków (podmiot prywatny) dokumentowana (oświadczenie, WORM — P42)?",
"Czy kontrola (KAS: porównanie marży z rynkiem — manipulacja cenami?) ma ścieżkę obronną (raporty rynkowe?)",
"Czy interakcje z P56 (GTU: towary używane?) i P71 (kasa: sprzedaż detaliczna marży?) spójne?",
]),
],
file_groups=[
dict(name="Narzędzia VAT", files=[
    ("Silnik stawek VAT", "JDG/tools/vat_rate_engine.py"),
    ("Detektor MPP", "JDG/tools/vat_mpp_auto_detector.py"),
    ("Detektor luk VAT", "JDG/tools/vat_gap_detector.py"),
    ("Matryca traceability VAT", "JDG/tools/vat_traceability_matrix.py"),
    ("Migrator rule_id VAT", "JDG/tools/vat_ruleid_migrator.py"),
    ("Walidator JPK", "JDG/tools/jpk_validator.py"),
]),
dict(name="Testy VAT", files=[
    ("Test VAT enterprise", "JDG/tests/test_vat_enterprise.py"),
    ("Test VAT micro atomic", "JDG/tests/test_p05_vat_micro_atomic.py"),
    ("Test audytu VAT macro", "JDG/tests/test_vat_macro_audit.py"),
    ("Test audytu VAT micro special", "JDG/tests/test_vat_micro_special_audit.py"),
    ("Test semantyki PCC", "JDG/tests/test_pcc_semantics.py"),
]),
dict(name="Dokumenty kontekstowe", files=[
    ("Dokument VAT micro", "JDG/docs/VAT_MICRO_P04.md"),
    ("Dokument VAT macro", "JDG/docs/VAT_MACRO_P03.md"),
    ("Raport audytu VAT", "JDG/docs/VAT_AUDYT_R03.md"),
    ("PCC/lokalne/akcyza", "JDG/docs/PCC_LOKALNE_AKCYZA_P14.md"),
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
]),
],
legal=[
"Ustawa VAT — art. 120 ust. 1–5 (schemat VAT marży: towary używane, dzieła sztuki, antyki — warunki nabycia).",
"Ustawa VAT — art. 120 ust. 4 (schemat tylko przy nabyciu: od osoby prywatnej / zwolnionego / schemat — weryfikacja warunków).",
"Ustawa VAT — art. 120 ust. 10 (ewidencja marży: per towar, marża, VAT) i ust. 11 (faktura bez VAT).",
"Ustawa VAT — art. 7 ust. 2 (komis: dostawą jest dostawa komitenta).",
"Ustawa VAT — art. 8 ust. 1? (usługa komisanta: prowizja — usługa odrębna).",
"Ustawa VAT — art. 119a? (VMS platformy — P70 kontekst: nie mieszać z marżą).",
"Rozporządzenie o KSeF (faktura marży w KSeF — schemat FA(3) pola marży — kontekst P54).",
"Ustawa VAT — art. 109 ust. 7? (ewidencja marży — szczegóły prowadzenia).",
],
innovations=[
("Margin scheme classifier", "warunki (towar, nabycie od kogo) jako reguły z cytatem — fail-closed (brak weryfikacji podmiotu = NEEDS_ADVICE)."),
("Purchase-VAT detector", "nabycie z VAT (od podatnika) → schemat niedostępny — asercja (duplikacja VAT = korekta ścieżka P74)."),
("Margin calculator", "VAT = 23% × (cena sprzedaży − cena nabycia) — testy (marża 0, ujemna, grosze P52)."),
("Per-item margin ledger", "ewidencja per sztuka (nabycie, sprzedaż, marża, VAT) ingested z walidacją — kontrola per towar możliwa."),
("Margin invoice generator", "faktura marży (bez wyróżnienia VAT, art. 120 ust. 10) — spójna z KSeF FA(3) polami marży."),
("Consignment triple-play", "komis: dostawa komitenta (faktura), prowizja (usługa 23%), zwrot aktywa (brak dostawy) — trzy ścieżki jedną regułą zestawu."),
("PPHU recognition", "podatnik VAT (pośrednik) → faktury od zleceniodawcy + prowizja — reguły łańcucha dokumentów."),
("Import-used path", "import towarów używanych (schemat marży) — ścieżka z dokumentami celnymi (SAD/PZC) ingested."),
("Condition-proof WORM", "oświadczenia o nabyciu (od kogo) archiwizowane WORM — dowód warunków (P84 pack)."),
("Market-price defense pack", "raporty cen rynkowych (manipulacja marży — ryzyko kontroli) — pakiet obronny (P84)."),
("Scheme-abuse detector", "wzorce nadużycia schematu (rotacja, ceny graniczne) → NEEDS_ADVICE (GAAR art. 119a OP — obrona silnika)."),
("GTU consistency", "towary używane w marży ↔ GTU_02 (odzież?) — spójność klasyfikacji (P56)."),
],
in_contracts=[
"Kontrakt ewidencji z P57 — ewidencja marży przez standardowy ingest (WORM oryginałów).",
"Kontrakt klasyfikacji z P56 — GTU i PKWiU spójne (jedno źródło klasyfikacji).",
],
out_contracts=[
"Margin scheme pack (klasyfikator, kalkulator, ewidencja) — wiąże P56, P71 (kasa) i P68.",
"Consignment triple-play — wejście do P32 (pipeline) i P40 (UI dokumentów).",
"Scheme-abuse detector — wejście do P84 (obrona) i P49 (fail-closed).",
],
acceptance_extra=[
"Test kalkulatora marży (min. 8 scenariuszy: marża 0, ujemna, grosze, import) — wyniki odtwarzalne.",
"Macierz schematu (typ towaru → warunki → dokumentacja → ryzyka) z cytatem art. 120 per wiersz.",
]),
dict(code="P80", slug="SPIS_NATURY_AMORT", title="SPIS Z NATURY, LIKWIDACJE I AMORTYZACJA SZCZEGÓŁOWA",
role="specjalistą od majątku trwałego (spis z natury, likwidacja, amortyzacja szczegółowa) w silnikach ewidencyjnych",
expertise="spis z natury (zawieszenie, likwidacja), amortyzacja jednorazowa 100k/50k, korekty po sprzedaży, współwłasność",
mission=[
"Przeanalizuj szczegóły majątkowe: spis z natury (po zawieszeniu działalności — wycofanie środków trwałych do majątku prywatnego, odnowienie po wznowieniu; po likwidacji — sprzedaż/likwidacja z VAT?), amortyzacja szczegóły (jednorazowa do 100 000 zł rocznie? aktualizacja limitów! do 50 000 zł — małe wdrożenia? weryfikacja limitów 2026, korekta po sprzedaży (art. 22j: sprzedaż w ciągu 12 miesięcy → przywrócenie kosztów od amortyzacji), amortyzacja nieujmowana (ulga na start — P55!), współwłasność majątkowa małżeńska (koszty/amortyzacja 50/50 — majątek wspólny), wycofanie z używania (art. 16a ust. 3: utrata prawa amortyzacji — 1 rok?), rewaloryzacja? nie — polska amortyzacja nieliniowa/degresywna (grupy 3–8, kontekst).",
"Zaprojektuj: rejestr środków trwałych (nabycie, wartość, grupa KŚT, stawki, metoda — jednorazowa/liniowa/degresywna/naturalna), ścieżka jednorazowej (limit roczny 100 000: licznik, testy, kolejność zakwalifikowania), ścieżka sprzedaży w 12 miesięcy (korekta: przywrócenie kosztów — art. 22j, testy), ścieżka zawieszenia (spis z natury: wycofanie, amortyzacja stop, odnowienie), współwłasność (podział 50/50, dokumentacja intercyzy?). Fail-closed: amortyzacja bez rejestru → NEEDS_ADVICE.",
],
subparts=[
dict(name="Rejestr środków trwałych",
goal="jedno źródło majątku",
questions=[
"Czy rejestr ST (nabycie, wartość, grupa KŚT, metoda, stawka) jest ingested (P57) i walidowany (grupa → stawka z tabel amortyzacyjnych)?",
"Czy metody (liniowa, jednorazowa 100k, jednorazowa 50k?, degresywna 1.5/2.0, naturalna) mają reguły z warunkami (degresywna: grupy 3–8, bez korekty)?",
"Czy współwłasność małżeńska (50/50) ma reguły (amortyzacja połowa, przychód połowa — dokumentacja)?",
"Czy wycofanie z używania (art. 16a ust. 3: utrata prawa do amortyzacji na 1 rok?) ma ścieżkę (data, test)?",
]),
dict(name="Jednorazowa i limity",
goal="limit 100 000 zł — kolejność i grosze",
questions=[
"Czy limit jednorazowej (100 000 zł rocznie? — weryfikacja aktualności, 50 000 dla małych?) liczy się narastająco (licznik roczny) — test granic?",
"Czy kolejność zastosowania (zakwalifikowania) regułowa (pierwsze zgłoszenia — data)?",
"Czy jednorazowa a współwłasność (limit 100k na podatnika? na majątek wspólny?) — reguła z testem (2 × 50%?)",
"Czy jednorazowa a ulga na start (amortyzacja nieujmowana — interakcja: nie można obu?) — asercja wykluczenia?",
]),
dict(name="Sprzedaż w 12 miesięcy i korekty",
goal="art. 22j — przywrócenie kosztów",
questions=[
"Czy sprzedaż/likwidacja w ciągu 12 miesięcy od nabycia (jednorazowa) → przywrócenie kosztów (art. 22j) — automatyczna korekta z testami (12 miesięcy: 364/365/366 dni — granica!)?",
"Czy korekta obejmuje też 50k (drugi limit) i degresywną (sprzedaż w ciągu 60 miesięcy — korekta proporcjonalna?) — reguły per metoda?",
"Czy przychód ze sprzedaży (zamortyzowany ST) = przychód (art. 14 ust. 2 pkt 8: nieodpłatne? nie — wartość wynikająca z ewidencji) — ścieżka?",
"Czy spis z natury po sprzedaży (zapasy? ST do majątku prywatnego) ma ścieżkę (rejestr → majątek prywatny)?",
]),
dict(name="Zawieszenie, likwidacja, spis",
goal="cykl życia majątku w przełomach",
questions=[
"Czy zawieszenie (P23 cykl życia) → spis z natury: wycofanie ST (amortyzacja stop — od miesiąca zawieszenia?), odnowienie po wznowieniu (obowiązek spisu) — ścieżka z terminami?",
"Czy likwidacja: spis z natury (wycofanie), sprzedaż majątku (VAT? PCC? — reguły, VAT po likwidacji: sprzedaż = dostawa opodatkowana?), ostatnia amortyzacja (do miesiąca likwidacji)?",
"Czy spis z natury generowany (dokument, suma, WORM) i walidowany (zgodność z rejestrem ST)?",
"Czy wznowienie (odnowienie ST z majątku prywatnego → ewidencja, amortyzacja od nowa? wartość?) ma ścieżkę z testami?",
]),
],
file_groups=[
dict(name="Narzędzia majątkowe", files=[
    ("Silnik amortyzacji", "JDG/tools/deprecation_engine.py"),
    ("Auditor amortyzacji PIT", "JDG/tools/pit_micro_amortization_auditor.py"),
    ("Rekonsylacja inwentaryzacji", "JDG/tools/inventory_reconciliation.py"),
    ("Inwentarz PIT micro", "JDG/tools/pit_micro_inventory.py"),
    ("Silnik zamknięcia UoR", "JDG/tools/uor_closing_engine.py"),
    ("Podwójna ewidencja UoR", "JDG/tools/uor_double_entry.py"),
    ("Symulator zawieszenia", "JDG/tools/zawieszenie_simulator.py"),
    ("Planer sukcesji", "JDG/tools/sukcesja_planner.py"),
]),
dict(name="Testy majątkowe", files=[
    ("Test PKPiR/UoR enterprise", "JDG/tests/test_pkpir_uor_enterprise.py"),
    ("Test rekonsylacji inwentaryzacji", "JDG/tests/test_inventory_reconciliation.py"),
    ("Test natywny amortyzacja", "JDG/tests/rego/test_native_amortyzacja.rego"),
    ("Test edge cases enterprise", "JDG/tests/test_edge_cases_enterprise.py"),
]),
dict(name="Dokumenty kontekstowe", files=[
    ("Księgowość PKPiR/UoR", "JDG/docs/KSIEGOWOSC_PKPIR_UOR_P09.md"),
    ("Dokument PIT macro", "JDG/docs/PIT_MACRO_P05.md"),
    ("Dokument PIT micro", "JDG/docs/PIT_MICRO_P06.md"),
    ("Audyt praw przedsiębiorców", "JDG/docs/PRAWA_PRZEDSIEBIORCOW_AUDYT_R02.md"),
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
]),
],
legal=[
"Ustawa o PIT — art. 22j ust. 1 pkt 1 (jednorazowa do 100 000 zł rocznie — weryfikacja limitu 2026), pkt 1a? (50 000 zł).",
"Ustawa o PIT — art. 22j (korekta przy sprzedaży w ciągu 12 miesięcy: przywrócenie kosztów od amortyzacji jednorazowej).",
"Ustawa o PIT — art. 22c (metody: liniowa, degresywna 1.5/2.0 grupy 3–8, naturalna), art. 22k (stawki roczne).",
"Ustawa o PIT — art. 22h (amortyzacja od miesiąca oddania do używania), art. 16a ust. 3 ust. 1 ustawy o rachunkowości? (wycofanie: utrata prawa na 1 rok).",
"Ustawa o PIT — art. 23 ust. 1 pkt 45 (ulga na start: amortyzacja nieujmowana — kontekst P55).",
"Ustawa o PIT — art. 14 ust. 2 pkt 8 (przychód z likwidacji/spis z natury? — weryfikacja zakresu: art. 14 ust. 2 pkt 8 i 8a).",
"Ustawa o rachunkowości — art. 31 ust. 3 (spis z natury: obowiązek), art. 3 ust. 1 pkt 15 (jednostka rozliczeniowa — kontekst).",
"Ustawa VAT — art. 7 ust. 1? (sprzedaż po likwidacji: dostawa opodatkowana — kontekst).",
],
innovations=[
("Fixed-asset master registry", "rejestr ST (grupa KŚT, metoda, stawka, współwłasność) ingested z walidacją — jedno źródło amortyzacji (P57 standard)."),
("One-off 100k quota engine", "roczny licznik jednorazowej (100 000) z kolejnością zakwalifikowania i testami granic — zero przekroczeń limitu."),
("12-month clawback engine", "sprzedaż/likwidacja w 12 miesięcy → automatyczne przywrócenie kosztów (art. 22j) z testami granic daty (364/365/366 dni — przestępny rok!)."),
("Degressive proportional clawback", "degresywna: korekta proporcjonalna (60 miesięcy) — reguły per metoda (jednorazowa ≠ degresywna ścieżki)."),
("Suspension spis z natury flow", "zawieszenie: wycofanie ST (dokument, suma, WORM), stop amortyzacji od miesiąca, odnowienie po wznowieniu — ścieżka kompletna z terminami."),
("Liquidation asset path", "likwidacja: ostatnia amortyzacja, spis z natury, sprzedaż majątku (VAT/PCC reguły) — end-to-end z testami."),
("Marital co-ownership split", "majątek wspólny: amortyzacja/przychód 50/50 z dokumentacją — reguły i testy (limit 100k × 50%?)."),
("Relief-exclusion assertion", "jednorazowa ↔ ulga na start (nieujmowana): asercja wzajemnego wykluczenia (art. 23 ust. 1 pkt 45) — zero podwójnych ulg."),
("Depreciation start guard", "od miesiąca oddania do używania (art. 22h) — data oddania wymagana (brak → NEEDS_ADVICE), nie ciche założenie nabycia."),
("Asset disposal chain", "sprzedaż ST: przychód (art. 14 ust. 2 pkt 8), VAT (sprzedaż z VAT — korekta P72?), PCC kontrahenta — jedna ścieżka."),
("Revalorization N/A guard", "rewaloryzacja (polska nie stosuje w PIT od 2019?) — asercja (reguła brak, z cytatem — zero fantazji)."),
("Asset audit pack", "pakiet audytowy (rejestr ST, spisy, korekty, dokumenty) — eksport jednym poleceniem (P60)."),
],
in_contracts=[
"Kontrakt rejestru z P57 — rejestr ST przez standardowy ingest (WORM dokumentów nabycia).",
"Kontrakt cyklu życia z P23 — zawieszenie/likwidacja spójne (jedne statusy, jeden rejestr).",
],
out_contracts=[
"Fixed-asset master registry — wiąże P72 (auta), P77 (dotacje: wyłączenie kwoty) i P68.",
"Clawback engines (12M, degresywna) — wejście do P74 (korekty) i P68.",
"Spis z natury flow — wejście do P23 (cykl życia), P42 (WORM dokumentów) i P68.",
],
acceptance_extra=[
"Test clawback 12 miesięcy (data graniczna w roku przestępnym) — odtwarzalne kwoty korekty.",
"Ścieżka zawieszenia (wycofanie → spis → wznowienie → odnowienie) z datami i dokumentami.",
]),
]
