# -*- coding: utf-8 -*-
"""Parts P37-P44: systemic closure wave of the V3 campaign (P44 = final certification)."""
PARTS = [

dict(code="P37", slug="OBSERWOWALNOSC", title="OBSERWOWALNOŚĆ — METRYKI, SLO, DASHBOARDY I WCZESNE OSTRZEGANIE",
role="inżynierem obserwowalności systemów krytycznych (SRE) dla silnika reguł podatkowych klasy ENTERPRISE",
expertise="metryki, SLO/SLA, alerting, dashboardy pewności, health tiers, telemetria decyzji, benchmarki wydajności",
mission=[
"Zbuduj pełną mapę obserwowalności fortecy: jakie metryki istnieją (metrics_generator, pewnosc_metrics, health_tier_engine, health_tier_recalculator, dashboardy z P35), czego brakuje (latencja eval, rozmiar bundle, czas decyzji p95, wskaźnik NEEDS_ADVICE, dryf prawny, świeżość ISAP), i jak alarmować zanim luka stanie się błędem księgowym. Forteca bez obserwowalności ślepnie — decyzja AUTO_POST musi mieć telemetrię tak jak kod ma coverage.",
"Zaprojektuj SLO dla decyzji: dostępność silnika, p95 latencji eval, dokładność (zgodność z golden oracle), świeżość prawa (maks. wiek weryfikacji ISAP), wskaźnik fail-closed (każdy NEEDS_ADVICE z powodem). Zdefiniuj error budget i procedurę jego wyczerpania (zamrożenie wdrożeń reguł). Przeprować głęboką analizę: które metryki są vanity (rośnie zawsze), a które actionable (zmuszają do działania).",
],
subparts=[
dict(name="Metryki istniejące i luki",
goal="inwentaryzacja metryk i nowych definicji",
questions=[
"Co realnie liczy metrics_generator i pewnosc_metrics (źródła danych, częstotliwość)?",
"Które metryki z P35 (Trust Score) i P31 (risk-of-fortress) są eksportowane i gdzie trafiają?",
"Których metryk brakuje: latencja p95, wskaźnik NEEDS_ADVICE, wiek weryfikacji ISAP, dryf mirror?",
"Które metryki są vanity (bez progu akcji) — lista z planem usunięcia lub podpięcia progu?",
]),
dict(name="SLO i error budget",
goal="formalne SLO dla decyzji podatkowych",
questions=[
"Jakie SLO mają sens dla silnika reguł (dostępność, latencja, dokładność, świeżość prawa)?",
"Jak mierzyć dokładność (zgodność z golden verdicts P10) w produkcji, skoro nie ma ground truth na żywo?",
"Co się dzieje przy wyczerpaniu error budgetu (freeze wdrożeń, eskalacja, tryb awaryjny)?",
"Jak SLO wiążą się z cyklem życia reguł (P07) — czy nowa reguła dostaje tymczasowe SLO (kanarek)?",
]),
dict(name="Alerting i runbooki",
goal="alarmy z runbookiem, nie szum",
questions=[
"Które alarmy są istotne (dryf prawny, spadek dokładności, przekroczenie latencji, brak świeżości)?",
"Czy każdy alarm ma runbook (co robić krok po kroku) — czy alarm bez runbooka to luka?",
"Jak uniknąć zmęczenia alertami (agregacja, priorytetyzacja, cicha godzina vs krytyczne)?",
"Czy alarmy trafiają do rejestrów kampanii (luka automatycznie do P30)?",
]),
dict(name="Telemetria decyzji i benchmarki",
goal="ślad każdej decyzji + wydajność silnika",
questions=[
"Czy Decision Certificate (P11) jest źródłem telemetrii (jakie domeny, jaka pewność, jaki tryb)?",
"Czy istnieją benchmarki wydajności eval (.benchmarks) i czy są w CI z progiem regresji?",
"Jak mierzyć koszt ewaluacji per domena (routing O(1) vs else-chain O(n) z P02)?",
"Jak obserwować wzrost liczby reguł (trend) i przewidywać przekroczenie budżetu latencji?",
]),
],
file_groups=[
dict(name="Narzędzia metryk i health", files=[
    ("Generator metryk", "JDG/tools/metrics_generator.py"),
    ("Metryki pewności", "JDG/tools/pewnosc_metrics.py"),
    ("Silnik tierów health", "JDG/tools/health_tier_engine.py"),
    ("Przeliczanie tierów health", "JDG/tools/health_tier_recalculator.py"),
    ("Rekonsylacja health micro", "JDG/tools/health_reconciliation_micro.py"),
    ("Dashboard enterprise", "JDG/tools/enterprise_dashboard.py"),
    ("Dashboard pewności", "JDG/tools/confidence_dashboard.py"),
    ("Dashboard dryfu", "JDG/tools/drift_dashboard.py"),
    ("Wizualizacja holograficzna", "JDG/tools/holographic_viz.py"),
]),
dict(name="Dane metryk i benchmarki", files=[
    ("Metryki pewności (dane)", "JDG/bundles/metrics_pewnosci.json"),
    ("Rejestr zdrowych wersji", "JDG/bundles/healthy_versions.json"),
    ("Stan control plane", "JDG/bundles/control_plane_state.json"),
    ("Rejestr wdrożeń", "JDG/bundles/deployments.json"),
    ("Katalog bundle", "JDG/bundles/bundle_catalog.json"),
    ("Benchmarki (katalog)", "JDG/.benchmarks"),
]),
dict(name="Dokumenty obserwowalności", files=[
    ("Dashboard pewności (dokument)", "JDG/docs/PEWNOSC_DASHBOARD.md"),
    ("Legal Twin raport", "JDG/docs/LEGAL_TWIN_RAPORT.md"),
    ("Traceability legal twin", "JDG/docs/LEGAL_TWIN_TRACEABILITY.md"),
    ("API referencja", "JDG/docs/API_REFERENCJA.md"),
    ("Inwentaryzacja plików", "JDG/docs/INWENTARYZACJA_PLIKOW.md"),
]),
],
legal=[
"Ustawa o rachunkowości — art. 4 ust. 1: telemetria jako dowód rzetelności procesu księgowego.",
"RODO — art. 5 ust. 2 (rozliczalność) i art. 32 (bezpieczeństwo przetwarzania: monitorowanie).",
"Ordynacja podatkowa — art. 119a: obserwowalność ścieżek agresywnych (wczesne wykrywanie).",
"Ustawa VAT — terminy deklaracji: metryki świeżości pipeline'u chronią terminowość (art. 109e).",
"Ustawa o ZUS — terminy składek: metryki kalendarza płatności.",
"Ustawa o rachunkowości — art. 74–75: archiwum i retencja telemetrii decyzji.",
"ISO/IEC 27001 (kontekst) — monitoring jako kontrola bezpieczeństwa (notatka, nie wymóg prawny).",
"Sarbanes-Oxley (kontekst) — nadrzędność audytowalności procesów automatycznych (notatka).",
],
innovations=[
("Decision SLO contract", "SLO zapisane jako dane (YAML): metryka, próg, okno, akcja; narzędzie waliduje zgodność — zmiana SLO jak zmiana parametru (P06)."),
("Freshness SLA dla prawa", "metryka wieku weryfikacji ISAP per akt; przekroczenie = alarm z listą aktów do re-checku (Law Radar P08)."),
("Needs-advice radar", "klasterizacja NEEDS_ADVICE w czasie; nagły wzrost = sygnał luki prawnej lub awarii danych (auto-ticket do P08/P30)."),
("Latency budget per domena", "rozdzielony budżet latencji na domeny; reguła przeciążająca budżet wpada do rejestru z analizą (else-chain → routing)."),
("Decision certificate as telemetry", "certyfikat = źródło metryk (bez dodatkowej instrumentacji): domena, pewność, tryb, podstawa prawna."),
("Error budget freeze", "automatyczne zamrożenie wdrożeń reguł przy wyczerpaniu budżetu (workflow CI odmawia merge)."),
("Anomaly detection na metrykach", "sezonowość księgowa (koniec miesiąca/kwartału) uwzględniona w detekcji anomalii — mniej fałszywych alarmów."),
("Golden drift watch", "ciągły porównywacz decyzji produkcyjnych z golden verdicts; rozjazd = alarm z diffem inputów."),
("Runbook-as-code", "runbooki w repo (Markdown) z linkiem z definicji alarmu; test = weryfikacja istnienia runbooka dla każdego alarmu."),
("Comprehensive status page", "jeden status fortecy (zewnętrzny): dostępność, SLO, ostatni dowód aktualności prawa, otwarte luki P0/P1."),
("Metryki kosztu decyzji", "tokeny/CPU per decyzja (szczególnie ścieżki AI z P33) — budżetowanie warstwy AI."),
("Benchmark regression gate", "benchmarki w CI z progiem regresji (np. +10% latencji p95 = BLOCKER) przed deployem bundle."),
],
in_contracts=[
"Kontrakt audytora z P35 — metryki pochodzą z audytów/bramek (schema JSON), nie z osobnych liczeń.",
"Kontrakt certyfikatu z P11 — telemetria decyzji oparta o Decision Certificate.",
],
out_contracts=[
"KATALOG METRYK I SLO (definicje, progi, runbooki) — wiąże P38 (deploy), P39 (CI) i P44.",
"Konwencja runbook-as-code (ścieżki, format) — wejście do P41 (dokumentacja).",
"Lista vanity metrics do usunięcia — wejście do P30 (fale innowacji) i P36.",
],
acceptance_extra=[
"Każda metryka w katalogu ma: definicję, źródło, próg, akcję, runbook (albo status do zdefiniowania).",
"Zestaw SLO przedstawiony jako kontrakt (tabela) z metodologią pomiaru i error budgetem.",
]),
dict(code="P38", slug="BUNDLE_DEPLOY", title="BUNDLE, DEPLOY I CYKL ŻYCIA WERSJI — CANARY, ROLLBACK, IMMUTABLE ARTEFAKTY",
role="inżynierem release'ów systemów policy-as-code, specjalistą od bezpiecznego wdrażania bundle reguł z pełnym rollbackiem",
expertise="OPA bundle API, canary, auto-rollback, podpisy artefaktów, WORM, immutabilność, replikacja",
mission=[
"Przeanalizuj warstwę bundle i deploy: bundle.sh, bundle_catalog.json, deployments.json, healthy_versions.json, deployment_orchestrator, certificate_service, dr_snapshots. Oceń: czy bundle jest wersjonowany i podpisany, czy wdrożenie jest atomowe, czy istnieje canary (mały % ruchu na nową wersję), czy rollback jest szybki i testowany, czy snapshot DR jest odtwarzalny. Błędny bundle = błędne deklaracje w skali masowej — to najwyższe ryzyko fortecy.",
"Zaprojektuj pełny cykl: budowanie (deterministyczne — ten input = ten output z checksumą), podpisanie, wdrożenie canary (porównanie decyzji z wersją produkcyjną na próbce), awans (100%), obwieszczenie (changelog do Law Radar), monitoring post-deploy (golden replay), auto-rollback przy regresji. Deployment ma być niespodzianką: wszystko zaplanowane, każde wdrożenie z powrotem do stabilnego stanu w minuty.",
],
subparts=[
dict(name="Budowanie i podpisywanie bundle",
goal="determinizm i integralność artefaktów",
questions=[
"Czy bundle.sh buduje deterministycznie (ten stan repo = ten sam output bytes)?",
"Czy artefakt ma checksumę i podpis (kto podpisuje, jak weryfikować przed load)?",
"Czy manifest_v2 i rule_registry są spójne z plikami w bundle (brak ophanów)?",
"Czy build ma bramki jakości (P29) jako wymóg — czy można zbudować bundle z łamiących reguł?",
]),
dict(name="Canary i awans",
goal="stopniowe wdrożenie z porównaniem decyzji",
questions=[
"Czy deployment_orchestrator wspiera canary (podzbiór ruchu/domów)?",
"Jak porównywać decyzje canary vs produkcja (golden replay na próbce, diff werdyktów)?",
"Kto/Co decyduje o awansie canary (metryki z P37: dokładność, latencja, wskaźnik NEEDS_ADVICE)?",
"Czy awans wymaga 4-eyes przy regułach krytycznych (VAT, PIT, ZUS)?",
]),
dict(name="Rollback i DR",
goal="szybki powrót i odtwarzalność po awarii",
questions=[
"Czy rollback jest przetestowany (gra wojenna: awaria → rollback w X minut)?",
"Czy healthy_versions.json automatycznie wskazuje ostatni dobry stan (po weryfikacji, nie deklaracji)?",
"Czy dr_snapshots są odtwarzalne (test restore w CI, nie tylko backup)?",
"Jak rozgraniczyć rollback techniczny i prawny (reguła poprawna technicznie, błędna prawnie — kto wycofuje)?",
]),
dict(name="Cykl życia wersji i audyt deployów",
goal="historia wdrożeń i powiązanie z lifecycle reguł",
questions=[
"Czy deployments.json ma pełną historię (wersja, data, kto, dlaczego, wynik canary)?",
"Czy wdrożenie bundle jest powiązane z lifecycle reguł (P07: SHADOW→ACTIVE per reguła)?",
"Czy istnieje changelog bundle dla przedsiębiorcy (co się zmieniło w decyzjach)?",
"Czy stare wersje są archiwizowane WORM (odtwarzalność dowodu z przeszłości, P05)?",
]),
],
file_groups=[
dict(name="Narzędzia bundle i deploy", files=[
    ("Skrypt budowy bundle", "JDG/bundles/bundle.sh"),
    ("Orkiestrator wdrożeń", "JDG/tools/deployment_orchestrator.py"),
    ("Serwis certyfikatów", "JDG/tools/certificate_service.py"),
    ("Menedżer lifecycle reguł", "JDG/tools/rule_lifecycle_manager.py"),
    ("Silnik self-healing", "JDG/tools/self_healing_engine.py"),
    ("WORM storage", "JDG/tools/worm_storage.py"),
    ("Silnik zdrowia tierów", "JDG/tools/health_tier_engine.py"),
]),
dict(name="Dane bundle i wdrożeń", files=[
    ("Katalog bundle", "JDG/bundles/bundle_catalog.json"),
    ("Rejestr wdrożeń", "JDG/bundles/deployments.json"),
    ("Zdrowe wersje", "JDG/bundles/healthy_versions.json"),
    ("Manifest bundle v2", "JDG/bundles/manifest_v2.json"),
    ("Rejestr reguł", "JDG/bundles/rule_registry.json"),
    ("Progi i stawki", "JDG/bundles/thresholds_data.json"),
    ("Zrzuty DR (katalog)", "JDG/bundles/dr_snapshots"),
    ("Golden verdicts (kontrola po deploy)", "JDG/bundles/golden_verdicts.json"),
]),
dict(name="Mirror i migracje", files=[
    ("Bundle mirror (skrypt)", "policies/jdg/bundles/bundle.sh"),
    ("Manifest bazowy mirror", "policies/jdg/bundles/base/manifest.json"),
    ("Overlay v2026 mirror", "policies/jdg/bundles/overlays/v2026/manifest.json"),
    ("Migracja RuleStore 001", "JDG/migrations/001_jdg_rule_store.sql"),
    ("Migracja 013 (tools/api/bundles)", "JDG/migrations/013_jdg_v18_tools_api_rulestore_bundles.sql"),
    ("Dokument rule lifecycle", "JDG/docs/RULE_LIFECYCLE.md"),
    ("Dokument control plane", "JDG/docs/CONTROL_PLANE_RULE_LIFECYCLE.md"),
]),
],
legal=[
"Ustawa o rachunkowości — art. 74–75: wersje reguł użyte przy księgowaniu muszą być archiwizowane (retencja).",
"Ordynacja podatkowa — art. 119a i 199a: kontrola zgodności wersji z prawem w momencie decyzji.",
"Ustawa VAT — art. 109e: ewidencje i JPK zgodne z przepisami na dzień wystawienia (wersjonowanie reguł).",
"eIDAS (UE 910/2014) — podpisy artefaktów i pieczęcie elektroniczne (kontekst integralności bundle).",
"RODO — art. 32: integralność i dostępność (kontrola wdrożeń, rollback, DR).",
"Ustawa o ZUS — terminy składek: deploy nie może przeciąć ścieżki płatności (okno wdrożenia).",
"Rozporządzenie MF o JPK — schematy wersjonowane: bundle musi deklarować obsługiwane schematy.",
"ISAP — obowiązek stosowania tekstu obowiązującego na datę zdarzenia (temporalność bundle).",
],
innovations=[
("Deterministic build + attestation", "build z checksumą i attestation (SLSA-style): kto zbudował, z jakiego commit, które bramki przepuściły."),
("Canary z decision diff", "canary porównuje werdykty canary vs produkcja na próbce realnych inputów (z anonimizacją); rozjazd = auto-hold."),
("Auto-rollback z powodem", "regresja (golden replay, latencja, NEEDS_ADVICE spike) → automatyczny rollback + raport z powodem + rejestr."),
("Blue-green dla reguł", "dwie pełne wersje bundle równolegle; przełączenie atomowe; stara wersja żyje do zamknięcia miesiąca (odtwarzalność)."),
("Worm archive wersji", "każda wersja bundle archiwizowana WORM (P43) — dowód „jak liczyliśmy 3 lata temu” bez błędów odtwarzania."),
("Deployment window", "okna wdrożeniowe wyłączone w okresach krytycznych (deklaracje VAT/PIT, ZUS) — kalendarz (P25) jako źródło blokad."),
("Bundle signature verification", "OPA ładuje wyłącznie podpisane bundle (weryfikacja przy load); unsigned = odrzucenie (fail-closed)."),
("Overlay versioning", "overlay v2026 jako pierwsza klasa: deklaracja zakresu (akty, daty), walidacja kolizji z bazą, wygasanie."),
("Post-deploy certification", "automatyczny certyfikat po każdym deploy (wyniki canary, golden replay, SLO) — do rejestru wdrożeń."),
("Infrastructure as legal record", "deployments.json jako artefakt prawny (kto wdrożył jaką wersję kiedy) z podpisem i WORM."),
("Shadow traffic evaluation", "nowa wersja bundle ewaluowana na strumieniu realnych decyzji (shadow) przez 24h przed canary."),
("Release notes auto-generated", "changelog z diffów reguł (progi, daty, stawki) generowany automatycznie — przedsiębiorca widzi co się zmieniło."),
],
in_contracts=[
"Standard narzędzia transformującego z P36 — budowanie bundle kończy się walidacją (L1–L5) i golden replay.",
"Katalog metryk z P37 — decyzja canary/awans oparta o SLO.",
],
out_contracts=[
"KONTRAKT DEPLOY (canary, awans, rollback, okna) — wiąże P39 (CI) i P43 (security/DR).",
"Format attestation bundle — wejście do P43 i P44 (certyfikacja finalna).",
"Zasady okien wdrożeniowych (kalendarz) — wejście do P25 i P38/P39 workflow.",
],
acceptance_extra=[
"Cykl deploy przedstawiony jako diagram (build → sign → canary → promote → monitor → rollback) z punktami walidacji.",
"Rollback przetestowany w projekcie (gra wojenna) — opis procedury i zmierzony czas (albo status nieprzetestowane).",
]),
dict(code="P39", slug="TESTY_CI", title="TESTY I CI — NATYWNE REGO, PYTEST, GOLDEN, FUZZ I BRAMKI BLOKUJĄCE",
role="architektem CI/CD dla systemów krytycznych z regułami Rego, specjalistą od strategii testowania (unit/property/fuzz/golden/temporal)",
expertise="native Rego tests, pytest, property-based testing, fuzzing, granice groszowe, testy temporalne, bramki merge",
mission=[
"Przeanalizuj warstwę testową: testy natywne Rego w pakietach, pytest (87 plików w JDG/tests), testy bramek v3 (P29), testy etapów (P31), golden (P10). Oceń piramidę testów: czy testuje się TO CO KRYTYCZNE (granice groszowe, day-0 nowelizacji, brakujące pola, waluty), czy tylko happy path? Zidentyfikuj testy zawsze-zielone, zduplikowane, zależne od kolejności i bez asercji negatywnych.",
"Zaprojektuj kompletną strategię: L1 unit rego (per reguła, granice), L2 integracyjne (domeny łączone), L3 kontraktowe (werdykt 25-polowy, certyfikat), L4 golden (przeszłość nie zmienia decyzji), L5 temporal (day-0/day+1), L6 fuzz/property (niezmienniki fail-closed), L7 wydajnościowe (benchmark). Każdy poziom: gdzie uruchamiany (PR/nightly/weekly), jaki próg, co blokuje merge. Przeprować głęboką analizę: które ryzyka księgowe są dziś nietestowane.",
],
subparts=[
dict(name="Testy natywne Rego i granice",
goal="jakość testów w pakietach rego",
questions=[
"Które pakiety nie mają testów natywnych (luka) — lista z planem uzupełnienia?",
"Czy testy pokrywają granice groszowe (0,00/0,01), waluty, zaokrąglenia i negatywne kwoty?",
"Czy testy mają asercje negatywne (brak pola → NEEDS_ADVICE) czy tylko pozytywne?",
"Czy testy rego uruchamiają się w CI przy każdym PR (workflow jdg-quality.yml)?",
]),
dict(name="Testy Python i piramida",
goal="pytest jako warstwa integracyjna",
questions=[
"Które z 87 testów pytest dublują testy natywne rego (koszt bez wartości)?",
"Czy testy są deterministyczne (brak flaków: kolejność, czas, sieć) — jak to mierzyć?",
"Czy testy kontraktowe (werdykt, certyfikat) pilnują schema wersjonowanej (breaking = BLOCKER)?",
"Czy split_micro_tests dzieli zgodnie z granicami domen (spójne raportowanie)?",
]),
dict(name="Testy temporalne i golden",
goal="przeszłość niezmienna, przejścia dat",
questions=[
"Czy każdy akt prawny w Sekcji 8 każdej części ma test day-1/day-0/day+1 (przełączenie)?",
"Czy golden verdicts (P10) uruchamiają się przy każdym PR (regresja decyzji = BLOCKER)?",
"Czy time-travel (P05) jest testowany na danych historycznych (odtwarzalność deklaracji)?",
"Czy testy temporalne generowane są automatycznie z tabeli aktów (P36)?",
]),
dict(name="Fuzz, property i wydajność",
goal="niezmienniki i regresja wydajności",
questions=[
"Czy property-based testy pilnują niezmienników (suma podatków ≥ 0, waluty deterministyczne)?",
"Czy fuzzing mutuje input i data (chaos P33) z asercją fail-closed?",
"Czy benchmarki (P37) są w CI z progiem regresji blokującym?",
"Jak raportować pokrycie prawne (akty→reguły→testy) w CI jako metrykę trendu?",
]),
],
file_groups=[
dict(name="Workflow CI i testy rdzenia", files=[
    ("Workflow jakości JDG", "JDG/.github/workflows/jdg-quality.yml"),
    ("Test rego rdzenia", "JDG/tests/jdg_rules_test.rego"),
    ("Test regresji P26", "JDG/tests/p26_regression_test.rego"),
    ("Test kontraktu enterprise", "JDG/tests/test_enterprise_operating_contract.py"),
    ("Test kontrol temporalnych", "JDG/tests/test_core_guards_temporal_thresholds.py"),
    ("Test pipeline podatkowy", "JDG/tests/test_tax_pipeline.py"),
    ("Test reguł podatkowych", "JDG/tests/test_tax_rules.py"),
    ("Test audytu podatkowy", "JDG/tests/test_tax_audit.py"),
]),
dict(name="Testy bramek i etapów", files=[
    ("Test bramki kampanii v3", "JDG/tests/test_compliance_v3_12.py"),
    ("Test cross-border v3", "JDG/tests/test_crossborder_v3_08.py"),
    ("Test PCC v3", "JDG/tests/test_pcc_v3_10.py"),
    ("Test ryczałtu v3", "JDG/tests/test_ryczalt_v3_09.py"),
    ("Test KSeF v3", "JDG/tests/test_ksef_jpk_v3_11.py"),
    ("Test bramek jakości v3", "JDG/tests/test_micro_quality_v3_13.py"),
    ("Test red team etap27", "JDG/tests/test_cross_domain_red_team_etap27_audit.py"),
    ("Test certyfikacji etap28", "JDG/tests/test_final_certification_etap28_audit.py"),
]),
dict(name="Testy domenowe wybrane", files=[
    ("Test VAT enterprise", "JDG/tests/test_vat_enterprise.py"),
    ("Test PCC/akcyza enterprise", "JDG/tests/test_pcc_excise_enterprise.py"),
    ("Test KKS enterprise", "JDG/tests/test_kks_enterprise.py"),
    ("Test cross-border enterprise", "JDG/tests/test_crossborder_enterprise.py"),
    ("Test RODO enterprise", "JDG/tests/test_rodo_enterprise.py"),
    ("Test AML enterprise", "JDG/tests/test_aml_enterprise.py"),
    ("Test BDO enterprise", "JDG/tests/test_bdo_enterprise.py"),
    ("Test hyper plan45", "JDG/tests/test_hyper_plan45_enterprise.py"),
]),
dict(name="Dokumenty strategii testowej", files=[
    ("Testy Rego i CI (dokument)", "JDG/docs/TESTY_REGO_CI_P23.md"),
    ("Developer guide", "JDG/docs/DEVELOPER_GUIDE.md"),
    ("OPA Rego developer guide", "JDG/docs/OPA_REGO_DEVELOPER_GUIDE.md"),
    ("FAQ", "JDG/docs/FAQ.md"),
    ("Bramka pokrycia testów", "JDG/tools/test_coverage_gate.py"),
    ("Auditor CI rego", "JDG/tools/test_rego_ci_auditor.py"),
    ("Plan pokrycia 95%", "JDG/tools/coverage_95_plan.py"),
    ("Raport pokrycia", "JDG/COVERAGE_REPORT.md"),
]),
],
legal=[
"Ordynacja podatkowa — art. 119a: testy GAAR jako dowód defensywności (klauzula nie złapie uczciwych).",
"Ustawa VAT — art. 108 (nieprawidłowa stawka): testy graniczne stawek minimalizują sankcje.",
"Ustawa o PIT — art. 45 ust. 5a–5b (interpretacje, CLZ): testy zgodności z interpretacjami MF.",
"Ustawa o ZUS — ulgi i 30-krotność: testy graniczne przejść między ulgami.",
"Ustawa o rachunkowości — art. 4 ust. 1: testy jako dowód rzetelności wyliczeń.",
"KKS — art. 56: testy fail-closed jako redukcja ryzyka czynu zabronionego.",
"Rozporządzenie o JPK — schematy: testy zgodności wersji schematów.",
"ISAP — testy temporalne jako implementacja zasady lex retro non agit (prawo na datę zdarzenia).",
],
innovations=[
("Test matrix from acts", "generator (P36) tworzy matrycę testów: akt × artykuł × granica (grosze/data/waluta) → przypadki; pokrycie matrycy = metryka CI."),
("Golden replay as PR gate", "golden verdicts uruchamiane przy każdym PR; jakakolwiek regresja decyzji = BLOCKER z diffem."),
("Temporal pair tests", "para testów (dzień przed/po przełączeniu) generowana automatycznie z valid_from/valid_to (P05)."),
("Negative-first testing", "konwencja: każdy test pozytywny musi mieć parę negatywną (brak pola → NEEDS_ADVICE); lint wymusza."),
("Property invariants pack", "biblioteka niezmienników (suma składek ≥ 0, VAT ∈ {stawki}, waluta nie Zmienia się mid-transaction) używana przez property/fuzz."),
("Mutation testing rego", "automatyczne mutacje reguł (P29) w nightly; czułość suite'a jako metryka trendu."),
("Flake quarantine", "test flakowy trafia do kwarantanny (osobny job) z terminem naprawy; zero trwałych flaków na ścieżce merge."),
("Contract version pinning", "testy kontraktowe pinują wersję schematu werdyktu; breaking change wymaga jawnego PR migracyjnego."),
("Coverage by legal act", "raport CI: pokrycie per akt prawny (nie per plik) — trend w P37, próg w bramce."),
("Performance budget CI", "benchmark eval na referencyjnym input; regresja >10% p95 = BLOCKER."),
("Seed-replay determinism", "każdy test z losowością zapisuje seed; CI replays po awarii 1:1."),
("Test impact map", "mapa zmiana_pliku → dotknięte testy (z P02 routing) — przyspieszenie PR (tylko istotne testy) bez utraty bezpieczeństwa."),
],
in_contracts=[
"Sieć walidacji z P34 — testy jako L-walidacji w CI; wspólne raporty JSON.",
"Katalog metryk z P37 — progi testowe/benchmarkowe jako SLO.",
],
out_contracts=[
"STRATEGIA TESTOWA (poziomy L1–L7, progi, co blokuje merge) — wiąże P29 (bramki), P43 (security tests) i P44.",
"Test matrix from acts (format, status pokrycia) — wejście do P44 (certyfikacja definicji sukcesu).",
"Konwencja kwarantanny flaków — wiąże P36 (generatory testów) i P41.",
],
acceptance_extra=[
"Piramida testów przedstawiona jako tabela: poziom → zakres → gdzie uruchamiany → próg → co blokuje.",
"Lista testów zawsze-zielonych (fasad) z dowodem i planem naprawy (min. 5 przykładów).",
]),
dict(code="P40", slug="API_DANE_UI", title="API, DANE I UI — ORKIESTRATOR DLA PRZEDSIĘBIORCY I KSIĘGOWEGO",
role="architektem API i doświadczenia użytkownika dla systemu księgowego klasy enterprise (developerzy, operatorzy, przedsiębiorcy)",
expertise="OpenAPI, kontrakty danych, idempotencja API, UI pewności, eksplikacja decyzji, RBAC",
mission=[
"Przeanalizuj warstwę API/UI: api/openapi.yaml, ORCHESTRATOR_DATA_CONTRACT.md, API_REFERENCJA.md, api.md, dashboardy (P35), kalendarz (P25). Oceń: czy API odpowiada przedsiębiorcy i księgowemu (decyzja → wyjaśnienie → działanie), czy jest spójne z kontraktem werdyktu (P03) i certyfikatem (P11), czy ma idempotencję, wersjonowanie, RBAC i limitowanie. API fortecy ma być proste jak kliknięcie księgowego: „pokaż mi decyzję i jej dowód”.",
"Zaprojektuj API idealne: /evaluate (decyzja z certyfikatem), /explain (łańcuch dowodów decyzji), /advice (kolejka NEEDS_ADVICE z triage), /calendar (terminy), /documents (pipeline dokumentów z P32), /rules (rejestr reguł dla człowieka). Każdy endpoint: schema, idempotency key, rate limit, RBAC, audyt (kto pytał i co dostał). UI: ekran decyzji (pewność, powód, działanie), ekran pewności domeny, ekran kalendarza, ekran pojedynczej faktury end-to-end.",
],
subparts=[
dict(name="Kontrakt API i wersjonowanie",
goal="spójność openapi z kontraktem werdyktu",
questions=[
"Czy openapi.yaml pokrywa wszystkie ścieżki decyzyjne (evaluate, explain, advice) czy tylko część?",
"Czy odpowiedź /evaluate zawiera pełny Decision Certificate (P11) czy skrócony (luka audytowa)?",
"Czy API jest wersjonowane (breaking change jak zarządzane) i czy schema werdyktu jest pinowana?",
"Czy istnieje idempotency key dla operacji zmieniających stan (booking, deklaracja)?",
]),
dict(name="RBAC, audyt i limity",
goal="bezpieczeństwo i rozliczalność API",
questions=[
"Czy role (przedsiębiorca, księgowy, audytor, admin) mają różne widoki danych (RODO minimalizacja)?",
"Czy każde wywołanie API jest logowane (kto, kiedy, co, jaki wynik) — WORM (P43)?",
"Czy rate limiting chroni silnik (eval kosztowny przy dużym bundle) i dane (exfiltration)?",
"Czy dostęp do NEEDS_ADVICE jest kontrolowany (kto może zatwierdzić decyzję — 4-eyes z P32)?",
]),
dict(name="Eksplikacja i UI pewności",
goal="człowiek rozumie decyzję i może działać",
questions=[
"Czy /explain pokazuje łańcuch: fakt → reguła → przepis → decyzja (z linkami do ISAP)?",
"Czy UI pewności (P35) pozwala operatorowi filtrować domeny i typy decyzji?",
"Czy ekran faktury pokazuje end-to-end (dokument → ewidencja → deklaracja → płatność → archiwum)?",
"Czy UI ma tryb audytora (tylko odczyt, pełne dowody, eksport)?",
]),
dict(name="Integracje zewnętrzne",
goal="KSeF, banki, ISAP, e-mail",
questions=[
"Czy integracja KSeF (P32) ma kontrakt wersjonowany (schematy FA(2)/FA(3)) i testy kontraktowe?",
"Czy feed bankowy ma odporność na duplikaty i kolejność (idempotencja ingest)?",
"Czy ISAP crawler (P34) ma API wewnętrzne z cache i świeżością (P37)?",
"Czy API deklaruje SLO (latencja, dostępność) i degradację (tryb offline, kolejki P32)?",
]),
],
file_groups=[
dict(name="Specyfikacje i kontrakty API", files=[
    ("Spec OpenAPI", "JDG/api/openapi.yaml"),
    ("Kontrakt danych orkiestratora", "JDG/docs/ORCHESTRATOR_DATA_CONTRACT.md"),
    ("API referencja", "JDG/docs/API_REFERENCJA.md"),
    ("Dokument api", "JDG/docs/api.md"),
    ("Generator dokumentacji API", "JDG/tools/api_doc_generator.py"),
    ("Serwis certyfikatów", "JDG/tools/certificate_service.py"),
    ("Stan control plane", "JDG/bundles/control_plane_state.json"),
    ("Spójność specyfikacji API", "JDG/bundles/api_spec_consistency.json"),
]),
dict(name="UI, dashboardy i kalendarz", files=[
    ("Dashboard enterprise", "JDG/tools/enterprise_dashboard.py"),
    ("Dashboard pewności", "JDG/tools/confidence_dashboard.py"),
    ("Dashboard dryfu", "JDG/tools/drift_dashboard.py"),
    ("Dokument dashboard pewności", "JDG/docs/PEWNOSC_DASHBOARD.md"),
    ("Kalendarz zbiorczy (P25)", "JDG/tools/zus_calendar.py"),
    ("Podręcznik użytkownika", "JDG/docs/PODRECZNIK_UZYTKOWNIKA.md"),
    ("FAQ", "JDG/docs/FAQ.md"),
]),
dict(name="Testy API", files=[
    ("Test risk API", "JDG/tests/test_risk_api.py"),
    ("Test orkiestrator kontraktu", "JDG/tests/test_orchestrator_data_contract.py"),
    ("Test control plane", "JDG/tests/test_p01_control_plane.py"),
    ("Test API/UI quality v3", "JDG/tests/test_api_ui_quality_v3_19.py"),
    ("Test API docs", "JDG/tools/api_doc_generator.py"),
]),
],
legal=[
"RODO — art. 15–22 (prawa podmiotowe: dostęp, wyjaśnienie decyzji zautomatyzowanej — API /explain).",
"RODO — art. 5 (minimalizacja: RBAC ogranicza dane do roli), art. 32 (bezpieczeństwo: rate limiting, audyt).",
"eIDAS — podpisy i pieczęcie na odpowiedziach API (integralność dowodu dla przedsiębiorcy).",
"Ustawa VAT — art. 106b (faktury KSeF: API zwraca zgodność ze schematem).",
"Ustawa o rachunkowości — art. 4 ust. 1 (sprawdzalność: eksport pełnego dowodu decyzji).",
"Ustawa o ZUS — API kalendarza płatności zgodne z terminami ustawowymi.",
"Prawo przedsiębiorców — art. 15f (informacja o terminach: UI kalendarza).",
"AI Act — przejrzystość dla użytkownika przy decyzjach z udziałem AI (oznaczenie w odpowiedzi API).",
],
innovations=[
("Decision-first API", "konwencja: każda odpowiedź decyzyjna zawiera Decision Certificate (nie skrót) — front-end i audytor korzystają z tego samego dowodu."),
("Explain chain", "/explain zwraca graf (Mermaid/JSON): fakt → reguła(rule_id) → przepis(art. z ISAP) → decyzja — z linkami do źródeł."),
("Idempotent writes", "wszystkie operacje zapisu z Idempotency-Key; retry klienta nie duplikuje księgowań (P32)."),
("RBAC + data minimization", "role mapowane na pola werdyktu (przedsiębiorca nie widzi metryk wewnętrznych; audytor widzi wszystko, tylko odczyt)."),
("API audit WORM", "każde wywołanie (kto, co, kiedy, wynik checksum) zapisane WORM — rozliczalność wywołań (RODO art. 5.2)."),
("Degradation ladder", "plan degradacji: pełny → tylko cache → tryb offline (kolejki P32) → read-only; deklarowany w nagłówku odpowiedzi."),
("Subscription webhook", "webhook na zmiany (nowa deklaracja, NEEDS_ADVICE, terminy) z podpisem (HMAC) i retry idempotentnym."),
("Playground dla księgowego", "endpoint sandbox: przetestuj regułę na fikcyjnym input (bez zapisu) — szkolenie i debugowanie (bez danych osobowych)."),
("Schema-first SDK", "generatory klientów z openapi (Python/TS) — integracje bez ręcznego mapowania pól."),
("Freshness header", "każda odpowiedź z X-Legal-Freshness (data ostatniej weryfikacji ISAP dla domeny) — przejrzystość ryzyka."),
("UI decision screen", "ekran: decyzja, pewność (%), powód w języku człowieka, podstawy prawne z linkami, akcje (zaakceptuj/skieruj do doradcy)."),
("Export evidence pack", "jeden klik: eksport całego dowodu decyzji (certyfikat, input, reguły, bundle hash, podpisy) jako pakiet PDF/ZIP."),
],
in_contracts=[
"Kontrakt werdyktu z P03 i certyfikatu z P11 — API zwraca dokładnie te struktury (bez prywatnych schematów).",
"Kontrakt pipeline z P32 — /documents odzwierciedla etapy pipeline'u (te same statusy).",
],
out_contracts=[
"KONTRAKT API (endpointy, schematy, RBAC, idempotencja) — wiąże P43 (security), P41 (dokumentacja) i P44.",
"Konwencja eksplikacji (/explain) — wejście do P11 (certyfikat) i P41 (podręcznik).",
"Degradation ladder (tryby) — wejście do P38 (deploy) i P43 (DR).",
],
acceptance_extra=[
"Każdy endpoint ma wiersz: ścieżka → metoda → schema → RBAC → idempotencja → audyt → test.",
"Ekran decyzji przedstawiony jako mockup tekstowy (layout + elementy + źródła danych).",
]),
dict(code="P41", slug="DOKUMENTACJA", title="DOKUMENTACJA ENTERPRISE — JEDNO ŹRÓDŁO PRAWDY, SPÓJNOŚĆ Z KODEM",
role="architektem dokumentacji technicznej (docs-as-code) dla systemów regulowanych z wymogami audytowymi",
expertise="spójność dokument–kod, generowanie dokumentacji, podręczniki rolowe, glosariusze, wymogi audytowe",
mission=[
"Przeanalizuj 65 dokumentów w JDG/docs (architektura, domeny, kampanie, rejestry) pod kątem: aktualności (liczby zgodne z realnym stanem — P34 doc_consistency_validator), spójności między dokumentami (ARCHITEKTURA.md vs ARCHITECTURE.md vs dokumenty święte), kompletności rolowej (developer, operator, auditor, przedsiębiorca). Dokumentacja fortecy to jej dowód prawny: „system działa tak, jak napisano” musi być prawdą weryfikowalną.",
"Zaprojektuj docs-as-code: dokument przykonsypowany do artefaktu (packiet, narzędzie, endpoint) — zmiana kodu bez zmiany dokumentacji nie przechodzi bramki docs (P29). Rozdziel warstwy: wizja (dokumenty święte), architektura, referencja (API/reguły), operacje (runbooki), użytkownik (podręcznik). Zdefiniuj glosariusz nadrzędny (SLOWNIK_REFERENCJI_PRAWNYCH, LEGAL_REFERENCE_ACTS) jako źródło terminów — bez definicji lokalnych duplikujących.",
],
subparts=[
dict(name="Spójność i aktualność dokumentów",
goal="dokument = prawda weryfikowalna",
questions=[
"Które dokumenty podają liczby (reguły, pliki, rule_id) sprzeczne z MANIFEST i realnym stanem (lista par)?",
"Czy ARCHITEKTURA.md (PL) i ARCHITECTURE.md (EN) są zgodne treściowo (diff semantyczny)?",
"Czy dokumenty domen (VAT_MACRO_P03, ZUS_MACRO_P07...) opisują obecne pakiety czy historię (dryf)?",
"Czy dokumenty święte mają zapewnioną nienaruszalność (zmiana tylko przez decyzję człowieka z ADR)?",
]),
dict(name="Warstwy i role dokumentacji",
goal="kompletność dla developer/operator/audytor/przedsiębiorca",
questions=[
"Czy DEVELOPER_GUIDE i OPA_REGO_DEVELOPER_GUIDE pokrywają pełny cykl (nowa reguła → test → deploy)?",
"Czy istnieje runbook dla każdego alarmu (P37) i procedury awaryjne (rollback P38)?",
"Czy podręcznik użytkownika wyjaśnia NEEDS_ADVICE w języku przedsiębiorcy (nie inżynierskim)?",
"Czy jest przewodnik audytora (jak zweryfikować zgodność systemu z prawem — ścieżki dowodowe)?",
]),
dict(name="Glosariusz i rejestry prawne",
goal="jedne definicje, jedno źródło terminów",
questions=[
"Czy SLOWNIK_REFERENCJI_PRAWNYCH pokrywa wszystkie terminy używane w regułach i dokumentach?",
"Czy LEGAL_REFERENCE_ACTS i LEGAL_SOURCE_REGISTRY są spójne (ten sam akt = ten sam identyfikator)?",
"Czy definicje terminów mają odwołania do ISAP (źródło prawne) czy tylko opisy?",
"Jak unikać duplikatów definicji (termin w 3 dokumentach z 3 opisami — luka)?",
]),
dict(name="Dokumentacja jako dowód",
goal="archiwizacja, wersjonowanie, eksport audytowy",
questions=[
"Czy dokumentacja jest wersjonowana z kodem (ten commit = ta dokumentacja)?",
"Czy istnieje eksport audytowy (pakiet dokumentów + checksumy) dla kontroli skarbowej?",
"Czy changelog systemu jest generowany (P30 rejestr wdrożeń) czy ręczny (dryf)?",
"Czy dokumentacja archiwizowana jest WORM (odtwarzalność stanu dokumentacji z przeszłości)?",
]),
],
file_groups=[
dict(name="Dokumenty święte i architektura", files=[
    ("Dokument święty 1 (target)", "JDG/docs/ARCHITEKTURA_OPA_ENTERPRISE_TARGET.md"),
    ("Dokument święty 2 (wizja V2)", "JDG/docs/WIZJA_OPA_ENTERPRISE_V2.md"),
    ("Architektura (PL)", "JDG/docs/ARCHITEKTURA.md"),
    ("Architecture (EN)", "JDG/docs/ARCHITECTURE.md"),
    ("Struktura projektu", "JDG/docs/STRUKTURA_PROJEKTU.md"),
    ("Manifest 2.0", "JDG/docs/MANIFEST_2_0.md"),
    ("Unified plan", "JDG/docs/UNIFIED_PLAN.md"),
    ("Analiza stanu OPA", "JDG/docs/ANALIZA_STANU_OPA_JAKO_SYSTEM.md"),
]),
dict(name="Guides i operacje", files=[
    ("Developer guide", "JDG/docs/DEVELOPER_GUIDE.md"),
    ("OPA Rego developer guide", "JDG/docs/OPA_REGO_DEVELOPER_GUIDE.md"),
    ("Podręcznik użytkownika", "JDG/docs/PODRECZNIK_UZYTKOWNIKA.md"),
    ("API referencja", "JDG/docs/API_REFERENCJA.md"),
    ("FAQ", "JDG/docs/FAQ.md"),
    ("Dokument narzędzi walidacji", "JDG/docs/NARZEDZIA_WALIDACJI_P22.md"),
    ("Katalog narzędzi", "JDG/docs/KATALOG_NARZEDZI.md"),
    ("Katalog reguł", "JDG/docs/KATALOG_REGUL.md"),
]),
dict(name="Glosariusz i rejestry", files=[
    ("Słownik referencji prawnych", "JDG/docs/SLOWNIK_REFERENCJI_PRAWNYCH.md"),
    ("Legal reference acts", "JDG/docs/LEGAL_REFERENCE_ACTS.md"),
    ("Rejestr źródeł prawnych", "JDG/docs/LEGAL_SOURCE_REGISTRY.md"),
    ("Kalendarz zmian prawnych", "JDG/docs/KALENDARZ_ZMIAN_PRAWNYCH.md"),
    ("Zgodność prawna", "JDG/docs/ZGODNOSC_PRAWNA.md"),
    ("Zgodność dokumenty księgowe", "JDG/docs/ZGODNOSC_DOKUMENTY_KSIEGOWE.md"),
    ("Dokument źródeł prawnych (Bbb)", "JDG/docs/Bbb"),
    ("Audit podstaw prawnych", "JDG/docs/AUDYT_PODSTAW_PRAWNYCH.md"),
]),
],
legal=[
"Ustawa o rachunkowości — art. 4 ust. 1–3: dokumentacja jako element sprawdzalności i rzetelności.",
"Ordynacja podatkowa — art. 193a: dokumentacja procesu wspiera weryfikację (dokumenty = dowód staranności).",
"RODO — art. 24 (rozliczalność), art. 30 (rejestr czynności: dokumentacja systemu).",
"AI Act — dokumentacja techniczna systemów (art. 11) jako wymóg regulacyjny.",
"Ustawa VAT/PIT/ZUS — cytowania w dokumentacji zgodne z ISAP (kolejna linia obrony przed fikcją prawną).",
"KSeF — dokumentacja integracji (schematy, wersje) jako element zgodności.",
"eIDAS — eksport audytowy z pieczęcią (integralność pakietu dokumentów).",
"Ustawa o ZUS — dokumentacja ulg i cykli (start, mały ZUS+) dla kontroli ZUS.",
],
innovations=[
("Doc-code binding", "każdy dokument ma sekcję front-matter z listą artefaktów, których opisuje; bramka docs sprawdza istnienie i świeżość (git diff)."),
("Single source of truth registers", "liczby (ile reguł, plików) generowane z repo do dokumentu (snippet) — zero ręcznych liczb (wykrywalnych przez P34)."),
("Role-based doc maps", "mapy czytania per rola (developer: ścieżka A→B→C; audytor: ścieżka dowodowa) — onboarding w minuty."),
("Semantic diff PL/EN", "narzędzie porównuje ARCHITEKTURA.md vs ARCHITECTURE.md (przekład semantyczny, nie słowo w słowo) — drift = alarm."),
("Glossary enforcement", "lint: termin z glosariusza użyty inaczej niż zdefiniowany = BLOCKER (konsekwencja językowa)."),
("Audit export pack", "jedno polecenie: pakiet (dokumenty, rejestry, checksumy, pieczęć) dla kontroli — gotowy w minuty."),
("Runbook coverage check", "bramka: każdy alarm (P37) musi mieć runbook; dokumentacja i obserwowalność spięte kontraktem."),
("Changelog automation", "changelog generowany z rejestru wdrożeń (P30) i migracji (P36) — historia systemu bez ręcznej pracy."),
("Doc freshness stamps", "każdy dokument ma „ostatnia weryfikacja”: narzędzie odświeża daty po walidacji (przejrzystość wieku informacji)."),
("Documentation testing", "przykłady w dokumentacji (curl, rego) testowane w CI (example-as-test) — zero zepsutych przykładów."),
("Auditor mode", "specjalny widok dokumentacji: pełne ścieżki dowodowe (jak sprawdzić każdą deklarację) — audyt szybszy."),
("Legacy doc retirement", "proces wycofywania przestarzałych dokumentów (status: CURRENT/ARCHIVED/SUPERSEDED w front-matter) — zero kanibalizmu wersji."),
],
in_contracts=[
"Kanon artefaktów z P00 — dokumentacja opisuje realny stan (mapa kanoniczna jako referencja).",
"Bramka docs z P29 — docs-as-code wymuszany w CI.",
],
out_contracts=[
"STRUKTURA DOKUMENTACJI (warstwy, mapy ról, glosariusz) — wiąże P40 (API docs) i P44.",
"Konwencja front-matter i statusów dokumentów — wejście do P36 (generatory) i P29.",
"Eksport audytowy (format pakietu) — wejście do P43 i P44.",
],
acceptance_extra=[
"Mapa dokumentacji (warstwy × role) przedstawiona jako tabela z identyfikacją luk rolowych.",
"Lista dokumentów z dryfem liczb (dokument → liczba → rzeczywistość) — min. 5 przykładów z dowodem.",
]),
dict(code="P42", slug="ENTERPRISE_RESZTA", title="ENTERPRISE — RESZTA LUK SYSTEMOWYCH: HEALTH TIERS, SMT, WORM, ZALEŻNOŚCI",
role="głównym inżynierem ds. niezawodności systemów regulowanych, domykającym luki architektury klasy enterprise",
expertise="health tiers, formal verification (SMT/Z3), WORM storage, harmonizacja domen, przegląd luk systemowych",
mission=[
"To część domykająca: przeanalizuj wszystko, co nie było objęte poprzednimi częściami, a deklaruje klasę enterprise: health_tier_engine/health_tier_recalculator (klasyfikacja zdrowia reguł), smt_z3_verification (dowody formalne), worm_storage (niezmienny archiw), str_generator (STR), rule_provenance_dna (DNA reguł), digital_twin/chaos (P33 wskazał), coverage_unifier (unifikacja pokrycia), ryczalt_zus_health_harmonizer (harmonizacja między domenami). Oceń realność vs fasada i projektuj domknięcia.",
"Wykaż się wykrywaniem luk systemowych NA WŁASNY RACHUNEK: przegląd katalogów (tools, bundles, rules, migrations) pod kątem elementów nieprzypisanych do żadnej części V3 — każdy taki element ma decyzję (przypisz do istniejącej części / nowa innowacja / oznacz do usunięcia). Zero martwych artefaktów w fortecy. Przeprować głęboką analizę zależności: które elementy zależą od siebie (graf) i gdzie usunięcie/awaria jednego kaskaduje.",
],
subparts=[
dict(name="Health tiers i harmonizacja domen",
goal="klasyfikacja zdrowia reguł i spójność między domenami",
questions=[
"Czy health_tier_engine ma realne kryteria (testy, legal basis, dryf) czy tylko etykiety?",
"Czy przeliczanie tierów jest automatyczne (CI/nightly) czy ręczne (dryf)?",
"Czy ryczalt_zus_health_harmonizer domyka realne interakcje (ryczałt wpływa na podstawę ZUS)?",
"Czy health_reconciliation_micro wykrywa rozjazdy micro vs macro ZUS?",
]),
dict(name="Dowody formalne i DNA reguł",
goal="SMT/Z3 i provenance",
questions=[
"Czy smt_z3_verification dowodzi czegoś realnego (równoważność reguł, niezmienniki) czy jest fasadą?",
"Czy rule_provenance_dna daje zapytywalny graf (akt→reguła→test) czy tylko etykiety?",
"Czy DNA reguł jest wykorzystywane przy ocenie wpływu zmiany (impact analysis P34)?",
"Czy STR generator produkuje czytelne ścieżki (STR) do rekonstrukcji błędów księgowych?",
]),
dict(name="WORM i integralność",
goal="niezmienniki archiwum",
questions=[
"Czy worm_storage daje realną niezmienność (hash chain, podpis, retencja) czy tylko nazwę?",
"Czy archiwizowane są: decyzje, certyfikaty, bundle, dokumentacja, logi API (P40)?",
"Czy istnieje test odtwarzalności z WORM (restore + weryfikacja checksum)?",
"Czy retencja jest zgodna z przepisami (podatkowa 5 lat, rachunkowa 5 lat — data liczenia)?",
]),
dict(name="Przegląd luk systemowych (self-scan)",
goal="zero martwych artefaktów",
questions=[
"Które pliki w tools/ i bundles/ nie są przypisane do żadnej części V3 (lista z decyzją)?",
"Które migracje (001–013) są martwe (kod nie używa tabel) — plan archiwizacji?",
"Które elementy mają cykliczne zależności (kaskada awarii) — jak przełamać cykle?",
"Co jeszcze brakuje fortecy enterprise (ruce, RBAC admin, multi-tenant, quota) — lista z priorytetami?",
]),
],
file_groups=[
dict(name="Narzędzia systemowe domykające", files=[
    ("Silnik tierów health", "JDG/tools/health_tier_engine.py"),
    ("Przeliczanie tierów", "JDG/tools/health_tier_recalculator.py"),
    ("Harmonizacja ryczałt-ZUS", "JDG/tools/ryczalt_zus_health_harmonizer.py"),
    ("Rekonsylacja health micro", "JDG/tools/health_reconciliation_micro.py"),
    ("Weryfikacja SMT/Z3", "JDG/tools/smt_z3_verification.py"),
    ("WORM storage", "JDG/tools/worm_storage.py"),
    ("Generator STR", "JDG/tools/str_generator.py"),
    ("DNA proweniencji reguł", "JDG/tools/rule_provenance_dna.py"),
    ("Unifier pokrycia", "JDG/tools/coverage_unifier.py"),
    ("Certification zero-defect", "JDG/tools/zero_defect_certification.py"),
]),
dict(name="Dane systemowe", files=[
    ("Kanon pokrycia (dane)", "JDG/bundles/coverage_canon.json"),
    ("Pustynie pokrycia", "JDG/bundles/coverage_deserts.json"),
    ("Graf prawny (zalążek LKG)", "JDG/bundles/legal_graph.json"),
    ("Rejestr certyfikatów decyzji", "JDG/bundles/decision_certificates.json"),
    ("Zdrowe wersje", "JDG/bundles/healthy_versions.json"),
    ("Test unifiera pokrycia", "JDG/tests/test_coverage_unifier.py"),
    ("Test infrastruktury control plane", "JDG/tests/test_control_plane_infrastructure.py"),
    ("Test infrastruktury legal twin", "JDG/tests/test_legal_twin_infrastructure.py"),
]),
dict(name="Rejestry i dokumenty domykające", files=[
    ("Rejestr reguł", "JDG/bundles/rule_registry.json"),
    ("Manifest bundle v2", "JDG/bundles/manifest_v2.json"),
    ("Pustynie pokrycia (dokument kanonu)", "JDG/docs/COVERAGE_CANON.md"),
    ("Legal Twin traceability", "JDG/docs/LEGAL_TWIN_TRACEABILITY.md"),
    ("Audit kompletny P24", "JDG/docs/AUDYT_KOMPLETNY_P24.md"),
    ("Remediacja podstaw prawnych P00", "JDG/docs/P00_REMEDIACJA_PODSTAW_PRAWNYCH.md"),
    ("Inwentaryzacja plików", "JDG/docs/INWENTARYZACJA_PLIKOW.md"),
    ("Katalog narzędzi", "JDG/docs/KATALOG_NARZEDZI.md"),
]),
],
legal=[
"Ustawa o rachunkowości — art. 74–75 (retencja 5 lat: WORM i liczenie terminów od końca roku obrotowego).",
"Ustawa VAT — art. 109 (ewidencje retencjonowane zgodnie z przepisami — WORM jako implementacja).",
"Ordynacja podatkowa — art. 86 §3 (obowiązek przechowywania dokumentów; kontekst archiwum).",
"Ustawa o PIT — art. 9a (rejestr VAT i dokumentacja 5 lat).",
"RODO — art. 5 ust. 1e (ograniczenie przechowywania: retencja WORM z datą wygaśnięcia).",
"RODO — art. 32 (integralność: hash chain WORM jako kontrola techniczna).",
"eIDAS — pieczęcie i podpisy na artefaktach archiwum (kontekst prawny WORM).",
"Ustawa o ZUS — dokumentacja składek (DR, RCA) w retencji (kontekst harmonizacji).",
],
innovations=[
("Health tier as data", "kryteria tierów (testy, legal basis, dryf, wiek) w YAML; engine oblicza, CI wymusza (dryf tierów = alarm)."),
("SMT proof pack", "zestaw dowodów formalnych dla krytycznych reguł (VAT stawki, PIT progi, ZUS 30-krotność): równoważność wersji, niezmienniki; dowody w CI."),
("WORM with hash chain", "bloki archiwum z hash chain i podpisem — manipulacja wykrywalna; test tamper-proof w CI (próba modyfikacji musi się nie powieść)."),
("Retention calculator", "automatyczne wyliczanie dat wygaśnięcia retencji (5 lat od końca roku obrotowego) per artefakt z listą do bezpiecznego usunięcia."),
("Provenance query API", "/provenance?rule_id=... zwraca pełne DNA (akt→nowela→art→reguła→test→bundle→certyfikat) — audyt w sekundy."),
("Coverage unifier contract", "unifikacja raportów pokrycia (plikowe, prawne, testowe) do jednego kanonu z wersjonowanym schematem (P37 konsumuje)."),
("Dependency graph health", "graf zależności artefaktów z detekcją cykli i punktów pojedynczej awarii (SPOF) — raport w CI."),
("Orphan artifact sweep", "automatyczny skan tools/bundles/migrations: artefakt bez właściciela-części → ticket do usunięcia/przypisania (zero martwych)."),
("System completeness register", "rejestr wymogów enterprise (RBAC, quota, multi-tenant, i18n, a11y) z statusem (jest/brak/plan) — prawdziwa luka widoczna."),
("STR-as-evidence", "STR (Structured Test Report/Ścieżka) włączony do certyfikatu decyzji przy awarii (rekonstrukcja bez wątpliwości)."),
("Cross-domain health contracts", "kontrakty zdrowia między domenami (ryczałt↔ZUS, VAT↔PKPiR): gdy domena A chora, B dostaje ostrzeżenie (propagacja ryzyka)."),
("Enterprise maturity ladder", "skala dojrzałości (L0-L5) z kryteriami testowalnymi — P44 certyfikuje poziom, nie deklarację."),
],
in_contracts=[
"Sieć walidacji z P34 i bramki z P29 — health tier i dowody SMT podłączone do raportów JSON.",
"Katalog metryk z P37 — tier i dojrzałość jako metryki monitorowane.",
],
out_contracts=[
"REJESTR KOMPLETNOŚCI SYSTEMOWEJ (luki, priorytety, plan) — wejście do P44 (certyfikacja) i P42-followup.",
"Kontrakt WORM (co archiwizujemy, retencja, test integralności) — wiąże P43 (security/DR) i P38.",
"Dependency graph (format + odczyt) — wejście do P38 (deploy: kolejność), P43 (DR: co krytyczne).",
],
acceptance_extra=[
"Lista elementów nieprzypisanych do części V3 z decyzją (przypisz/usuń/nowa innowacja) — zero pozycji bez decyzji.",
"SMT/Z3: konkretny dowód formalny zaprojektowany dla min. 1 krytycznej reguły (teza + narzędzie + kryterium).",
]),
dict(code="P43", slug="SECURITY_DR", title="BEZPIECZEŃSTWO, ODPORNOŚĆ I DR — FORTYFIKACJA OSTATECZNA",
role="architektem bezpieczeństwa (AppSec/SRE) systemów krytycznych finansowo, projektantem disaster recovery dla silnika reguł",
expertise="threat modeling, RBAC/sekrety, integralność (podpisy, WORM), BCP/DR, chaos engineering, ransomware defense",
mission=[
"Zbezpiecz fortecę: threat model silnika (kto może zmienić reguły? jak wykryć manipulację? co przy ransomware?), zarządzanie sekretami (klucze API KSeF/MF, podpisy bundle), kontrola dostępu (RBAC, 4-eyes, least privilege), integralność (podpisy P38, WORM P42, hash chain), zabezpieczenie pipeline'u CI (dostęp do repo, provenance buildów). Bezpieczeństwo fortecy = granice: kto, co, kiedy, z jakim dowodem.",
"Zaprojektuj DR: RTO/RDO dla silnika (decyzje księgowe nie mogą przestać płynąć), scenariusze (utrata bundle, korupcja RuleStore, awaria OPA, ransomware, insider), snapshoty (dr_snapshots) odtwarzalne w ci, chaos engineering (chaos_engineering, chaos_runner) jako ciągły test odporności, procedure paper-based (awaryjna księgowość ręczna) na czarną godzinę. Przeprować głęboką analizę: ataki prawne (próba wstrzyknięcia reguły przez PR) i techniczne (inject do input).",
],
subparts=[
dict(name="Threat model i kontrola dostępu",
goal="granice zaufania i uprawnień",
questions=[
"Czy istnieje threat model (dokument) dla silnika — kto/wąskie gardła/ataki?",
"Czy RBAC (P40) obejmuje też administrowanie regułami (kto może zmienić regułę produkcyjną)?",
"Czy 4-eyes jest egzekwowane technicznie (przykłady: deploy krytyczny, korekta duża) czy tylko proceduralnie?",
"Czy sekrety (klucze, podpisy) są w sejfie (nie w repo/env) z rotacją i audytem użycia?",
]),
dict(name="Integralność i anty-manipulacja",
goal="wykrywalność każdej manipulacji",
questions=[
"Czy bundle podpisany (P38) i weryfikowany przy load (fail-closed na podpis)?",
"Czy WORM (P42) z hash chain wykrywa tamper (test prób modyfikacji)?",
"Czy pipeline CI jest chroniony (chronione branche, wymagane review, provenance builds)?",
"Czy istnieje kanal zgłoszeń (whistleblower) i procedura reakcji na podejrzenie manipulacji regułami?",
]),
dict(name="DR i ciągłość",
goal="RTO/RDO, snapshoty, chaos",
questions=[
"Czy zdefiniowano RTO/RDO dla decyzji (ile może trwać przerwa) i czy są testowane?",
"Czy dr_snapshots są odtwarzane w CI (test restore), a nie tylko backupowane?",
"Czy chaos_engineering testuje realne scenariusze (awaria OPA, limit, corrupt input) z asercją fail-closed?",
"Czy istnieje procedura księgowości awaryjnej (ręcznej) na czas DR z późniejszą rekonsylacją?",
]),
dict(name="Odporność prawna i ransomware",
goal="najgorsze scenariusze",
questions=[
"Czy jest plan na ransomware (izolacja, odtwarzanie z WORM, raport do organów — RODO 72h)?",
"Czy reguły mają ścieżkę awaryjną (quarantine podejrzanych reguł bez pełnego rollback)?",
"Czy istnieje red team prawny (próba wniesienia błędnej reguły przez proces) — wyniki?",
"Czy DR obejmuje też dane zewnętrzne (KSeF outbox, banki) — jak utrzymać terminy (P25) przy awarii?",
]),
],
file_groups=[
dict(name="Narzędzia bezpieczeństwa", files=[
    ("Szyfrowanie post-quantum", "JDG/tools/quantum_safe_encryption.py"),
    ("Chaos engineering", "JDG/tools/chaos_engineering.py"),
    ("Chaos runner", "JDG/tools/chaos_runner.py"),
    ("Self-healing engine", "JDG/tools/self_healing_engine.py"),
    ("WORM storage", "JDG/tools/worm_storage.py"),
    ("Orkiestrator wdrożeń", "JDG/tools/deployment_orchestrator.py"),
    ("Serwis certyfikatów", "JDG/tools/certificate_service.py"),
    ("Skanner fraudu grafowego", "JDG/tools/fraud_graph_scanner.py"),
    ("Test strażnika semantycznego", "JDG/tests/test_semantic_guard.py"),
    ("Test silnika ryzyka", "JDG/tests/test_risk_guard.py"),
]),
dict(name="Dane DR i integralności", files=[
    ("Zrzuty DR (katalog)", "JDG/bundles/dr_snapshots"),
    ("Zdrowe wersje", "JDG/bundles/healthy_versions.json"),
    ("Rejestr wdrożeń", "JDG/bundles/deployments.json"),
    ("Katalog bundle", "JDG/bundles/bundle_catalog.json"),
    ("Stan control plane", "JDG/bundles/control_plane_state.json"),
    ("Dokument RODO/AML P16", "JDG/docs/RODO_AML_BEZPIECZENSTWO_P16.md"),
    ("Test AML", "JDG/tests/test_aml_enterprise.py"),
    ("Test RODO", "JDG/tests/test_rodo_enterprise.py"),
]),
dict(name="Kontekst zgodności", files=[
    ("RODO/AML/P16 (dokument)", "JDG/docs/RODO_AML_BEZPIECZENSTWO_P16.md"),
    ("Dokument zgodności prawnej", "JDG/docs/ZGODNOSC_PRAWNA.md"),
    ("Dokument zgodności księgowej", "JDG/docs/ZGODNOSC_DOKUMENTY_KSIEGOWE.md"),
    ("Prawa przedsiębiorców audyt", "JDG/docs/PRAWA_PRZEDSIEBIORCOW_AUDYT_R02.md"),
    ("Dokument święty 1 (target)", "JDG/docs/ARCHITEKTURA_OPA_ENTERPRISE_TARGET.md"),
    ("Dokument święty 2 (wizja V2)", "JDG/docs/WIZJA_OPA_ENTERPRISE_V2.md"),
]),
],
legal=[
"RODO — art. 32 (bezpieczeństwo: pseudonimizacja, szyfrowanie, odporność), art. 33–34 (breach: 72h raport).",
"RODO — art. 28 (procesory: integracje), art. 35 (DPIA dla systemów krytycznych).",
"eIDAS — podpisy kwalifikowane/pieczęcie dla bundle i dowodów (kontekst prawny integralności).",
"Ustawa o rachunkowości — art. 74 (retencja i ochrona przed zniszczeniem: DR, WORM).",
"Ustawa o ZUS — ciągłość zobowiązań składkowych przy awarii (terminy nienaruszalne).",
"Ustawa VAT — art. 108–109e: system musi zapewnić ewidencje nawet w DR (ciężar po stronie podatnika).",
"Ustawa o krajowym systemie cyberbezpieczeństwa (UKSC) — obowiązki operatorów usług kluczowych (kontekst klasyfikacji).",
"RODO art. 82 / KKS — odpowiedzialność i środki po naruszeniu (raport, odszkodowanie, procedury).",
],
innovations=[
("Threat model as code", "model zagrożeń w YAML (atak → wektor → kontrola → test); testy kontrol w CI — threat model żyje, nie rdzewieje."),
("Rule quarantine", "mechanizm izolacji pojedynczej reguły (podejrzenie manipulacji/błędu) bez pełnego rollbacku bundle — chirurgiczna reakcja."),
("Dual-control deploys", "wymóg dwóch zatwierdzeń (techniczne + prawne) dla reguł krytycznych; egzekwowane w CI (nie tylko procedura)."),
("Secrets rotation with attestation", "rotacja kluczy z dowodem (kiedy, kto, co) i testem, że stary klucz już nie działa — fail-closed."),
("Chaos legal drill", "cykliczna gra wojenna: próba wniesienia błędnej reguły przez cały proces (PR→bramki→deploy) — raport luk procesowych."),
("Restore drills w CI", "co tydzień automatyczny restore z dr_snapshots/WORM do środowiska test + weryfikacja checksum — backup bez testu to mit."),
("Paper-mode runbook", "kompletna procedura księgowości ręcznej (formularze, terminy, rekonsylacja po DR) — forteca działa nawet bez IT."),
("Tamper-evident rule history", "każda zmiana reguły z hash chain w WORM: historia nie podlega cichej edycji (audyt w pełni niezawodny)."),
("Ransomware playbook", "izolacja → ocena → odtwarzanie → raport (RODO 72h) → rekonsylacja księgowa; ćwiczony co kwartał."),
("Breach taxonomy", "klasyfikacja naruszeń (dane, integralność, dostępność) z gotowymi raportami i ścieżkami prawymi (RODO/UODO)."),
("Zero standing access", "dostęp produkcyjny tylko na czas (JIT) z dowodem użycia — zero stałych uprawnień admina."),
("DR legal continuity", "w DR automatyczny tryb „deklaracje na ostrożnych parametrach” (najbezpieczniejsze wartości) z oznaczeniem decyzji jako DR."),
],
in_contracts=[
"Kontrakt deploy z P38 (podpisy, rollback) — security warstwy integralności.",
"Kontrakt WORM z P42 — tamper-evidence jako podstawa anty-manipulacji.",
],
out_contracts=[
"THREAT MODEL I KONTROLE (atak → kontrola → test) — wiąże P44 (certyfikacja) i P41 (runbooki).",
"Plan DR (RTO/RDO, scenariusze, ćwiczenia) — wejście do P38 (deploy) i P44.",
"Playbook ransomware + breach taxonomy — wejście do P41 (dokumentacja operacyjna).",
],
acceptance_extra=[
"Threat model przedstawiony jako tabela: wektor → kontrola → test → status (min. 10 wektorów).",
"Plan DR z RTO/RDO i scenariuszami odtworzonymi w projekcie (albo jawnie: nieprzetestowane = luka P1).",
]),
dict(code="P44", slug="CERTYFIKACJA_FINALNA", title="CERTYFIKACJA FINALNA FORTECY — ZAMKNIĘCIE KAMPANII V3 I DEKLARACJA STANU",
role="przewodniczącym komisji certyfikacyjnej systemów policy-as-code, składającym finalny raport właścicielowi projektu",
expertise="synteza kampanii, certyfikacja, rozliczenie definicji sukcesu, mapa decyzji wdrożeniowych, ścieżka V4",
mission=[
"Zamknij kampanię V3: zsyntetyzuj kontrakty wyjściowe P00–P43, rejestry luk (P0–P3), rejestry wdrożeń (P30), syntezy etapów (P31) i certyfikuj STAN fortecy wobec dokumentów świętych. Certyfikat ma być prawdziwy: zero deklaracji bez dowodu — każde twierdzenie ma artefakt (test, raport, rejestr). Zdefiniuj, co zostało do zrobienia, w jakiej kolejności, z jakimi zależnościami i kto decyduje (4-eyes).",
"Rozlicz definicję sukcesu kampanii: Legal Twin (pokrycie prawa z dowodami), Golden Oracle (przeszłość niezmienna), Decision Certificate (każda decyzja dowodowa), Law Radar (proaktywna adaptacja), Declarative Change (prosta zmiana reguł), invarianty runtime, fail-closed. Dla każdego filaru: status (DOWIEDZIONE/CZĘŚCIOWE/DEKLAROWANE), dowody, luki, plan domknięcia. Zaprojektuj ścieżkę V4: kolejne fale (domeny nowe, AI, integracje) z kontraktami dziedziczonymi z V3.",
],
subparts=[
dict(name="Rozliczenie filarów dokumentów świętych",
goal="status każdego filaru z dowodami",
questions=[
"Legal Twin: jaki jest mierzalny pokrycie akt→reguł→testów (z coverage_unifier P42) i gdzie pustynie?",
"Golden Oracle: czy replay przeszłości działa (testy, dane, bundle historyczne)?",
"Decision Certificate: czy każda decyzja AUTO_POST ma certyfikat (pobierz próbkę z decision_certificates.json)?",
"Law Radar i Declarative Change: czy zmiana prawa → zmiana reguł jest prosty, szybki, bezpieczny (dowód z case'u)?",
]),
dict(name="Rejestry luk i priorytetyzacja",
goal="jedna lista zadań z priorytetami",
questions=[
"Ile luk P0/P1/P2/P3 zgromadziła kampania (agregacja z P00–P43) i ile już wdrożono (P30)?",
"Które luki P0 blokują certyfikację (hard gates) i co je domyka?",
"Jak priorytetyzować (wpływ na poprawność księgowania vs koszt vs ryzyko prawne) — metodologia?",
"Co przechodzi do V4 (rejestr z kontraktami) a co jest anulowane (z uzasadnieniem)?",
]),
dict(name="Certyfikat finalny i hard gates",
goal="dowód, nie deklaracja",
questions=[
"Jak brzmieć certyfikat (struktura, dowody, ograniczenia odpowiedzialności)?",
"Czy zero_defect_certification (P42) i final_certification_v4_gate mają spójne kryteria?",
"Które twierdzenia pozostają [NIEZWERYFIKOWANE] (prawo, dane zewnętrzne) — jawne ograniczenia?",
"Kto podpisuje certyfikat (4-eyes) i jak jest archiwizowany (WORM, hash, retencja)?",
]),
dict(name="Ścieżka V4 i dziedzictwo",
goal="kontynuacja bez utraty kontraktów",
questions=[
"Które kontrakty P00–P43 obowiązują w V4 (lista, źródło prawdy)?",
"Które domeny/obszary to fale V4 (np. nowe akty 2027, integracje bankowe, AI zaawansowane)?",
"Jak zmierzyć postęp V4 (metryki z P37) i kiedy wywołać kolejną certyfikację?",
"Czy kampania V3 spełniła cel: silnik = ufortyfikowana forteca (ocena własna z dowodami)?",
]),
],
file_groups=[
dict(name="Certyfikacja i rejestry finalne", files=[
    ("Gate certyfikacji finalnej v4", "JDG/tools/final_certification_v4_gate.py"),
    ("Audyt certyfikacji etap28", "JDG/tools/final_certification_etap28_audit.py"),
    ("Certification zero-defect", "JDG/tools/zero_defect_certification.py"),
    ("Test certyfikacji finalnej v4", "JDG/tests/test_final_certification_v4.py"),
    ("Rejestr certyfikatów decyzji", "JDG/bundles/decision_certificates.json"),
    ("Evidence final certification v4", "JDG/bundles/final_certification_v4_evidence.json"),
    ("Rejestr wdrożeń", "JDG/bundles/deployments.json"),
    ("Zdrowe wersje", "JDG/bundles/healthy_versions.json"),
]),
dict(name="Syntezy i dowody kampanii", files=[
    ("Kanon pokrycia (dane)", "JDG/bundles/coverage_canon.json"),
    ("Pustynie pokrycia", "JDG/bundles/coverage_deserts.json"),
    ("Golden verdicts", "JDG/bundles/golden_verdicts.json"),
    ("Graf prawny (LKG)", "JDG/bundles/legal_graph.json"),
    ("Enterprise operating contract", "JDG/bundles/enterprise_operating_contract.json"),
    ("Stan control plane", "JDG/bundles/control_plane_state.json"),
    ("Status kampanii P00–P30", "JDG/prompts_status.yaml"),
    ("Raport pokrycia", "JDG/COVERAGE_REPORT.md"),
]),
dict(name="Dokumenty święte i zamknięcie", files=[
    ("Dokument święty 1 (target)", "JDG/docs/ARCHITEKTURA_OPA_ENTERPRISE_TARGET.md"),
    ("Dokument święty 2 (wizja V2)", "JDG/docs/WIZJA_OPA_ENTERPRISE_V2.md"),
    ("Kanon pokrycia (dokument)", "JDG/docs/COVERAGE_CANON.md"),
    ("Raport luk pokrycia", "JDG/docs/LEGAL_COVERAGE_GAP_RAPORT.md"),
    ("Legal Twin raport", "JDG/docs/LEGAL_TWIN_RAPORT.md"),
    ("Legal Twin traceability", "JDG/docs/LEGAL_TWIN_TRACEABILITY.md"),
    ("Zgodność prawna", "JDG/docs/ZGODNOSC_PRAWNA.md"),
    ("Audit podstaw prawnych", "JDG/docs/AUDYT_PODSTAW_PRAWNYCH.md"),
]),
],
legal=[
"Wszystkie akty z Sekcji 8 części P00–P43 — certyfikat finalny agreguje statusy weryfikacji (ISAP) per akt.",
"Ordynacja podatkowa — art. 119a, 199a (kontekst oceny zgodności finalnej).",
"Ustawa o rachunkowości — art. 4, 74–75 (certyfikat jako dowód rzetelności, retencja).",
"RODO — art. 5.2, 24 (rozliczalność: certyfikat = dokument rozliczalności systemu).",
"AI Act — dokumentacja finalna systemu (jeśli warstwa AI w zakresie).",
"Ustawa VAT/PIT/ZUS — finalne pokrycie materiałowe per podatek (status DOWIEDZONE/CZĘŚCIOWE).",
"KKS — finalna redukcja ryzyka czynu zabronionego (dowód z testów fail-closed).",
"eIDAS — podpis certyfikatu finalnego (integralność i autentyczność deklaracji).",
],
innovations=[
("Hard gate certificate", "certyfikat wydawany wyłącznie gdy wszystkie hard gates (luki P0) zamknięte; inaczej: raport „brak certyfikacji” z listą — zero marketingu."),
("Filar scoreboard", "tabela filarów (Legal Twin, Oracle, Certificate, Radar, Change) z statusem DOWIEDZONE/CZĘŚCIOWE/DEKLAROWANE i dowodami."),
("Campaign aggregate ledger", "automatyczna agregacja rejestru luk z wszystkich raportów V3 do jednego rejestru z deduplikacją (ta sama luka w 2 raportach = 1 wpis)."),
("Decision map for owner", "mapa decyzyjna właściciela: co wdrożyć najpierw (P0), co wymaga doradcy podatkowego, co wymaga budżetu — jedna strona."),
("V4 inheritance contract", "jawna lista kontraktów dziedziczonych (standardy, schematy, bramki) — V4 nie zaczyna od zera."),
("Success metric freeze", "definicja sukcesu zapisana jako dane (metryki + progi) przed certyfikacją — ocena na dowodach, nie na wrażeniu."),
("Certificate WORM + signature", "certyfikat finalny podpisany i archiwizowany WORM z retencją — dowód na lata."),
("Knowledge transfer pack", "pakiet przekazania (dokumenty, runbooki, rejestry, kontakty decyzji) — forteca operowalna przez innych niż twórcy."),
("Certification renewal policy", "kiedy certyfikat wygasa (nowelizacje, deploy krytyczny, czas) — mechanizm odnowienia zamiast wiecznej ważności."),
("Legacy cleanup closure", "finalna fala usuwania fasad/martwych artefaktów wykrytych w kampanii (P30/P36/P42) — zero długu technicznego na start V4."),
("Owner attestation", "właściciel potwierdza przyjęcie certyfikatu z listą zastrzeżeń — 4-eyes domknięte po stronie biznesowej."),
("Fortress self-portrait", "auto-portret systemu: jeden diagram + tabela (komponenty, kontrakty, dowody) — punkt wejścia dla każdego nowego inżyniera/audytora."),
],
in_contracts=[
"Wszystkie kontrakty wyjściowe P00–P43 (lista w raporcie finalnym) — rozliczasz każdy.",
"Definicja sukcesu z README serii V3 — rozliczasz filar po filarze z dowodami.",
],
out_contracts=[
"CERTYFIKAT FINALNY (status filarów, luki, decyzje, ograniczenia) — dla właściciela projektu.",
"Rejestr V4 (kontrakty dziedziczone + fale + metryki) — wejście do przyszłych kampanii.",
"Knowledge transfer pack — dla zespołu operacyjnego (V4 i produkcja).",
],
acceptance_extra=[
"Scoreboard filarów wypełniony: każdy filar ma status z dowodami (zero deklaracji bez dowodu).",
"Mapa decyzyjna właściciela na jednej stronie (tabela: działanie → zależności → kto decyduje → priorytet).",
"Ocena własna: czy forteca jest ufortyfikowana — argumentacja za/przeciw z dowodami (bez sellingu).",
]),
]
