# -*- coding: utf-8 -*-
"""Parts P00-P07: systemic core of the V3 campaign."""
PARTS = [

dict(code="P00", slug="MAPA_KANONICZNA", title="MAPA KANONICZNA, INWENTARYZACJA I KONTRAKT INTEGRACYJNY SERII V3",
role="głównym architektem systemów policy-as-code dla polskiej JDG, audytorem inwentaryzacji i projektantem kontraktów integracyjnych między częściami kampanii",
expertise="inwentaryzacja artefaktów, wykrywanie sprzeczności dokument–kod, kanon identyfikatorów, kontrakty interfejsowe, baseline dla Legal Twin i control plane",
mission=[
"Zbuduj KANONICZNY BASELINE modułu JDG dla całej serii V3: rzeczywisty stan plików, pakietów Rego, rule_id, testów, migracji, bundle, polityk i dokumentacji — weryfikowany przeciw strukturze repozytorium, nie przeciw deklaracjom. To raport, z którym pozostałe 44 części będą się spinać: ich oceny braków, identyfikatory i standardy muszą móc się na nim oprzeć.",
"Wykryj WSZYSTKIE sprzeczności między dokumentacją a kodem i między dokumentami (np. inne liczby plików/rule_id w MANIFEST vs rzeczywistość, dryf mirrors `JDG/rules` vs `policies/`, nieaktualne raporty). Każdą sprzeczność oznacz BLOCKER-em z dowodami obu stron. Wygeneruj kontrakty integracyjne: kanon identyfikatorów (rule_id, luki, innowacje, kontrakty), format tabeli dowodów, format rejestru luk, format kontraktów międzyczęściowych — tak aby zmiany z raportów kolejnych części były spójnie połączone, a nie przypadkiem zbieżne.",
],
subparts=[
dict(name="Inwentaryzacja artefaktów kodu (rules, micro, domeny)",
goal="pełna mapa pakietów Rego i rule_id z dowodami liczbowymi, nie deklaracjami",
questions=[
"Ile faktycznie jest plików .rego w JDG/rules i w policies/ (liczby z tabeli dowodów, nie z MANIFEST)?",
"Które pakiety mają warstwę macro, micro i enterprise — gdzie są luki tej trójstruktury?",
"Które pliki nie są objęte żadnym testem natywnym Rego ani pytestem?",
"Które pliki to jawne backupy/śmieci (np. .bak_stubs_removed, .p03backup) i kto je trzyma w repo?",
]),
dict(name="Inwentaryzacja danych, migracji i bundle",
goal="mapa RuleStore: migracje SQL, JSON-e w bundles/, spójność liczb między nimi",
questions=[
"Czy manifest_v2.json, rule_registry.json i metrics_pewnosci.json podają te same liczby reguł? Gdzie się różnią?",
"Które migracje (001–013) mają pokrycie w kodzie narzędzi, a które są martwe?",
"Czy thresholds_data.json pokrywa wszystkie pliki _*_rates.rego (czy jeszcze istnieją wartości w regułach)?",
"Które artefakty bundle są wygenerowane, a które ręczne — jak to udowodnić?",
]),
dict(name="Spójność dokumentacji i rejestrów kampanii",
goal="stan dokumentów świętych vs dokumentów opisowych vs raportów poprzednich kampanii",
questions=[
"Które dokumenty opisowe podają liczby sprzeczne z realnym stanem (wymień pary: dokument → liczba → dowód rzeczywisty)?",
"Czy docs/ARCHITEKTURA.md i docs/ARCHITECTURE.md są zgodne ze sobą i z dokumentami świętymi?",
"Które raporty poprzednich kampanii (raporty_glm52, prompts_status.yaml P00–P30) deklarują wdrożenia bez dowodu w kodzie?",
"Czy docs/COVERAGE_CANON.md jest zgodny z bundles/coverage_canon.json?",
]),
dict(name="Kontrakt integracyjny serii V3",
goal="zdefiniowanie standardów, których wszystkie kolejne części mają przestrzegać",
questions=[
"Jaki jest kanon identyfikatorów luk/innowacji/konfliktów/pytań dla serii V3 (format, zakresy, rezerwacje)?",
"Jaki jest minimalny kontrakt werdyktu i tabeli dowodów, który wszystkie części honorują?",
"Jaką ścieżkę zapisu raportów i rejestrów przyjmujemy (konwencja nazw, kolejność, idempotentność)?",
"Jak rozstrzygać konflikty kontraktowe między częściami (procedura, właściciel, SLA)?",
]),
],
file_groups=[
dict(name="Dokumenty struktury i inwentaryzacji", files=[
    ("Struktura katalogów JDG", "JDG/docs/STRUKTURA_PROJEKTU.md"),
    ("Inwentaryzacja plików (dokument)", "JDG/docs/INWENTARYZACJA_PLIKOW.md"),
    ("Manifest 2.0 (deklaracje liczb)", "JDG/docs/MANIFEST_2_0.md"),
    ("Analiza stanu OPA jako systemu (luki L1–L12)", "JDG/docs/ANALIZA_STANU_OPA_JAKO_SYSTEM.md"),
    ("Katalog reguł", "JDG/docs/KATALOG_REGUL.md"),
    ("Katalog narzędzi", "JDG/docs/KATALOG_NARZEDZI.md"),
    ("Kanon pokrycia (dokument)", "JDG/docs/COVERAGE_CANON.md"),
]),
dict(name="Pliki korzeniowe modułu JDG", files=[
    ("README modułu JDG", "JDG/README.md"),
    ("MANIFEST modułu (wygenerowany)", "JDG/MANIFEST.md"),
    ("Raport pokrycia", "JDG/COVERAGE_REPORT.md"),
    ("Plan unifikacyjny v8", "JDG/unified_plan_v8.yaml"),
    ("Postęp planu unifikacyjnego", "JDG/unified_plan_progress.yaml"),
    ("Status kampanii P00–P30", "JDG/prompts_status.yaml"),
    ("Generator manifestu", "JDG/tools/generate_manifest.py"),
    ("Manifest v2 (narzędzie)", "JDG/tools/manifest_v2.py"),
]),
dict(name="Dane bundle (RuleStore / rejestry)", files=[
    ("Manifest bundle v2", "JDG/bundles/manifest_v2.json"),
    ("Rejestr reguł", "JDG/bundles/rule_registry.json"),
    ("Dane progów/stawek", "JDG/bundles/thresholds_data.json"),
    ("Metryki pewności", "JDG/bundles/metrics_pewnosci.json"),
    ("Graf prawny (zalążek LKG)", "JDG/bundles/legal_graph.json"),
    ("Pustynie pokrycia", "JDG/bundles/coverage_deserts.json"),
    ("Kanon pokrycia (dane)", "JDG/bundles/coverage_canon.json"),
    ("Zdrowe wersje bundle", "JDG/bundles/healthy_versions.json"),
]),
dict(name="API, migracje i skrypt modułu", files=[
    ("Specyfikacja OpenAPI", "JDG/api/openapi.yaml"),
    ("Migracja 001 — RuleStore", "JDG/migrations/001_jdg_rule_store.sql"),
    ("Migracja 013 — tools/api/rulestore/bundles", "JDG/migrations/013_jdg_v18_tools_api_rulestore_bundles.sql"),
    ("Skrypt budowy bundle", "JDG/bundles/bundle.sh"),
]),
dict(name="Mirror policies (porównanie soource-of-truth)", files=[
    ("Mirror pakietu jdg (katalog)", "policies/jdg"),
    ("Mirror orkiestratora", "policies/jdg/main_jdg.rego"),
    ("Bundle mirror jdg (skrypt)", "policies/jdg/bundles/bundle.sh"),
    ("Manifest bazowy overlay", "policies/jdg/bundles/base/manifest.json"),
    ("Overlay v2026", "policies/jdg/bundles/overlays/v2026/manifest.json"),
    ("Overlay v2027", "policies/jdg/bundles/overlays/v2027/manifest.json"),
]),
dict(name="Mapa testów (katalogi, nie pojedyncze pliki)", files=[
    ("Katalog testów JDG", "JDG/tests"),
    ("Testy auto (pytest)", "JDG/tests/auto"),
    ("Testy natywne Rego", "JDG/tests/rego"),
    ("README testów", "JDG/tests/README.md"),
]),
],
focus=[
"Rekonesans liczb: policz pliki .rego per katalog (rules/, rules/micro/, rules/<domeny>) i podaj liczby w tabeli dowodów — to SĄ kanon P00.",
"Wykryj wszystkie pliki z rozszerzeniami backupowymi lub duplikatami nazw i zaproponuj procedurę oczyszczenia bez utraty historii.",
"Zbuduj macierz: pakiet → warstwa (macro/micro/enterprise) → testy → bundle → status lifecycle (SHADOW/CANDIDATE/ACTIVE) — puste pola to luki.",
"Porównaj liczby z docs/MANIFEST_2_0.md, JDG/MANIFEST.md i bundles/manifest_v2.json — każda rozbieżność = konflikt Cxx.",
"Oceń dryf mirrors: co w JDG/rules nie ma odpowiednika w policies/ i odwrotnie — spisz reguły dryfu.",
"Zaprojektuj format RAPORTU V3 jako kontraktu: sekcje, identyfikatory, tabele — dokument do wklejenia w kolejne prompty jako standard.",
"Zdefiniuj słownik pojęć serii (luka, innowacja, konflikt kontraktowy, dowód, bloker) — bez tego części użyją różnych definicji.",
"Oceń gotowość JDG do bycia „systemem” wg dokumentów świętych: co już jest infrastrukturą, a co tylko deklaracją reguł.",
"Wskaż 10 największych ryzyk integracyjnych serii V3 (np. raporty niezgodne z kodem, duplikacja prac) i zabezpieczenia w kontraktach.",
"Sprawdź spójność JDG/prompts_status.yaml z raportami w JDG/raporty_glm52 — które pozycje mają raport, a które nie.",
"Zaproponuj mechanizm „versioned canonical snapshot” — jak zamrozić baseline P00 na czas kampanii, by zmiany w repo nie unieważniały raportów.",
"Oceń strukturę katalogów pod kątem Declarative Change (dokument święty V2, F6): czy struktura wspiera formularzową zmianę reguł?",
"Zaplanuj rejestr wszystkich 45 raportów V3 (tabela: kod, status, luki P0/P1, kontrakt) jako żywy artefakt w repo.",
],
legal=[
"Ordynacja podatkowa (akt ramowy odpowiedzialności, terminów, odsetek — odniesienia w całym silniku)",
"Ustawa – Prawo przedsiębiorców (cykl życia JDG: wpis, zawieszenie, wznowienie, sukcesja)",
"Ustawa o rachunkowości (UoR — ewidencje, dowody, retencja)",
"Ustawa o PIT (formy opodatkowania, ulgi, KUP)",
"Ustawa o VAT (stawki, zwolnienia, MPP, KSeF)",
"Ustawa o systemie ubezpieczeń społecznych (ZUS) + ustawa o świadczeniach opieki zdrowotnej",
"Ustawa o zryczałtowanym podatku dochodowym (ryczałt, karta)",
"ISAP i RCL jako źródła weryfikacji (isap.sejm.gov.pl, legislacja.gov.pl) — status źródeł, nie akt",
],
innovations=[
("Canonical Snapshot Engine", "zamrożenie baseline liczbowego (hash plików, liczby rule_id) z możliwością re-ewaluacji różnicowej w każdej kolejnej części"),
("Registry of Registries", "jeden indeks wszystkich rejestrów (rule_registry, legal_graph, policy_registry, healthy_versions) z wykrywaniem sprzeczności między nimi"),
("Contract Schema DSL", "deklaratywny schemat kontraktów międzyczęściowych (YAML/JSON) z walidatorem w CI, żeby żadna część nie złamała standardu"),
("Drift Watchdog Docs↔Code", "stały porównywacz liczby/typy artefaktów w dokumentach vs rzeczywistość z alarmem BLOCKER"),
("Mirror Delta Detector", "automatyczny raport różnic JDG/rules vs policies/ z klasyfikacją (strukturalny, treściowy, wersjonujący) i sugestią sync"),
("Campaign Ledger", "rejestr wszystkich raportów V3 z licznikami luk/innowacji i statusem wdrożenia — podstawa P44"),
("ID Canon", "globalna rezerwacja identyfikatorów V3-Pxx-Lxx/Ixx/Cxx/Qxx z detectorem kolizji między raportami"),
("Evidence Table Generator", "generator szablonu tabeli dowodów z listy plików promptu — każda część startuje z gotową strukturą"),
("Blocker Triage Matrix", "macierz rozstrzygania konfliktów BLOCKER (dokument święty wins, procedura eskalacji, SLA)"),
("Repo Hygiene Planner", "plan oczyszczenia backupów/śmieci z gwarancją odtworzenia (archiwum tagów git, nie usuwanie historii)"),
("Baseline Reconciliation Report", "porównanie baseline P00 z baseline z dokumentu ANALIZA_STANU — co zmieniło się od analizy luki L1–L12"),
("Series Automation Contract", "definicja tego, co każdy raport MUSI zawierać maszynowo (parsowalne sekcje) — narzędzie walidacji raportów w CI"),
],
in_contracts=[
"To jest część PIERWSZA — nie ma wcześniejszych kontraktów; ustalasz je TY i wszystkie dalsze części honorują.",
],
out_contracts=[
"Kanon identyfikatorów serii V3 (format i zakresy V3-Pxx-Lxx/Ixx/Cxx/Qxx) — wiążący dla P01–P44.",
"Faktyczny stan liczbowy repo (pliki/rule_id/testy) — używany przez wszystkie części jako odnośnik o P00.",
"Format tabeli dowodów i rejestru luk — standard sekcji raportów P01–P44.",
"Lista konfliktów BLOCKER C00-x do rozstrzygnięcia przed uruchomieniem części domenowych (P10+).",
"Rejestr backupów/śmieci do oczyszczenia z planem bezpiecznej eliminacji.",
],
acceptance_extra=[
"Tabela dowodów zawiera liczby per katalog (rules/, micro/, domeny, tests/) — nie sumy „wydaje mi się”.",
"Kontrakt integracyjny jest wyrażony jako parsowalny schemat (sekcja w raporcie) i opisany słowami.",
]),

dict(code="P01", slug="LEGAL_TWIN_LKG", title="LEGAL TWIN, LEGAL KNOWLEDGE GRAPH I ŚCIEŻKA DOWODOWA ZGODNOŚCI Z PRAWEM",
role="Legal Engineerem i architektem Legal Knowledge Graph dla polskiego prawa podatkowego z doświadczeniem w traceability klasy finansowej",
expertise="modelowanie aktów prawnych jako grafu, dwukierunkowe pokrycie prawo↔reguła, weryfikacja podstaw prawnych w ISAP/RCL, dowód istnienia przepisu na dzień transakcji",
mission=[
"Zbuduj pełny projekt Legal Twin (Filar V2/F1 z dokumentu świętego): AKT → ARTYKUŁ → USTĘP/PUNKT → WERSJA (valid_from/valid_to) → INTERPRETACJA/ORZECZENIE → REGUŁA → TEST → WERDYKT → CERTYFIKAT. Wszystkie reguły silnika mają być dwukierunkowo powiązane z węzłami prawa; pokrycie prawa ma być MIERZONE (LCI/TCL), nie deklarowane.",
"Zweryfikuj katalog źródeł prawnych z JDG/docs/Bbb wobec oficjalnych publikatorów (ISAP/RCL/MF): numer Dz.U., tytuł, daty, treść artykułów. Wykryj wszystkie podstawy prawne w regułach, które są niezweryfikowane, podejrzane lub fikcyjne, i zaprojektuj pipeline ich mediacji. Zaprojektuj reverse coverage: każdy węzeł materialny (przepis z wartością/terminem/stawką) musi mieć ≥ 1 regułę — węzeł bez reguły to alarm „prawo istnieje, system go nie zna”.",
],
subparts=[
dict(name="Model danych LKG i migracja z jdg_legal_cartography",
goal="ewolucja istniejącej cartografii do pełnego grafu prawnego zgodnie z V2/F1",
questions=[
"Jakie pola musi mieć węzeł legal_node (identyfikator, tekst, wersje, źródło, status, jednostka redakcyjna)?",
"Czy migracje 003/005/006 pokrywają model z dokumentu świętego V2 — czego brakuje do legal_graph?",
"Jak wersjonować tekst przepisu po nowelizacji, żeby time-travel werdyktu był dowodliwy?",
"Jak odwzorować strukturę jednostek redakcyjnych (art./ust./pkt/lit.) w identyfikatorach węzłów?",
]),
dict(name="Dwukierunkowe pokrycie i metryki LCI/TCL/RV/UVR",
goal="mierzalność pewności prawnej zamiast deklaracji",
questions=[
"Jak dokładnie obliczać LCI (Legal Coverage Index) per domena — co jest licznikiem, co mianownikiem?",
"Czy narzędzia reverse_coverage_detector i legal_coverage_heatmap liczą to samo? Rozbieżności?",
"Czy coverage_deserts.json (pustynie pokrycia) jest aktualny względem realnych reguł? Jak to sprawdzić?",
"Jaki próg LCI per domena jest osiągalny w 90 dni i jaki plan drogowy do ≥ 99%?",
]),
dict(name="Weryfikacja katalogu Bbb i podstaw prawnych w regułach",
goal="medycyna prawna katalogu źródeł i audyt _legal_basis w kodzie",
questions=[
"Które pozycje Bbb mają numery Dz.U. nie do zweryfikowania lub podejrzane (lista z tagiem [BŁĄD_PODSTAWY_PRAWNEJ?])?",
"Które reguły mają _legal_basis wskazujące na przepisy nieobecne w Bbb i niezweryfikowane w ISAP?",
"Jak wygląda procedura weryfikacji (kto, jakie źródło, jaki dowód, jaki status) i jak ją zautomatyzować?",
"Jakie interpretacje KIS/orzeczenia NSA są cytowane w regułach i czy mają status wiążący czy tylko pomocniczy?",
]),
dict(name="Ścieżka dowodowa werdyktu: reguła→test→bundle→certyfikat",
goal="odtworzenie dowodu przepisu w wersji z dnia transakcji w każdej chwili",
questions=[
"Czy provenance.rego przenosi legal refs do werdyktu 25-polowego? Czego brakuje do `_legal_basis_refs` z wersjami węzłów?",
"Jak certyfikat decyzji (V2/F4) ma weryfikować się offline wobec Merkle/HSM?",
"Czy testy natywne Rego pokrywają legal_basis każdej reguły krytycznej? Jak wygenerować braki?",
"Jak legal graph łączy się z golden replay (zmiana przepisu → uzasadniona zmiana werdyktu)?",
]),
],
file_groups=[
dict(name="Dokumenty Legal Twin i źródeł prawnych", files=[
    ("Raport Legal Twin", "JDG/docs/LEGAL_TWIN_RAPORT.md"),
    ("Rejestr źródeł prawnych", "JDG/docs/LEGAL_SOURCE_REGISTRY.md"),
    ("Traceability Legal Twin", "JDG/docs/LEGAL_TWIN_TRACEABILITY.md"),
    ("Słownik referencji prawnych", "JDG/docs/SLOWNIK_REFERENCJI_PRAWNYCH.md"),
    ("Audyt podstaw prawnych", "JDG/docs/AUDYT_PODSTAW_PRAWNYCH.md"),
    ("Remediacja podstaw prawnych P00", "JDG/docs/P00_REMEDIACJA_PODSTAW_PRAWNYCH.md"),
    ("Raport luk pokrycia prawnego", "JDG/docs/LEGAL_COVERAGE_GAP_RAPORT.md"),
    ("Pokrycie prawne (dokument)", "JDG/docs/LEGAL_COVERAGE.md"),
    ("Akty referencyjne (dokument)", "JDG/docs/LEGAL_REFERENCE_ACTS.md"),
    ("Zgodność z prawem (dokument)", "JDG/docs/ZGODNOSC_PRAWNA.md"),
]),
dict(name="Reguły i dane Legal Twin", files=[
    ("Kanon domknięcia pokrycia prawnego", "JDG/rules/p00_legal_coverage_closure.rego"),
    ("Provenance werdyktów", "JDG/rules/provenance.rego"),
    ("Temporalność (wersje przepisów)", "JDG/rules/temporal.rego"),
    ("Interpretacje sądowe jako reguły", "JDG/rules/judicial_interpretations_enterprise.rego"),
    ("Graf prawny (dane bundle)", "JDG/bundles/legal_graph.json"),
    ("Kanon referencji prawnych (dane)", "JDG/bundles/legal_reference_canon.json"),
    ("Audyt legal basis (dane)", "JDG/bundles/legal_basis_audit.json"),
    ("Luki pokrycia prawnego (dane)", "JDG/bundles/legal_coverage_gaps.json"),
    ("Pustynie pokrycia (dane)", "JDG/bundles/coverage_deserts.json"),
]),
dict(name="Narzędzia LKG, weryfikacji i traceability", files=[
    ("Silnik Legal Twin", "JDG/tools/legal_twin_engine.py"),
    ("Narzędzie legal_twin", "JDG/tools/legal_twin.py"),
    ("Traceability Legal Twin", "JDG/tools/legal_twin_traceability.py"),
    ("Generator LKG", "JDG/tools/lkg_generator.py"),
    ("Walidator legal basis v1", "JDG/tools/validate_legal_basis.py"),
    ("Walidator legal basis v2", "JDG/tools/validate_legal_basis_v2.py"),
    ("Rejestr źródeł prawnych (narzędzie)", "JDG/tools/legal_source_registry.py"),
    ("Audyt legal basis (narzędzie)", "JDG/tools/legal_basis_audit.py"),
    ("Raport luk pokrycia (narzędzie)", "JDG/tools/legal_coverage_gap_report.py"),
    ("Detector reverse coverage", "JDG/tools/reverse_coverage_detector.py"),
    ("Heatmapa pokrycia prawnego", "JDG/tools/legal_coverage_heatmap.py"),
    ("Kalendarz zmian prawnych (narzędzie)", "JDG/tools/legal_change_calendar.py"),
    ("Kalendarz zmian prawnych (dane)", "JDG/bundles/legal_change_calendar.json"),
    ("Macierz traceability", "JDG/tools/traceability_matrix.py"),
]),
dict(name="Migracje i testy Legal Twin", files=[
    ("Migracja 003 — legal twin", "JDG/migrations/003_jdg_v8_legal_twin.sql"),
    ("Migracja 005 — legal sources", "JDG/migrations/005_jdg_v10_legal_sources.sql"),
    ("Migracja 006 — legal traceability", "JDG/migrations/006_jdg_v11_legal_traceability.sql"),
    ("Test rejestru źródeł prawnych", "JDG/tests/test_legal_source_registry.py"),
    ("Test traceability", "JDG/tests/test_legal_twin_traceability.py"),
    ("Test rekonsyliacji inwentarza", "JDG/tests/test_inventory_reconciliation.py"),
    ("Test infrastruktury Legal Twin", "JDG/tests/test_legal_twin_infrastructure.py"),
]),
],
focus=[
"Porównaj model z dokumentu świętego V2/F1 z realnymi migracjami i bundle — zbuduj plan ewolucji bez rewrite.",
"Przeanalizuj KAŻDĄ regułę z `_legal_basis` w wybranych pakietach krytycznych i skategoryzuj status weryfikacji.",
"Zaprojektuj schemat legal_node_id (kanoniczny format adresu przepisu) zgodny z jednostkami redakcyjnymi.",
"Określ, jak w LKG reprezentować rozporządzenia wykonawcze (np. stawki VAT) i akty zmieniające (nowelizacje).",
"Zaprojektuj procedurę 4-eyes dla weryfikacji podstaw prawnych (prawnik + engineer) z dowodem w rejestrze.",
"Oceń, czy interpretacje KIS mogą być regułami ACTIVE, czy tylko NEEDS_ADVICE — granica prawa wiążącego.",
"Zaprojektuj reverse coverage pipeline: diff akt → nowe węzły → brakujące reguły → issue automatyczne.",
"Zaplanuj eksport dowodu przepisu (PDF/XML) dla Decision Certificate na dzień transakcji.",
"Oceń spójność danych bundle (legal_graph.json) z realnym kodem — czy JSON jest generowany czy ręczny?",
"Zaproponuj alert „pustynia pokrycia” jako bramkę CI: nowy przepis w Bbb bez reguły = fail.",
"Określ, jak reprezentować prawo UE (dyrektywy, DAC6, CBAM) obok prawa krajowego w jednym grafie.",
"Zaprojektuj test property: „każda reguła krytyczna ma ≥1 test cytujący ten sam legal_node_id”.",
],
legal=[
"Ordynacja podatkowa — art. 14a/14b (interpretacje ogólne i indywidualne jako źródła)",
"Ustawa o VAT — struktura artykułów implementowanych w regułach (art. 41, 43, 86, 108a, 113)",
"Ustawa o PIT — art. 26 (ulgi), art. 30c, art. 22–23 (KUP)",
"Ustawa o systemie ubezpieczeń społecznych — art. 18a/18c (ulgi ZUS), art. 22 (stopy)",
"Ustawa o rachunkowości — art. 4–5, 74 (retencja)",
"Ustawa – Prawo przedsiębiorców — art. 5, 14, 22–25",
"Ustawa o zryczałtowanym podatku dochodowym — art. 6–12 (stawki ryczałtu)",
"Rozporządzenia wykonawcze MF (JPK_VAT, wzory deklaracji, obniżone stawki VAT)",
],
innovations=[
("Legal Node Versioning Engine", "wersjonowanie tekstów przepisów z diffem prawnym i dowodem time-travel na dzień transakcji"),
("Reverse Coverage Sentinel", "automat: nowy przepis w LKG bez reguły → issue z priorytetem per severity przepisu"),
("ISAP Proof Snapshot", "archiwizacja tekstu przepisu (PDF+hash) na dzień transakcji jako dowód niezależny od ISAP uptime"),
("Legal Basis Health Score", "scoring każdej reguły: zweryfikowana podstawa / niezweryfikowana / podejrzana z dashboardem trendu"),
("Interpretation Layer Isolation", "sztywna separacja prawa powszechnego od interpretacji/orzeczeń w regułach i werdyktach"),
("Legal Diff → Rule Draft Pipeline", "diff nowelizacji → automatyczny szkic zmian reguł (SHADOW) z 4-eyes"),
("Coverage Desert Radar", "mapa pustyn pokrycia per domena z planem zasiedlenia i alertem tygodniowym"),
("Bidirectional Consistency Gate", "bramka CI: reguła bez węzła prawnego = fail; węzeł materialny bez reguły = fail"),
("Legal Graph Merkle Root", "hash drzewa grafu prawnego w każdym werdykcie — dowód spójności zbioru podstaw"),
("Retroactivity Auditor", "audyt: czy zmiana reguł zmieniła historyczne werdykty bez zmiany przepisu (golden oracle hook)"),
("Source Certification Workflow", "pełny workflow certyfikacji źródła (ISAP → prawnik → wpis do rejestru → status CERTIFIED)"),
("Legal Twin API", "API /legal/nodes + /legal/proof z historią wersji dla UI księgowej i certyfikatów"),
],
in_contracts=[
"Honoruj baseline liczbowy i kanon identyfikatorów z raportu V3_P00 (sekcja KONTRAKT WYJŚCIOWY).",
"Każdy wniosek o podstawie prawnej prowadź z pełnym cytatem i statusem weryfikacji (ZWERYFIKOWANO/NIEZWERYFIKOWANO/BŁĄD?).",
],
out_contracts=[
"Schemat legal_node_id i model danych legal_graph — wiążący dla P05 (temporal), P08 (Law Radar), P11 (certyfikaty).",
"Procedura weryfikacji podstaw prawnych — wiążąca dla wszystkich części domenowych P10–P36.",
"Status listy pozycji Bbb (zweryfikowane/podejrzane) — wejście do remediacji dla części domenowych.",
"Definicje i wzory metryk LCI/TCL/RV/UVR — P44 liczy je w certyfikacji finalnej.",
],
acceptance_extra=[
"Każda pozycja Bbb wymieniona w raporcie ma status weryfikacji i uzasadnienie, nie ogólnik „do sprawdzenia”.",
"Model LKG zawiera przykładową ścieżkę dowodową dla jednego przepisu end-to-end (akt→reguła→test→werdykt).",
]),

dict(code="P02", slug="ORKIESTRATOR", title="ORKIESTRATOR MULTI-PASS, SHARDED ROUTING I SAFE MERGE",
role="ekspertem OPA/Rego i architektem deterministycznych silników decyzyjnych klasy finansowej",
expertise="pipeline Multi-Pass PASS 0–8, routing O(1), safe_merge z allowlistą niemutowalną, determinizm, kolizje pakietów, early-abort",
mission=[
"Przeanalizuj orkiestrator main_jdg.rego end-to-end: przepływ PASS 0–8, sharded routing (ADR-009), First-Match-Wins else-chain, safe_merge z allowlistą niemutowalną (ZUS/business), POST-MERGE i warunki early-abort. Udowodnij lub obal: determinizm, kompletność (każde wejście dostaje werdykt), monotoniczność merge i brak nadpisań pól krytycznych.",
"Zaprojektuj docelowy model orkiestracji zgodny z dokumentami świętymi: warstwa konstytucyjna (V2/F2) jako runtime invariant check w POST-MERGE, klasa pewności CERTAIN/CONDITIONAL/NEEDS_ADVICE (V2/F4) w kontrakcie, ścieżki degradacji fail-closed. Wskaż różnice między dokumentacją a kodem — każda rozbieżność BLOCKER.",
],
subparts=[
dict(name="Przepływ PASS 0–8 i POST-MERGE",
goal="formalny opis kroków, wejść/wyjść, właścicieli pól i punktów abortu",
questions=[
"Które PASS-y są niezbędne, a które dublują pracę (koszt latencji bez wartości)?",
"Co dokładnie dzieje się w POST-MERGE i czy invariant check jest tam w ogóle wykonywany?",
"Które pola werdyktu mają jednego właściciela, a które mogą być nadpisane przez wiele PASS-ów?",
"Gdzie kod może abortować bez werdyktu (lukę kompletności) i jak to wykryć testem?",
]),
dict(name="Routing i determinizm",
goal="dowód, że routing jest deterministyczny, kompletny i O(1)",
questions=[
"Czy sharded router pokrywa wszystkie domeny? Jakie wejście wypada poza shardy i co wtedy?",
"Czy First-Match-Wins else-chain w shardach daje ten sam wynik niezależnie od kolejności kompilacji?",
"Jak testować determinizm (property test: permutacja wejść → ten sam werdykt)?",
"Czy koszty ewaluacji rosną liniowo z liczbą reguł w shardzie — co zmierzyć i jak zoptymalizować?",
]),
dict(name="safe_merge i niemutowalność",
goal="audyt allowlisty niemutowalnej, precedencji i monotoniczności",
questions=[
"Jakie pola są w allowliście niemutowalnej (ZUS/business) i czy lista jest kompletna wobec ryzyka finansowego?",
"Czy merge może po cichu nadpisać kwoty, stawki albo legal refs — jaki test to blokuje?",
"Czy merge jest monotoniczny (informacja tylko przyrasta) — jak udowodnić?",
"Jak wygląda konflikt merge i czy konflikt zawsze prowadzi do NEEDS_ADVICE (fail-closed)?",
]),
dict(name="Degradacja, fallback i mirrors",
goal="ścieżki awaryjne i spójność mirror policies/jdg/main_jdg.rego",
questions=[
"Czy fallback/api_fallback zwracają ważny kontrakt werdyktu czy „cichy” ubytek pól?",
"Jak degradacja współpracuje z fail-closed: kiedy wolno wydać werdykt przy częściowych danych?",
"Czy mirror orkiestratora w policies/jdg jest aktualny wobec JDG/rules — wykryte różnice jako konflikty?",
"Jaka jest ścieżka awarii bundle (persist=true, zdrowe wersje) i czy orkiestrator ją obsługuje?",
]),
],
file_groups=[
dict(name="Rdzeń orkiestratora", files=[
    ("Orkiestrator główny", "JDG/rules/main_jdg.rego"),
    ("Sharded routing", "JDG/rules/routing.rego"),
    ("Helpery wspólne", "JDG/rules/_helpers_jdg.rego"),
    ("Metadane reguł", "JDG/rules/_metadata_jdg.rego"),
    ("Fallback (silnik)", "JDG/rules/fallback.rego"),
    ("API fallback", "JDG/rules/api_fallback.rego"),
    ("Konflikty", "JDG/rules/conflicts.rego"),
    ("Edge cases", "JDG/rules/edge_cases.rego"),
]),
dict(name="Dokumenty kontraktowe orkiestracji", files=[
    ("Kontrakt danych orkiestratora", "JDG/docs/ORCHESTRATOR_DATA_CONTRACT.md"),
    ("Decision Core (P02)", "JDG/docs/DECISION_CORE_P02.md"),
    ("Analiza stanu (luki L1–L12)", "JDG/docs/ANALIZA_STANU_OPA_JAKO_SYSTEM.md"),
]),
dict(name="Testy orkiestratora", files=[
    ("Test orkiestratora enterprise", "JDG/tests/test_p03_orchestrator_enterprise.py"),
    ("Test kontraktu danych orkiestratora", "JDG/tests/test_orchestrator_data_contract.py"),
    ("Test blokujący orkiestratora", "JDG/tests/auto/test_p01_orchestrator_enterprise.py"),
    ("Natywny test orkiestratora", "JDG/tests/rego/test_r01_orchestrator_core_enterprise.rego"),
    ("Test fundamentu enterprise", "JDG/tests/rego/test_p01_fundament_enterprise.rego"),
]),
dict(name="Mirrors i zależności", files=[
    ("Mirror orkiestratora (policies)", "policies/jdg/main_jdg.rego"),
    ("Mirror routing (policies)", "policies/jdg/routing.rego"),
    ("Mirror fallback (policies)", "policies/jdg/fallback.rego"),
    ("Mirror konfliktów (policies)", "policies/jdg/conflicts.rego"),
]),
],
focus=[
"Zbuduj diagram ASCII/Mermaid PASS 0–8 z właścicielami pól i punktami abortu — jako kontrakt w raporcie.",
"Znajdź wszystkie ścieżki, gdzie werdykt może wyjść bez provenance lub legal refs — każdy przypadek = luka.",
"Zapropоnuj testy metamorficzne: zmiana wejścia niesemantyczna → werdykt niezmienny.",
"Oceń koszt ewaluacji orkiestratora (szacunek O: PASS × reguły per shard) i zaprojektuj indeksy/ranking przyspieszeń.",
"Sprawdź, czy safe_merge allowlista pokrywa pola kwotowe wszystkich domen (VAT/PIT/ZUS/KKS) — zaproponuj rozszerzenie.",
"Zaprojektuj invariant check w POST-MERGE (V2/F2) na 20 twardych niezmiennikach — lista startowa w raporcie.",
"Wskaż miejsca, gdzie kod używa wartości liczbowych zamiast data.thresholds (ADR-002) — dla P06 do migracji.",
"Porównaj main_jdg.rego z mirror policies/jdg/main_jdg.rego — pełna lista różnic (konflikt lub sync task).",
"Zaprojektuj ścieżkę awaryjną: uszkodzony bundle → persist/healthy_versions → werdykt degradowany z klasą NEEDS_ADVICE.",
"Oceń, czy early-abort może pominąć obowiązki sprawozdawcze (np. JPK) — ryzyko ciszy zamiast alertu.",
"Zaproponuj routing metadata: jak dodać nową domenę bez edycji orkiestratora (deklaratywnie, zgodnie z V2/F6).",
"Zdefiniuj test „kompletności”: 10 000 losowych wejść → 100% werdyktów z pełnym kontraktem (brak luk).",
],
legal=[
"Ordynacja podatkowa — art. 190–193 (decyzje i ich doręczanie jako paradygmat werdyktu z uzasadnieniem)",
"Ustawa o VAT — art. 108a (MPP jako przykład decyzji BLOCKER w orkiestracji)",
"Ustawa o PIT — art. 44 (zaliczki — krytyczne pola kwotowe w allowliście)",
"Ustawa o systemie ubezpieczeń społecznych — art. 22/47 (ZUS niemutowalny w merge)",
"Ustawa o rachunkowości — art. 4 (zasada memoriału jako paradygmat PASS-ów okresowych)",
],
innovations=[
("Constitutional PASS", "dedykowany PASS walidacji 20 niezmienników konstytucyjnych (V2/F2) z BLOCK + auto-revert"),
("Determinism Prover", "test property na permutacjach wejścia i kolejności reguł — dowód determinizmu w CI"),
("Field Ownership Matrix", "automatyczna macierz: pole → kto zapisuje → kto może nadpisać → allowlista wygenerowana z kodu"),
("Shard Completeness Sentinel", "test: każde wejście mapuje się na dokładnie jeden shard (zero orphan, zero podwójnych)"),
("Degradation Ladder", "schodek degradacji: pełny → częściowy → NEEDS_ADVICE, z jawnymi kryteriami przejścia i audytem"),
("Latency Budget Guard", "budżet ms per PASS; przekroczenie → alarm + auto-tuning kolejności reguł"),
("Merge Monotonicity Prover", "dowód monotoniczności merge testem na delta-werdyktach"),
("Orchestrator Telemetry Hooks", "metryki per PASS (czas, liczba dopasowań, aborty) do obserwowalności i SLO"),
("Declarative Shard Registry", "shardy rejestrowane deklaratywnie (JSON) — dodanie domeny bez dotykania orkiestratora"),
("Early-Abort Forensics", "logowanie każdego abortu z powodem i statystyką — zero cichych braków werdyktów"),
("Mirror Sync Gate", "CI: mirror policies/jdg/main_jdg.rego musi być bit-do-bit zgodny z canonical albo wymusza sync"),
("Verdict Completeness Fuzzer", "fuzz 10k wejść: zero odpowiedzi bez pełnego 25-polowego kontraktu"),
],
in_contracts=[
"Honoruj kanon identyfikatorów i baseline z V3_P00; format tabeli dowodów zgodny z kontraktem P00.",
"Honoruj model legal_node_id z V3_P01 — provenance w orkiestratorze ma przenosić te identyfikatory.",
],
out_contracts=[
"Definitywna lista pól niemutowalnych safe_merge (rozszerzona o domeny) — wiąże P03–P44.",
"Kontrakt invariants w POST-MERGE (lista 20 niezmienników) — wejście dla P04.",
"Standard telemetrii PASS (nazwy metryk, tagi) — wejście dla P37/P41/P43.",
"Lista hardcode’ów w orkiestratorze do migracji — wejście dla P06.",
"Decyzja o statusie mirror orkiestratora (sync/gate) — wejście dla P38/P40.",
],
acceptance_extra=[
"Raport zawiera diagram przepływu PASS 0–8 z punktami abortu i właścicielami pól.",
"Każda wykryta rozbieżność dokument↔kod ma osobny konflikt C02-x z cytatami obu stron.",
]),

dict(code="P03", slug="KONTRAKT_WERDYKTU", title="KONTRAKT WERDYKTU 25-POLOWY, KOMPOZYCJA DECYZJI I KLASA PEWNOŚCI",
role="ekspertem kontraktów API w systemach finansowych i projektantem kontraktu decyzyjnego z klasą pewności",
expertise="25-polowy kontrakt werdyktu (ADR-004), kompozycja decyzji, scoring pewności, degradacja kontraktu, zgodność OpenAPI",
mission=[
"Zbadaj 25-polowy kontrakt werdyktu (ADR-004) w kodzie, OpenAPI i testach: kompletność pól, typy, walidacje, provenance, legal refs, klasa pewności. Zaprojektuj kompatybilne rozszerzenie kontraktu (certainty_class wg V2/F4, invariant refs, golden hash) bez łamania istniejących klientów — z planem migracji wersjonowanej.",
"Zaprojektuj kompozycję decyzji: jak PARTIAL wyniki z wielu domen składają się w jeden werdykt klasy CERTAIN/CONDITIONAL/NEEDS_ADVICE; jaka jest semantyka każdego pola przy degradacji; jak scoring pewności wpływa na AUTO_POST. Granica jest twarda: fail-closed — wątpliwość nigdy nie księguje automatycznie.",
],
subparts=[
dict(name="Audyt 25 pól w kodzie i OpenAPI",
goal="pełna zgodność specyfikacji z implementacją",
questions=[
"Czy wszystkie 25 pól jest produkowanych przez orkiestrator w każdej ścieżce (happy/fallback/error)?",
"Czy OpenAPI (JDG/api/openapi.yaml) opisuje te same pola z tymi samymi typami i wymagalnością?",
"Które pola są optionale bez uzasadnienia i niosą ryzyko ciszy (np. brak legal refs)?",
"Jak testy (unit/contract) pilnują kontraktu — co testują braki?",
]),
dict(name="Klasa pewności i scoring",
goal="semantyka CERTAIN/CONDITIONAL/NEEDS_ADVICE i wpływ na AUTO_POST",
questions=[
"Czy decision_scoring/adaptive_trust produkuje wartości używane w kontrakcie, czy żyją osobno?",
"Jakie warunki muszą być spełnione, by werdykt był CERTAIN — czy lista jest zamknięta i testowalna?",
"Czy NEEDS_ADVICE zamyka AUTO_POST w każdej ścieżce (w tym fallback)?",
"Jak pewność z różnych domen się komponuje (min/max/weighted) i kto to rozstrzyga?",
]),
dict(name="Degradacja kontraktu i błędy",
goal="co klient dostaje, gdy dane/usługi są niedostępne",
questions=[
"Czy degradacja zwraca pełny kontrakt z pustymi polami, czy skrócony — i co z tego wynika dla klienta?",
"Jak są kodowane błędy (enum kody) i czy klient może je programowo rozróżnić?",
"Czy „puste pole” jest rozróżnialne od „pole nie dotyczy” od „nie wiem” — czy kontrakt to wyraża?",
"Jak wygląda wersjonowanie kontraktu (breaking vs additive) i kto pilnuje zgodności?",
]),
dict(name="Provenance i legal refs w werdykcie",
goal="kompletny łańcuch dowodowy w każdym werdykcie",
questions=[
"Czy werdykt niesie bundle_version, rule_version, threshold_version (determinizm odtworzenia)?",
"Czy legal refs mają identyfikatory węzłów LKG z wersjami (wg kontraktu P01)?",
"Czy merkle/hash provenance jest liczony i weryfikowalny offline?",
"Czego brakuje do „dowodu dla KAS” w jednym obiekcie werdyktu?",
]),
],
file_groups=[
dict(name="Reguły kompozycji i kontraktu", files=[
    ("Kompozytor decyzji", "JDG/rules/decision_composer_enterprise.rego"),
    ("Kompletność decision core", "JDG/rules/decision_core_completeness_enterprise.rego"),
    ("Scoring decyzji", "JDG/rules/decision_scoring_enterprise.rego"),
    ("Adaptive trust scoring", "JDG/rules/adaptive_trust_scoring_enterprise.rego"),
    ("Walidacja reguł", "JDG/rules/validation.rego"),
    ("Provenance", "JDG/rules/provenance.rego"),
    ("Fallback", "JDG/rules/fallback.rego"),
]),
dict(name="Dokumenty kontraktowe", files=[
    ("Kontrakt danych orkiestratora", "JDG/docs/ORCHESTRATOR_DATA_CONTRACT.md"),
    ("Guardy rdzenia i progi temporalne", "JDG/docs/CORE_GUARDS_TEMPORAL_THRESHOLDS.md"),
    ("Dashboard pewności", "JDG/docs/PEWNOSC_DASHBOARD.md"),
    ("Referencja API", "JDG/docs/API_REFERENCJA.md"),
]),
dict(name="Specyfikacja API i narzędzia", files=[
    ("OpenAPI", "JDG/api/openapi.yaml"),
    ("Kontrakt danych orkiestratora (narzędzie)", "JDG/tools/orchestrator_data_contract.py"),
    ("Weryfikacja invariantów werdyktu", "JDG/tools/verify_verdict_invariants.py"),
    ("Certyfikat decyzji (narzędzie)", "JDG/tools/decision_certificate.py"),
    ("Dashboard pewności (narzędzie)", "JDG/tools/confidence_dashboard.py"),
    ("Metryki pewności (narzędzie)", "JDG/tools/pewnosc_metrics.py"),
    ("Konsystencja specyfikacji API", "JDG/tools/api_spec_consistency.py"),
]),
dict(name="Testy kontraktu", files=[
    ("Test operating contract", "JDG/tests/test_enterprise_operating_contract.py"),
    ("Test kontraktu danych orkiestratora", "JDG/tests/test_orchestrator_data_contract.py"),
    ("Test walidatora enterprise", "JDG/tools/validate_enterprise_contract.py"),
    ("Migracja 008 — kontrakt orkiestratora", "JDG/migrations/008_jdg_v13_orchestrator_contract.sql"),
]),
],
focus=[
"Zbuduj tabelę: pole → typ → producent (PASS) → walidacja → test → status (dowód per pole).",
"Zaprojektuj rozszerzenie kontraktu o certainty_class, invariant_refs, legal_basis_refs, golden_hash — plan migracji additive.",
"Zdefiniuj zamkniętą listę warunków CERTAIN (np. pełne dane, wszystkie reguły ACTIVE, invarianty OK, legal refs verified).",
"Zaprojektuj semantykę pustych pól (null vs absent vs N/A) i walidator schematu w CI.",
"Oceń, czy scoring pewności jest testowalny (deterministyczny) i jaka jest jego telemetria.",
"Sprawdź zgodność testów contract z OpenAPI — mechanizm wykrywania dryfu specyfikacja↔kod.",
"Zaprojektuj strategię wersjonowania kontraktu (major/minor) i okres współistnienia wersji.",
"Zdefiniuj kontrakt błędów (kody, semantyka, retry-ability) — klient musi programowo rozróżniać.",
"Zaproponuj „werdykt papierowy”: reprezentacja do PDF/certyfikatu z pełnym łańcuchem dowodów (F4).",
"Oceń, czy pola audytowe wystarczą dla 50-letniej retencji — co dołożyć (retencja, podpisy, odtworzenie).",
"Zaprojektuj test diffu kontraktu: zmiana OpenAPI bez zmiany testów = fail.",
"Wskaż ścieżki degradacji, które zwracają skrócony kontrakt — każda to luka fail-closed.",
],
legal=[
"Ordynacja podatkowa — art. 189b (sposób ustalenia treści zobowiązania jako paradygmat uzasadnienia werdyktu)",
"Ustawa o VAT — art. 106b–106n (dane faktury jako wzór kompletności danych kontraktu)",
"Ustawa o PIT — art. 45 (zeznania: kompletność pól deklaracji jako wzór)",
"Ustawa o rachunkowości — art. 20–21 (dowody księgowe jako wzór kompletności dowodowej)",
"Ustawa o systemie ubezpieczeń społecznych — art. 47 (deklaracje ZUS DRA/RCA jako wzór pól kwotowych)",
],
innovations=[
("Contract Version Matrix", "macierz wersji kontraktu × pola × klienci z planem deprecation"),
("Certainty Class Engine", "deterministyczny silnik klasy pewności z zamkniętą listą warunków i testami granicznymi"),
("Empty-Semantics Schema", "rozróżnienie null/absent/NA z walidatorem i dokumentacją per pole"),
("Golden Hash in Verdict", "hash warunków ewaluacji w każdym werdykcie — odtworzenie 1:1 w golden replay"),
("Contract Diff CI Gate", "bramka: każdy diff OpenAPI wymaga diffu testów (korelacja zmian)"),
("Legal Refs Completeness Guard", "reguła BLOCKER: werdykt dotyczący decyzji materialnej bez legal refs = nie wyjście z silnika"),
("Verdict as Evidence Object", "werdykt jako samostatny obiekt dowodowy (podpis, merkle, retencja) gotowy do eksportu"),
("Scoring Telemetry", "pełna telemetria scoringu (rozkłady klas pewności) z alarmami dryfu"),
("Client Compatibility Suite", "testy zgodności dla głównych ścieżek klienta przy zmianie kontraktu"),
("Degradation Contract Patterns", "wzorce pełnego kontraktu przy degradacji (puste ≠ błędne) z testami per wzorzec"),
("AUTO_POST Gate Contract", "maszynowy warunek AUTO_POST w kontrakcie (pole + walidacja) — fail-closed z natury typu"),
("Error Taxonomy DSL", "deklaratywna taksonomia błędów generująca dokumentację i kody synchronicznie"),
],
in_contracts=[
"Honoruj kontrakt orkiestracji i allowlistę niemutowalnych pól z V3_P02.",
"Honoruj model legal_node_id z V3_P01 przy projektowaniu legal refs w kontrakcie.",
],
out_contracts=[
"Docelowy schemat werdyktu (25 pól + rozszerzenia) — wiąże P04 (invarianty), P11 (certyfikaty), P41 (API).",
"Zamknięta lista warunków CERTAIN i ścieżek degradacji — wiąże P04 i P43.",
"Taksonomia błędów — wiąże P41 (API/integracje).",
"Lista pól audytowych dla retencji — wejście dla P43 (WORM/retencja).",
],
acceptance_extra=[
"Każde z 25 pól ma wiersz w macierzy: producent, walidacja, test, status dowodu.",
"Rozszerzenie kontraktu zawiera przykładowy JSON przed/po (additive, bez breaking change).",
]),

dict(code="P04", slug="INVARIANTY_RUNTIME", title="WARSTWA KONSTYTUCYJNA — RUNTIME INVARIANTS I EGZEKUCJA FAIL-CLOSED",
role="ekspertem niezawodności systemów decyzyjnych i projektantem warstwy konstytucyjnej (Filar V2/F2)",
expertise="niezmienniki runtime, fail-closed, auto-revert, weryfikacja werdyktów, ewaluacja różnicowa",
mission=[
"Zbuduj pełny projekt Warstwy Konstytucyjnej (V2/F2): 20–40 twardych niezmienników („suma odliczeń ≤ dochód”, „stawka ∈ {0,5,8,23}”, „ZUS nigdy nadpisany”, „kwoty ≥ 0”, „legal refs obecne”, „temporalnie spójne”) weryfikowanych na KAŻDYM werdykcie w runtime — nie tylko w CI. Naruszenie = BLOCK + alarm + auto-revert do ostatniego zdrowego werdyktu.",
"Zaprojektuj mechanikę egzekucji: gdzie w pipeline (PASS/POST-MERGE) invarianty się uruchamiają, co robią przy naruszeniu (BLOK, nie „warning”), jak alertują, jak współpracują z rollbackiem i jak są testowane (negatywne testy invariantów, fuzz, chaos). Upewnij się, że egzekucja jest tańsza niż pełna re-ewaluacja (koszt latencji).",
],
subparts=[
dict(name="Katalog niezmienników konstytucyjnych",
goal="kompletna lista niezmienników z semantyką i dowodem uzasadnienia prawnego",
questions=[
"Które niezmienniki już istnieją w runtime_invariants_enterprise.rego — czy są egzekwowane czy tylko opisane?",
"Które niezmienniki wynikają z prawa (lista per domena VAT/PIT/ZUS/KKS/ORD) i kto je certyfikuje?",
"Które niezmienniki są strukturalne (kontrakt, provenance, temporalność) i universalne dla wszystkich werdyktów?",
"Jak priorytetyzować: które naruszenie musi blokować, a które może degradować klasę pewności?",
]),
dict(name="Mechanika egzekucji w runtime",
goal="miejsce w pipeline, koszt, zachowanie przy naruszeniu",
questions=[
"Czy invariant check jest w POST-MERGE (V2) — czy wykonuje się na każdym werdykcie z dowodem?",
"Jaki jest koszt latencji egzekucji i jak go zminimalizować (indeksowanie, early-exit, prekompilacja)?",
"Co się dzieje po naruszeniu: BLOCK? auto-revert? alarm? kto jest powiadamiany (ślad audytowy)?",
"Czy naruszenie invariantu może skutkować tylko warningiem (to luka fail-closed)?",
]),
dict(name="Auto-revert i współpraca z rollbackiem",
goal="powrót do zdrowego stanu w minutach, bez utraty audytu",
questions=[
"Jak system wybiera „ostatni zdrowy werdykt/konfigurację” i jak weryfikuje jego zdrowie?",
"Czy auto-revert zachowuje pełny audyt incydentu (co, dlaczego, kto zatwierdził politykę)?",
"Jak auto-revert współgra z rule lifecycle (rollback reguły vs rollback werdyktu)?",
"Jak testować revert (chaos: zepsuta reguła, manipulacja danymi, uszkodzony bundle)?",
]),
dict(name="Testowanie warstwy konstytucyjnej",
goal="dowód, że invarianty faktycznie chronią",
questions=[
"Jak testować invarianty negatywnie (celowe naruszenie w teście → BLOCK)?",
"Jak fuzzing ujawnia invarianty, które przechodzą happy path a łamią się na granicach (grosze, waluty, zerowe)?",
"Jak zmierzyć skuteczność (ile incydentów złapanych w runtime vs CI vs produkcja)?",
"Czy istnieje ewaluacja różnicowa (dwa węzły, ten sam wynik) i jak ją wdrożyć wg V2/F3?",
]),
],
file_groups=[
dict(name="Reguły i narzędzia niezmienników", files=[
    ("Runtime invariants (reguła)", "JDG/rules/audit/runtime_invariants_enterprise.rego"),
    ("Audyt plan44 (reguła)", "JDG/rules/audit/plan44_audit.rego"),
    ("Audyt plan45 (reguła)", "JDG/rules/audit/plan45_audit.rego"),
    ("Walidacja reguł", "JDG/rules/validation.rego"),
    ("Check invariantów runtime (narzędzie)", "JDG/tools/runtime_invariants_check.py"),
    ("Checker niezmienników (narzędzie)", "JDG/tools/invariant_checker.py"),
    ("Weryfikacja invariantów werdyktu", "JDG/tools/verify_verdict_invariants.py"),
    ("Ewaluacja różnicowa", "JDG/tools/differential_evaluation.py"),
]),
dict(name="Dane i migracje", files=[
    ("Migracja 009 — core guards", "JDG/migrations/009_jdg_v14_core_guards.sql"),
    ("Guardy rdzenia (dokument)", "JDG/docs/CORE_GUARDS_TEMPORAL_THRESHOLDS.md"),
]),
dict(name="Testy niezmienników", files=[
    ("Test guardów rdzenia", "JDG/tests/test_core_guards_temporal_thresholds.py"),
    ("Test operating contract", "JDG/tests/test_enterprise_operating_contract.py"),
    ("Test natywny menedżera lifecycle (rollback)", "JDG/tests/rego/test_native_lifecycle_manager_enterprise.rego"),
]),
dict(name="Powiązane reguły obronności", files=[
    ("Gwarancja niezawodności (reguła)", "JDG/rules/reliability_guarantee_enterprise.rego"),
    ("Odporność KSeF (przykład domeny)", "JDG/rules/ksef_resilience_enterprise.rego"),
    ("Deklaracja konfliktów", "JDG/rules/conflict_declaration_enterprise.rego"),
]),
],
focus=[
"Zbuduj katalog 30+ niezmienników: ID, opis, uzasadnienie prawne/strukturalne, domena, priorytet (BLOCK/DEGRADE).",
"Oceń, które invarianty są dzisiaj egzekwowane w runtime, a które tylko w CI — tabela: niezmiennik → egzekucja → dowód.",
"Zaprojektuj koszt egzekucji: plan indeksowania/incremental check, budżet < 5% latencji p95.",
"Zaprojektuj protokół naruszenia: BLOCK → alarm → auto-revert → incydent → post-mortem automatyczny.",
"Zdefiniuj interakcję invariantów z certainty_class (P03): naruszenie = NEEDS_ADVICE zawsze (fail-closed).",
"Zaplanuj testy negatywne invariantów jako wymagane w CI (każdy niezmiennik ma test „naruszenie → BLOCK”).",
"Zaprojektuj ewaluację różnicową (V2/F3): hash werdyktów na ≥ 2 węzłach, rozbieżność = alarm.",
"Oceń, czy obecne reguły audytujące (plan44/45) dublują invarianty — co przenieść do runtime, a co zostawić w CI.",
"Zaprojektuj dashboard niezmienników (złamanie, częstotliwość, trend) do obserwowalności.",
"Wskaż niezmienniki wymuszone prawem, które brakują całkowicie (np. ZUS zdrowotna ≥ 0, PIT nieujemny podatek bez zwrotu automatycznego).",
"Zaprojektuj politykę eskalacji: niezmiennik złamany 2× w 24h → freeze domeny + review 4-eyes.",
"Określ, jak wersjonować katalog niezmienników (zmiana = decyzja architektoniczna z ADR).",
],
legal=[
"Ustawa o VAT — art. 86 (odliczenia ≤ podatek należny), art. 108a (MPP obowiązkowy dla listy/15k)",
"Ustawa o PIT — art. 27 (podatek ≥ 0), art. 26 (odliczenia ≤ dochód)",
"Ustawa o systemie ubezpieczeń społecznych — art. 22 (stopy składkowe jako zakresy)",
"Ustawa o świadczeniach opieki zdrowotnej — art. 79–81 (składka zdrowotna ≥ 0 i progi)",
"Ordynacja podatkowa — art. 56 (odsetki ≥ 0), art. 57 (zakaz dyrektywy wewnętrznej — determinizm)",
"Ustawa o rachunkowości — art. 7 (zasada podwójnego zapisu jako niezmiennik bilansowy)",
],
innovations=[
("Constitution Catalog", "wersjonowany katalog niezmienników z ADR, właścicielem, testem i statusem egzekucji"),
("Zero-Latency Invariant Index", "prekompilowane indeksy niezmienników (early-exit) — egzekucja < 1% budżetu latencji"),
("Violation Autopsy", "automatyczny post-mortem każdego naruszenia (przyczyna, reguła, dane) do rejestru incydentów"),
("Dual-Node Consensus", "ewaluacja różnicowa krytycznych domen na 2 węzłach z hashem wyniku (V2/F3)"),
("Invariant Mutation Testing", "mutacje reguł muszą łamać invariant w teście — dowód skuteczności katalogu"),
("Graceful Degrade Map", "mapa: naruszenie niezmiennika X → werdykt NEEDS_ADVICE (nigdy ciche przejście)"),
("Constitutional Freeze", "automatyczne zamrożenie domeny po powtarzającym się naruszeniu + procedura odblokowania 4-eyes"),
("Invariant Provenance", "każdy werdykt niesie listę wykonanych invariantów i ich wyniki (dowód dla audytu)"),
("Legal Invariant Registry", "niezmienniki podpięte pod legal_node (P01) — zmiana przepisu sugeruje przegląd niezmiennika"),
("Negative Test Generator", "generator testów naruszeń dla każdego niezmiennika (szkielet auto-testów)"),
("Runtime Cost Ledger", "rejestr kosztu egzekucji per niezmiennik — podstawa optymalizacji"),
("Chaos Constitution Drill", "cotygodniowy chaos: celowe złamanie niezmiennika w staging → pomiar czasu BLOCK+revert"),
],
in_contracts=[
"Honoruj kontrakt werdyktu i certainty_class z V3_P03 — invarianty są elementem klasy pewności.",
"Honoruj model legal_node_id z V3_P01 przy wiązaniu niezmienników z przepisami.",
"Honoruj listę 20 niezmienników startowych z V3_P02 (POST-MERGE) — rozszerz, nie dubluj.",
],
out_contracts=[
"Katalog niezmienników (ID, semantyka, egzekucja) — wiąże P06 (progi), P29 (KKS), P43 (chaos/DR) i P44 (certyfikacja).",
"Protokół naruszenia i auto-revert — wiąże P07 (lifecycle rollback) i P38 (deployment).",
"Wymagania testów negatywnych invariantów — wiąże P39 (testy/CI).",
"Interfejs ewaluacji różnicowej — wiąże P38/P43.",
],
acceptance_extra=[
"Każdy niezmiennik ma przypisane: uzasadnienie prawne lub strukturalne oraz test negatywny (istniejący albo do stworzenia).",
"Raport zawiera pomiar/szacunek kosztu egzekucji i plan jego ograniczenia.",
]),

dict(code="P05", slug="TEMPORALNOSC", title="TEMPORALNOŚĆ, TIME-TRAVEL I DOWÓD NIEZMIENNOŚCI PRZESZŁOŚCI",
role="ekspertem temporalnych systemów prawnych i wersjonowania danych w systemach księgowych",
expertise="valid_from/valid_to, algebra interwałów, time-travel, retroaktywność, odtwarzalność historyczna",
mission=[
"Udowodnij (lub obal z dowodem), że system spełnia zasadę „zmiana prawa nigdy nie zmienia przeszłości”: re-ewaluacja historycznej transakcji z tym samym snapshotem daje identyczny werdykt. Przeanalizuj temporal.rego, wersjonowanie reguł i parametrów, detekcję luk/nakładek interwałów (algebra interwałów Allen-like), granice day-1/day-0/day+1 i strefy czasowe.",
"Zaprojektuj model czasowy klasy ENTERPRISE: macierz dat (transakcja, ewaluacja, wejście w życie, publikacja, wiedza), obsługę retroaktywnych nowelizacji i przepisów przejściowych, snapshoty ewaluacyjne (bundle+reguły+parametry+legal nodes+schema) jako jednostka odtwarzalności, oraz bramkę temporalną w CI (zero luk, zero nakładek).",
],
subparts=[
dict(name="Audyt okien ważności reguł i parametrów",
goal="kompletność i poprawność valid_from/valid_to w kodzie",
questions=[
"Które reguły krytyczne nie mają okien ważności (implicit „zawsze”) i gdzie to grozi błędem po nowelizacji?",
"Czy detekcja luk/nakładek interwałów działa dla reguł, parametrów i węzłów LKG (trzy warstwy)?",
"Jak obsłużone są okna otwarte (valid_to = null) i czy ich semantyka jest jednorodna?",
"Czy testy graniczne day-1/day-0/day+1 istnieją dla nowelizacji w danych (lista z dowodami)?",
]),
dict(name="Time-travel i snapshoty",
goal="odtworzenie historycznego werdyktu 1:1",
questions=[
"Z czego składa się pełny snapshot ewaluacyjny i czy wszystkie składniki są wersjonowane?",
"Czy istnieje mechanizm „przebicia” współczesnych danych do przeszłości (np. dziś zaktualizowany próg w historycznej ewaluacji) — jak go wykryć?",
"Jak odtworzyć werdykt z 12 miesięcy temu (narzędzia, dane, procedura) — czy jest to testowane?",
"Czy provenance werdyktu wystarcza do odtworzenia (bundle_version, rule_version, threshold_version)?",
]),
dict(name="Retroaktywność i przepisy przejściowe",
goal="poprawna obsługa prawa zmieniającego się wstecz i okresów przejściowych",
questions=[
"Jak system reprezentuje przepis retroaktywny (valid_from w przeszłości przy publikacji dziś)?",
"Czy przepisy przejściowe (dupa ścieżki dla starych faktów) są modelowane w regułach — przykłady z dowodami?",
"Jak wykrywać kolizję retroaktywności z golden replay (zajdzie uzasadniona zmiana historycznego werdyktu)?",
"Jaka jest procedura rewizji zadeklarowanych deklaracji po retroaktywnej nowelizacji (powiadomienie, korekta)?",
]),
dict(name="Granice czasowe i edge cases",
goal="przeskoki roku, strefy, okresy rozliczeniowe, zegar systemowy",
questions=[
"Czy leapy year (29.02) i zmiany czasu są bezpieczne w kalkulacjach terminów?",
"Jak okresy rozliczeniowe (miesiąc/kwartał) przecinają się z oknami ważności reguł?",
"Czy źródło czasu jest pojedyncze (clock service) czy rozproszone w regułach — ryzyko niejednoznaczności?",
"Jak testowane są granice kwartałów/miesięcy w zaliczkach i deklaracjach?",
]),
],
file_groups=[
dict(name="Reguły i dane temporalne", files=[
    ("Temporalność (reguła)", "JDG/rules/temporal.rego"),
    ("Progi temporalne", "JDG/rules/thresholds_jdg.rego"),
    ("Mirror temporal (policies)", "policies/jdg/temporal.rego"),
    ("Mirror progi (policies)", "policies/tax/temporal.rego"),
]),
dict(name="Narzędzia temporalne", files=[
    ("Detector dryfu temporalnego", "JDG/tools/temporal_drift_detector.py"),
    ("Bramka interwałów temporalnych", "JDG/tools/temporal_interval_gate.py"),
    ("Guardy rdzenia i progi (narzędzie)", "JDG/tools/core_guards_temporal_thresholds.py"),
    ("Silnik snapshotów PIT", "JDG/tools/pit_temporal_snapshot_engine.py"),
    ("Symulator amendacji prawa", "JDG/tools/law_amendment_simulator.py"),
]),
dict(name="Testy temporalne", files=[
    ("Test ważności temporalnej", "JDG/tests/test_temporal_validity.py"),
    ("Test menedżera temporalności", "JDG/tests/test_temporal_manager.py"),
    ("Test guardów i progów", "JDG/tests/test_core_guards_temporal_thresholds.py"),
]),
dict(name="Dane i dokumenty", files=[
    ("Dane progów", "JDG/bundles/thresholds_data.json"),
    ("Guardy rdzenia (dokument)", "JDG/docs/CORE_GUARDS_TEMPORAL_THRESHOLDS.md"),
    ("Migracja 009 — core guards", "JDG/migrations/009_jdg_v14_core_guards.sql"),
]),
],
focus=[
"Wypisz z temporal.rego wszystkie mechanizmy i porównaj z dokumentem świętym V1 §6 — różnice jako luki.",
"Zaprojektuj algebrę interwałów z dowodem: zero luk + zero nakładek per rule_id/parametr (formalnie, nie deklaratywnie).",
"Zbuduj macierz 5 dat (transakcja/ewaluacja/efekt/publikacja/wiedza) i przypisz ją do realnych scenariuszy JDG.",
"Zaprojektuj Snapshot ID: hash(bundle+reguły+parametry+legal nodes+schema) jako klucz odtwarzalności werdyktu.",
"Sprawdź testy day-1/day-0/day+1: które nowelizacje w danych mają testy, a które nie (tabela).",
"Zaprojektuj „Time Gate” CI: każda nowa wersja reguły/parametru wymaga testów granicznych i dowodu ciągłości.",
"Oceń obsługę stref czasowych (Polska CET/CEST) w terminach — pojedyncze źródło prawdy czasu.",
"Zaprojektuj procedurę retroaktywności: alerty, rewizja deklaracji, komunikacja z golden replay.",
"Wskaż reguły z hardcoded datami (2024/2025/2026) — lista do migracji do parametrów (P06).",
"Zaprojektuj test „przeszłość nietykalna”: re-ewaluacja golden setu z nowym bundle → zmiany tylko z uzasadnieniem prawnym.",
"Oceń spójność mirrors temporal (policies/jdg vs JDG/rules) — różnice jako konflikty C05-x.",
"Zaplanuj metryki temporalne: liczba luk, nakładek, okien otwartych, testów granicznych (dashboard).",
],
legal=[
"Ordynacja podatkowa — art. 12 (moment powstania zobowiązania), art. 26k (cofnięcie aktu), art. 56–57 (odsetki w czasie)",
"Ustawa o VAT — art. 19a (obowiązek podatkowy w czasie), art. 86b (korekta w czasie), art. 109 (ewidencja w czasie)",
"Ustawa o PIT — art. 9 ust. 2 (forma opodatkowania na cały rok), art. 44 (zaliczki w czasie)",
"Ustawa o systemie ubezpieczeń społecznych — art. 47 (terminy), art. 18a/18c (okresy ulg)",
"Ustawa – Prawo przedsiębiorców — art. 22–25 (zawieszenie: skutki w czasie)",
"Zasada lex retro non agit i przepisy przejściowe (konstytucja art. 2 — zaufanie do prawa) jako paradygmat modelu",
],
innovations=[
("Interval Algebra Prover", "formalny dowód ciągłości okien (bez luk/nakładek) wykonywany w CI na trzech warstwach"),
("Snapshot ID & Vault", "immutowalne snapshoty ewaluacyjne z hashem — odtworzenie werdyktu 1:1 na żądanie"),
("Five-Date Matrix", "model pięciu dat każdej decyzji z automatycznym wykrywaniem sprzeczności"),
("Retroactivity Sentinel", "wykrywanie retroaktywnych zmian i automatyczna lista deklaracji do rewizji"),
("Time Gate CI", "bramka: zmiana okna ważności wymaga testów day-1/0/+1 i dowodu ciągłości"),
("Past Immunity Test", "test „przeszłość nietykalna” na golden setcie po każdej zmianie bundle"),
("Temporal Telemetry", "metryki okien (luki, nakładki, otwarte okna) z alertami na dryf"),
("Clock Service Contract", "pojedyncze źródło czasu dla całego silnika (walidacja stref i DST)"),
("Transition Rule Pattern Library", "biblioteka wzorców przepisów przejściowych (stare fakty → nowe reguły) z testami"),
("Legislated-Future Dry Run", "automatyczne „dry run” przyszłych wersji reguł (valid_from w przyszłości) na danych bieżących"),
("Time-Travel API", "API odtworzenia werdyktu historycznego z Snapshot ID (dla audytu i KAS)"),
("Temporal Coverage Heatmap", "mapa pokrycia testami granicznymi per nowelizacja — plan domknięcia luk"),
],
in_contracts=[
"Honoruj model legal_node_id i wersjonowanie przepisów z V3_P01 — okna reguł muszą się spinać z oknami przepisów.",
"Honoruj listę niezmienników temporalnych z V3_P04 (jeśli dotyczy) — nie dubluj, rozszerzaj.",
"Honoruj allowlistę niemutowalnych pól z V3_P02 — temporalność nie może ich nadpisywać.",
],
out_contracts=[
"Model Snapshot ID i skład snapshotu — wiąże P06 (parametry), P10 (golden oracle), P38 (bundle).",
"Bramka Time Gate CI — wiąże P39 (testy/CI).",
"Procedura retroaktywności i rewizji — wiąże P08 (Law Radar) i P11 (certyfikaty).",
"Wzorce przepisów przejściowych — wiąże wszystkie części domenowe P10–P36.",
],
acceptance_extra=[
"Raport zawiera przynajmniej trzy ścieżki time-travel krok po kroku (scenariusz, dane, wynik) z oznaczeniem tego, co jest dowodem, a co projektem.",
"Każdy odkryty hardcode dat/stawek ma identyfikator luki i trasę do P06.",
]),

dict(code="P06", slug="PARAMETRY_DANE", title="PARAMETRY JAKO DANE: PROGI, STAWKI, LIMITY I HOT-RELOAD",
role="ekspertem zarządzania danymi referencyjnymi (MDM) w systemach finansowych i architektem Data Service",
expertise="dokończenie ADR-002 (zero hardcode), wersjonowane parametry z hot-reload, walidacja zakresów, time-travel danych",
mission=[
"Dokończ ADR-002 w 100%: ZERO wartości liczbowych w regułach. Zrób pełną inwentaryzację hardcode’ów (pliki _*_rates.rego i wszystkie reguły domenowe), zaprojektuj docelowy Data Service: wersjonowane parametry (key, value, valid_from/valid_to, source_act, changed_by), walidacja zakresów przy zapisie, hot-reload ≤ 15 min (cel: < 1 min), golden dataset dla danych (zmiana danych nie może złamać stawek wzorcowych).",
"Parametr = dane; logika = reguła. Stawki, progi, limity, terminy, mapy (PKWiU→stawka, GTU, KŚT) mają żyć w warstwie danych z pełną temporalnością i dowodem źródła (akt prawny). Zaprojektuj ścieżkę zmiany parametru przez Declarative Change (V2/F6): formularz → walidacja → wersja → hot-reload — bez budowy bundle.",
],
subparts=[
dict(name="Inwentaryzacja hardcode’ów w regułach",
goal="pełna lista wartości liczbowych w kodzie i plan migracji",
questions=[
"Które pliki _*_rates.rego (lista z grup 6.x) jeszcze trzymają wartości i ile ich jest (liczby z dowodów)?",
"Które reguły domenowe mają wartości w treści (stawki, progi, terminy) poza warstwą danych?",
"Jak priorytetyzować migrację (ryzyko błędnej decyzji × częstotliwość użycia)?",
"Czy hardcoded_audit.json odzwierciedla stan faktyczny — jak zweryfikować automatycznie?",
]),
dict(name="Model parametru i walidacja",
goal="schemat parametru, zakresy, źródło, odpowiedzialność",
questions=[
"Czy thresholds_data.json pokrywa wszystkie parametry używane przez reguły — jak wykryć parametry-duchy?",
"Jak wygląda walidacja zakresu przy zapisie (np. stawka ∈ dozwolone wartości wg aktu) i kto ją egzekwuje?",
"Czy każdy parametr ma źródło (akt/artykuł) i datę obowiązywania — jak to wymusić w schema?",
"Jak reprezentować parametry zależne od kontekstu (np. progi per PKD, per gmina) bez eksplozji liczby kluczy?",
]),
dict(name="Hot-reload i spójność",
goal="zmiana danych bez restartu i bez niespójności",
questions=[
"Czy data_service.py wspiera wersjonowane wpisy i hot-reload — co brakuje do celu < 15 min / < 1 min?",
"Jak zapobiegać niezgodności wersji (reguła oczekuje parametru w wersji X, data ma Y) — walidacja zgodności?",
"Czy zmiana danych jest audytowalna (kto, kiedy, na podstawie czego) i odwracalna (rollback danych)?",
"Jak testować hot-reload (test: zmiana stawki → nowa ewaluacja bez restartu → stary werdykt historyczny nietknięty)?",
]),
dict(name="Golden dataset danych",
goal="dane wzorcowe jako tarcza regresji",
questions=[
"Czy istnieje golden dataset stawek/progów i czy jest testowany po każdej zmianie danych?",
"Jak zbudować dataset graniczny (grosze, waluty, progi ±0,01, wartości zerowe i maksymalne)?",
"Kto certyfikuje dane wzorcowe (procedura, właściciel, cykl)?",
"Jak dataset łączy się z golden replay werdyktów (P10)?",
]),
],
file_groups=[
dict(name="Warstwy stawek/progów w regułach", files=[
    ("Progi centralne", "JDG/rules/thresholds_jdg.rego"),
    ("Stawki PKPiR", "JDG/rules/_pkpir_rates.rego"),
    ("Stawki UoR", "JDG/rules/_uor_rates.rego"),
    ("Stawki cross-border", "JDG/rules/_crossborder_rates.rego"),
    ("Stawki compliance", "JDG/rules/_compliance_rates.rego"),
    ("Stawki edge cases/konflikty", "JDG/rules/_edge_cases_conflicts_rates.rego"),
    ("Stawki KKS micro", "JDG/rules/_kks_micro_rates.rego"),
    ("Stawki PCC/lokalne/akcyza", "JDG/rules/_pcc_local_excise_rates.rego"),
    ("Stawki cyklu życia biznesu", "JDG/rules/_business_lifecycle_rates.rego"),
    ("Stawki ZUS micro", "JDG/rules/micro/_zus_micro_rates.rego"),
    ("Stawki KKS macro", "JDG/rules/kks/_kks_macro_rates.rego"),
]),
dict(name="Narzędzia danych i audytu hardcode", files=[
    ("Data Service", "JDG/tools/data_service.py"),
    ("Progi P13 (narzędzie)", "JDG/tools/p13_thresholds.py"),
    ("Progi P14 (narzędzie)", "JDG/tools/p14_thresholds.py"),
    ("Audyt hardcode (narzędzie)", "JDG/tools/hardcoded_audit.py"),
    ("Bramka audytu hardcode", "JDG/tools/hardcoded_audit_gate.py"),
    ("Rejestr limitów", "JDG/tools/limits_registry.py"),
]),
dict(name="Dane i dokumenty", files=[
    ("Dane progów (bundle)", "JDG/bundles/thresholds_data.json"),
    ("Audyt hardcode (bundle)", "JDG/bundles/hardcoded_audit.json"),
    ("Migracja 001 — RuleStore", "JDG/migrations/001_jdg_rule_store.sql"),
    ("Analiza stanu (hardcode ~265 wartości)", "JDG/docs/ANALIZA_STANU_OPA_JAKO_SYSTEM.md"),
]),
dict(name="Testy danych", files=[
    ("Test guardów i progów", "JDG/tests/test_core_guards_temporal_thresholds.py"),
    ("Test narzędzi P13", "JDG/tests/test_p13_tools.py"),
]),
],
focus=[
"Zbuduj rejestry hardcode’ów: plik → liczba wartości → przykłady → domena → ryzyko — liczone z kodu, nie z dokumentów.",
"Zaprojektuj schemat parametru: key, value, unit, valid_from/valid_to, source_act, article, changed_by, scope (global/domena/kontekst).",
"Zaprojektuj walidator zakresów z regułami pochodzącymi z aktu (np. VAT ∈ {0,5,8,23,NP}) — nieprawidłowa wartość = odrzucenie zapisu.",
"Zaprojektuj mapę zależności: reguła → parametry, parametr → reguły (dwukierunkowo) — użyte przy analizie wpływu nowelizacji.",
"Zaplanuj hot-reload: mechanizm, SLO (< 1 min), audyt, rollback danych, test spójności wersji.",
"Zaprojektuj golden dataset danych (stawki/progi wzorcowe + graniczne) i procedurę jego certyfikacji.",
"Wskaż parametry zależne od zewnętrznych źródeł (minimalne wynagrodzenie, przeciętne, kursy NBP) i ich ścieżkę aktualizacji.",
"Zaprojektuj deklaratywną ścieżkę zmiany parametru (formularz V2/F6) — krok do P09.",
"Oceń, czy limity gminne (podatek od nieruchomości) mogą być parametrami z walidacją zakresu ustawowego.",
"Zaprojektuj test: „zero wartości liczbowych poza warstwą danych” jako bramka CI (hardcoded_audit_gate).",
"Wskaż parametry, które dziś żyją w dwóch miejscach (reguła + data) — ryzyko rozjazdu, plan unifikacji.",
"Zaplanuj telemetrię danych: liczba parametrów, wiek, świeżość źródła, ostatnia weryfikacja.",
],
legal=[
"Ustawa o VAT — art. 41 (stawki), art. 113 (limit 200 tys.), art. 108a (MPP 15 tys.)",
"Ustawa o PIT — art. 27 (skala), art. 30c (19%), art. 30ca (IP Box 5%), art. 26h (limit termomodernizacji)",
"Ustawa o zryczałtowanym podatku dochodowym — art. 12 (stawki ryczałtu)",
"Ustawa o systemie ubezpieczeń społecznych — art. 18a/18c (ulgi), art. 22 (stopy składkowe)",
"Ustawa o świadczeniach opieki zdrowotnej — art. 79–81 (progi zdrowotnej)",
"Ustawa o podatkach i opłatach lokalnych (stawki gminne i ich górne granice ustawowe)",
"Rozporządzenia MF o obniżonych stawkach VAT i wzorach deklaracji (parametry systemowe)",
"Obwieszczenia o minimalnym wynagrodzeniu i przeciętnym wynagrodzeniu (parametry pochodne)",
],
innovations=[
("Parameter Schema v2", "pełny schemat parametru z zakresem, źródłem, scope i walidacją przy zapisie"),
("Zero-Hardcode Gate", "bramka CI: wykrywanie wartości liczbowych w regułach z allowlistą wyrażeń strukturalnych"),
("Parameter Lineage", "dwukierunkowy graf reguła↔parametr z automatyczną analizą wpływu nowelizacji"),
("Golden Data Dataset", "certyfikowany dataset stawek/progów wzorcowych + granicznych, testowany przy każdej zmianie"),
("Hot-Reload SLO Watch", "pomiar czasu od zatwierdzenia do aktywności parametru z alarmami SLO"),
("External Rate Feeders", "automatyczne feedy: minimalne/przeciętne wynagrodzenie, kursy NBP — z walidacją i audytem"),
("Contextual Parameter Maps", "parametry kontekstowe (per gmina/PKD) bez eksplozji kluczy (spójne przestrzenie nazw)"),
("Parameter Rollback", "jednoklik rollback wersji parametru z pełnym audytem i dowodem w golden replay"),
("Data Freshness Dashboard", "świeżość i weryfikacja źródeł każdego parametru (wiek, akt, ostatni audyt)"),
("Declarative Parameter Form", "formularz V2/F6 dla parametrów: opis ludzki → walidacja → wersja → hot-reload"),
("Range Proof Tests", "testy własności: wartości parametrów zawsze w zakresach ustawowych (property-based)"),
("Parameter Usage Telemetry", "które parametry faktycznie wpływają na decyzje (frekwencja) — priorytetyzacja audytu"),
],
in_contracts=[
"Honoruj model Snapshot ID i okna temporalne z V3_P05 — parametry są pełnoprawną warstwą time-travel.",
"Honoruj baseline z V3_P00 przy inwentaryzacji hardcode (liczby z raportu P00 są punktem odniesienia).",
],
out_contracts=[
"Schemat parametru i zakresy walidacji — wiąże wszystkie części domenowe P10–P36 (migracja ich wartości).",
"Mechanizm hot-reload i rollback danych — wiąże P38 (deployment) i P09 (declarative change).",
"Golden dataset danych — wiąże P10 (golden oracle) i P39 (testy).",
"Rejestr hardcode’ów z priorytetami — wiąże P39 (bramka CI zero-hardcode).",
],
acceptance_extra=[
"Rejestr hardcode’ów zawiera liczby per plik wyliczone z analizy kodu (dowody), nie tylko przykłady.",
"Projekt Data Service zawiera sekwencję zmiany parametru end-to-end (formularz → produkcja) z punktami kontrolnymi.",
]),

dict(code="P07", slug="RULE_LIFECYCLE", title="CYKL ŻYCIA REGUŁ: SHADOW→CANDIDATE→ACTIVE→ROLLBACK I OPERACJE AWARYJNE",
role="ekspertem release engineering i zarządzania cyklem życia polityk (control plane OPA)",
expertise="lifecycle reguł, awans z shadow, A/B canary, auto-rollback, kill-switch, hot-reload rejestru",
mission=[
"Przeanalizuj istniejący cykl życia reguł (rule_lifecycle_enterprise.rego, rule_lifecycle_manager.py) i podnieś go do poziomu dokumentu świętego V1 §3: DODANIE (7 kroków zautomatyzowanych), ZMIANA (nowa wersja + shadow + canary + auto-rollback — nigdy edycja na żywo), USUNIĘCIE (deprecate→retire→purge z karencją), KILL-SWITCH (pauza reguły/pakietu < 1 s).",
"Zaprojektuj 4-eyes i separację obowiązków (autor ≠ recenzent ≠ operator), raport „reguły do usunięcia” tygodniowy, dowody ciągłości czasowej (algebra interwałów z P05) przy każdej operacji, oraz integrację z bundle deployment (P38) tak, aby zmiana prawa była prosta, szybka i niezawodna — sedno wymogu: OPA jako SYSTEM.",
],
subparts=[
dict(name="Audyt istniejącego lifecycle",
goal="co działa, co jest deklaratywne, co brakuje",
questions=[
"Czy SHADOW→CANDIDATE→ACTIVE→ROLLED_BACK działa na danych rejestru (rule_registry.json) z dowodami operacji?",
"Czy awans wymaga kryteriów (testy, delta shadow ≤ 2%, metryki jakości) czy jest ręczny?",
"Czy rollback jest automatyczny przy naruszeniu progów i czy zachowuje audyt?",
"Czy operacje lifecycle są audytowalne (kto/kiedy/dlaczego) i odwracalne?",
]),
dict(name="Dodanie i zmiana reguły",
goal="prostota zmiany przy zachowaniu bramek",
questions=[
"Ile kroków dziś wymaga dodanie reguły — gdzie proces wypada z 7-krokowego celu V1 §3.2?",
"Czy nowa wersja reguły pozostawia starą nietkniętą (immutable) z pełnym time-travel?",
"Czy shadow compare liczony jest automatycznie (delta werdyktów) i alarmuje > 2%?",
"Czy 4-eyes (autor ≠ recenzent ≠ operator) jest egzekwowane technicznie, nie tylko opisane?",
]),
dict(name="Usunięcie i karencja",
goal="bezpieczne wygaszanie bez łamania historii",
questions=[
"Czy deprecate→retire→purge jest zaimplementowane z okresami karencji (2 okresy rozliczeniowe)?",
"Czy purge weryfikuje zero odwołań (werdykty, reguły, testy) przed usunięciem z bundle?",
"Czy generowany jest tygodniowy raport „reguły do usunięcia” — czy ktoś go czyta (telemetria procesu)?",
"Jak usuwanie współgra z golden replay (historia werdyktów nienaruszona)?",
]),
dict(name="Operacje awaryjne",
goal="kill-switch i szybkość reakcji",
questions=[
"Czy POST /rules/{id}/suspend działa w < 1 s (hot-reload) i czy jest audytowany z alertem?",
"Czy można wstrzymać cały pakiet/domenę jednym ruchem — jak to przetestować?",
"Czy istnieje lista zdrowych wersji (healthy_versions) i procedura przywrócenia — jak działa?",
"Jakie SLO dla MTTR (≤ 15 min) i auto-rollback (≤ 5 min) jest dziś mierzone — co brakuje?",
]),
],
file_groups=[
dict(name="Reguły i narzędzia lifecycle", files=[
    ("Lifecycle reguł (reguła)", "JDG/rules/rule_lifecycle_enterprise.rego"),
    ("Manager lifecycle (reguła)", "JDG/rules/lifecycle_manager_enterprise.rego"),
    ("Menedżer cyklu życia (narzędzie)", "JDG/tools/rule_lifecycle_manager.py"),
    ("Control plane lifecycle (narzędzie)", "JDG/tools/control_plane_lifecycle.py"),
    ("Orkiestrator deploymentu", "JDG/tools/deployment_orchestrator.py"),
    ("Orkiestrator rolloutu", "JDG/tools/rollout_orchestrator.py"),
    ("Silnik samonaprawy", "JDG/tools/self_healing_engine.py"),
    ("Silnik niezawodności", "JDG/tools/differential_evaluation.py"),
]),
dict(name="Dane rejestru", files=[
    ("Rejestr reguł (bundle)", "JDG/bundles/rule_registry.json"),
    ("Zdrowe wersje (bundle)", "JDG/bundles/healthy_versions.json"),
    ("Deploymenty (bundle)", "JDG/bundles/deployments.json"),
]),
dict(name="Dokumenty i migracje", files=[
    ("Cykl życia reguł (dokument)", "JDG/docs/RULE_LIFECYCLE.md"),
    ("Control plane lifecycle (dokument)", "JDG/docs/CONTROL_PLANE_RULE_LIFECYCLE.md"),
    ("Migracja 007 — control plane lifecycle", "JDG/migrations/007_jdg_v12_control_plane_lifecycle.sql"),
    ("Migracja 004 — control plane", "JDG/migrations/004_jdg_v9_control_plane.sql"),
]),
dict(name="Testy lifecycle", files=[
    ("Test control plane lifecycle", "JDG/tests/test_control_plane_lifecycle.py"),
    ("Test infrastruktury control plane", "JDG/tests/test_control_plane_infrastructure.py"),
]),
],
focus=[
"Odtwórz ścieżkę zmiany reguły krok po kroku (kod, nie dokumentacja): kto generuje testy, kto liczy delta, kto awansuje.",
"Zaprojektuj kryteria awansu jako zamkniętą listę (testy OK, delta ≤ 2%, jakość ≥ 95%, brak konfliktów) z automatem.",
"Zaprojektuj immutable versions: nowa wersja = nowy wpis, stara nietykalna; edycja pliku na żywo = BLOCKER w CI.",
"Zaprojektuj 4-eyes techniczne: podpisy PR, bramki GitHub/CI, audyt operacji z podpisami ról.",
"Zaprojektuj kill-switch: pauza reguły/pakietu < 1 s, audyt, alert, automatyczny tryb NEEDS_ADVICE dla dotkniętych decyzji.",
"Oceń integrację lifecycle z bundle (P38): czy awans reguły wyzwala build+sign+canary automatycznie?",
"Zaprojektuj tygodniowy raport reguł do usunięcia (stubs, dead rules, deprecations) z telemetrią procesu.",
"Oceń zgodność z Declarative Change (V2/F6) i wskaż, co przenieść do P09.",
"Zaprojektuj „reguła roku podatkowego”: automatyczne wymuszanie wersji na granicy roku (valid_from 01.01).",
"Sprawdź spójność rule_registry.json z kodem (rejestr vs rzeczywistość) — mechanizm rekonsyliacji.",
"Zaprojektuj metryki lifecycle: MTTR, czas PR→produkcja, liczba rollbacków, delta shadow (dashboard SLO).",
"Wskaż ryzyka simultanicznych zmian (dwie reguły w jednej domenie jednocześnie) i zaprojektuj kolejkowanie zmian.",
],
legal=[
"Ordynacja podatkowa — art. 241–241n (umowy/apelacje jako paradygmat wersjonowania i korekt wstecz)",
"Ustawa o VAT — art. 108 (samorzutne korekty stawek jako wzorzec „nowa wersja, stara nietykalna”)",
"Ustawa o PIT — art. 9 ust. 2 (wybór formy na cały rok podatkowy jako wzorzec granic wersji)",
"Ustawa o rachunkowości — art. 4 ust. 5 (stosowanie zasad niezmienionych w roku — paradygmat immutability)",
"Ustawa – Prawo przedsiębiorców — art. 22–25 (zawieszenie/wznowienie jako wzorzec suspend/resume reguły)",
],
innovations=[
("Promotion Contract Engine", "automat oceny kryteriów awansu (testy/delta/jakość) z jawnym wyrokiem i audytem"),
("Immutable Rule Vault", "wersje reguł jako nietykalne artefakty (hash, podpis) z zakazem edycji w CI"),
("Shadow Delta Automator", "automatyczne porównanie shadow↔active na próbce transakcji z raportem różnic"),
("Kill-Switch SLA", "pauza reguły < 1 s z audytem i automatycznym NEEDS_ADVICE dla dotkniętych strumieni"),
("4-Eyes Enforcement Layer", "techniczne wymuszenie separacji ról w pipeline (pr, review, deploy) z podpisami"),
("Retirement Scheduler", "automat: deprecate → karencja → retire → purge z weryfikacją zerowych odwołań"),
("Change Queue & Locks", "kolejkowanie zmian per domena z blokadami (zero symultanicznych zmian konfliktowych)"),
("Fiscal-Year Version Boundary", "automatyczne granice wersji na 01.01 z testami przejścia roku"),
("Registry Reconciler", "rekonsyliacja rule_registry.json ↔ kod (ryzyko dryfu rejestru) w CI"),
("Lifecycle Telemetry", "SLO dashboard: czas PR→produkcja, MTTR, rollbacki, delta shadow, wiek SHADOW"),
("Emergency Runbook DSL", "deklaratywne runbooki awaryjne (scenariusz → kroki → weryfikacja) z testami tabletop"),
("Auto-Post Gate Lifecycle", "reguła może być ACTIVE ale z flagą NO_AUTO_POST — granica zaufania zarządzana w lifecycle"),
],
in_contracts=[
"Honoruj okna temporalne i Snapshot ID z V3_P05 — operacje lifecycle muszą zachowywać ciągłość czasową (dowód P05).",
"Honoruj kontrakt invariants z V3_P04 — naruszenie invariantu = automatyczny rollback wg protokołu P04.",
],
out_contracts=[
"Kryteria awansu i protokół 4-eyes — wiąże P38 (deployment), P40 (jakość) i P44 (certyfikacja).",
"Protokół kill-switch i SLO MTTR — wiąże P43 (security/DR).",
"Proces deprecate→retire→purge — wiąże P39 (testy) i P44.",
"Rejestr zmian jako źródło dla P09 (declarative change) i P08 (Law Radar pipeline).",
],
acceptance_extra=[
"Raport zawiera odtworzoną z kodu (nie z dokumentacji) ścieżkę zmiany reguły krok po kroku z oceną każdego kroku.",
"Projekt zawiera przynajmniej trzy scenariusze awaryjne z runbookiem i przewidywanym czasem reakcji.",
]),
]
