# -*- coding: utf-8 -*-
"""Parts P61-P68: repair wave 3 — integrations, money flow, RBAC/multi-tenant, gap sweep, new tools, chaos, self-learning, re-certification."""
PARTS = [

dict(code="P61", slug="INTEGRACJE_DOMKNIECIE", title="INTEGRACJE ZEWNĘTRZNE — KSEF/MF, BANKI, NBP, ISAP NA POZIOMIE PRODUKCYJNYM",
role="inżynierem integracji systemów zewnętrznych (MF, banki, NBP, ISAP) z doświadczeniem produkcji finansowej",
expertise="kontrakty API zewnętrznych, retry z backoff, circuit breakery, dane referencyjne z provenance, sandbox testowanie",
mission=[
"Zweryfikuj integracje zewnętrzne end-to-end: KSeF/MF (sesje, statusy, UPO — P54 domyka reguły, tu TRANSPORT: autoryzacja, klucze, limity API, timeouty), banki (feed: parowanie płatności, idempotencja, rozjazdy), NBP (kursy: tabela A/B, daty, cache, provenance), ISAP (crawler: kontrakty, cache, świeżość — P47). Każda integracja ma kontrakt (schema, SLA zewnętrzne, retry, circuit breaker, degradacja), test kontraktowy (mock + sandbox) i metryki (P58). Awaria zewnętrzna nie może zatrzymać fortecy — degradacja kontrolowana (kolejki P57, tryby offline P54) i czytelna.",
"Zaprojektuj warstwę integracyjną: kontrakt standardowy (każda integracja: health check, status, degradacja, metryki, runbook), sandbox replay (testy na danych sandbox MF/NBP), provenance danych referencyjnych (kursy z datą+checksumą, akty z URL ISAP), cache z TTL i inwalidacją. Przeprować głęboką analizę: które integracje są realnie podłączone (kod+test), a które tylko nazwane (fasady integracji) — rejestr z planem.",
],
subparts=[
dict(name="Transport KSeF/MF",
goal="transport niezależny od reguł — niezawodny",
questions=[
"Czy autoryzacja (tokeny, certyfikaty KSeF) ma zarządzanie (sejf P59, rotacja, audyt użycia)?",
"Czy limity API MF (rate limits) respektowane (governor P57) z backoff i alarmami?",
"Czy timeouty i circuit breaker (awaria MF → kolejka, nie blokada) są testowane (chaos)?",
"Czy transport jest testowany na sandbox (dane testowe MF) w CI — czy tylko mock?",
]),
dict(name="Banki i płatności",
goal="feed bankowy niezawodny i zparowany",
questions=[
"Czy feed bankowy ma idempotencję (retry nie duplikuje parowania) i rozstrzyganie konfliktów (dwa przelewy, jedna faktura)?",
"Czy rozjazdy (przelew bez faktury, faktura bez przelewu) mają ścieżkę (NEEDS_ADVICE z kandydatami)?",
"Czy parowanie respektuje daty wartości vs księgowania (rozdzielność bankowa)?",
"Czy testy bankowe używają realistycznych danych (multikurencyjność, masowe przelewy)?",
]),
dict(name="NBP i dane referencyjne",
goal="kursy z provenance, cache z inwalidacją",
questions=[
"Czy kursy (tabela A/B) mają provenance (data tabeli, checksuma, URL NBP) i cache z TTL?",
"Czy brak kursu na datę (weekend/święto) ma ścieżkę zgodną z art. 31a (ostatnia dostępna) z testami dat świątecznych?",
"Czy dane referencyjne (kursy, PKWiU, GTU) mają wersjonowanie (P46/P53) i walidację przy odświeżeniu?",
"Czy integracja NBP jest testowana na danych historycznych (replay walutowy P52)?",
]),
dict(name="ISAP i registry",
goal="crawler niezawodny i świeży",
questions=[
"Czy crawler ISAP ma kontrakt (rate limits ISAP, cache, retry) i metryki (P58 freshness per akt)?",
"Czy zmiana strony/struktury ISAP wykrywana jest (health check) i alarmowana (crawler martwy = law radar ślepy)?",
"Czy dane z ISAP są cacheowane z inwalidacją i provenance (URL, data pobrania, checksuma)?",
"Czy sandbox/replay ISAP (dane zapisane) testuje ścieżki prawne bez live dostępu (CI offline)?",
]),
],
file_groups=[
dict(name="Narzędzia integracji", files=[
    ("Pipeline aktualizacji ISAP", "JDG/tools/isap_rule_update_pipeline.py"),
    ("Crawler ISAP", "JDG/tools/isap_crawler.py"),
    ("Kolejka offline KSeF", "JDG/tools/ksef_offline_queue.py"),
    ("Outbox KSeF", "JDG/tools/ksef_outbox.py"),
    ("Test KSeF generator", "JDG/tests/test_ksef_generator.py"),
    ("Test natywny banking automation", "JDG/tests/rego/test_native_banking_automation_enterprise.rego"),
    ("Test natywny edelivery gateway", "JDG/tests/rego/test_native_edelivery_gateway_enterprise.rego"),
    ("Test deadline monitor", "JDG/tests/rego/test_native_deadline_monitor_enterprise.rego"),
]),
dict(name="Dane referencyjne i kursy", files=[
    ("Progi i stawki (dane)", "JDG/bundles/thresholds_data.json"),
    ("Dokument kontrol temporalnych", "JDG/docs/CORE_GUARDS_TEMPORAL_THRESHOLDS.md"),
    ("Test kontrol temporalnych", "JDG/tests/test_core_guards_temporal_thresholds.py"),
    ("Toolkit cross-border", "JDG/tools/p13_crossborder_toolkit.py"),
    ("Dokument cross-border", "JDG/docs/CROSSBORDER_P12.md"),
    ("Test natywny crossborder", "JDG/tests/rego/test_native_crossborder.rego"),
    ("Test natywny cashflow predictor", "JDG/tests/rego/test_native_cashflow_tax_predictor_enterprise.rego"),
    ("Walidator JPK", "JDG/tools/jpk_validator.py"),
]),
dict(name="Monitoring integracji", files=[
    ("Dashboard dryfu", "JDG/tools/drift_dashboard.py"),
    ("Generator metryk", "JDG/tools/metrics_generator.py"),
    ("Chaos engineering", "JDG/tools/chaos_engineering.py"),
    ("Chaos runner", "JDG/tools/chaos_runner.py"),
    ("Silnik self-healing", "JDG/tools/self_healing_engine.py"),
    ("Test risk API", "JDG/tests/test_risk_api.py"),
    ("Test tax pipeline", "JDG/tests/test_tax_pipeline.py"),
    ("Worm storage", "JDG/tools/worm_storage.py"),
]),
],
legal=[
"Ustawa VAT — art. 106na–106nf (KSeF: transport, autoryzacja, sesje — obowiązki podatnika).",
"Ustawa VAT — art. 31a (kursy NBP: tabela, daty — integracja NBP jako obowiązek prawny).",
"Ustawa o rachunkowości — art. 28 ust. 1 pkt 11 (wycena walut: kursy — provenance NBP).",
"Ordynacja podatkowa — art. 193a (weryfikacja: dane z zewnętrznych muszą być odtwarzalne — provenance).",
"RODO — art. 28 (procesory: integracje zewnętrzne z danymi osobowymi — kontekst banków).",
"eIDAS — autoryzacja i podpisy w komunikacji z MF (certyfikaty KSeF).",
"Ustawa o ZUS — art. 47–48 (Płatnik: integracja z systemem ZUS — kontekst P55).",
"AI Act — systemy AI z danymi zewnętrznymi: śledzenie pochodzenia danych (kontekst P33).",
],
innovations=[
("Integration standard contract", "każda integracja: health check, status, degradacja, metryki, runbook — standard wymuszony bramką (zero fasad integracji)."),
("Circuit breaker per integration", "awaria MF/NBP/bank → otwarcie obwodu (kolejka) → półotwarcie (probe) → zamknięcie — testowany chaos (P43)."),
("Reference data provenance chain", "kursy/PKWiU/GTU/akty: data, źródło, checksuma, URL — każda wartość użyta w decyzji ma pochodzenie (audyt schodzi do źródła)."),
("Sandbox replay CI", "testy integracji na danych sandbox (MF, NBP historyczne) w CI — bez live w PR (stabilne, powtarzalne)."),
("Cache with provenance TTL", "cache danych referencyjnych z TTL, inwalidacją i provenance — świeżość (P58) mierzona na cachu (nie tylko na źródle)."),
("Bank reconciliation contract", "parowanie: dopasowanie → rozjazd → NEEDS_ADVICE z kandydatami — zero cichych dopasowań przy konflikcie."),
("Holiday-aware rate path", "brak kursu na weekend/święto: ostatnia dostępna tabela (art. 31a) — testy na kalendarzu świąt 2026–2028."),
("Integration registry", "rejestr integracji (kanał, kontrakt, status REAL/PLANNED/FACADE) — zero integracji nazwanych bez ścieżki."),
("Degradation ladder per integration", "plan degradacji per integracja (pełny → cache → offline → read-only) z deklaracją w nagłówku odpowiedzi (P40)."),
("Outbox pattern for MF", "wzorzec outbox: dokument → kolejka trwała → wysyłka z idempotencją → statusy — awaria nie gubi niczego."),
("External SLA monitoring", "metryki SLA zewnętrznych (latencja MF, dostępność NBP) — dane do negocjacji/zmiany kanału (jeśli nisze)."),
("Integration attestation in certificate", "certyfikat decyzji zawiera wersje danych referencyjnych (kursy, tabele) użytych — pełna odtwarzalność."),
],
in_contracts=[
"Kontrakt ingestu z P57 — integracje wchodzą przez ingest (wspólne walidacje, dedup, statusy).",
"Kontrakt sekretów z P59 — klucze integracji w sejfie (rotacja, audyt).",
],
out_contracts=[
"Rejestr integracji (kanał → kontrakt → status) — wejście do P68 i P41.",
"Kontrakt danych referencyjnych (provenance, cache, walidacja) — wiąże P46, P52, P53.",
"Monitoring integracji (metryki) — wejście do P58.",
],
acceptance_extra=[
"Rejestr integracji z statusem REAL/PLANNED/FACADE per kanał (zero nazwanych bez ścieżki).",
"Circuit breaker przedstawiony jako diagram stanów (zamknięty→otwarty→półotwarty) z pro i testami przejść.",
]),
dict(code="P62", slug="PRZEPYWY_PIENIEZNE", title="PRZEPYWY PIENIĘŻNE — PŁATNOŚCI, PRIORYTETY I CASHFLOW W HORYZONCIE",
role="inżynierem przepływów finansowych (cashflow, płatności) w systemach księgowych z doświadczeniem automatyzacji płatności",
expertise="priorytet płatności, idempotentne wykonanie, harmonogram płatności, cashflow predykcja, odsetki",
mission=[
"Zweryfikuj ścieżkę pieniądza: wyliczenie → priorytet (ZUS > VAT > PIT? co z odsetkami zaległości?) → harmonogram (terminy P25) → wykonanie (idempotentne!) → potwierdzenie (feed bankowy zparowany — P61) → archiwum. Wygeneruj rejestr luk: brak idempotencji wykonania (podwójna płatność!), brak priorytetu regułowego (kolejność ręczna), brak planowania cashflow (terminy bez salda → braki płatnicze), brak odsetek od zaległości (przypominajki), brak trybu awaryjnego (awaria banku → kolejka).",
"Zaprojektuj ścieżkę idealną: silnik płatności (reguły priorytetów z data.thresholds), harmonogram z walidacją salda (cashflow: zaliczki, terminy, saldo prognozowane), wykonanie idempotentne (klucz płatności, duplikat wykrywany), potwierdzenie zparowane z feedem, archiwum WORM. Tryb awaryjny: awaria banku → kolejka offline + przypominajki + rekonsylacja po awarii. Odsetki od zaległości (art. 56 OP) liczone automatycznie (parametry P46) — przedsiębiorca widzi koszt zwłoki na żywo (P40).",
],
subparts=[
dict(name="Priorytet i harmonogram",
goal="kolejność płatności regułowa i walidowana",
questions=[
"Czy priorytet płatności (ZUS/VAT/PIT/inni) jest regułowy (data.thresholds) i testowany (konflikt terminów)?",
"Czy harmonogram waliduje saldo (przyszłe terminy vs prognozowane saldo) — cashflow aware?",
"Czy terminy przenoszone na dni robocze (święta) — kalendarz P25 spójny z płatnościami?",
"Czy konflikt dwóch płatności w tym samym dniu ma regułę rozstrzygania (kwota? odsetki? termin?)?",
]),
dict(name="Wykonanie idempotentne",
goal="płatność wykonana dokładnie raz",
questions=[
"Czy każda płatność ma klucz idempotencji (retry nie duplikuje)?",
"Czy duplikat wykrywany jest (rejestr duplikatów + alarm + procedura zwrotu)?",
"Czy wykonanie ma dwa kroki (rezerwacja → wykonanie) z walidacją między nimi?",
"Czy awaria po wykonaniu (brak potwierdzenia banku) ma ścieżkę (probe + rekonsylacja — P61)?",
]),
dict(name="Cashflow i predykcja",
goal="terminy z saldem — zero braków płatniczych",
questions=[
"Czy cashflow prognozuje saldo (zaliczki, terminy, przychody) w horyzoncie (miesiąc/kwartał)?",
"Czy termin bez salda generuje alert WCZEŚNIE (plan finansowy, nie dzień przed)?",
"Czy cashflow predictor (test natywny istnieje) jest podpięty do harmonogramu płatności?",
"Czy przedsiębiorca widzi prognozę w UI (P40) z akcjami (przesuń płatność? zaliczka?)?",
]),
dict(name="Odsetki i zaległości",
goal="koszt zwłoki widoczny i automatyczny",
questions=[
"Czy odsetki od zaległości (art. 56 OP, stawki P46) liczone automatycznie (na żywo w UI)?",
"Czy przypominajki (7/3/1 dzień przed terminem) są zautomatyzowane (kanał: UI, e-mail)?",
"Czy zaległość wykrywana jest z feedu (brak potwierdzenia w terminie → alarm P0)?",
"Czy ścieżka odsetki → plan spłaty → rekonsylacja jest testowana end-to-end?",
]),
],
file_groups=[
dict(name="Narzędzia płatności i cashflow", files=[
    ("Test priorytetów płatności (kontrakt)", "JDG/tests/test_payment_priority_service.py"),
    ("Test priorytetów (engine)", "JDG/tests/test_priority_engine.py"),
    ("Test natywny cashflow predictor", "JDG/tests/rego/test_native_cashflow_tax_predictor_enterprise.rego"),
    ("Test natywny banking automation", "JDG/tests/rego/test_native_banking_automation_enterprise.rego",
    ),
    ("Kalkulator odsetek (test)", "JDG/tests/rego/test_native_audit_defense_enterprise.rego"),
    ("Kalendarz ZUS (terminy)", "JDG/tools/zus_calendar.py"),
    ("Silnik ryzyka (test)", "JDG/tests/test_risk_guard.py"),
    ("Test integracji silnika ryzyka", "JDG/tests/test_risk_guard_integration.py"),
]),
dict(name="Pipeline i archiwum", files=[
    ("Test tax pipeline", "JDG/tests/test_tax_pipeline.py"),
    ("WORM storage", "JDG/tools/worm_storage.py"),
    ("Rejestr wdrożeń (kontekst wykonania)", "JDG/bundles/deployments.json"),
    ("Dokument automatyzacji", "JDG/docs/AUTOMATYZACJA_KSIEGOWOSCI_P18.md"),
    ("Test payment priority (dane)", "JDG/tests/test_payment_priority_service.py"),
    ("Test fraud graph", "JDG/tests/test_fraud_graph_scanner.py"),
    ("Dokument logika biznesowa", "JDG/docs/LOGIKA_BIZNESOWA.md"),
    ("Kalkulator ZUS (kontekst kwot)", "JDG/tools/zus_calculator.py"),
]),
],
legal=[
"Ordynacja podatkowa — art. 15 (obowiązek podatkowy płatnika: terminy płatności), art. 16 (zaliczki).",
"Ordynacja podatkowa — art. 56 (odsetki od zaległości: stawka i zasady liczenia — parametry P46).",
"Ustawa o ZUS — art. 47–48 (terminy DRA i płatności składek — priorytet).",
"Ustawa VAT — art. 108 (nieprawidłowa stawka: zwrot/płatność — kontekst korekt).",
"Ustawa o rachunkowości — art. 4 ust. 4 (dowody: potwierdzenia płatności zparowane).",
"KKS — art. 56 (uleganie w płatnościach podatkowych: rażące niedbalstwo — kontekst pilności).",
"Ustawa o rachunkowości — art. 5 (zapisy odzwierciedlają wykonane płatności — idempotencja).",
"Prawo bankowe (kontekst) — zlecenia i potwierdzenia: dowody bankowe w rekonsylacji.",
],
innovations=[
("Payment rule engine", "priorytet/konflikty jako reguły z data.thresholds — kolejność płatności z uzasadnieniem (dlaczego ZUS przed VAT — kwota odsetek porównawczo)."),
("Idempotent execution", "klucz płatności (deklaracja+termin+kwota) — retry/duplikat wykrywany; podwójna płatność strukturalnie niemożliwa."),
("Two-phase payment", "rezerwacja → wykonanie z walidacją między (saldo, status) — awaria między fazami = rezerwacja cofnięta."),
("Cashflow-aware schedule", "harmonogram waliduje prognozowane saldo (zaliczki, terminy) — alert WCZEŚNIE (tygodnie, nie godziny) przed brakiem."),
("Interest live view", "odsetki od zaległości liczone na żywo (art. 56 OP, parametry) — przedsiębiorca widzi koszt zwłoki w UI (motywacja do terminowości)."),
("Reminder ladder", "drabina przypomnień (7/3/1 dzień) na kanałach (UI, e-mail) — terminowość wsparta automatyzacją."),
("Payment archive WORM", "potwierdzenia płatności WORM z checksumą — dowody dla audytu i rekonsylacji."),
("Failure mode playbook", "awaria banku: kolejka offline, przypominajki, rekonsylacja po awarii (P61) — playbook testowany chaos (P43)."),
("Payment duplication ledger", "rejestr podwójnych płatności (wykrytych) z procedurą zwrotu — przejrzystość zdarzeń (zero cichych strat)."),
("Balance guard", "płatność nie wychodzi przy prognozowanym saldo < kwota (chyba że override 4-eyes) — ochrona przed debetem podatkowym."),
("Multi-bank ready", "schemat płatności gotowy na wiele banków (tenant_id, bank_id) — rozwój bez migracji."),
("Cashflow scenario runner", "symulacje (nowa inwestycja, zmiana przychodów) → wpływ na terminy i odsetki — planowanie z liczbami (digital twin P33)."),
],
in_contracts=[
"Kontrakt pipeline z P32 — wykonanie płatności etapem pipeline (wspólne statusy, idempotencja).",
"Kalendarz z P25 — terminy płatności z przenoszeniem na dni robocze (jedno źródło).",
],
out_contracts=[
"Kontrakt silnika płatności (priorytety, idempotencja, cashflow) — wiąże P40 (UI), P61 (banki) i P68.",
"Metryki płatności (terminowość, duplikaty, odsetki) — wejście do P58.",
"Playbook awarii płatności — wejście do P43 (DR) i P41 (runbooki).",
],
acceptance_extra=[
"Diagram ścieżki pieniądza (wyliczenie→priorytet→harmonogram→wykonanie→potwierdzenie→archiwum) z punktami walidacji.",
"Rejestr luk z min. 3 scenariuszami awaryjnymi (awaria banku, duplikat, brak salda) i planami reakcji.",
]),
dict(code="P63", slug="RBAC_MULTITENANT", title="RBAC, MULTI-TENANT I DANE — IZOLACJA I UPRawnienia NA POZIOMIE ENTERPRISE",
role="architektem platform SaaS finansowych (multi-tenant, RBAC) z doświadczeniem audytów uprawnień",
expertise="RBAC/ABAC, izolacja tenantów, minimalizacja danych, audyt dostępu, przygotowanie do skalowania",
mission=[
"Przeanalizuj model dostępu: czy API (P40) ma RBAC (role: przedsiębiorca/księgowy/audytor/admin — różne pola), czy dane są izolowane (tenant_id wszędzie — gotowość multi-tenant), czy audyt dostępu istnieje (kto co widział/eksportował — RODO art. 30). Wygeneruj rejestr luk (pola bez RBAC, ścieżki bez audytu, dane osobowe bez minimalizacji) i projekt: RBAC jako dane (role→pola werdyktu), izolacja tenantów w regułach (tenant_id w input — reguły nigdy nie mieszają), audyt dostępu WORM.",
"Zaprojektuj przygotowanie na skalowanie: schemat multi-tenant (tenant_id w każdej tabeli/kolejce/rejestrze), migracja istniejących danych (plan), limitowanie per tenant (quota — ochrona przed hałasem), eksport/usunięcie danych tenant (RODO art. 17 prawo do bycia zapomnianym — ścieżka z WORM retencją prawną). Zero wersji „na razie jedyny tenant” bez schematu — migracja później kosztuje 10× więcej.",
],
subparts=[
dict(name="RBAC i pola werdyktu",
goal="rola ogranicza widok — technicznie",
questions=[
"Czy role (przedsiębiorca/księgowy/audytor/admin) mają mapowanie na pola (przedsiębiorca nie widzi metryk wewnętrznych)?",
"Czy RBAC jest egzekwowany na poziomie API (schema) czy tylko UI (luka: bezpośrednie wywołania)?",
"Czy istnieją testy RBAC (rola X nie widzi pola Y — asercje)?",
"Czy 4-eyes (zatwierdzenia) ma role oddzielone (ten sam user nie może obu ról — separation of duties)?",
]),
dict(name="Izolacja tenantów",
goal="dane nie mieszają się — strukturalnie",
questions=[
"Czy tenant_id jest w: tabelach (migracje), kolejkach, rejestrach, inputach reguł?",
"Czy reguły nigdy nie zwracają danych innego tenant (testy izolacji — asercje)?",
"Czy cache (P61) jest per-tenant (podział kluczy cache)?",
"Czy eksport/usunięcie tenant ma ścieżkę (RODO art. 17/20) z retencją prawną (WORM 5 lat — gdzie granica)?",
]),
dict(name="Audyt dostępu",
goal="kto co widział — dowód",
questions=[
"Czy dostęp do danych osobowych jest audytowany (kto, kiedy, jakie dane, po co) WORM?",
"Czy eksporty są audytowane (jaki pakiet, jaki zakres) — zero cichych eksportów?",
"Czy dostęp awaryjny (break-glass) jest oznaczony i raportowany (po użyciu — review obowiązkowy)?",
"Czy audyt dostępu jest analizowany (anomalie: dostęp w nocy, masowe eksporty) — alarmy P58?",
]),
dict(name="Minimalizacja i retencja",
goal="dane tylko potrzebne i tylko tak długo",
questions=[
"Czy dane osobowe (NIP, imię, adres) są minimalizowane w telemetrii i logach (pseudonimizacja)?",
"Czy retencja (5 lat podatkowa) jest kalkulowana automatycznie (P42) z datą bezpiecznego usunięcia?",
"Czy usunięcie danych po retencji jest zautomatyzowane (nie „kiedyś”) — harmonogram?",
"Czy dokumentacja (P41) opisuje przepływy danych (RODO art. 30 rejestr) — aktualna?",
]),
],
file_groups=[
dict(name="API i dostęp", files=[
    ("Spec OpenAPI", "JDG/api/openapi.yaml"),
    ("Test risk API", "JDG/tests/test_risk_api.py"),
    ("Kontrakt orkiestratora", "JDG/docs/ORCHESTRATOR_DATA_CONTRACT.md"),
    ("Test kontraktu orkiestratora", "JDG/tests/test_orchestrator_data_contract.py"),
    ("Dokument API referencja", "JDG/docs/API_REFERENCJA.md"),
    ("Dashboard pewności (kontekst ról)", "JDG/tools/confidence_dashboard.py"),
    ("Dashboard enterprise", "JDG/tools/enterprise_dashboard.py"),
    ("Serwis certyfikatów (audyt dostępu)", "JDG/tools/certificate_service.py"),
]),
dict(name="RODO i dane", files=[
    ("Dokument RODO/AML", "JDG/docs/RODO_AML_BEZPIECZENSTWO_P16.md"),
    ("Test RODO enterprise", "JDG/tests/test_rodo_enterprise.py"),
    ("Test AML enterprise", "JDG/tests/test_aml_enterprise.py"),
    ("WORM storage", "JDG/tools/worm_storage.py"),
    ("Test coverage unifiera (kontekst retencji)", "JDG/tests/test_coverage_unifier.py"),
    ("Dokument zgodności prawnej", "JDG/docs/ZGODNOSC_PRAWNA.md"),
    ("Test infrastruktury control plane", "JDG/tests/test_control_plane_infrastructure.py"),
    ("Migracja RuleStore 001", "JDG/migrations/001_jdg_rule_store.sql"),
]),
dict(name="Kontekst skalowania", files=[
    ("Migracje (katalog)", "JDG/migrations"),
    ("Migracja 013 (tools/api/rulestore)", "JDG/migrations/013_jdg_v18_tools_api_rulestore_bundles.sql"),
    ("Silnik self-healing", "JDG/tools/self_healing_engine.py"),
    ("Dokument święty 2 (wizja skalowania)", "JDG/docs/WIZJA_OPA_ENTERPRISE_V2.md"),
    ("Test infrastruktury legal twin", "JDG/tests/test_legal_twin_infrastructure.py"),
    ("Katalog narzędzi", "JDG/docs/KATALOG_NARZEDZI.md"),
    ("Szyfrowanie post-quantum", "JDG/tools/quantum_safe_encryption.py"),
    ("Dokument święty 1 (kontekst)", "JDG/docs/ARCHITEKTURA_OPA_ENTERPRISE_TARGET.md"),
]),
],
legal=[
"RODO — art. 5 ust. 1c (minimalizacja), art. 25 (privacy by design — RBAC/izolacja jako mechanizm).",
"RODO — art. 15–22 (prawa podmiotowe: dostęp, sprostowanie, usunięcie art. 17, przenoszenie art. 20).",
"RODO — art. 30 (rejestr czynności przetwarzania), art. 32 (bezpieczeństwo), art. 35 (DPIA multi-tenant).",
"Ustawa o rachunkowości — art. 74 (retencja: 5 lat — granica z prawem do usunięcia RODO).",
"Ustawa o rachunkowości — art. 9 (przetwarzanie po stronie księgowości: dostęp uprawniony).",
"Ustawa AML — art. 48 (bezpieczeństwo informacji — kontekst).",
"eIDAS — autoryzacja dostępu (podpisy/pieczęcie — kontekst audytu dostępu).",
"Ustawa o ZUS — art. 56 (tajemnica: dostęp uprawniony — kontekst RBAC).",
],
innovations=[
("RBAC as data", "role→pola (matrix) w YAML: zmiana uprawnień bez deployu; bramka: test RBAC per rola (asercje pola niewidoczne)."),
("Separation of duties gate", "4-eyes wymaga różnych osób (identyfikator usera vs role) — technicznie egzekwowane (nie dwa konta jednej osoby)."),
("Tenant isolation tests", "asercje: reguła/cache/kolejka nigdy nie przekracza tenant — test izolacji w CI (zero mieszania strukturalnego)."),
("Break-glass with review", "dostęp awaryjny: wyraźnie oznaczony, raportowany, obowiązkowy review po użyciu — kontrole zamiast założeń."),
("Access audit analytics", "analiza audytu dostępu (anomalie: noc, masowe eksporty, powtarzalne wzorce) — alarmy P58 z runbookami."),
("Right-to-be-forgotten workflow", "usunięcie danych tenant: ścieżka z retencją prawną (co usuwane, co retencjonowane do 5 lat, dlaczego) — dokumentowane i testowane."),
("Per-tenant quotas", "limit wolumenu/eval per tenant — ochrona przed hałasem i atakiem (fair use)."),
("Data flow map", "mapa przepływów danych (kanał → magazyn → użycie → retencja) — dokument RODO art. 30 generowany z kodu."),
("Pseudonymization by default", "telemetria/logi/eksporty pseudonimizowane (tenant_id → hash) — RODO by design (minimalizacja mechanizmem)."),
("Multi-tenant schema readiness", "schemat (tenant_id wszędzie) już dziś + plan migracji — gotowość bez future-proofingu na siłę."),
("Permission drift alarm", "nagłe rozszerzenie uprawnień (diff RBAC data) → alarm + review — manipulacja uprawnieniami wykrywalna."),
("Role onboarding pack", "przydział roli = pakiet (dostępy, ścieżka czytania P60, obowiązki) — zero ról bez dokumentu i testu."),
],
in_contracts=[
"Kontrakt API z P40 — RBAC na poziomie API (schema), nie tylko UI.",
"Kontrakt WORM z P42 — audyt dostępu w niezmiennym archiwum.",
],
out_contracts=[
"KONTRAKT RBAC (role→pola, testy) — wiąże P40 (API), P59 (security) i P68.",
"Plan multi-tenant (schema, migracja, quota) — wejście do kampanii przyszłych i P68.",
"Rejestr czynności RODO (art. 30, generowany) — wejście do P41 i P68.",
],
acceptance_extra=[
"Matrix RBAC (4 role × kategorie pól) przedstawiona z asercjami testowymi per komórka.",
"Plan multi-tenant (schema + migracja + quota) z listą elementów wymagających zmiany — kompletny.",
]),
dict(code="P64", slug="LUKA_SWEEP", title="SWEEP LUK REZYDUALNYCH — PRZEGLĄD CAŁOŚCIOWY PO FALACH NAPRAW",
role="głównym audytorem kończącym kampanie naprawcze, wyspecjalizowanym w znajdowaniu tego, co przeoczyły inne fale",
expertise="przegląd resztkowy, krzyżowy przegląd artefaktów, detekcja ślepych plam, rejestr rezydualny",
mission=[
"Po falach naprawczych (P45–P63) wykonaj przejrzenie REZYDUALNE: przejrzyj katalogi (rules, tools, bundles, migrations, tests, docs) w poszukiwaniu elementów nieprzypisanych do żadnej części i luk przeoczonych: pliki osierocone, migracje martwe, reguły niedotykalne przez pipeline (routing), testy osierocone od reguł, dokumenty-widma, narzędzia bez testów. Każdy element: decyzja (przypisz/usuń/napraw) — zero elementów bez właściciela i bez ścieżki.",
"Wygeneruj rejestr rezydualny z planem domknięcia i przypisaniem do fal V4. Wykonaj krzyżowe kontrole: (a) każda reguła ma test? (b) każdy test ma regułę? (c) każde narzędzie ma test? (d) każda integracja ma kontrakt? (e) każda ścieżka decyzyjna ma fail-closed? (f) każdy parametr ma okno? (g) każda podstawa prawna zweryfikowana? — rejestry per kontrola z licznikami. Przeprować głęboką analizę: jakie klasy luk przechodzą przez wszystkie fale (ślepe plamy procesu) i jak je domknąć strukturalnie.",
],
subparts=[
dict(name="Orphan sweep per katalog",
goal="element bez właściciela — wykryty",
questions=[
"Które pliki w rules/ nie są osiągalne z routingu (P02) i nie mają testów (osierocone)?",
"Które narzędzia (tools/) nie mają testów i nie są importowane (martwe)?",
"Które migracje (001–013) nie mają pokrycia w kodzie (martwe — plan archiwizacji)?",
"Które testy testują elementy nieistniejące (osierocone od reguł — rejestr)?",
]),
dict(name="Cross-checks systemowe",
goal="7 kontrol krzyżowych z licznikami",
questions=[
"(a) reguła bez testu — ile i które (per domena)?",
"(b) test bez reguły (osierocone) — ile i które?",
"(c) narzędzie bez testu — ile i które?",
"(d) integracja bez kontraktu (P61) — które kanały?",
"(e) ścieżka decyzyjna bez fail-closed (P49) — które reguły?",
"(f) parametr bez okna (P46/P53) — które wartości?",
"(g) podstawa prawna niezweryfikowana (P47) — które reguły?",
]),
dict(name="Ślepe plamy procesu",
goal="klasy luk przechodzące przez fale",
questions=[
"Które klasy luk (np. „reguła dopisana bez testu przy hotfix”) powtarzają się w wszystkich falach?",
"Jakie kontrolki brakuje w procesie PR (przykład: hotfix bez review prawne)?",
"Które części V3 zadeklarowały „OK” bez dowodu (rejestr deklaracji bez dowodu — P30)?",
"Jak domknąć ślepe plamy strukturalnie (bramka, proces, automat) — plan z terminami?",
]),
dict(name="Rejestr rezydualny i V4",
goal="co zostało — z planem",
questions=[
"Ile pozycji ma rejestr rezydualny (per klasa, per domena, per priorytet)?",
"Które pozycje przechodzą do V4 (z kontraktami) a które domyka się teraz (plan godzinowy)?",
"Jak mierzyć postęp domknięcia (metryki P58) — tablica trendu?",
"Czy rejestr rezydualny jest kompletny (sweep drugiego przebiegu — potwierdzenie stabilności)?",
]),
],
file_groups=[
dict(name="Katalogi do sweep", files=[
    ("Reguły (katalog)", "JDG/rules"),
    ("Narzędzia (katalog)", "JDG/tools"),
    ("Bundles (katalog)", "JDG/bundles"),
    ("Migracje (katalog)", "JDG/migrations"),
    ("Testy (katalog)", "JDG/tests"),
    ("Dokumentacja (katalog)", "JDG/docs"),
    ("Mirror policies (katalog)", "policies/"),
    ("Struktura projektu (dokument)", "JDG/docs/STRUKTURA_PROJEKTU.md"),
]),
dict(name="Narzędzia sweep i rejestrów", files=[
    ("Detektor dead rules", "JDG/tools/dead_rule_detector.py"),
    ("Detektor dead code else-chain", "JDG/tools/else_chain_dead_code_detector.py"),
    ("Detektor konfliktów między pakietami", "JDG/tools/cross_package_conflict_detector.py"),
    ("Walidator spójności dokumentów", "JDG/tools/doc_consistency_validator.py"),
    ("Symulator wpływu reguł", "JDG/tools/rule_impact_simulator.py"),
    ("Crossref plan50", "JDG/tools/crossref_plan50.py"),
    ("Heat mapa pokrycia prawnego", "JDG/tools/legal_coverage_heatmap.py"),
    ("Analizator wpływu migracji", "JDG/tools/migration_impact_analyzer.py"),
]),
dict(name="Kontekst rejestrów", files=[
    ("Status kampanii P00–P30", "JDG/prompts_status.yaml"),
    ("Raport pokrycia", "JDG/COVERAGE_REPORT.md"),
    ("Kanon pokrycia (dane)", "JDG/bundles/coverage_canon.json"),
    ("Pustynie pokrycia (dane)", "JDG/bundles/coverage_deserts.json"),
    ("Inwentaryzacja plików", "JDG/docs/INWENTARYZACJA_PLIKOW.md"),
    ("Raport luk prawnych", "JDG/docs/LEGAL_COVERAGE_GAP_RAPORT.md"),
    ("Test legal source registry", "JDG/tests/test_legal_source_registry.py"),
    ("Katalog narzędzi", "JDG/docs/KATALOG_NARZEDZI.md"),
]),
],
legal=[
"Ordynacja podatkowa — art. 193a (weryfikacja: sweep jako dowód kompletności procesu).",
"Ustawa o rachunkowości — art. 4 ust. 1 (sprawdzalność: każdy element ma właściciela i ścieżkę).",
"Ustawa VAT — art. 109e (kompletność ewidencji — sweep reguł jako warunek).",
"KKS — art. 56 (redukcja ryzyka: rejestr rezydualny jako dowód staranności).",
"RODO — art. 5 ust. 1d (prawidłowość: dane/reguły bez właściciela naruszają prawidłowość).",
"RODO — art. 32 (bezpieczeństwo: przegląd okresowy systemu).",
"Ustawa o ZUS — art. 47 (spójność deklaracji: sweep wyklucza rozjazdy).",
"AI Act — systemy AI: przeglądy okresowe (kontekst P33).",
],
innovations=[
("Sweep register with SLA", "rejestr rezydualny: element → klasa → priorytet → plan → deadline — trend spadkowy (do zera przed P68)."),
("Seven cross-checks suite", "7 kontrol krzyżowych (reguła-test, test-reguła, narzędzie-test, integracja-kontrakt, fail-closed, okno parametru, podstawa) — jako bramki CI z licznikami."),
("Blind-spot taxonomy", "taksonomia ślepych plam (hotfix bez testu, copy-paste bez review, deklaracja bez dowodu) — klasa → kontrola strukturalna."),
("Ownerless artifact detector", "detektor: plik bez odwołania z kodu/dokumentów (orphan) — rejestr z decyzją (przypisz/usuń)."),
("Second-pass stability check", "drugi przebieg sweep po naprawach: rejestr stabilny (zero nowych) = dowód kompletności sweep."),
("Declaration-vs-evidence register", "rejestr deklaracji bez dowodu (z raportów P00–P67) — zero deklaracji bez dowodu w finalnym raporcie."),
("Residual risk score", "skalarne ryzyko rezydualne (liczba luk × waga klas) — trend do P68, próg certyfikacji."),
("Cross-check dashboard", "tablica 7 kontrol (liczniki, trend) — stan kompletności widoczny codziennie."),
("Sweep automation", "sweep jako narzędzie (nie jednorazowa analiza) — uruchamiany cyklicznie (CI weekly) z rejestrem przyrostowym."),
("Handover to V4", "rejestr rezydualny → V4 z kontraktami (dziedziczenie standardów) — zero utraty wiedzy między kampaniami."),
("Sweep of sweeps", "meta-kontrola: czy sweep objął wszystkie katalogi (lista katalogów vs przejrzane) — zero katalogów pominiętych."),
("Residual report format", "standard raportu rezydualnego (klasy, priorytety, plany) — wielokrotnego użytku (V4, kampanie przyszłe)."),
],
in_contracts=[
"Rejestry z P45–P63 (stuby, hardcode, prawne, mirror, fail-closed, duplikaty, pustynie, granice, temporal, KSeF, ZUS, VAT/PIT, ingest, observability, security, docs, integracje, płatności, RBAC) — sweep uzupełnia, nie duplikuje.",
"Kanon artefaktów z P00 — sweep odwołuje się do mapy kanonicznej (zero ponownej inwentaryzacji od zera).",
],
out_contracts=[
"REJESTR REZYDUALNY (kompletny) — wejście do P68 (re-certyfikacja) i V4.",
"Seven cross-checks suite (bramki) — wiąże P39 (CI) i P29 (bramki).",
"Ślepe plamy (taksonomia + kontrole) — wejście do P41 (procesy) i kampanii przyszłych.",
],
acceptance_extra=[
"Rejestr rezydualny z licznikami per kontrola krzyżowa (a–g) i per domena — kompletny.",
"Taksonomia ślepych plam z min. 5 klasami i kontrolami strukturalnymi dla każdej.",
]),
dict(code="P65", slug="NOWE_NARZEDZIA", title="NOWE NARZĘDZIA FORTECY — CO PRZEGAPIŁA FALA (Projekty 8–12 narzędzi)",
role="projektantem narzędzi inżynierskich (developer experience) dla systemów policy-as-code",
expertise="projektowanie CLI/API narzędzi, automatyzacja brakująca, DX, generatory celowane",
mission=[
"Na podstawie luk z P45–P64 zaprojektuj BRAKUJĄCE narzędzia (8–12 projektów kompletnych): np. semantic diff dla Rego (porównanie AST z klasyfikacją zmiany), generator testów z treści przepisu (karty pustyni P51), cashflow simulator (P62), simulator tymczasowy (P53), walidator RBAC (P63), benchmark eval (P37), tamper test WORM (P42), chaos suite prawny (P49). Każde narzędzie: interfejs (CLI/API), dane we/wy, integracja z bramkami (P29) i CI (P39), test, dokumentacja (P41).",
"Wybierz 3 priorytetowe (ROI: wpływ na poprawność vs koszt) i rozwiń do szczegółów: pseudokod, przypadki testowe, integracja, plan wdrożenia z terminem. Narzędzia mają mieć wspólny kontrakt (wejście → raport JSON zgodny z P29, exit codes, dry-run) — spójność narzędziowa fortecy. Przeprować głęboką analizę: które narzędzia da się zbudować z istniejących elementów (kompozycja) a które wymagają nowego kodu.",
],
subparts=[
dict(name="Katalog narzędzi z luk",
goal="8–12 projektów kompletnych",
questions=[
"Które luki (P45–P64) wymagają nowego narzędzia (a które domknie istniejące/kompozycja)?",
"Które narzędzia istnieją, ale wymagają rozszerzenia (o jakie — plan)?",
"Jaki wspólny kontrakt narzędzi (wejście → raport JSON → exit codes → dry-run) — definicja?",
"Które narzędzia wymagają integracji z bramkami (P29) i w jakiej kolejności?",
]),
dict(name="Priorytetowe 3 z szczegółami",
goal="pseudokod, testy, plan wdrożenia",
questions=[
"Które 3 narzędzia mają najwyższe ROI (wpływ na poprawność × częstość użycia / koszt)?",
"Jak wygląda pseudokod (algorytm, struktury) — czytelny dla inżyniera?",
"Jakie przypadki testowe (pozytywne, negatywne, brzegowe) — tabela?",
"Jaki plan wdrożenia (kroki, terminy, zależności, właściciel)?",
]),
dict(name="Kompozycja istniejących",
goal="zero duplikacji — buduj z tego, co jest",
questions=[
"Które nowe narzędzia da się zbudować z kompozycji istniejących (narzędzie A + B + glue)?",
"Które istniejące narzędzia mogą stać się bibliotekami (moduł do importu) — plan refactor?",
"Czy kontrakt raportu JSON (P29) pozwala na łańcuchowanie narzędzi (pipeline narzędzi)?",
"Które narzędzia wymagają nowej zależności (biblioteki) — ryzyko supply chain (P59)?",
]),
dict(name="DX i przyjęcie",
goal="narzędzie używane = wartość",
questions=[
"Jakie CLI/API ergonomia (flagi, output, help) — projekt UX narzędzi?",
"Czy dokumentacja narzędzi (P41) generowana z definicji (zero dryfu)?",
"Czy narzędzia mają tryb CI i tryb lokalny (dla developera) — różnice?",
"Jak mierzyć przyjęcie (metryki użycia) — które narzędzia znikają (nieużywane = dead P50)?",
]),
],
file_groups=[
dict(name="Wzorce narzędzi istniejących", files=[
    ("Walidator spójności dokumentów", "JDG/tools/doc_consistency_validator.py"),
    ("Matryca traceability", "JDG/tools/traceability_matrix.py"),
    ("Analizator wpływu migracji", "JDG/tools/migration_impact_analyzer.py"),
    ("Symulator wpływu reguł", "JDG/tools/rule_impact_simulator.py"),
    ("Heat mapa pokrycia prawnego", "JDG/tools/legal_coverage_heatmap.py"),
    ("Symulator form podatkowych", "JDG/tools/tax_form_whatif_simulator.py"),
    ("Silnik kompletności ZUS", "JDG/tools/zus_completeness_engine.py"),
    ("Śledzacz okresów preferencyjnych", "JDG/tools/preferential_period_tracker.py"),
]),
dict(name="Katalog narzędzi i standardy", files=[
    ("Katalog narzędzi", "JDG/docs/KATALOG_NARZEDZI.md"),
    ("Dokument narzędzi walidacji", "JDG/docs/NARZEDZIA_WALIDACJI_P22.md"),
    ("README narzędzi", "JDG/tools/README.md"),
    ("Dokument OPA Rego developer guide", "JDG/docs/OPA_REGO_DEVELOPER_GUIDE.md",
    ),
    ("Bramka narzędzi", "JDG/tools/tools_quality_v3_16_gate.py",
    ),
    ("Test bramki narzędzi", "JDG/tests/test_tools_quality_v3_16.py"),
    ("Dokument OPA jako system", "JDG/docs/OPA_JAKO_SYSTEM_P21.md",
    ),
    ("Dokument dokumentacja (kontekst DX)", "JDG/docs/DEVELOPER_GUIDE.md"),
]),
],
legal=[
"Ordynacja podatkowa — art. 119a (GAAR: narzędzia defensywne — wykrywanie agresywnych ścieżek).",
"Ustawa o rachunkowości — art. 4 ust. 1 (narzędzia jako gwarancja sprawdzalności).",
"Ustawa o rachunkowości — art. 5 (narzędzia pilnujące pierwotności dowodów).",
"Ustawa VAT — art. 109e (narzędzia kompletności ewidencji).",
"Ustawa o PIT — art. 9a (narzędzia spójności dokumentacji i ewidencji).",
"RODO — art. 25 (privacy by design: narzędzia minimalizacji).",
"Ustawa o ZUS — art. 47 (narzędzia terminowości).",
"KKS — art. 56 (narzędzia wczesnej detekcji błędów).",
],
innovations=[
("Tool standard contract", "każde narzędzie: wejście → raport JSON (schema P29) → exit codes → dry-run — spójność narzędziowa (łańcuchowanie w CI)."),
("Semantic diff for Rego", "porównanie AST (warunki, progi, skutki) z klasyfikacją zmiany (kosmetyczna/progowa/semantyczna) — różne ścieżki review."),
("Rule-to-tests generator", "generator testów z treści przepisu (karty pustyni P51): struktura przypadków brzegowych z przepisu — przyspieszenie 5×."),
("Cashflow simulator", "symulacja płynności (terminy, salda, odsetki) — scenariusze dla przedsiębiorcy (P62 digital twin)."),
("Temporal simulator", "symulacja przełączeń day-0 (nowela przed wejściem) — planowanie zmian bez ryzyka (P53 sandbox)."),
("RBAC validator", "walidacja matrix RBAC (P63): rola bez testu = BLOCKER; automatyczne testy per komórka matrix."),
("Eval benchmark tool", "benchmark wydajności eval (P37): p95 latencji per domena, próg regresji w CI."),
("WORM tamper tester", "test integralności WORM (próba modyfikacji → wykrywalna) — dowód niezmienności (P42/P59)."),
("Legal chaos suite", "chaos prawny (P49): mutacje przepisów (parametryzacja) z asercją fail-closed — defensywność mierzalna."),
("Composition-first rule", "przed nowym narzędziem: sprawdzenie kompozycji (A+B+glue) — zero duplikacji funkcjonalności."),
("Tool adoption metrics", "metryki użycia narzędzi (CI wywołania) — narzędzie nieużywane → plan (poprawa DX albo usunięcie P50)."),
("Tool documentation generator", "dokumentacja generowana z definicji narzędzia (zero dryfu — P60 binding)."),
],
in_contracts=[
"Rejestry luk z P45–P64 — narzędzia domykają rejestry (każde narzędzie wiąże się z luką).",
"Kontrakt raportu JSON z P29 — wspólny format wyjścia narzędzi.",
],
out_contracts=[
"KATALOG NARZĘDZI NOWYCH (8–12 projektów, 3 szczegółowe) — wejście do P68 i V4.",
"Wspólny kontrakt narzędzi (standard) — wiąże P29, P36 (generatory) i P41 (docs).",
"Plan wdrożenia 3 priorytetowych (terminy, właściciele) — wejście do V4 i P68.",
],
acceptance_extra=[
"Katalog 8–12 narzędzi z kontraktem wspólnym — 3 z pełnymi szczegółami (pseudokod, testy, plan).",
"Analiza kompozycji (które narzędzia z istniejących elementów) — zero duplikacji funkcjonalności.",
]),
dict(code="P66", slug="CHAOS_ODPORNOSC", title="CHAOS I ODPORNOŚĆ — FORTECA TESTOWANA NISZCZYCIELEM",
role="inżynierem chaos engineering dla systemów finansowych krytycznych, projektantem eksperymentów odpornościowych",
expertise="eksperymenty chaos (input, data, zależności, czas), asercje fail-closed, steady state hypothesis, blast radius",
mission=[
"Zaprojektuj program chaos engineering: steady state hypothesis (system w normie: decyzje płyną, latencja < SLO, fail-closed działa) → eksperymenty (mutacje input/data, awarie integracji P61, opóźnienia, zatrzymanie zależności, corrupt WORM, brak kursu NBP, awaria MF w szczycie deklaracji) → asercje (zero cichych AUTO_POST, kolejki rosną kontrolnie, degradacja czytelna, alarmy działają) → blast radius (eksperymenty w izolacji, nie na produkcji bez wyłącznika).",
"Wygeneruj rejestr eksperymentów (10–15) z: hipotezą, krokiem, asercją, rollback, metrykami (P58), harmonogramem (chaos day co miesiąc?). Zintegruj z chaos_runner (istnieje) — program ciągły, nie jednorazowy. Przeprować głęboką analizę: które scenariusze awarii są najbardziej prawdopodobne (MF w szczycie, NBP w weekend, bank w połowie miesiąca) i najbardziej kosztowne (błędne deklaracje masowe) — priorytety eksperymentów.",
],
subparts=[
dict(name="Steady state i hipotezy",
goal="co jest normą — mierzalne",
questions=[
"Jak zdefiniować steady state (metryki normy: wolumen decyzji, latencja, wskaźnik NEEDS_ADVICE) — liczby?",
"Jakie hipotezy odporności („przy awarii MF kolejka rośnie, deklaracje spóźnione zero”)?",
"Jak weryfikować hipotezę (przed/po eksperyment — metryki porównanie)?",
"Które hipotezy są testowalne automatycznie (CI) a które wymagają chaos day (kontrolowany)?",
]),
dict(name="Katalog eksperymentów",
goal="10–15 eksperymentów z pełnym projektem",
questions=[
"Które mutacje input/data (P49 chaos suite) rozszerzyć o zależności (MF, NBP, bank, ISAP)?",
"Jak wygląda karta eksperymentu (hipoteza, kroki, asercja, rollback, metryki, blast radius)?",
"Które eksperymenty mają najwyższe ROI (prawdopodobieństwo × koszt awarii)?",
"Jak wygląda harmonogram (chaos day co miesiąc? eksperymenty w CI co PR?)",
]),
dict(name="Asercje i bezpieczeństwo eksperymentów",
goal="eksperyment nie zniszczy fortecy",
questions=[
"Jakie asercje obowiązkowe (zero cichych AUTO_POST — najważniejsza)?",
"Jak ograniczyć blast radius (środowisko izolowane, wyłącznik, ograniczenie czasu)?",
"Jak rollback eksperymentu (przywrócenie stanu — automatyczny)?",
"Czy eksperymenty na produkcji mają wyłącznik awaryjny (kill switch) i godzinę okna?",
]),
dict(name="Program ciągły",
goal="odporność utrzymywana, nie deklarowana",
questions=[
"Czy chaos_runner podpięty do harmonogramu (CI weekly / chaos day monthly)?",
"Jak dokumentować wyniki (rejestr eksperymentów z trendem odporności)?",
"Jak luki wykryte chaosem wchodzą do rejestru napraw (P64)?",
"Jak mierzyć dojrzałość chaos (poziomy: eksperymenty w CI → chaos day → game days)?",
]),
],
file_groups=[
dict(name="Narzędzia chaos", files=[
    ("Chaos engineering", "JDG/tools/chaos_engineering.py"),
    ("Chaos runner", "JDG/tools/chaos_runner.py"),
    ("Silnik self-healing", "JDG/tools/self_healing_engine.py"),
    ("Digital twin simulator", "JDG/tools/digital_twin_simulator.py"),
    ("Test edge cases enterprise", "JDG/tests/test_edge_cases_enterprise.py"),
    ("Test natywny edge cases", "JDG/tests/rego/test_native_edge_cases_enterprise.rego"),
    ("Test natywny red team etap27", "JDG/tests/rego/test_native_cross_domain_red_team_etap27.rego"),
    ("Symulator wpływu reguł", "JDG/tools/rule_impact_simulator.py"),
]),
dict(name="Degradacja i ciągłość", files=[
    ("Kolejka offline KSeF", "JDG/tools/ksef_offline_queue.py"),
    ("Outbox KSeF", "JDG/tools/ksef_outbox.py"),
    ("Zrzuty DR (katalog)", "JDG/bundles/dr_snapshots"),
    ("Zdrowe wersje", "JDG/bundles/healthy_versions.json"),
    ("Test weryfikatora inwariantów", "JDG/tools/verify_verdict_invariants.py"),
    ("Test edge cases (dane)", "JDG/tests/test_edge_cases_enterprise.py"),
    ("Test konfliktów enterprise", "JDG/tests/test_conflicts_enterprise.py"),
    ("Silnik tierów health", "JDG/tools/health_tier_engine.py"),
]),
dict(name="Kontekst odporności", files=[
    ("Dokument święty 1 (kontekst)", "JDG/docs/ARCHITEKTURA_OPA_ENTERPRISE_TARGET.md"),
    ("Dokument święty 2 (kontekst)", "JDG/docs/WIZJA_OPA_ENTERPRISE_V2.md"),
    ("Workflow jakości", "JDG/.github/workflows/jdg-quality.yml"),
    ("Dokument rule lifecycle", "JDG/docs/RULE_LIFECYCLE.md"),
    ("Dashboard dryfu", "JDG/tools/drift_dashboard.py"),
    ("Test natywny decision composer", "JDG/tests/rego/test_native_decision_composer_enterprise.rego"),
    ("Kalkulator KKS kary (kontekst skutków)", "JDG/tools/kks_penalty_simulator.py"),
    ("Dokument RODO/AML", "JDG/docs/RODO_AML_BEZPIECZENSTWO_P16.md"),
]),
],
legal=[
"RODO — art. 32 ust. 1 pkt d (proces regularnego testowania i oceny skuteczności środków technicznych — chaos jako wymóg).",
"Ustawa o rachunkowości — art. 4 ust. 1 (odporność jako gwarancja rzetelności wyliczeń w warunkach awarii).",
"Ustawa VAT — art. 109e (kompletność ewidencji niezależnie od warunków awaryjnych).",
"Ustawa o ZUS — art. 47 (terminy nienaruszalne — odporność chroni terminowość).",
"Ordynacja podatkowa — art. 56 (odsetki: awaria nie jest zwolnieniem — odporność minimalizuje koszt).",
"KKS — art. 56 (chaos jako dowód staranności — redukcja ryzyka czynu zabronionego).",
"UKSC (kontekst) — testy odporności systemów krytycznych.",
"AI Act — odporność systemów AI na błędne dane (kontekst P33).",
],
innovations=[
("Steady state hypothesis pack", "definicja normy (metryki, progi) jako dane — hipotezy testowalne automatycznie (przed/po eksperyment)."),
("Experiment card standard", "karta eksperymentu (hipoteza, kroki, asercje, rollback, blast radius, metryki) — standard wielokrotnego użytku."),
("Dependency chaos matrix", "macierz: zależność (MF/NBP/bank/ISAP) × tryb awarii (timeout, błąd, zatrzymanie) → oczekiwane zachowanie — 15+ kombinacji testowanych."),
("Kill switch for experiments", "wyłącznik awaryjny eksperymentu (sekundy, nie minuty) — eksperymenty bezpieczne dla produkcji."),
("Chaos day calendar", "cykliczny chaos day (miesięczny) z planem eksperymentów i raportem luk — odporność ćwiczona, nie deklarowana."),
("Auto-rollback experiments", "asercja złamana → automatyczny rollback eksperymentu + raport — zero eksperymentów pozostawionych w złym stanie."),
("Chaos maturity ladder", "poziomy dojrzałości (L1: eksperymenty w CI → L5: game days z zespołem) — ścieżka rozwoju odporności."),
("Failure injection as data", "definicje awarii w YAML (typ, zależność, czas, nasilenie) — nowe scenariusze bez kodu."),
("Chaos findings to repair register", "luki wykryte chaosem → rejestr napraw (P64) z SLA — chaos karmi proces naprawczy."),
("Resilience trend metric", "wskaźnik odporności (eksperymenty zaliczone/wszystkie) — trend kwartalny do P68."),
("Peak-time chaos", "eksperymenty w szczycie deklaracji (symulowane) — najgorsze momenty testowane świadomie."),
("Game day scenario pack", "scenariusze game days (awaria złożona: MF+NBP+bank) — trening zespołu, nie tylko systemu."),
],
in_contracts=[
"Kontrakt chaos z P49 (chaos input suite) — chaos P66 rozszerza o zależności (integracje, czas, dane).",
"Metryki z P58 — eksperymenty mierzone metrykami (przed/po, hipotezy).",
],
out_contracts=[
"KATALOG EKSPERYMENTÓW (10–15 z kartami) — wejście do P68 i P43 (DR drills).",
"Program chaos (harmonogram, dojrzałość) — wiąże P39 (CI) i P41 (runbooki).",
"Rejestr luk chaos (feed do napraw) — wejście do P64 i V4.",
],
acceptance_extra=[
"Katalog eksperymentów z min. 10 kartami (hipoteza, asercja, rollback, metryki) — gotowe do uruchomienia.",
"Macierz chaos zależności (zależność × tryb awarii) z oczekiwanymi zachowaniami — kompletna.",
]),
dict(code="P67", slug="SELF_LEARNING", title="SELF-LEARNING FORTECY — PĘTLA WIEDZY Z DECYZJI I WYJĄTKÓW",
role="projektantem systemów uczących się z human-in-the-loop w domenach regulowanych (finance, tax)",
expertise="pętla feedback z decyzji, klasterizacja NEEDS_ADVICE, sugestie reguł z wyjątków, guardrails AI (P33), metryki uczenia",
mission=[
"Zaprojektuj pętlę samouczenia: decyzje (AUTO_POST i NEEDS_ADVICE) → analiza wzorców (klaster: powtarzalne NEEDS_ADVICE = kandydat na regułę; AUTO_POST z późniejszą korektą = słaba reguła) → sugestie (propozycje reguł/parametrów z dowodami statystycznymi) → human-in-the-loop (4-eyes) → lifecycle (P07) → telemetria (P58). Silnik ma się uczyć z własnych wyjątków — prawnie bezpiecznie (AI proponuje, człowiek decyduje, SMT/Z3 weryfikuje — P33).",
"Zaprojektuj metryki uczenia: (a) liczba klasterów NEEDS_ADVICE → nowych reguł (przyspieszenie domykania pustyni P51), (b) wskaźnik korekt AUTO_POST (spadek = reguły lepsze), (c) czas do reguły z wyjątku (trend). Guardrails: sugestia nie może omijać SMT/Z3, golden replay, 4-eyes — pętla uczenia w granicach fortecy (nie samowola AI). Przeprować głęboką analizę: jakie dane uczące są dostępne (certyfikaty P11, korekty, przeglądy operatorów) i jakie brakują (plan domknięcia).",
],
subparts=[
dict(name="Pętla feedback z decyzji",
goal="decyzje karmią reguły",
questions=[
"Jak klasterizować NEEDS_ADVICE (powody, domeny, kwoty) — kandydaci na nowe reguły?",
"Jak wykrywać słabe reguły (AUTO_POST → korekta w X dni — wskaźnik per reguła)?",
"Jak sugestia reguły powstaje (statystyka klaster → draft reguły → walidacja → 4-eyes)?",
"Jak pętla respektuje lifecycle (P07): sugestia → SHADOW → walidacja → CANDIDATE → ACTIVE?",
]),
dict(name="Dane uczące",
goal="co karmi uczenie",
questions=[
"Czy certyfikaty (P11) mają strukturę przyjazną analizie (powody NEEDS_ADVICE ustrukturyzowane)?",
"Czy korekty (rekonsylacje P62) są sprzężone z regułami (która reguła zawiniła)?",
"Czy przeglądy operatorów (P35 feedback loop) są rejestrowane (dane uczące)?",
"Jakich danych brakuje (np. wyniki przeglądów prawnych — P47 mediacje) — plan domknięcia?",
]),
dict(name="Guardrails uczenia",
goal="AI proponuje, forteca decyduje",
questions=[
"Czy sugestia omija SMT/Z3 (P33) — jak wymusić ścieżkę walidacji?",
"Czy golden replay (P10) obowiązuje sugestie (regresja = odrzucenie)?",
"Czy 4-eyes jest egzekwowane na sugestiach (dwaj ludzie przed SHADOW)?",
"Czy sugestie mają epokę prawną (P53) — zmiana prawa unieważnia sugestie (procesy czasowe)?",
]),
dict(name="Metryki uczenia",
goal="uczenie mierzalne",
questions=[
"Jakie metryki (advice→rule conversion, korekta rate, czas-do-reguły) — definicje i progi?",
"Czy metryki w P58 — wspólne źródło (zero duplikacji)?",
"Jak raportować pętlę (dashboard uczenia: klaster → sugestia → status)?",
"Jak mierzyć, że uczenie pomaga (przyspieszenie domykania pustyni — porównanie z P51)?",
]),
],
file_groups=[
dict(name="Narzędzia AI i analizy", files=[
    ("Adaptive trust score", "JDG/tools/adaptive_trust_score.py"),
    ("Predyktor orzeczeń", "JDG/tools/judgment_predictor.py"),
    ("Generator reguł AI", "JDG/tools/ai_augmented_rule_generator.py"),
    ("LLM bridge", "JDG/tools/llm_bridge.py"),
    ("Weryfikacja SMT/Z3", "JDG/tools/smt_z3_verification.py"),
    ("Auditor innowacji neural mesh", "JDG/tools/neural_mesh_innovations_auditor.py"),
    ("Digital twin simulator", "JDG/tools/digital_twin_simulator.py"),
    ("Dashboard pewności", "JDG/tools/confidence_dashboard.py"),
]),
dict(name="Rejestry decyzji i korekt", files=[
    ("Rejestr certyfikatów decyzji", "JDG/bundles/decision_certificates.json"),
    ("Metryki pewności (dane)", "JDG/bundles/metrics_pewnosci.json"),
    ("Serwis certyfikatów", "JDG/tools/certificate_service.py"),
    ("Złote orzeczenia", "JDG/bundles/golden_verdicts.json"),
    ("Dokument neural mesh", "JDG/docs/NEURAL_MESH_INNOWACJE_P20.md"),
    ("Dokument dashboard pewności", "JDG/docs/PEWNOSC_DASHBOARD.md"),
    ("WORM storage", "JDG/tools/worm_storage.py"),
    ("Metryki pewności (tool)", "JDG/tools/pewnosc_metrics.py"),
]),
dict(name="Guardrails i lifecycle", files=[
    ("Menedżer lifecycle", "JDG/tools/rule_lifecycle_manager.py"),
    ("Dokument rule lifecycle", "JDG/docs/RULE_LIFECYCLE.md"),
    ("Dokument kontrol temporalnych", "JDG/docs/CORE_GUARDS_TEMPORAL_THRESHOLDS.md"),
    ("Test natywny GAAR shield", "JDG/tests/rego/test_native_gaar_shield_enterprise.rego"),
    ("Dokument święty 2 (kontekst)", "JDG/docs/WIZJA_OPA_ENTERPRISE_V2.md"),
    ("Dokument OPA jako system", "JDG/docs/OPA_JAKO_SYSTEM_P21.md"),
    ("Dokument automatyzacji", "JDG/docs/AUTOMATYZACJA_KSIEGOWOSCI_P18.md"),
    ("Dokument legal twin traceability", "JDG/docs/LEGAL_TWIN_TRACEABILITY.md"),
]),
],
legal=[
"RODO — art. 22 (decyzje zautomatyzowane: człowiek w pętli — human-in-the-loop jako wymóg prawny).",
"RODO — art. 13 ust. 2 lit. f (informacja o logice automatycznego przetwarzania — przejrzystość sugestii).",
"AI Act — nadzór człowieka nad systemami AI (guardrails jako wymóg regulacyjny).",
"Ordynacja podatkowa — art. 119a (GAAR: uczenie nie może promować agresywnych ścieżek).",
"Ustawa o rachunkowości — art. 4 ust. 1 (uczenie nie narusza rzetelności — walidacje obowiązkowe).",
"Ustawa VAT — art. 108 (sugestie stawek zawsze walidowane ISAP — P47).",
"Ustawa o ZUS — art. 18a (sugestie parametrów przez lifecycle, nie bezpośrednio).",
"KKS — art. 56 (pętla uczenia jako dowód staranności — redukcja błędów).",
],
innovations=[
("Advice-to-rule pipeline", "klaster NEEDS_ADVICE → draft reguły (generator) → SMT/Z3 → golden replay → 4-eyes → SHADOW — wyjątek dziś, reguła jutro."),
("Correction-rate per rule", "wskaźnik: reguły z korektami po AUTO_POST — słabe reguły widoczne (trend spadkowy = uczenie działa)."),
("Learning telemetry in P58", "metryki uczenia w katalogu (advice→rule, korekta rate, czas-do-reguły) — wspólne źródło."),
("Suggestion expiry by law epoch", "sugestie mają epokę prawną (P53) — nowela unieważnia sugestie (stale learning = zero)."),
("Guardrails enforcement tests", "testy: sugestia bez SMT/Z3/replay/4-eyes odrzucana — guardrails technicznie, nie proceduralnie."),
("Learning dashboard", "tablica pętli: klaster → sugestia → status (SHADOW/ACTIVE) → efekt (spadek NEEDS_ADVICE) — uczenie widoczne."),
("Data readiness register", "rejestr danych uczących (co dostępne, czego brakuje, plan) — uczenie nie zaczyna się od zera przy V4."),
("Human feedback loop", "przeglądy operatorów (P35) jako dane uczące — oceny decyzji karmią sugestie (pętla zamknięta)."),
("Learning safety metrics", "metryki bezpieczeństwa uczenia (ile sugestii odrzucono przez SMT/Z3/replay) — forteca broni się przed złym uczeniem."),
("Knowledge base from verdicts", "baza wiedzy z certyfikatów (powody, wykładnia) — zapytywalna (kiedy podobny przypadek → podobne rozwiązanie)."),
("Curriculum for rules", "kolejkowanie sugestii (ROI: częstość przypadku × wpływ) — uczenie priorytetyzowane biznesowo."),
("Post-learning replay", "po wdrożeniu reguły z sugestii: replay historii na nowej regule (czy przeszłość zmienia decyzje — P10 powiązany)."),
],
in_contracts=[
"Warstwa AI z P33 — sugestie przez sandbox (SMT/Z3, audit promptów) — pętla uczenia w granicach.",
"Lifecycle z P07 — sugestie jako SHADOW/CANDIDATE (zero bypass).",
],
out_contracts=[
"KONTRAKT PĘTLI UCZENIA (pipeline, guardrails, metryki) — wejście do P68 i V4.",
"Metryki uczenia (definicje) — wejście do P58.",
"Rejestr danych uczących (status + plan) — wejście do V4.",
],
acceptance_extra=[
"Pętla uczenia przedstawiona jako diagram (decyzja → analiza → sugestia → walidacje → lifecycle) z punktami guardrails.",
"Metryki uczenia z definicjami i progami (min. 4 metryki) — mierzalne od startu.",
]),
dict(code="P68", slug="RECERTYFIKACJA_FINALNA", title="RE-CERTYFIKACJA FORTECY — DOWÓD STANU PO FALACH NAPRAWCZYCH",
role="przewodniczącym komisji re-certyfikacyjnej, składającym finalny raport właścicielowi po falach naprawczych",
expertise="synteza fal naprawczych, rozliczenie rejestrów (P45–P67), hard gates certyfikacji, mapa V4",
mission=[
"Rozlicz fale naprawcze: dla każdego rejestru (P45 stuby, P46 hardcode, P47 prawne, P48 mirror, P49 fail-closed, P50 duplikaty, P51 pustynie, P52 granice, P53 temporal, P54 KSeF, P55 ZUS, P56 VAT/PIT, P57 ingest, P58 observability, P59 security, P60 docs, P61 integracje, P62 płatności, P63 RBAC, P64 sweep, P65 narzędzia, P66 chaos, P67 uczenie) — status domknięcia z dowodami. Hard gates: zero stubów ACTIVE, zero hardcode wartości prawnych, 100% podstaw zweryfikowanych lub oznaczonych, zero dryfu mirror semantycznego, zero ścieżek fail-open na AUTO_POST — naruszenie = brak re-certyfikacji (raport „brak” z listą).",
"Zdefiniuj certyfikat re-certyfikacji: scoreboard filarów (Legal Twin, Golden Oracle, Certificate, Radar, Change, Fail-closed, Precyzja arytmetyczna, Odporność, Uczenie) z statusem DOWIEDZONE/CZĘŚCIOWE/DEKLAROWANE i dowodami. Mapa V4: co dalej (fale, priorytety, kontrakty dziedziczone z V3). Ocena własna: czy forteca jest ufortyfikowana — argumentacja za/przeciw z dowodami. Zero sellingu: raport ma być prawdą weryfikowalną, nie marketingiem.",
],
subparts=[
dict(name="Rozliczenie rejestrów naprawczych",
goal="każdy rejestr z statusem i dowodami",
questions=[
"Które rejestry (P45–P67) domknięte (trend do zera / cele osiągnięte) — z dowodami (rejestry, metryki)?",
"Które rejestry częściowo domknięte (ile pozycji zostało, plan, deadline)?",
"Które hard gates naruszone (stuby ACTIVE, hardcode, fail-open, dryf) — lista BLOCKERÓW?",
"Czy drugi przebieg sweep (P64) potwierdza stabilność (zero nowych luk) — dowód?",
]),
dict(name="Scoreboard filarów",
goal="filary z statusem dowodowym",
questions=[
"Legal Twin: pokrycie (P51) z pełnym łańcuchem — % i trend?",
"Golden Oracle: replay przeszłości (P53) — czy działa grosz w grosz?",
"Decision Certificate: kompletność certyfikatów (P11) — próba pobrana i zweryfikowana?",
"Law Radar i Declarative Change: zmiana prawa → zmiana reguł — czas i ścieżka (case study)?",
]),
dict(name="Hard gates i certyfikat",
goal="dowód, nie deklaracja",
questions=[
"Jaka jest pełna lista hard gates (P45–P67 + P44) — z statusem per gate?",
"Czy zero_defect_certification (P42) i final_certification_v4_gate są spójne z hard gates?",
"Które twierdzenia pozostają [NIEZWERYFIKOWANE] — jawne ograniczenia certyfikatu?",
"Kto podpisuje (4-eyes) i jak archiwizowany (WORM, hash, retencja)?",
]),
dict(name="Mapa V4 i ocena własna",
goal="kontynuacja i prawda",
questions=[
"Które kontrakty V3 dziedziczy V4 (lista, źródło prawdy) — zero utraty standardów?",
"Które fale V4 (nowe akty 2027, AI rozwój, integracje) — priorytety z rejestrem rezydualnym (P64)?",
"Jak mierzyć postęp V4 (metryki P58) i kiedy kolejna re-certyfikacja (polityka odnowienia)?",
"Czy forteca jest ufortyfikowana (ocena własna za/przeciw z dowodami) — zero sellingu?",
]),
],
file_groups=[
dict(name="Certyfikacja i rejestry finalne", files=[
    ("Gate certyfikacji finalnej v4", "JDG/tools/final_certification_v4_gate.py"),
    ("Test certyfikacji finalnej v4", "JDG/tests/test_final_certification_v4.py"),
    ("Certification zero-defect", "JDG/tools/zero_defect_certification.py"),
    ("Rejestr certyfikatów decyzji", "JDG/bundles/decision_certificates.json"),
    ("Evidence final certification v4", "JDG/bundles/final_certification_v4_evidence.json"),
    ("Kanon pokrycia (dane)", "JDG/bundles/coverage_canon.json"),
    ("Złote orzeczenia", "JDG/bundles/golden_verdicts.json"),
    ("Status kampanii P00–P30", "JDG/prompts_status.yaml"),
]),
dict(name="Rejestry naprawczych (kontrola domknięcia)", files=[
    ("Rule registry (stuby/unikalność)", "JDG/bundles/rule_registry.json"),
    ("Progi i stawki (hardcode check)", "JDG/bundles/thresholds_data.json"),
    ("Pustynie pokrycia (domknięcie)", "JDG/bundles/coverage_deserts.json"),
    ("Rejestr wdrożeń (historia)", "JDG/bundles/deployments.json"),
    ("Zdrowe wersje (stabilność)", "JDG/bundles/healthy_versions.json"),
    ("Enterprise operating contract", "JDG/bundles/enterprise_operating_contract.json"),
    ("Raport pokrycia", "JDG/COVERAGE_REPORT.md"),
    ("Test kontraktu enterprise", "JDG/tests/test_enterprise_operating_contract.py"),
]),
dict(name="Dokumenty święte i kontekst", files=[
    ("Dokument święty 1", "JDG/docs/ARCHITEKTURA_OPA_ENTERPRISE_TARGET.md"),
    ("Dokument święty 2", "JDG/docs/WIZJA_OPA_ENTERPRISE_V2.md"),
    ("Legal Twin raport", "JDG/docs/LEGAL_TWIN_RAPORT.md"),
    ("Raport luk prawnych", "JDG/docs/LEGAL_COVERAGE_GAP_RAPORT.md"),
    ("Zgodność prawna", "JDG/docs/ZGODNOSC_PRAWNA.md"),
    ("Audit podstaw prawnych", "JDG/docs/AUDYT_PODSTAW_PRAWNYCH.md"),
    ("Kalendarz zmian prawnych", "JDG/docs/KALENDARZ_ZMIAN_PRAWNYCH.md"),
    ("Inwentaryzacja plików", "JDG/docs/INWENTARYZACJA_PLIKOW.md"),
]),
],
legal=[
"Wszystkie akty z Sekcji 8 części P00–P67 — certyfikat re-certyfikacji agreguje statusy weryfikacji per akt (ISAP).",
"Ordynacja podatkowa — art. 119a, 199a (finalna ocena zgodności klauzul i interpretacji).",
"Ustawa o rachunkowości — art. 4, 74–75 (certyfikat jako dowód rzetelności, retencja).",
"RODO — art. 5.2, 24, 30 (rozliczalność i rejestr czynności — certyfikat jako dokument).",
"AI Act — dokumentacja finalna (kontekst warstwy AI P33/P67).",
"Ustawa VAT/PIT/ZUS — finalne pokrycie materiałowe per podatek (status DOWIEDZONE/CZĘŚCIOWE).",
"KKS — finalna redukcja ryzyka (dowód z testów fail-closed i chaos).",
"eIDAS — podpis certyfikatu (integralność i autentyczność deklaracji).",
],
innovations=[
("Hard gate certificate", "re-certyfikat wydawany wyłącznie gdy wszystkie hard gates zamknięte — inaczej raport „brak re-certyfikacji” z listą (zero marketingu)."),
("Register settlement table", "tabela rozliczenia: rejestr → cel → status (DOMKNIĘTY/CZĘŚCIOWY) → dowód → trend — dla każdego z 23 rejestrów."),
("Filar scoreboard V3", "9 filarów z statusem DOWIEDZONE/CZĘŚCIOWE/DEKLAROWANE i dowodami — prawdziwy obraz fortecy."),
("Residual → V4 map", "rejestr rezydualny (P64) → fale V4 (priorytety, kontrakty) — zero utraty wiedzy między kampaniami."),
("Success metric freeze V3", "definicja sukcesu jako dane (metryki + progi) przed oceną — ocena na dowodach, nie na wrażeniu."),
("Certificate WORM + signature", "re-certyfikat podpisany i archiwizowany WORM z retencją — dowód na lata."),
("Renewal policy", "polityka odnowienia (nowelizacje, deploy krytyczny, czas — wygaśnięcie certyfikatu) — certyfikat żywy, nie wieczny."),
("Owner attestation", "właściciel potwierdza przyjęcie z zastrzeżeniami (4-eyes biznesowe) — domknięcie po stronie biznesowej."),
("Knowledge transfer pack", "pakiet przekazania (rejestry, runbooki, kontrakty, kontakty) — forteca operowalna przez innych."),
("Fortress self-portrait V3", "auto-portret: diagram + tabela (komponenty, kontrakty, dowody) — punkt wejścia dla każdego nowego."),
("Truth-first attestation", "deklaracja: co DOWIEDZONE, co CZĘŚCIOWE, co DEKLAROWANE — zero sellingu (każde twierdzenie z artefaktem)."),
("Campaign post-mortem", "post-mortem kampanii V3 (co zadziałało, co nie, co zmienić w V4) — uczenie się procesu kampanii."),
],
in_contracts=[
"Wszystkie kontrakty wyjściowe P00–P67 (rozliczasz każdy w tabeli rozliczenia).",
"Definicja sukcesu z README serii V3 (rozliczasz filar po filarze z dowodami).",
],
out_contracts=[
"RE-CERTYFIKAT FINALNY (scoreboard, hard gates, ograniczenia) — dla właściciela projektu.",
"Rejestr V4 (kontrakty dziedziczone + fale + metryki) — wejście do przyszłych kampanii.",
"Knowledge transfer pack — dla zespołu operacyjnego (V4 i produkcja).",
],
acceptance_extra=[
"Tabela rozliczenia 23 rejestrów (P45–P67) ze statusem i dowodami — kompletna.",
"Ocena własna fortecy (za/przeciw) z argumentacją dowodową — zero sellingu, tylko prawda.",
]),
]
