# -*- coding: utf-8 -*-
"""Parts P29-P36: quality wave, report gates, audits and tools of the V3 campaign."""
PARTS = [

dict(code="P29", slug="KAMPANIE_JAKOSCI_V3", title="KAMPANIE JAKOŚCI V3 — 8 BRAMEK (MICRO/HYPER/ENTERPRISE/TOOLS/TESTS_CI/BUNDLES/API_UI/DOCS)",
role="headem jakości inżynierii policy-as-code, projektantem bramek jakościowych i audytorem kampanii naprawczych w repozytoriach klasy enterprise",
expertise="definicja bramek merge, kampanie naprawcze, metryki jakości rego, sanitizacja flaków testowych, audyt kompletności dokumentacji",
mission=[
"Zweryfikuj istnienie, semantykę i szczelność OŚMIU bramek jakości v3 (v3_13 micro, v3_14 hyper, v3_15 enterprise, v3_16 tools, v3_17 tests_ci, v3_18 bundles, v3_19 api_ui, v3_20 docs) oraz ich testów. Bramka bez testu, test bez asercji negatywnej albo bramka pomijalna w CI to luka BLOCKER: forteca jest silna dokładnie tak bardzo, jak jej najszczelniejsza bramka.",
"Zaprojektuj podniesienie każdej bramki do standardu: deterministyczne wyznaczanie statusu, brak stanu zależnego od kolejności uruchomień, raport wyjściowy w kontrakcie werdyktu, propagacja wyniku do Decision Certificate. Wskaż bramki fasadowe (zawsze zielone) i zaprojektuj dla nich realne asercje. Przeprować głęboką analizę kosztów: które kontrole przesunąć z pytest do native Rego (szybszy feedback na PR), a które zostawić w Pythonie.",
],
subparts=[
dict(name="Bramki rego/micro i hyper (v3_13, v3_14)",
goal="szczelność bramek jakości reguł micro i hiperkontekstów",
questions=[
"Czego dokładnie pilnują bramki micro (duplikaty rule_id? stuby? else-chain?) — odnieś się do kodu bramek?",
"Czy bramka hyper wykrywa konflikty plan45 z domenami VAT/PIT/ZUS/RODO, czy tylko sprawdza obecność plików?",
"Które asercje są zawsze-zielone (fasada) i jakie realne asercje zaproponujesz zamiast nich?",
"Jak wynik bramki wpływa na status SHADOW/CANDIDATE/ACTIVE reguł objętych kontrolą?",
]),
dict(name="Bramki enterprise, tools i tests_ci (v3_15, v3_16, v3_17)",
goal="jakość warstwy enterprise, spójność narzędzi i zdrowie CI",
questions=[
"Czy bramka enterprise weryfikuje kontrakt werdyktu 25-polowy (ADR-004), czy tylko statyczne schematy?",
"Które narzędzia są nieużywane przez żadną bramkę (martwe narzędzia) — jak je albo podłączysz, albo usuniesz?",
"Czy tests_ci pilnuje flaków (kolejność, czas, zależność od sieci) i czy wymaga seedowalności?",
"Jaki jest minimalny próg pokrycia blokujący merge i czy jest on egzekwowany, czy tylko raportowany?",
]),
dict(name="Bramki bundles, api_ui i docs (v3_18, v3_19, v3_20)",
goal="integralność bundle, spójność API/UI i kompletność dokumentacji",
questions=[
"Czy bramka bundles wykrywa rozjazd manifest_v2 vs rule_registry vs pliki .rego (checksum, liczby)?",
"Czy specyfikacja openapi.yaml jest walidowana przy każdej zmianie API (breaking change = BLOCKER)?",
"Czy bramka docs wykrywa odwołania do nieistniejących plików i liczby sprzeczne z MANIFEST?",
"Które dokumenty są wymagane dla każdego nowego pakietu (konwencja: README + kontrakt + testy)?",
]),
dict(name="Integracja bramek z lifecycle i certyfikacją",
goal="spina bramki z cyklem życia reguł i finalną certyfikacją fortecy",
questions=[
"Które bramki są wymogiem przejścia CANDIDATE→ACTIVE, a które działają tylko na produkcji (monitoring)?",
"Jak automatycznie otworzyć powrót SHADOW, gdy bramka produkcyjna wykryje dryf po wdrożeniu?",
"Czy P44 (certyfikacja) może polegać na wynikach tych bramek jako dowodzie — czego jeszcze potrzebuje?",
"Zaprojektuj pojedynczy raport jakości zbiorczy (jeden JSON → dashboard → certyfikat).",
]),
],
file_groups=[
dict(name="Bramki jakości v3", files=[
    ("Bramka micro", "JDG/tools/micro_quality_v3_13_gate.py"),
    ("Bramka hyper", "JDG/tools/hyper_quality_v3_14_gate.py"),
    ("Bramka enterprise", "JDG/tools/enterprise_quality_v3_15_gate.py"),
    ("Bramka tools", "JDG/tools/tools_quality_v3_16_gate.py"),
    ("Bramka tests_ci", "JDG/tools/tests_ci_quality_v3_17_gate.py"),
    ("Bramka bundles", "JDG/tools/bundles_quality_v3_18_gate.py"),
    ("Bramka api_ui", "JDG/tools/api_ui_quality_v3_19_gate.py"),
    ("Bramka docs", "JDG/tools/docs_quality_v3_20_gate.py"),
    ("Bramka ksef v3", "JDG/tools/ksef_jpk_v3_gate.py"),
    ("Bramka kampanii v3", "JDG/tools/v3_campaign_gate.py"),
]),
dict(name="Testy bramek jakości", files=[
    ("Test micro", "JDG/tests/test_micro_quality_v3_13.py"),
    ("Test hyper", "JDG/tests/test_hyper_quality_v3_14.py"),
    ("Test enterprise", "JDG/tests/test_enterprise_quality_v3_15.py"),
    ("Test tools", "JDG/tests/test_tools_quality_v3_16.py"),
    ("Test tests_ci", "JDG/tests/test_tests_ci_quality_v3_17.py"),
    ("Test bundles", "JDG/tests/test_bundles_quality_v3_18.py"),
    ("Test api_ui", "JDG/tests/test_api_ui_quality_v3_19.py"),
    ("Test docs", "JDG/tests/test_docs_quality_v3_20.py"),
]),
dict(name="Dokumenty jakości i CI", files=[
    ("Testy Rego i CI (dokument)", "JDG/docs/TESTY_REGO_CI_P23.md"),
    ("Workflow jakości JDG", "JDG/.github/workflows/jdg-quality.yml"),
    ("Dokument cyklu życia reguł", "JDG/docs/RULE_LIFECYCLE.md"),
    ("Dokument control plane", "JDG/docs/CONTROL_PLANE_RULE_LIFECYCLE.md"),
    ("Plan pokrycia 95%", "JDG/tools/coverage_95_plan.py"),
    ("Narzędzie bramki pokrycia testów", "JDG/tools/test_coverage_gate.py"),
    ("Auditor CI rego", "JDG/tools/test_rego_ci_auditor.py"),
]),
],
legal=[
"Ustawa o rachunkowości — wymóg rzetelności i sprawdzalności dowodów księgowych (weryfikacja ISAP).",
"Ordynacja podatkowa (art. 119a, 193a) — odpowiedzialność za rzetelne procesy wyznaczania zobowiązania.",
"RODO (art. 5 ust. 2, art. 24) — rozliczalność procesów automatycznych (dowód działania bramek).",
"KKS (art. 56) — karalność za błędne deklaracje: jakość procesu redukuje ryzyko czynu zabronionego.",
"Ustawa VAT — obowiązek prawidłowego wyliczenia i terminowości JPK_V7 (jakość reguł = jakość deklaracji).",
"Prawo przedsiębiorców (art. 8b) — minimalizacja obciążeń compliant business; automatyzacja z dowodem.",
"Ustawa o ZUS — poprawność składek zależy od jakości reguł (bramki pilnują regresji).",
"Regulamin ISAP/RCL — weryfikacja tekstów aktów używanych w testach granicznych.",
],
innovations=[
("Bramka łączna (composite quality gate)", "jeden punkt wejścia uruchamiający 8 bramek z uniformowanym raportem JSON i wspólnym exit-code semantyki dla CI."),
("Mutation testing dla reguł", "automatyczne mutacje reguł (zmiana progu, odwrócenie warunku) z asercją, że testy je ZŁAPIĄ — mierzy realną czułość suite'a, nie linie pokrycia."),
("Quality debt ledger", "rejestr długów jakości z datami, właścicielem i ścieżką spłaty; bramka wymusza spłatę przed dodawaniem nowych reguł."),
("Deterministyczny seed dla testów", "każdy test losowy ma seed zapisywany w nazwie raportu; replay 1:1 po awarii."),
("Profil czasowy bramek", "śledzenie czasu wykonania każdej bramki; alarm przy dryfie >50% (sygnał degradacji repo)."),
("Kontrakt bramki jako dane", "definicja bramki (kontrole, progi, zakres) w YAML — zmiana progu bez deployu kodu, zgodna z P06 (parametry-as-data)."),
("Auto-kwit blokujący merge", "wynik bramki generuje komentarz PR z listą łamanych kontrol i dokładnymi liniami Rego."),
("Mapa cieplna jakości domen", "agregacja wyników 8 bramek do heateampy per domena (VAT/PIT/ZUS/...) z trendem kwartalnym."),
("Detekcja fasadowych asercji", "statyczna analiza testów: test bez asercji negatywnej oznaczany jako fasada z rejestru wymagań."),
("Powiązanie bramek z Decision Certificate", "certyfikat decyzji zawiera ID wersji bramek, które przepuściły reguły — pełny dowód provenance."),
("Automatyczny upgrade testów", "generator testów granicznych z tabeli aktów (P36) podłączony pod bramki v3 jako wymóg CANDIDATE→ACTIVE."),
("Raport zgodności z dokumentami świętymi", "kontrola, że bramki nie dopuszczają rozwiązań sprzecznych z ARCHITEKTURA_OPA_ENTERPRISE_TARGET.md i WIZJA_OPA_ENTERPRISE_V2.md."),
],
in_contracts=[
"Standard identyfikatorów i raportów z P00 (mapa kanoniczna) — bramki muszą emitować zgodne nazwy.",
"Kontrakt werdyktu 25-polowy z P03 — wynik bramki jest wejściem do kompozycji decyzji.",
],
out_contracts=[
"Rejestr bramek i ich kontroli (tabela: bramka → kontrola → zakres → próg → test) dla P39 (CI) i P44 (certyfikacja).",
"Lista fasad (testy/bramki bez realnych asercji) z priorytetem naprawy dla P34/P36.",
"Standard raportu jakości JSON (schema + przykłady) obowiązujący P37 (obserwowalność) i P44.",
],
acceptance_extra=[
"Każda z 8 bramek v3 ma w raporcie wiersz: kontrola → test → status szczelności → plan naprawy.",
"Mutation testing zaprojektowane dla min. 1 domeny (przykład end-to-end z wynikami oczekiwanymi).",
]),
dict(code="P30", slug="FALE_INNOWACJI_GATES", title="FALE INNOWACJI — 24 GATE'Y RAPORTÓW R01–R24 I SPÓJNOŚĆ WDROŻEŃ",
role="inżynierem kampanii innowacyjnych i audytorem wdrożeń po raportach GLM, specjalistą od śledzenia cyklu pomysł→raport→kod→test→produkcja",
expertise="gate'y raportów, konwersja rekomendacji na zadania, detekcja wdrożeń fasadowych, pomiar wskaźnika wdrożenia (adopt-rate)",
mission=[
"Zmapuj 24 gate'y raportów (report01–report24) do domen i oceniaj: czy gate weryfikuje RZECZYSTE wdrożenie rekomendacji z raportu GLM (kod + testy), czy tylko obecność plików o właściwej nazwie. Fasadowe wdrożenia (plik istnieje, semantyki nie ma) to największe zagrożenie rzetelności kampanii — wymień je wszystkie z dowodami.",
"Zaprojektuj nadrzędny rejestr wdrożeń: każda rekomendacja z raportów poprzednich kampanii ma status OPEN/IN_PROGRESS/DONE/REJECTED z dowodem (commit, test, artefakt). Na tej podstawie policz realny adopt-rate kampanii i wskaż rekomendacje warte wdżenia w V3. Przeprować głębokie myślenie nad priorytetyzacją: wpływ na poprawność księgowania vs koszt wdrożenia.",
],
subparts=[
dict(name="Gate'y rdzenia systemowego (report01–report08)",
goal="orchestrator, VAT, PIT, ZUS, KKS, Ordynacja — wdrożenia rdzenia",
questions=[
"Czy gate report01 pilnuje kontraktu danych orkiestratora z ORCHESTRATOR_DATA_CONTRACT.md?",
"Które innowacje z raportów VAT (R02/R03) i PIT (R04/R05) są w kodzie, a które tylko na papierze?",
"Czy ZUS (R06) i KKS (R07) mają wdrożone własne toolkit'y z testami granicznymi groszowymi?",
"Czy Ordynacja (R08) wdrożyła symulator odsetek/przedawnień z dowodami testowymi?",
]),
dict(name="Gate'y księgowości i domen szczególnych (report09–report15)",
goal="księgowość, cross-border, PCC, lifecycle, hyper, RODO/AML/BDO, KSeF",
questions=[
"Czy R09 (księgowość) wdrożył zamknięcie miesiąca UoR z pełnym śladem audytowym?",
"Które elementy cross-border (R10) i PCC (R11) są fasadowe (plik bez semantyki)?",
"Czy R12 (lifecycle/ryczałt) respektuje P07 (SHADOW→ACTIVE) i P06 (parametry-as-data)?",
"Czy KSeF/JPK (R15) wdrożył kolejki offline/outbox z idempotencją wysyłki?",
]),
dict(name="Gate'y systemowe i AI (report16–report22)",
goal="OPA jako system, AI/enterprise, narzędzia, control plane, bundle",
questions=[
"Czy R16 (OPA jako system) domknął luki L1–L12 z ANALIZA_STANU_OPA_JAKO_SYSTEM.md?",
"Czy innowacje AI (R17/R18) mająsandbox izolacji (brak wpływu na decyzje bez human-in-the-loop)?",
"Czy R20–R22 wdrożyły control plane, natywne testy rego i synchronizację mirror policies?",
"Które rekomendacje są sprzeczne z dokumentami świętymi i wymagają odrzucenia z uzasadnieniem?",
]),
dict(name="Rejestr wdrożeń i adopt-rate",
goal="pojedyncze źródło prawdy o tym, co rzeczywiście wdrożono",
questions=[
"Jak zautomatyzować weryfikację DONE (commit hash + test + artefakt, bez ręcznych deklaracji)?",
"Które rekomendacje wiszą OPEN najdłużej i dlaczego (zależności? koszt? brak decyzji człowieka)?",
"Jak mierzyć adopt-rate per domena i per fala (raport → wdrożenie)?",
"Zaprojektuj proces selekcji rekomendacji do kampanii V4 z scoringiem ROI.",
]),
],
file_groups=[
dict(name="Gate'y rdzenia i domen (R01–R15)", files=[
    ("Gate R01 orchestrator", "JDG/tools/orchestrator_core_report01_gate.py"),
    ("Gate R02 VAT core", "JDG/tools/vat_core_report02_gate.py"),
    ("Gate R03 VAT micro", "JDG/tools/vat_micro_report03_gate.py"),
    ("Gate R04 PIT core", "JDG/tools/pit_core_report04_gate.py"),
    ("Gate R05 PIT enterprise", "JDG/tools/pit_enterprise_report05_gate.py"),
    ("Gate R06 ZUS", "JDG/tools/zus_report06_gate.py"),
    ("Gate R07 KKS", "JDG/tools/kks_report07_gate.py"),
    ("Gate R08 Ordynacja", "JDG/tools/ordynacja_obrona_report08_gate.py"),
    ("Gate R09 księgowość", "JDG/tools/ksiegowosc_report09_gate.py"),
    ("Gate R10 cross-border", "JDG/tools/crossborder_report10_gate.py"),
    ("Gate R11 PCC/lokalne/akcyza", "JDG/tools/pcc_lokalne_akcyza_report11_gate.py"),
    ("Gate R12 ryczałt lifecycle", "JDG/tools/ryczalt_cykl_zycia_report12_gate.py"),
    ("Gate R13 hiperkonteksty", "JDG/tools/hyper_konteksty_report13_gate.py"),
    ("Gate R14 RODO/AML/BDO", "JDG/tools/rodo_aml_bdo_report14_gate.py"),
    ("Gate R15 KSeF/JPK", "JDG/tools/ksef_jpk_report15_gate.py"),
]),
dict(name="Gate'y systemowe i AI (R16–R24)", files=[
    ("Gate R16 OPA jako system", "JDG/tools/opa_system_report16_gate.py"),
    ("Gate R16 innowacje systemowe", "JDG/tools/system_opa_innovations_report16_gate.py"),
    ("Gate R17 enterprise AI", "JDG/tools/enterprise_ai_report17_gate.py"),
    ("Gate R18 enterprise AI neural", "JDG/tools/enterprise_ai_neural_report18_gate.py"),
    ("Gate R18 narzędzia systemowe", "JDG/tools/tools_system_report18_gate.py"),
    ("Gate R19 automatyzacja księgowości", "JDG/tools/automatyzacja_ksiegowosci_report19_gate.py"),
    ("Gate R20 control plane", "JDG/tools/system_opa_control_plane_report20_gate.py"),
    ("Gate R21 native rego", "JDG/tools/native_rego_report21_gate.py"),
    ("Gate R22 bundle+API", "JDG/tools/bundle_api_report22_gate.py"),
    ("Gate R22 mirror policies", "JDG/tools/policies_mirror_report22_gate.py"),
    ("Gate R23 dokumentacja", "JDG/tools/documentation_report23_gate.py"),
    ("Gate R24 forteca", "JDG/tools/forteca_report24_gate.py"),
    ("Gate R24 legal twin", "JDG/tools/legal_twin_report24_gate.py"),
    ("Gate R24 policies", "JDG/tools/policies_report24_gate.py"),
    ("Gate R20 pytest", "JDG/tools/pytest_report20_gate.py"),
]),
dict(name="Dokumenty fali innowacji", files=[
    ("OPA jako system P21", "JDG/docs/OPA_JAKO_SYSTEM_P21.md"),
    ("Neural mesh P20", "JDG/docs/NEURAL_MESH_INNOWACJE_P20.md"),
    ("Narzędzia walidacji P22", "JDG/docs/NARZEDZIA_WALIDACJI_P22.md"),
    ("Automatyzacja księgowości P18", "JDG/docs/AUTOMATYZACJA_KSIEGOWOSCI_P18.md"),
    ("Etapy kampanii 10–28", "JDG/docs/KAMPANIA_GLM52_ETAPY_10_28.md"),
    ("Kalendarz zmian prawnych", "JDG/docs/KALENDARZ_ZMIAN_PRAWNYCH.md"),
    ("Status promptów P00–P30", "JDG/prompts_status.yaml"),
]),
],
legal=[
"Ordynacja podatkowa — art. 119a (klauzula GAAR), art. 21 (obowiązek współpracy), art. 193a (weryfikacja).",
"Ustawa o rachunkowości — art. 4 ust. 1 (rzetelność), art. 5 (archiwum dowodowe decyzji).",
"Ustawa VAT — art. 106b–109e (ewidencje), art. 108 (nieprawidłowa stawka).",
"Ustawa o PIT — art. 22–30c (przychody/koszty, ryczałt).",
"KKS — art. 56, art. 57 (czyn zabroniony: błędna deklaracja; wdrożenia reguł redukują ryzyko).",
"RODO — art. 22 (zautomatyzowane decyzje) i art. 35 (DPIA dla systemów AI w księgowości).",
"AI Act (EU) — klasyfikacja ryzyka systemów AI wspierających decyzje podatkowe (weryfikacja statusu).",
"Ustawa o ZUS — terminowość i poprawność składek (efekt wdrożeń reguł ZUS).",
],
innovations=[
("Rejestr wdrożeń jako dane", "JSON/YAML w repo z pollingiem CI: status DONE wymaga dowodu (test zielony + plik), automatyzacja wykrywania fałszywych DONE."),
("Adopt-rate dashboard", "metryka per domena: % rekomendacji wdrożonych z dowodem; trend w P37."),
("Diff semantyczny wdrożenia", "porównanie AST/rego sugerowanego w raporcie vs zaimplementowanego — wykrywa wdrożenia fasadowe."),
("Kontrakt selekcji V4", "scoring rekomendacji (wpływ na AUTO_POST, koszt, ryzyko prawne) zautomatyzowany w narzędziu."),
("Traceability rekomendacja→PR", "każdy PR referuje ID rekomendacji z raportu; reverse-check wykrywa PR bez pochodzenia."),
("Wind-down fasad", "kampania automatycznego usunięcia martwych plików fasadowych (z rejestrem i skanem zależności)."),
("Progowanie ryzyka rekomendacji", "klasyfikacja rekomendacji: trywialna / istotna / krytyczna z różnymi ścieżkami wdrożenia (4-eyes dla krytycznych)."),
("Golden replay po wdrożeniu", "każde wdrożenie uruchamia replay golden verdicts (P10) — regresja blokuje merge."),
("Budget wdrożeniowy", "limit zmian w jednym wdrożeniu (maks. N reguł), by awaria była lokalizowalna."),
("Data-driven changelog", "automatyczny changelog z rejestru wdrożeń (domena, rekomendacja, dowód, ryzyko) dla audytu."),
("Detekcja wdrożeń konfliktowych", "porównanie wdrożeń między domenami wykrywające sprzeczne implementacje tej samej zasady."),
("Zamknięcie pętli z Law Radar", "rekomendacje prawne z P08 automatycznie tworzą wpisy w rejestrze wdrożeń (nigdy nie giną)."),
],
in_contracts=[
"Kanon inwentaryzacji z P00 — zakaz traktowania deklaracji DONE bez dowodu (kod+test) jako faktu.",
"Kontrakt bramek jakości z P29 — gate'y raportów korzystają z tego samego raportu JSON.",
],
out_contracts=[
"REJESTR WDROŻEŃ (statusy + dowody + adopt-rate) — wejście do P44 (certyfikacja) i P41 (dokumentacja).",
"Lista fasad i rekomendacji sprzecznych z dokumentami świętymi — priorytety naprawy dla P34.",
"Kontrakt selekcji rekomendacji (schema + scoring) — wejście do kampanii przyszłych (P44 referuje).",
],
acceptance_extra=[
"Każdy gate R01–R24 ma wiersz: domena → weryfikuje semantykę, czy tylko obecność → dowód.",
"Adopt-rate policzony co najmniej dla 3 domen z jawnym metodologią (tabela z liczbami).",
]),
dict(code="P31", slug="ETAPY_AUDYTOW_12_28", title="ETAPY AUDYTÓW 12–28 — DOMKNIĘCIE CYKLU KAMPANII ETAPOWEJ",
role="audytorem końcowym kampanii etapowej i specjalistą od syntezy wyników audytów wielodomowych w systemach policy-as-code",
expertise="audyty etapowe, synteza wyników, rozliczenie deklaracji z dowodami, decyzja o statusie fortecy",
mission=[
"Przeanalizuj 17 audytów etapowych (etap12 ZUS core → etap28 final certification): ich kod, testy, raporty wynikowe. Dla każdego etapu rozlicz: co deklarował, co weryfikuje, czego nie obejmuje. Etapy to kampania poprzednia — V3 nie kopiuje wyników, tylko weryfikuje, czy ich deklaracje są dowiedzione w obecnym stanie repozytorium.",
"Zaprojektuj supersyntezę: jeden raport scalający wyniki etapów z wynikami gate'ów R01–R24 (P30) i bramek v3 (P29) w pojedynczą mapę ryzyka fortecy. Wskaż sprzeczności między etapami (np. etap deklaruje kompletność ZUS, a etap13 wykrywa luki micro) i zaprojektuj mechanizm rozstrzygania (najnowszy dowód wygrywa, ale z rejestrem).",
],
subparts=[
dict(name="Etapy ZUS i księgowości (12–15)",
goal="audytów ZUS core/micro, PKPiR, UoR",
questions=[
"Czy etap12/13 pilnują specyfiki ZUS (30-krotność, ulgi, chorobowe) czy tylko plików?",
"Czy etap14 (PKPiR) weryfikuje zamknięcie miesiąca i przeniesienia między kolumnami?",
"Czy etap15 (UoR) domyka korekty wyniku i różnice z PKPiR?",
"Które deklaracje etapów 12–15 nie mają pokrycia testowego dzisiaj?",
]),
dict(name="Etapy domen pozostałych (16–21)",
goal="KKS/Ordynacja, cross-border, lifecycle biznesowy, lokalne/akcyza, KSeF/JPK, RODO/AML/BDO/HR",
questions=[
"Czy etap16 (KKS/Ordynacja) testuje przedawnienie i karę wytaczaną jednocześnie?",
"Czy etap17 (cross-border) obejmuje waluty i WDT po zmianach 2025/2026?",
"Czy etap18 (cykl życia firmy) pokrywa zawieszenie i sukcesję end-to-end?",
"Czy etapy 20–21 testują KSeF 2.0 i HR/PPK z granicami dat?",
]),
dict(name="Etapy systemowe (22–28)",
goal="hiperkonteksty, AI/enterprise, tests/CI, tools/api/rulestore/bundles, mirror sync, red team, certyfikacja",
questions=[
"Czy etap22 (hiperkonteksty) jest spójny z P28 (plan45) — kto jest źródłem prawdy?",
"Czy etap23 (AI) egzekwuje human-in-the-loop dla decyzji AUTO_POST?",
"Czy etap26 (mirror sync) ma test wykrywający dryf canonical vs policies?",
"Czy etap27 (red team) generuje ataki regułowe (mutacje input) z asercją fail-closed?",
]),
dict(name="Supersynteza wyników",
goal="jedna mapa ryzyka z etapów, gate'ów i bramek",
questions=[
"Jak skalować zgodność między raportami (kto wygrywa przy sprzeczności)?",
"Czy można automatycznie wygenerować syntezę (narzędzie) — podaj projekt interfejsu?",
"Które ryzyka przekraczają etapy i domeny (wspólna przyczyna główna)?",
"Czy syntezę można podpiąć pod Decision Certificate jako tło ryzyka decyzji?",
]),
],
file_groups=[
dict(name="Audyty etapów 12–19", files=[
    ("Etap12 ZUS core", "JDG/tools/zus_core_etap12_audit.py"),
    ("Etap13 ZUS micro", "JDG/tools/zus_micro_etap13_audit.py"),
    ("Etap14 PKPiR", "JDG/tools/pkpir_etap14_audit.py"),
    ("Etap15 UoR", "JDG/tools/uor_etap15_audit.py"),
    ("Etap16 KKS/Ordynacja", "JDG/tools/kks_ord_etap16_audit.py"),
    ("Etap17 cross-border", "JDG/tools/crossborder_etap17_audit.py"),
    ("Etap18 cykl życia", "JDG/tools/business_lifecycle_etap18_audit.py"),
    ("Etap19 lokalne/akcyza", "JDG/tools/local_excise_etap19_audit.py"),
]),
dict(name="Audyty etapów 20–28", files=[
    ("Etap20 KSeF/JPK", "JDG/tools/ksef_jpk_etap20_audit.py"),
    ("Etap21 RODO/AML/BDO/HR", "JDG/tools/rodo_aml_bdo_hr_etap21_audit.py"),
    ("Etap22 hiperkonteksty", "JDG/tools/hyper_enterprise_contexts_etap22_audit.py"),
    ("Etap23 AI neural", "JDG/tools/enterprise_ai_neural_etap23_audit.py"),
    ("Etap24 tests/CI", "JDG/tools/tests_ci_quality_etap24_audit.py"),
    ("Etap25 tools/api/rulestore", "JDG/tools/tools_api_rulestore_bundles_etap25_audit.py"),
    ("Etap26 mirror sync", "JDG/tools/policies_mirror_sync_etap26_audit.py"),
    ("Etap27 red team", "JDG/tools/cross_domain_red_team_etap27_audit.py"),
    ("Etap28 certyfikacja", "JDG/tools/final_certification_etap28_audit.py"),
]),
dict(name="Testy etapów", files=[
    ("Test PKPiR etap14", "JDG/tests/test_pkpir_etap14_audit.py"),
    ("Test UoR etap15", "JDG/tests/test_uor_etap15_audit.py"),
    ("Test KKS/Ord etap16", "JDG/tests/test_kks_ord_etap16_audit.py"),
    ("Test cross-border etap17", "JDG/tests/test_crossborder_etap17_audit.py"),
    ("Test lifecycle etap18", "JDG/tests/test_business_lifecycle_etap18_audit.py"),
    ("Test lokalne/akcyza etap19", "JDG/tests/test_local_excise_etap19_audit.py"),
    ("Test KSeF etap20", "JDG/tests/test_ksef_jpk_etap20_audit.py"),
    ("Test RODO/AML/BDO/HR etap21", "JDG/tests/test_rodo_aml_bdo_hr_etap21_audit.py"),
    ("Test hyper etap22", "JDG/tests/test_hyper_enterprise_contexts_etap22_audit.py"),
    ("Test AI etap23", "JDG/tests/test_enterprise_ai_neural_etap23_audit.py"),
    ("Test CI etap24", "JDG/tests/test_tests_ci_quality_etap24_audit.py"),
    ("Test tools etap25", "JDG/tests/test_tools_api_rulestore_bundles_etap25_audit.py"),
    ("Test mirror etap26", "JDG/tests/test_policies_mirror_sync_etap26_audit.py"),
    ("Test red team etap27", "JDG/tests/test_cross_domain_red_team_etap27_audit.py"),
    ("Test certyfikacji etap28", "JDG/tests/test_final_certification_etap28_audit.py"),
]),
dict(name="Dokumenty kampanii etapowej", files=[
    ("Etapy 10–28 (dokument)", "JDG/docs/KAMPANIA_GLM52_ETAPY_10_28.md"),
    ("ZUS macro P07", "JDG/docs/ZUS_MACRO_P07.md"),
    ("ZUS micro P08", "JDG/docs/ZUS_MICRO_P08.md"),
    ("Księgowość P09", "JDG/docs/KSIEGOWOSC_PKPIR_UOR_P09.md"),
    ("KSeF/JPK P17", "JDG/docs/KSEF_JPK_EDEKLARACJE_P17.md"),
    ("RODO/AML P16", "JDG/docs/RODO_AML_BEZPIECZENSTWO_P16.md"),
]),
],
legal=[
"Ustawa o ZUS — stawki, 30-krotność, ulgi (obiekty etapów 12–13).",
"Ustawa o rachunkowości — ewidencja, korekty, archiwum (etapy 14–15).",
"KKS — przestępstwa skarbowe, przedawnienie, dobrowolne ujawnienie (etap 16).",
"Ordynacja podatkowa — odsetki, przedawnienie, współdziałanie (etap 16).",
"Ustawa VAT — WDT/WNT, MPP, kursy (etap 17), JPK_V7 (etap 20).",
"Ustawa o PIT — ryczałt, cykl życia firmy, ulgi (etapy 18–19).",
"RODO/AML — obiekty etapu 21 (art. 5–6 RODO; ustawa AML art. 2, 48).",
"KSeF — rozporządzenie MF o KSeF 2.0 (etap 20; weryfikacja harmonogramu w podatki.gov.pl).",
],
innovations=[
("Unified audit schema", "wspólny JSON-schema wyników etapów (pass/fail/partial z dowodami) umożliwiający automatyczną syntezę."),
("Cross-etap conflict detector", "narzędzie porównujące deklaracje etapów ze stanem aktualnym; sprzeczność = konflikt Cxx."),
("Red team pack", "zestaw ataków regułowych (mutacje input, brakujące pola, skrajne daty) wielokrotnego użytku per domena."),
("Risk-of-fortress score", "skalarne ryzyko z syntezy etapów+gate'ów+bramek; monitorowane w P37, donoszone do certyfikatu decyzji."),
("Wiedza etapów jako dane", "definicje audytów etapowych w YAML; audytor = silnik interpretujący dane (zmiana audytu bez zmiany kodu)."),
("Auto-rerun po nowelizacji", "Law Radar (P08) wyzwala automatyczny rerun dotkniętych etapów po nowelizacji."),
("Ślad audytowy uruchomień", "każdy run etapu zapisywany WORM (P43) z checksumą stanu repo."),
("Frontier matrix", "macierz etap×domena z datami ostatniego dowodu — wykrywa etapy „wygasłe” (brak dowodu >90 dni)."),
("Rozstrzyganie sprzeczności", "procedura: najnowszy dowód wygrywa; stara deklaracja wchodzi do rejestru mediacji z reason."),
("Certification pack generator", "automatyczny pakiet PDF/MD dla P44: synteza + dowody + luki P0/P1."),
("Kampania domknięcia etapów", "plan naprawy etapów bez dowodów (priorytet: ZUS core/micro, UoR, KSeF)."),
("Feed do P30", "wyniki etapów jako wejście do rejestru wdrożeń (jedna historia, dwie perspektywy)."),
],
in_contracts=[
"Kanon dowodowy z P00 — deklaracja etapu jest twierdzeniem, dowodem jest kod/test/artefakt.",
"Kontrakt bramek z P29 — wspólny raport JSON (schema) i identyfikatory.",
],
out_contracts=[
"Supersynteza ryzyka (mapa etap×domena×ryzyko) — wejście do P37 (obserwowalność) i P44 (certyfikacja).",
"Red team pack (zestaw ataków) — wielokrotnego użytku w P34 i P43.",
"Konwencja rozstrzygania sprzeczności (najnowszy dowód + rejestr mediacji) — wiąże P40/P41/P44.",
],
acceptance_extra=[
"Każdy etap 12–28 ma wiersz syntezujący: deklaracja → weryfikacja dzisiaj → status dowodu.",
"Supersynteza ma macierz etap×domena z identyfikacją przynajmniej 3 sprzeczności między raportami.",
]),
dict(code="P32", slug="AUTOMATYZACJA_KSIEGOWOSCI", title="AUTOMATYZACJA KSIEGOWOŚCI JDG — OD FAKTURY DO ARCHIWUM (CEL NADRZĘDNY)",
role="głównym inżynierem automatyzacji księgowości JDG, projektantem end-to-end pipeline'u faktura→ewidencja→deklaracja→płatność→archiwum",
expertise="pipeline'y księgowe, zamknięcie miesiąca, ewidencje PKPiR/UoR, wyliczanie podatków i składek, kolejki e-dokumentów, idempotencja",
mission=[
"To część mostowa celu nadrzędnego serii: OPA ma maksymalnie zautomatyzować CODZIENNE księgowanie JDG. Przeanalizuj obecny pipeline (narzędzia wyliczania, zamknięcia, generowania JPK, kolejek KSeF, priorytetów płatności, agregacji faktów) i zaprojektuj end-to-end przepływ: dokument wchodzi (KSeF/e-mail/skan) → OPA klasyfikuje i wycenia → ewidencje się aktualizują → deklaracje się składają → płatności się planują → archiwum się zamyka z pełnym śladem dowodowym.",
"Zdefiniuj kontrakt fail-closed na każdym etapie: brak pola, sprzeczność, niepewność prawna = NEEDS_ADVICE, nigdy ciche AUTO_POST. Zaprojektuj idempotencję (dwukrotne dostarczenie faktury nie może podwójnie zaksięgować), korekty (nota obciążeniowa koryguje bez psucia historii) i zamknięcie miesiąca jako transakcję atomową z możliwością otwarcia wyłącznie na dowód audytowy.",
],
subparts=[
dict(name="Ingest dokumentów i klasyfikacja",
goal="od KSeF/skanu/e-mailu do ustrukturyzowanej transakcji",
questions=[
"Jak dzisiaj dane wchodzą do silnika (input API? pliki?) — gdzie brak normalizacji?",
"Klasyfikacja kosztu/przychodu: kto decyduje (reguły rego? konfiguracja?) i jak działa fail-closed?",
"Detekcja duplikatów dokumentów (hash, NIP+data+kwota) — czy istnieje, czy testowana?",
"Jak obsłużyć dokument niekompletny (brak NIP, brak daty) — ścieżka NEEDS_ADVICE z powodem?",
]),
dict(name="Wycena i ewidencje (VAT, PKPiR/UoR)",
goal="auto-wyliczenie VAT, zaksięgowanie PKPiR/UoR z granicami groszowymi",
questions=[
"Czy wyliczenie VAT (stawka, zwolnienie, MPP) używa reguł macro+micro spójnie (P12/P13)?",
"Czy księgowanie PKPiR respektuje kolumny (7, 12, 13) i przepisy o kosztach (art. 22 PIT)?",
"Czy różnice PKPiR vs UoR są wykrywane i raportowane automatycznie?",
"Czy zaokrąglenia są jednorodne (banker's vs half-up) i testowane na granicach groszowych?",
]),
dict(name="Deklaracje i płatności",
goal="generowanie JPK_V7/deklaracji, terminy, priorytet płatności, wcześniejsze korekty",
questions=[
"Kto decyduje o dacie płatności (kalendarz terminów P25) i jak wygląda retry przy awarii?",
"Czy priorytet płatności (ZUS vs VAT vs PIT) jest regułowy i testowany?",
"Czy generowanie JPK jest walidowane (jpk_validator) przed wysyłką i zapisywane z checksumą?",
"Jak wygląda korekta po wysyłce (deklaracja korygująca) — ślad, testy, rollback?",
]),
dict(name="Zamknięcie miesiąca i archiwum",
goal="atomowe zamknięcie, raport miesiąca, archiwum WORM z checksumami",
questions=[
"Czy zamknięcie miesiąca jest atomowe (wszystkie ewidencje się zgadzają lub nic się nie zamyka)?",
"Czy raport miesiąca zawiera pełny ślad: decyzje, pewność, podstawy prawne, certyfikaty?",
"Czy archiwum jest niezmienne (WORM, checksuma) i czy istnieje test integralności archiwum?",
"Jak wygląda procedura otwarcia miesiąca po zamknięciu (kto może, co się loguje)?",
]),
],
file_groups=[
dict(name="Narzędzia księgowe rdzenia", files=[
    ("Toolkit księgowości P11", "JDG/tools/p11_accounting_toolkit.py"),
    ("Silnik zamknięcia UoR", "JDG/tools/uor_closing_engine.py"),
    ("UoR pełnopodatkowy (double-entry)", "JDG/tools/uor_double_entry.py"),
    ("Kalkulator ZUS", "JDG/tools/zus_calculator.py"),
    ("Kalkulator chorobowy ZUS", "JDG/tools/zus_zasilkowa_calculator.py"),
    ("Silnik stawek VAT", "JDG/tools/vat_rate_engine.py"),
    ("Detektor MPP", "JDG/tools/vat_mpp_auto_detector.py"),
    ("Kalendarz ZUS", "JDG/tools/zus_calendar.py"),
]),
dict(name="Pipeline dokumentów i płatności", files=[
    ("Test agregacji faktów (kontrakt danych)", "JDG/tests/test_facts_aggregator.py"),
    ("Test priorytetów płatności (kontrakt)", "JDG/tests/test_payment_priority_service.py"),
    ("Skanner fraudu grafowego", "JDG/tools/fraud_graph_scanner.py"),
    ("Test silnika ryzyka", "JDG/tests/test_risk_guard.py"),
    ("Test integracji silnika ryzyka", "JDG/tests/test_risk_guard_integration.py"),
    ("Test silnika priorytetów", "JDG/tests/test_priority_engine.py"),
    ("Test strażnika semantycznego", "JDG/tests/test_semantic_guard.py"),
    ("Kolejka offline KSeF", "JDG/tools/ksef_offline_queue.py"),
    ("Outbox KSeF", "JDG/tools/ksef_outbox.py"),
    ("Generator JPK", "JDG/tools/jpk_generator.py"),
    ("Walidator JPK", "JDG/tools/jpk_validator.py"),
    ("Auto-gen JPK", "JDG/tools/jpk_autogen.py"),
]),
dict(name="Testy pipeline'u", files=[
    ("Test agregacji faktów", "JDG/tests/test_facts_aggregator.py"),
    ("Test priorytetów płatności", "JDG/tests/test_payment_priority_service.py"),
    ("Test fraud graph", "JDG/tests/test_fraud_graph_scanner.py"),
    ("Test risk guard", "JDG/tests/test_risk_guard.py"),
    ("Test tax pipeline", "JDG/tests/test_tax_pipeline.py"),
    ("Test PKPiR/UoR enterprise", "JDG/tests/test_pkpir_uor_enterprise.py"),
    ("Test VAT enterprise", "JDG/tests/test_vat_enterprise.py"),
    ("Test KSeF generator", "JDG/tests/test_ksef_generator.py"),
]),
dict(name="Dokumenty automatyzacji", files=[
    ("Automatyzacja księgowości P18 (dokument)", "JDG/docs/AUTOMATYZACJA_KSIEGOWOSCI_P18.md"),
    ("Logika biznesowa", "JDG/docs/LOGIKA_BIZNESOWA.md"),
    ("Zgodność z dokumentami księgowymi", "JDG/docs/ZGODNOSC_DOKUMENTY_KSIEGOWE.md"),
    ("Księgowość P09 (dokument)", "JDG/docs/KSIEGOWOSC_PKPIR_UOR_P09.md"),
    ("Podręcznik użytkownika", "JDG/docs/PODRECZNIK_UZYTKOWNIKA.md"),
    ("FAQ", "JDG/docs/FAQ.md"),
]),
],
legal=[
"Ustawa o rachunkowości — art. 4–5 (rzetelność, ewidencja), art. 21 (wycena), art. 74–75 (archiwum).",
"Ustawa o PIT — art. 22 (koszty), art. 22a–22f (amortyzacja), art. 24a (PKPiR), art. 9 ust. 1a (UoR).",
"Rozporządzenie MF o PKPiR — kolumny ewidencji, zasady wpisywania (weryfikacja wersji w ISAP).",
"Ustawa VAT — art. 106b–109e (ewidencja, JPK), art. 19a (moment powstania obowiązku podatkowego), art. 19b (MPP).",
"Ustawa VAT — art. 108 (nieprawidłowa stawka), art. 86–87 (odliczenia).",
"Ustawa o ZUS — terminy i podstawa wymiaru składek (integracja z kalendarzem płatności).",
"Ordynacja podatkowa — art. 15 (płatność), art. 16 (zaliczki), art. 45 (terminy PIT).",
"KSeF — rozporządzenie MF o ustrukturyzowanych fakturach (schematy, terminy; weryfikacja w crd.gov.pl).",
],
innovations=[
("Auto-booking pipeline z decision certificate", "każde zaksięgowanie generuje certyfikat decyzji (P11) z pełnym łańcuchem dowodów — księgowanie jest zawsze wytłumaczalne."),
("Idempotency keys", "hash dokumentu jako klucz idempotencji; podwójne dostarczenie = zerowy efekt + alarm."),
("Two-phase close month", "zamknięcie miesiąca w 2 fazach (przygotowanie → zatwierdzenie) z walidacją niezgodności między ewidencjami."),
("Kolejka NEEDS_ADVICE z triage", "wszystkie niepewności trafiają do jednej kolejki z klasterizacją przypadków (P10 golden replay jako sugerent decyzji)."),
("Reconciliation with bank feed", "porównanie wyciągu bankowego z ewidencją (auto-parowanie płatności, alarm rozjazdów)."),
("Granice groszowe jako dane testowe", "automatycznie generowane przypadki 0,00/0,01/99999999,99 per reguła wyliczania (P36 jako generator)."),
("Replay sezonowy", "rewizja całego kwartału na nowych wersjach reguł (czy starą deklarację wydałbyś dzisiaj inaczej?) — raport dryfu."),
("Automatyczne korekty pre-deadline", "silnik wykrywa błędy przed terminem deklaracji i proponuje korektę z oceną ryzyka (art. 21 Ordynacji)."),
("Przepływ 4-eyes", "krytyczne AUTO_POST (np. korekta >X zł) wymagają drugiej osoby; ślad 4-eyes w certyfikacie."),
("Dokument → decyzja → archiwum", "pojedynczy identyfikator dokumentu prowadzi przez wszystkie etapy (traceability end-to-end)."),
("Limity automatyzacji jako dane", "konfiguracja tego, co wolno automatycznie księgować (progi kwotowe, domeny), w data.thresholds — zmiana bez deployu."),
("Backpressure na awarie zewnętrzne", "awaria KSeF/MF wstrzymuje pipeline w kontrolowany sposób (offline queue) z raportem zgodności terminowej."),
],
in_contracts=[
"Kontrakt werdyktu 25-polowy z P03 — każdy krok pipeline'u emituje zgodny werdykt.",
"Kontrakt invariantów z P04 — pipeline nigdy nie omija warstwy konstytucyjnej (fail-closed egzekwowany centralnie).",
],
out_contracts=[
"KONTRAKT PIPELINE (etapy, dane wejściowe/wyjściowe, idempotencja, fail-closed) — wiąże P40 (API) i P38 (bundle/deploy).",
"Schema raportu miesiąca (zamknięcie) — wejście do P40 (UI/dashboard) i P41 (dokumentacja).",
"Lista automatyzowalnych ścieżek z progiem pewności — wejście do P44 (certyfikacja definicji sukcesu).",
],
acceptance_extra=[
"Mapa end-to-end pipeline'u (Mermaid) z zaznaczeniem wszystkich punktów fail-closed.",
"Każdy etap pipeline'u ma przypisany: narzędzie → test → podstawę prawną → tryb awaryjny.",
]),
dict(code="P33", slug="NEURAL_MESH_AI", title="WARSTWA AI ENTERPRISE — NEURAL MESH, LLM BRIDGE I HUMAN-IN-THE-LOOP",
role="architektem warstwy AI dla systemów decyzyjnych krytycznych (policy-as-code), specjalistą od bezpiecznej integracji LLM z regułami OPA",
expertise="neural mesh, LLM bridge, generowanie reguł AI, SMT/Z3, trust score, digital twin, sandboxing AI, human-in-the-loop",
mission=[
"Przeanalizuj warstwę AI (neural mesh, llm_bridge, ai_augmented_rule_generator, judgment_predictor, smt_z3_verification, autonomous_tax_strategy, adaptive_trust_score, digital_twin_simulator, holographic_viz, federated_tax_mesh, blockchain_audit_trail, quantum_safe_encryption). Oceń, które z nich mają REALNĄ semantykę, a które są fasadami (plik bez mechanizmu). AI w fortecy podatkowej ma jeden cel: pomagać człowiekowi szybciej dochodzić do pewności — NIGDY nie może autonomicznie wymusić AUTO_POST.",
"Zaprojektuj bezpieczną architekturę AI: sandbox (propozycje AI nie mają uprawnień zapisu do reguł produkcyjnych), ścieżka awansu (propozycja → walidacja SMT/Z3 + golden replay → 4-eyes → SHADOW → ACTIVE), pełny audyt promptów i odpowiedzi, red-team promptów (injection). Przeprować głęboką analizę ryzyk prawnych AI Act i RODO art. 22 dla każdego elementu warstwy.",
],
subparts=[
dict(name="Neural mesh i LLM bridge",
goal="co realnie robi warstwa AI dzisiaj i jak ma działać",
questions=[
"Czy neural mesh ma realną komunikację między węzłami, czy jest to fasada — dowód z kodu?",
"Czy llm_bridge izoluje klucze, limituje koszty, loguje prompty (audytowalność) — czy brakuje?",
"Jak wyjście LLM trafia do propozycji reguły (format, walidacja, idempotencja)?",
"Czy jest mechanizm odrzucenia halucynacji prawnych (numer Dz.U. z checkują ISAP)?",
]),
dict(name="Generowanie i weryfikacja reguł AI",
goal="AI propozycje reguł z dowodem matematycznym przed awansem",
questions=[
"Czy ai_augmented_rule_generator weryfikuje poprawność Rego (parse, lint) przed propozycją?",
"Czy smt_z3_verification dowodzi równoważności starej i nowej reguły (counterexample)?",
"Czy judgment_predictor jest używany do triage NEEDS_ADVICE, czy sam decyduje (naruszenie fail-closed)?",
"Jaka jest ścieżka awansu propozycji AI (czy respektuje P07 lifecycle i 4-eyes)?",
]),
dict(name="Symulacja, zaufanie i obiekty specjalne",
goal="digital twin, trust score, strategia autonomiczna, mesh federacyjny",
questions=[
"Czy digital_twin_simulator symuluje realne dane (anonymizowane?) czy fasadowe scenariusze?",
"Czy adaptive_trust_score wpływa na decyzje AUTO_POST (jeśli tak — to naruszenie invariantów P04)?",
"Czy autonomous_tax_strategy może proponować agregresywne optymalizacje (GAAR art. 119a) — kto broni granic?",
"Czy federated_tax_mesh i blockchain_audit_trail mają realny model danych, czy są to nazwy bez semantyki?",
]),
dict(name="Zgodność prawna warstwy AI",
goal="AI Act, RODO art. 22, audyt promptów",
questions=[
"Które elementy warstwy AI podpadają pod AI Act (klasyfikacja ryzyka, obowiązki dokumentacyjne)?",
"Czy decyzje z udziałem AI mają jawne oznaczenie w Decision Certificate (transparencja)?",
"Czy prompty zawierają dane osobowe (RODO) — jak je minimalizować/pseudonimizować?",
"Zaprojektuj red-team promptów (injection, wyłudzenie klucza, wyjście poza rolę) i testy.",
]),
],
file_groups=[
dict(name="Narzędzia AI rdzenia", files=[
    ("LLM bridge", "JDG/tools/llm_bridge.py"),
    ("Generator reguł AI", "JDG/tools/ai_augmented_rule_generator.py"),
    ("Predyktor orzeczeń", "JDG/tools/judgment_predictor.py"),
    ("Weryfikacja SMT/Z3", "JDG/tools/smt_z3_verification.py"),
    ("Strategia podatkowa autonomiczna", "JDG/tools/autonomous_tax_strategy.py"),
    ("Adaptive trust score", "JDG/tools/adaptive_trust_score.py"),
    ("Auditor innowacji neural mesh", "JDG/tools/neural_mesh_innovations_auditor.py"),
    ("Generator STR", "JDG/tools/str_generator.py"),
]),
dict(name="Symulacja i obiekty specjalne", files=[
    ("Digital twin simulator", "JDG/tools/digital_twin_simulator.py"),
    ("Chaos engineering", "JDG/tools/chaos_engineering.py"),
    ("Chaos runner", "JDG/tools/chaos_runner.py"),
    ("Wizualizacja holograficzna", "JDG/tools/holographic_viz.py"),
    ("Mesh federacyjny", "JDG/tools/federated_tax_mesh.py"),
    ("Audit trail blockchain", "JDG/tools/blockchain_audit_trail.py"),
    ("Szyfrowanie post-quantum", "JDG/tools/quantum_safe_encryption.py"),
    ("Self-healing engine", "JDG/tools/self_healing_engine.py"),
    ("WORM storage", "JDG/tools/worm_storage.py"),
]),
dict(name="Dokumenty AI", files=[
    ("Neural mesh P20 (dokument)", "JDG/docs/NEURAL_MESH_INNOWACJE_P20.md"),
    ("OPA jako system P21", "JDG/docs/OPA_JAKO_SYSTEM_P21.md"),
    ("Dashboard pewności", "JDG/docs/PEWNOSC_DASHBOARD.md"),
    ("Legal Twin raport", "JDG/docs/LEGAL_TWIN_RAPORT.md"),
]),
],
legal=[
"AI Act (Rozporządzenie UE 2024/1689) — klasyfikacja ryzyka, obowiązki przejrzystości i nadzoru człowieka.",
"RODO — art. 22 (decyzje zautomatyzowane), art. 25 (privacy by design), art. 35 (DPIA).",
"Ordynacja podatkowa — art. 119a (GAAR): strategia autonomiczna nie może promować działań sztucznych.",
"Ustawa VAT/PIT — każda propozycja AI respektuje stawki/limity z data.thresholds (ADR-002), nie „zgaduje”.",
"KKS — odpowiedzialność za błędne deklaracje nie przenosi się na AI; człowiek zatwierdza (4-eyes).",
"Ustawa o rachunkowości — art. 4 ust. 1: dowody wygenerowane z pomocą AI muszą być sprawdzalne.",
"Prawo autorskie — status artefaktów generowanych przez AI w repo (notatka prawna do weryfikacji).",
"ROZPORZĄDZENIE o KSeF — AI nie może modyfikować faktur po ich utrwaleniu (integralność dokumentu).",
],
innovations=[
("AI Proposal Pipeline", "formalna ścieżka: LLM → walidacja składni → SMT/Z3 → golden replay → 4-eyes → SHADOW; żadna propozycja nie omija ścieżki."),
("Sandbox uprawnień AI", "konto techniczne AI bez uprawnień zapisu do reguł produkcyjnych; awans wyłącznie przez PR człowieka."),
("Halucynacja prawna guard", "weryfikacja każdej podstawy prawnej z odpowiedzi LLM w ISAP (crawler) przed prezentacją człowiekowi."),
("Prompt audit ledger", "każdy prompt+odpowiedź zapisany WORM z checksumą — pełna odtwarzalność sesji AI."),
("Red-team prompt suite", "zestaw ataków (injection, jailbreak, exfiltration) testowany na bridge'u; wynik blokuje merge przy slabości."),
("Trust score jako telemetria", "adaptive_trust_score NIE wpływa na decyzje — tylko rankuje kolejki do przeglądu (odcięcie od AUTO_POST)."),
("Digital twin na danych syntetycznych", "syntetyczne dane JDG (generator) zamiast realnych — RODO by design; twin mierzy wpływ zmian reguł przed wdrożeniem."),
("Cost governor", "limit tokenów/kosztu per sesja AI z alarmami; awarie zewnętrzne nie zatrzymują pipeline'u (degradacja do trybu bez AI)."),
("Explain-first UI", "propozycja AI zawsze z wyjaśnieniem (który przepis, który dowód) — zakaz czarnoskrzynkowych sugestii."),
("Federated learning guard", "jeśli mesh sięga po dane zewnętrzne — tylko zanonimizowane agregaty (kontrakt prywatności)."),
("Quantum-safe plan", "plan migracji kluczy/podpisów do post-quantum z harmonogramem (nawet jeśli to fitura — dokument decyzji)."),
("AI w triage NEEDS_ADVICE", "judgment_predictor wyłącznie sortuje kolejki do człowieka; sugestia zawsze z dowodem i percentylem pewności."),
],
in_contracts=[
"Inwarianty fail-closed z P04 — warstwa AI jest wyłącznie advisory, nigdy wykonawcza.",
"Kontrakt cyklu życia z P07 — propozycje AI wchodzą przez SHADOW/CANDIDATE jak każda inna reguła.",
],
out_contracts=[
"ARCHITEKTURA AI (sandbox, ścieżka awansu, audyt, red-team) — wiąże P40 (API: endpointy AI), P43 (security) i P44.",
"Kontrakt prywatności AI (minimalizacja danych, pseudonimizacja) — wejście do P22 (RODO/AML) i P41.",
"Red-team prompt suite (plik testowy) — wielokrotnego użytku w CI (P39).",
],
acceptance_extra=[
"Każde narzędzie AI ma wiersz: realna semantyka (dowód z kodu) albo fasada (dowód) → plan naprawy/usunięcia.",
"Ścieżka awansu propozycji AI przedstawiona jako diagram z punktami walidacji i odpowiedzialnościami.",
]),
dict(code="P34", slug="WALIDACJA_NARZEDZIA", title="NARZĘDZIA WALIDACJI I HIGIENA KODU — ZERO STUBÓW, ZERO DEAD CODE",
role="specjalistą od walidacji statycznej i dynamicznej reguł Rego oraz higieny repozytorium policy-as-code klasy enterprise",
expertise="lintery rego, detektory dead code i tautologii, walidacja podstaw prawnych, walidatory dokumentacji, statyczna analiza",
mission=[
"Przeanalizuj narzędzia walidacji: validate_rules, lint_rego_rules, validate_legal_basis (v1+v2), dead_rule_detector, tautology_guard, else_chain_dead_code_detector, cross_ref_validator, cross_package_conflict_detector, doc_consistency_validator, hardcoded_audit, temporal_interval_gate, verify_verdict_invariants, validate_enterprise_contract. Oceń ich pokrycie: co wykrywają, co omijają, czy są podłączone do bramek (P29) i CI (P39). Narzędzie nieużywane to dead tool — forteca nie może mieć martwych strażników.",
"Zaprojektuj sieć walidacji wielopoziomowej: L1 składnia (parse/lint), L2 semantyka (tautologie, dead code, else-chain), L3 prawna (podstawy, temporalność), L4 spójność (cross-refs, kontrakty, mirror), L5 runtime (invarianty). Każdy poziom: narzędzie → test narzędzia → bramka → CI. Przeprować głęboką analizę luk: które klasy błędów przechodzą przez wszystkie poziomy dziś (np. reguła semantycznie poprawna, prawnie nieaktualna)?",
],
subparts=[
dict(name="Poziomy L1–L2: składnia i semantyka rego",
goal="lint, tautologie, dead code, else-chain",
questions=[
"Czy lint_rego_rules pokrywa konwencje nazewnicze (rule_id, pakiet) i ADR-002 (brak hardcode)?",
"Czy tautology_guard wykrywa reguły zawsze-true i zawsze-false (przykłady z repo)?",
"Czy else_chain_dead_code_detector znajduje unreachable else i otwarte negatywy?",
"Czy dead_rule_detector wykrywa reguły nieużywane przez orkiestrator (routing P02)?",
]),
dict(name="Poziom L3: podstawy prawne i temporalność",
goal="walidacja legal basis i okien temporalnych",
questions=[
"Czy validate_legal_basis_v2 weryfikuje format (akt/art/ust/Dz.U./data) i spójność z LEGAL_SOURCE_REGISTRY?",
"Czy wykrywa niemożliwe daty (nowelizacja przed ustawą) i duplikaty podstaw?",
"Czy temporal_interval_gate pilnuje pokrycia czasowego (luka między valid_from/valid_to)?",
"Czy są testy na day-1/day+1 przełączeń (P05) generowane automatycznie?",
]),
dict(name="Poziom L4: spójność międzypakietowa i dokumentacyjna",
goal="cross-ref, konflikty, mirror, dokumentacja",
questions=[
"Czy cross_ref_validator wykrywa odwołania do nieistniejących reguł/pól werdyktu?",
"Czy cross_package_conflict_detector wykrywa dwie reguły piszące do tej samej ścieżki werdyktu?",
"Czy doc_consistency_validator porównuje liczby w dokumentach z realnym stanem (MANIFEST vs ls)?",
"Czy walidacja mirror (policies vs canonical) jest częścią tej sieci czy osobna (P29)?",
]),
dict(name="Poziom L5: runtime i kontrakty",
goal="invarianty, verdict, kontrakt enterprise",
questions=[
"Czy verify_verdict_invariants działa na live bundle (smoke po deploy)?",
"Czy validate_enterprise_contract pilnuje kontraktu operacyjnego (test_enterprise_operating_contract)?",
"Czy hardcoded_audit wykrywa liczby magiczne w rego (stawki/daty) — jakie ma wyjątki?",
"Które narzędzia są niepodłączone do bramek/CI — lista z planem podłączenia albo usunięcia?",
]),
],
file_groups=[
dict(name="Walidatory rego i higiena", files=[
    ("Walidator reguł", "JDG/tools/validate_rules.py"),
    ("Linter rego", "JDG/tools/lint_rego_rules.py"),
    ("Konwerter true→warunki", "JDG/tools/convert_true_to_conditions.py"),
    ("Detektor tautologii", "JDG/tools/tautology_guard.py"),
    ("Detektor dead code else-chain", "JDG/tools/else_chain_dead_code_detector.py"),
    ("Detektor dead rules", "JDG/tools/dead_rule_detector.py"),
    ("Audyt hardcode", "JDG/tools/hardcoded_audit.py"),
    ("Konwerter debug", "JDG/tools/debug_converter.py"),
]),
dict(name="Walidatory prawne i temporalne", files=[
    ("Walidacja podstaw prawnych", "JDG/tools/validate_legal_basis.py"),
    ("Walidacja podstaw prawnych v2", "JDG/tools/validate_legal_basis_v2.py"),
    ("Walidacja P24", "JDG/tools/validate_p24_legal_basis.py"),
    ("Brama interwałów temporalnych", "JDG/tools/temporal_interval_gate.py"),
    ("Crawler ISAP", "JDG/tools/isap_crawler.py"),
    ("Pipeline aktualizacji ISAP", "JDG/tools/isap_rule_update_pipeline.py"),
    ("Alarm dryfu ISAP", "JDG/tools/isap_drift_alarm.py"),
    ("Analizator wpływu zmiany prawnej", "JDG/tools/legal_change_impact_analyzer.py"),
]),
dict(name="Walidatory spójności", files=[
    ("Walidator cross-ref", "JDG/tools/cross_ref_validator.py"),
    ("Detektor konfliktów między pakietami", "JDG/tools/cross_package_conflict_detector.py"),
    ("Walidator spójności dokumentów", "JDG/tools/doc_consistency_validator.py"),
    ("Matryca traceability", "JDG/tools/traceability_matrix.py"),
    ("Matryca traceability VAT", "JDG/tools/vat_traceability_matrix.py"),
    ("Proponent ADR", "JDG/tools/adr_auto_proposer.py"),
    ("Auditor numeracji inicjatyw", "JDG/tools/initiative_numbering_auditor.py"),
    ("Symulator wpływu reguł", "JDG/tools/rule_impact_simulator.py"),
]),
dict(name="Walidatory runtime i kontraktów", files=[
    ("Weryfikacja inwarianentów werdyktu", "JDG/tools/verify_verdict_invariants.py"),
    ("Walidacja kontraktu enterprise", "JDG/tools/validate_enterprise_contract.py"),
    ("Detektor dryfu temporalnego", "JDG/tools/temporal_drift_detector.py"),
    ("Heat mapa pokrycia prawnego", "JDG/tools/legal_coverage_heatmap.py"),
    ("Analizator wpływu migracji", "JDG/tools/migration_impact_analyzer.py"),
    ("Dokument narzędzi walidacji", "JDG/docs/NARZEDZIA_WALIDACJI_P22.md"),
    ("Test kontraktu enterprise", "JDG/tests/test_enterprise_operating_contract.py"),
    ("Rejestr źródeł prawnych", "JDG/docs/LEGAL_SOURCE_REGISTRY.md"),
]),
],
legal=[
"Ordynacja podatkowa — art. 119a (GAAR: walidacja musi wykrywać reguły promujące konstrukcje sztuczne).",
"Ustawa VAT — art. 108–109e (walidacja stawek, ewidencji, terminów).",
"Ustawa o PIT — art. 22, 30c (walidacja kosztów i form opodatkowania).",
"Ustawa o ZUS — walidacja podstaw wymiaru i ulg (preferencyjny start, mały ZUS+).",
"Ustawa o rachunkowości — art. 4 ust. 1: sprawdzalność dowodów wymuszana przez walidatory.",
"RODO — art. 5 ust. 1e (retencja): walidatory pilnują okien ważności danych.",
"ISAP/RCL — reguły weryfikacji tekstów aktów (konwencja cytowania, Dz.U., rok, pozycja).",
"Rozporządzenia wykonawcze MF — walidacja schematów JPK/KSeF w L3.",
],
innovations=[
("Walidacja jako sieć DAG", "poziomy L1–L5 jako graf zależności z lokalnym retry i raportem per poziom (czym wcześniej przerwać PR)."),
("Semantic diff dla Rego", "porównanie AST dwóch wersji reguły z klasyfikacją zmiany (kosmetyczna/progowa/semantyczna) i różnymi ścieżkami wdrożenia."),
("Legal basis linter online", "integracja z ISAP crawlerem: podstawa prawna sprawdzana na PR (dostępność) i nocnie (dryf)."),
("Tautologia fuzzing", "losowe generowanie inputów (property-based) z asercją, że reguła nie jest stała dla wszystkich inputów."),
("Cross-write detector", "statyczne wykrywanie dwóch reguł zapisujących tę samą ścieżkę werdyktu bez precedence (konflikt = BLOCKER)."),
("Mirror semantic parity", "walidacja, że policies/ i JDG/rules/ mają identyczne semantyki (AST diff), nie tylko nazwy plików."),
("Doc-numbers invariant", "dowolna liczba w dokumentacji (liczba reguł, plików) musi mieć anchor do narzędzia liczącego — inaczej [DEKLARACJA]."),
("Auto-fix z 4-eyes", "narzędzia proponują automatyczne poprawki (konwersja stubów) jako PR z etykietą wymagającą przeglądu człowieka."),
("Walidacja jako usługa", "endpoint API (P40) uruchamiający walidację ad hoc na dowolnym bundle (własny lub kandydujący) — używa orkiestrator testów."),
("Coverage heatmap ciągła", "legal_coverage_heatmap odświeżany codziennie z trendem; spadek pokrycia = alert do Law Radar (P08)."),
("Snapshot walidacji do certyfikatu", "Decision Certificate zawiera ID przebiegu walidacji (wersje narzędzi) — provenance decyzji."),
("Rejestr wyjątków", "każde wyłączenie reguły walidacji (suppress) ma termin wygaśnięcia i właściciela — zero wiecznych wyłączeń."),
],
in_contracts=[
"Kanon artefaktów z P00 — walidatory respektują rejestry (rule_registry, thresholds_data) jako źródło prawdy.",
"Kontrakt bramek z P29 — wyniki walidacji emitują zgodny raport JSON.",
],
out_contracts=[
"SIEĆ WALIDACJI (poziomy, narzędzia, testy, bramki) — wiąże P39 (CI) i P44 (certyfikacja).",
"Lista narzędzi dead/undconnected z decyzją (podłączyć/usunąć) — wejście do P30 i P36.",
"Standard suppress z terminem wygaśnięcia — wiąże P43 (security governance).",
],
acceptance_extra=[
"Każde narzędzie walidacji ma wiersz: poziom L1–L5 → co wykrywa → test → bramka → status podłączenia.",
"Min. 3 przykłady błędów, które przechodzą przez wszystkie poziomy dzisiaj (z propozycją zamknięcia).",
]),
dict(code="P35", slug="AUDYTORY_DOMENOWE", title="AUDYTORY DOMENOWE I DASHBOARDY — VAT/PIT/ZUS/KKS/KSEF/ORDYNACJA",
role="inżynierem audytów domenowych i projektantem dashboardów pewności dla operatorów systemu księgowego",
expertise="audytory domen (vat_macro/micro, zus, ksef), dashboardy pewności i dryfu, agregacja sygnałów jakości",
mission=[
"Przeanalizuj audytory domenowe (vat_macro_audit, vat_micro_auditor, vat_micro_core_audit, vat_micro_special_audit, vat_micro_inventory, zus_macro_auditor, zus_micro_auditor, ksef_jpk_edeklaracje_auditor) oraz dashboardy (enterprise_dashboard, confidence_dashboard, drift_dashboard, PEWNOSC_DASHBOARD.md). Oceń, czy audytory mierzą TO, co istotne prawnie (nie tylko obecność plików), i czy dashboardy prezentują stan pozwalający operatorowi podjąć świadomą decyzję (pewność, dryf, luki prawne).",
"Zaprojektuj ujednolicony kontrakt audytora: dane wejściowe (pakiet, dane testowe, progi), wynik (score, luki, dowody, rekomendacje), integracja z dashboardem i certyfikatem. Audytor domeny musi odpowiadać na pytanie operatora: „Czy mogę zaufać tej domenie na AUTO_POST dla tego typu transakcji?” — z odpowiedzią skwantowaną i dowodową.",
],
subparts=[
dict(name="Audyty VAT (macro, micro core, micro special)",
goal="głębokość audytu największej domeny",
questions=[
"Czy vat_macro_audit pokrywa stawki/zwolnienia/przełączenia okresowe (P12)?",
"Czy vat_micro_core_audit testuje wyliczenia na granicach groszowych i MPP (P13)?",
"Czy vat_micro_special_audit obejmuje przypadki szczególne (towary aneksowane, turystyka, kredyty)?",
"Czy audytory VAT wykrywają dryf mirror vs canonical (P29)?",
]),
dict(name="Audyty ZUS i KSeF",
goal="macro/micro ZUS i KSeF/JPK",
questions=[
"Czy zus_macro_auditor weryfikuje 30-krotność, ulgi i przejścia między ulgami (P26)?",
"Czy zus_micro_auditor testuje chorobowe, świadczenia i terminy DRA?",
"Czy ksef_auditor pilnuje harmonogramu 2.0, schemat XSD i kolejki offline?",
"Które audytory emitują wynik zgodny z kontraktem raportu JSON (P29)?",
]),
dict(name="Dashboardy (enterprise, confidence, drift)",
goal="stan systemu widoczny dla operatora",
questions=[
"Czy enterprise_dashboard agreguje wyniki bramek/audytów czy liczy własne (rozdzielenie obliczeń i prezentacji)?",
"Czy confidence_dashboard pokazuje pewność per domena i per typ decyzji (AUTO_POST vs NEEDS_ADVICE)?",
"Czy drift_dashboard pokazuje dryf prawny, kodowy i mirror w jednym widoku?",
"Czy dashboardy mają wersjonowany kontrakt danych (schema) i testy?",
]),
dict(name="Kontrakt audytora domeny",
goal="uniformizacja: wejście → score → luki → rekomendacje",
questions=[
"Jaki jest minimalny kontrakt wyniku audytora (schema JSON)?",
"Jak skwantyfikować pewność domeny (metodologia, skala, progi AUTO_POST)?",
"Jak audytor ma reagować na brak danych (fail-closed: score UNKNOWN z powodem)?",
"Kto konsumuje wynik: dashboard, certyfikat, red team, P44 — czy każdy ma własny widok?",
]),
],
file_groups=[
dict(name="Audyty VAT", files=[
    ("Audyt VAT macro", "JDG/tools/vat_macro_audit.py"),
    ("Auditor VAT micro", "JDG/tools/vat_micro_auditor.py"),
    ("Audyt VAT micro core", "JDG/tools/vat_micro_core_audit.py"),
    ("Audyt VAT micro special", "JDG/tools/vat_micro_special_audit.py"),
    ("Inwentaryzacja VAT micro", "JDG/tools/vat_micro_inventory.py"),
    ("Narzędzia innowacji VAT", "JDG/tools/vat_innovation_tools.py"),
    ("Heat mapa VAT", "JDG/tools/vat_gap_detector.py"),
    ("Audyt VAT macro (test)", "JDG/tests/test_vat_macro_audit.py"),
    ("Test audytu micro core", "JDG/tests/test_vat_micro_core_audit.py"),
    ("Test audytu micro special", "JDG/tests/test_vat_micro_special_audit.py"),
]),
dict(name="Audyty PIT/ZUS/KSeF", files=[
    ("Audyt PIT macro", "JDG/tests/test_pit_macro_audit.py"),
    ("Audyt PIT micro ulgi", "JDG/tests/test_pit_micro_reliefs_audit.py"),
    ("Auditor ZUS macro", "JDG/tools/zus_macro_auditor.py"),
    ("Auditor ZUS micro", "JDG/tools/zus_micro_auditor.py"),
    ("Inwentaryzacja ZUS micro", "JDG/tools/zus_micro_inventory.py"),
    ("Jakość ZUS micro", "JDG/tools/zus_micro_quality.py"),
    ("Auditor KSeF/JPK", "JDG/tools/ksef_jpk_edeklaracje_auditor.py"),
    ("Test audytu ZUS core", "JDG/tests/test_zus_core_etap12_audit.py"),
    ("Test audytu ZUS micro", "JDG/tests/test_zus_micro_etap13_audit.py"),
    ("Test audytu KSeF", "JDG/tests/test_ksef_jpk_etap20_audit.py"),
]),
dict(name="Dashboardy i sygnały", files=[
    ("Dashboard enterprise", "JDG/tools/enterprise_dashboard.py"),
    ("Dashboard pewności", "JDG/tools/confidence_dashboard.py"),
    ("Dashboard dryfu", "JDG/tools/drift_dashboard.py"),
    ("Dokument dashboard pewności", "JDG/docs/PEWNOSC_DASHBOARD.md"),
    ("Dokument zgodności prawnej", "JDG/docs/ZGODNOSC_PRAWNA.md"),
    ("Dokument pokrycia prawnego", "JDG/docs/LEGAL_COVERAGE.md"),
    ("Raport luk pokrycia", "JDG/docs/LEGAL_COVERAGE_GAP_RAPORT.md"),
    ("Dokument PIT audit", "JDG/docs/PIT_AUDYT_R04.md"),
    ("Dokument VAT audit", "JDG/docs/VAT_AUDYT_R03.md"),
]),
],
legal=[
"Ustawa VAT — art. 41 (stawki), art. 43 (zwolnienia), art. 19a–19b (MPP), art. 100 (deklaracje).",
"Ustawa o PIT — art. 27, 30c, 30f (formy opodatkowania, ulgi).",
"Ustawa o ZUS — art. 18a–18e (podstawa wymiaru, 30-krotność), ulgi (start, mały ZUS+).",
"KSeF — rozporządzenie MF (schemat FA(2)/FA(3), harmonogram; weryfikacja w crd.gov.pl).",
"Ordynacja podatkowa — art. 119a (GAAR) jako kontekst audytu agresywnych ścieżek.",
"Ustawa o rachunkowości — audyt jako dowód rzetelności (art. 4 ust. 1).",
"RODO — minimalizacja danych w dashboardach (dane osobowe nie w metrykach bez potrzeby).",
"KKS — audytory jako redukcja ryzyka czynu zabronionego (art. 56) przez wczesne wykrywanie błędów.",
],
innovations=[
("Domain Trust Score", "skwantyfikowana pewność domeny (0–100) z metodologią (pokrycie prawne × jakość testów × wyniki audytu × dryf) i progami AUTO_POST."),
("Auditor as data", "definicja audytu (kontrole, progi, przykłady) w YAML; audytor = silnik interpretujący (zmiana audytu bez deployu)."),
("Golden case registry", "rejestr przypadków referencyjnych per domena (input → oczekiwany werdykt) używany przez audytory, red team i P10."),
("Unified audit report", "jeden schema wyniku audytora (score, luki, dowody) konsumowany przez dashboardy i certyfikat."),
("Drill-down do dowodu", "dashboard: metryka → klik → lista reguł → klik → kod + test + podstawa prawna (pełny ślad)."),
("Skew detection", "wykrywanie rozjazdu między metrykami (wysoka pewność vs spadek pokrycia testów) z alarmem."),
("Dashboardy jako dane", "konfiguracja dashboardu (metryki, progi, alarmy) w YAML — zmiana widoku bez deployu."),
("Audyt ciągły vs per-PR", "rozdzielenie: per-PR (szybkie) i nocne (głębokie) z różnymi zestawami kontrol."),
("Ocena operatora", "feedback loop: operator ocenia decyzję NEEDS_ADVICE; ocena zasilia golden registry i trust score."),
("Alert routing", "alarmy domeny kierowane do właściwego właściciela (konfiguracja jako dane) z SLA reakcji."),
("Legal freshness stamp", "dashboard pokazuje „ostatni dowód aktualności prawa” per domena (ISAP check date) — przejrzystość ryzyka."),
("Audyt inverse", "audytor generuje przypadki, dla których AUTO_POST byłby niebezpieczny (negatywna przestrzeń) — dowód defensywności."),
],
in_contracts=[
"Kontrakt bramek z P29 — audytory emitują zgodny raport JSON; dashboardy konsumują, nie przeliczają.",
"Kanon inwentaryzacji z P00 — audytory odwołują się do rule_registry i mapy pakietów.",
],
out_contracts=[
"KONTRAKT AUDYTORA DOMENY (schema wyniku + metodologia Trust Score) — wiąże P37 (obserwowalność) i P44.",
"Golden case registry (format + pierwsze przypadki) — wejście do P10 (golden oracle) i P39 (CI).",
"Konfiguracja dashboardów (YAML) — wejście do P40 (UI/API).",
],
acceptance_extra=[
"Każdy audytor domeny ma wiersz: co mierzy → schema wyniku → test → dashboard → status.",
"Trust Score przedstawiony z metodologią, progi i przykładem end-to-end (domena VAT).",
]),
dict(code="P36", slug="GENERATORY_MIGRATORY", title="GENERATORY I MIGRATORY — PLAN33/PLAN50, NAPRAWY, DEDUPLIKACJA, PROWIENIE",
role="inżynierem generatorów kodu reguł i migracji repozytorium policy-as-code, specjalistą od bezpiecznych masowych operacji na regułach",
expertise="generatory reguł, migratory rule_id, naprawy legal basis, deduplikacja, generatory testów, idempotentne konwersje",
mission=[
"Przeanalizuj rodzinę generatorów i migratorów: generate_micro_rules, generate_massive_rules, generate_from_plan50, crossref_plan50, parse_plan33_and_generate, dedup_micro_plan33, fix_* (duplicates, legal_basis, thresholds, naming, hyper), convert_true_to_conditions, generate_test_suite, generate_missing_package_tests, generate_enterprise_tests, split_micro_tests, vat_ruleid_migrator, rule_lifecycle_manager, generate_manifest, manifest_v2, generate_coverage_report. Oceń idempotencję (re-run bez szkody), dry-run, ślad (co zmieniono i dlaczego), rollback.",
"Zaprojektuj standard narzędzia transformującego: wejście (plan/rejestr), dry-run z diff, zastosowanie z dziennikiem zmian (JSON per plik), walidacja po zmianie (uruchom walidatory P34 + bramki P29), automatyczny rollback przy niepowodzeniu. Generatory mają produkować reguły zgodne z konwencjami od razu (rule_id, legal basis, temporalność, parametry-as-data) — zero reguł „do poprawki później”.",
],
subparts=[
dict(name="Generatory z planów (plan33, plan50)",
goal="parsowanie planów i generowanie reguł/testów",
questions=[
"Czy parse_plan33_and_generate respektuje konwencje nazewnicze i legal basis od razu?",
"Czy crossref_plan50 pilnuje spójności między planem a istniejącymi regułami (duplikaty)?",
"Czy generate_from_plan50 ma dry-run i diff przed zapisem?",
"Które generatory tworzą reguły bez testów (luka) i jak to wymusić?",
]),
dict(name="Naprawy (fix_*) i deduplikacja",
goal="masowe naprawy legal basis, progów, nazewnictwa",
questions=[
"Czy fix_p00_duplicates i fix_plan34_duplicates mają rejestry zmian (co→na_co→dlaczego)?",
"Czy fix_p07_thresholds przenosi progi do data.thresholds (ADR-002) z testem regresji?",
"Czy dedup_micro_plan33 pilnuje unikalności rule_id globalnie?",
"Czy naprawy są idempotentne (re-run = zero zmian) — jak to testować?",
]),
dict(name="Generatory testów i manifestów",
goal="testy z reguł, manifesty z repo, raporty pokrycia",
questions=[
"Czy generate_test_suite generuje testy graniczne (grosze, daty, waluty) czy tylko case'i pozytywne?",
"Czy generate_missing_package_tests wykrywa pakiety bez testów i tworzy szkielety z asercjami?",
"Czy generate_manifest/manifest_v2 mają walidację (brak utraty reguł przy regeneracji)?",
"Czy generate_coverage_report liczy pokrycie prawne (akty→reguły) czy tylko plikowe?",
]),
dict(name="Standard narzędzia transformującego",
goal="uniform: dry-run → apply → walidacja → rollback",
questions=[
"Jaki jest minimalny interfejs narzędzia transformującego (CLI, plik dziennika, exit codes)?",
"Jak automatycznie uruchomić walidację po zmianie i cofnąć przy błędzie (transakcja repo)?",
"Czy rule_lifecycle_manager zarządza stanem migracji (co już przemigrowano)?",
"Jak migracje respektują mirror policies (zmiana canonical → sync mirror)?",
]),
],
file_groups=[
dict(name="Generatory z planów", files=[
    ("Generator micro rules", "JDG/tools/generate_micro_rules.py"),
    ("Generator massive rules", "JDG/tools/generate_massive_rules.py"),
    ("Parser plan33 i generator", "JDG/tools/parse_plan33_and_generate.py"),
    ("Generator z plan50", "JDG/tools/generate_from_plan50.py"),
    ("Cross-ref plan50", "JDG/tools/crossref_plan50.py"),
    ("Dedup micro plan33", "JDG/tools/dedup_micro_plan33.py"),
    ("Generatory rego (dokument)", "JDG/docs/OPA_REGO_DEVELOPER_GUIDE.md"),
    ("Plan unifikacyjny v8", "JDG/unified_plan_v8.yaml"),
    ("Postęp planu v8", "JDG/unified_plan_progress.yaml"),
]),
dict(name="Naprawy i migratory", files=[
    ("Fix p00 duplicates", "JDG/tools/fix_p00_duplicates.py"),
    ("Fix p00 legal basis closure", "JDG/tools/fix_p00_legal_basis_closure.py"),
    ("Fix plan34 duplicates", "JDG/tools/fix_plan34_duplicates.py"),
    ("Fix plan34 legal basis", "JDG/tools/fix_plan34_legal_basis.py"),
    ("Fix p06 legal basis", "JDG/tools/fix_p06_legal_basis.py"),
    ("Fix p07 thresholds", "JDG/tools/fix_p07_thresholds.py"),
    ("Fix hyper legal basis", "JDG/tools/fix_hyper_legal_basis.py"),
    ("Fix micro plan33 legal basis", "JDG/tools/fix_micro_plan33_legal_basis.py"),
    ("Fix p10 plan33 KKS", "JDG/tools/fix_p10_plan33_kks.py"),
    ("Fix ZUS naming", "JDG/tools/fix_zus_naming.py"),
    ("Migrator rule_id VAT", "JDG/tools/vat_ruleid_migrator.py"),
    ("Menedżer lifecycle reguł", "JDG/tools/rule_lifecycle_manager.py"),
    ("Konwerter true→warunki", "JDG/tools/convert_true_to_conditions.py"),
]),
dict(name="Generatory testów i raportów", files=[
    ("Generator test suite", "JDG/tools/generate_test_suite.py"),
    ("Generator brakujących testów pakietów", "JDG/tools/generate_missing_package_tests.py"),
    ("Generator testów enterprise", "JDG/tools/generate_enterprise_tests.py"),
    ("Split testów micro", "JDG/tools/split_micro_tests.py"),
    ("Generator manifestu", "JDG/tools/generate_manifest.py"),
    ("Manifest v2 (narzędzie)", "JDG/tools/manifest_v2.py"),
    ("Generator raportu pokrycia", "JDG/tools/generate_coverage_report.py"),
    ("Generatory promptów GLM", "JDG/tools/generate_glm52_prompty.py"),
    ("Generator promptów V3", "JDG/tools/generate_v3_prompty.py"),
    ("Weryfikator kampanii GLM52", "JDG/tools/verify_glm52_campaign.py"),
]),
],
legal=[
"Ordynacja podatkowa — art. 119a: generator nie może produkować reguł promujących sztuczne konstrukcje.",
"Ustawa VAT — generowane reguły stawek/zwolnień z poprawnym cytowaniem (art. 41, 43).",
"Ustawa o PIT — generatory ryczałtu (art. 12 ust. 1 i tabela ryczałtów) z weryfikacją stawek.",
"Ustawa o ZUS — generatory składek respektują 30-krotność i ulgi (art. 18a, 18ab).",
"Ustawa o rachunkowości — ślad zmian (dziennik) jako wymóg sprawdzalności dowodów.",
"RODO — art. 5 ust. 1c (ograniczenie celu): narzędzia transformujące nie kopiują danych osobowych.",
"Konwencje ISAP — cytowanie w generowanych regułach (akt, rok, pozycja) zgodne z rejestrem.",
"ADR-002 (parametry-as-data) — konwencja repo: generatory nie hardcodują stawek.",
],
innovations=[
("Transform transaction", "narzędzie transformujące jako transakcja: dry-run diff → apply z dziennikiem → auto-walidacja → auto-rollback; zero stanów pośrednich."),
("Idempotency certificate", "każde narzędzie ma test idempotencji (drugi run = zero diff) wymuszony w bramce P29."),
("Plan-to-rules pipeline", "plan (YAML) → walidacja planu (crossref, duplikaty) → generacja reguł+testów jednocześnie (zakaz reguły bez testu)."),
("Migration ledger", "globalny dziennik migracji (które narzędzie, kiedy, jakie pliki) z checksumami — pełna odtwarzalność historii."),
("Guard rails generatora", "generatory odmawiają produkcji reguł bez: legal basis, rule_id, okna temporalnego, testu — fail-fast z komunikatem."),
("Golden replay po migracji", "automatyczny replay P10 po każdej masowej zmianie (regresja = auto-rollback)."),
("Mirror-aware apply", "narzędzie aktualizuje canonical i mirror w jednej transakcji (sync guarantee z P39)."),
("Generator testów granicznych", "z tabeli aktów (progi, daty, stawki) automatyczne przypadki brzegowe groszowe i day-0/day+1."),
("Dry-run report", "raport przed zmianą: ile plików, jakie reguły, jakie ryzyka — do 4-eyes dla zmian krytycznych."),
("Naming convention enforcer", "walidator konwencji nazewniczych (rule_id, pakiety, pliki) jako wymóg generatorów."),
("Migracja jako dane", "definicja migracji (mapowania, wyjątki) w YAML; narzędzie silnikiem — przegląd migracji bez kodu."),
("Zero-orphan guarantee", "po każdej transformacji kontrola: żadna reguła bez testu, żaden test bez reguły, żaden manifest bez pliku."),
],
in_contracts=[
"Kanon nazewniczy z P00 — generatory produkują zgodne rule_id i ścieżki (bez wyjątków).",
"Siek walidacji z P34 — transformacje kończą się uruchomieniem walidacji (L1–L5).",
],
out_contracts=[
"STANDARD NARZĘDZIA TRANSFORMUJĄCEGO (interfejs, dziennik, rollback) — wiąże P38 (bundle/deploy) i P39 (CI).",
"Migration ledger (format + historia) — wejście do P44 (certyfikacja) i P41 (dokumentacja).",
"Zero-orphan check (narzędzie + bramka) — wejście do P29 i P39.",
],
acceptance_extra=[
"Każde narzędzie transformujące ma wiersz: idempotentne? dry-run? dziennik? rollback? test?",
"Zero-orphan check zaprojektowany z przykładem end-to-end (generator → reguła → test → manifest).",
]),
]
