# ═══════════════════════════════════════════════════════════════════════════════
# NexusAI JDG Policies — P24 Micro-Module Innovations Enterprise v7.0
# Generated: 2026-08-01
# Package: jdg.p24.innovations
# Implements: I1 (CEIDG Auto-File), I2 (Lump Sum Rate Matcher), I4 (Construction Tax Calc),
#             I10 (VAT Rate Auto-Classifier), I3 (Succession Scorecard), I7 (Decision Engine),
#             I8 (Unregistered Activity Detector)
# ═══════════════════════════════════════════════════════════════════════════════

package jdg.p24.innovations

import future.keywords.in
import data.jdg.helpers

default decide := {
    "matched": false,
    "rule_id": "jdg.p24.innovations.no_match",
    "package": "jdg.p24.innovations",
    "priority": 999999
}

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  I1 — CEIDG Auto-File + Change Detector (5 reguł)                           ║
# ║  Automatyczne wykrywanie zmian i generowanie wniosku CEIDG-1 z terminem 7 dni║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# jdg.p24.i1.r1: i1_ceidg_change_detected_address
decide := {
    "matched": true,
    "rule_id": "jdg.p24.i1.r1",
    "package": "jdg.p24.innovations",
    "priority": 210001,
    "_routing": "AUTO_FILE",
    "_routing_reason": "I1: Wykryto zmianę adresu — automatyczne zgłoszenie CEIDG w 7 dni",
    "_legal_basis": "Art. 14 ust. 1 ustawy o CEIDG",
    "_warnings": ["[P24-I1] Zmiana adresu JDG wykryta automatycznie. Wniosek CEIDG-AKT zostanie wygenerowany. Masz 7 dni na złożenie."]
} {
    object.get(input.jdg_entrepreneur, "address_changed_detected", false) == true
    object.get(input.jdg_entrepreneur, "ceidg_autofile_enabled", false) == true
}

# jdg.p24.i1.r2: i1_ceidg_change_detected_pkd
else := {
    "matched": true,
    "rule_id": "jdg.p24.i1.r2",
    "package": "jdg.p24.innovations",
    "priority": 210002,
    "_routing": "AUTO_FILE",
    "_routing_reason": "I1: Wykryto zmianę PKD — automatyczne zgłoszenie CEIDG",
    "_legal_basis": "Art. 14 ust. 1 ustawy o CEIDG",
    "_warnings": ["[P24-I1] Zmiana kodów PKD wykryta. Wniosek CEIDG-AKT zostanie wygenerowany z nowymi kodami."]
} {
    object.get(input.jdg_entrepreneur, "pkd_changed_detected", false) == true
    object.get(input.jdg_entrepreneur, "ceidg_autofile_enabled", false) == true
}

# jdg.p24.i1.r3: i1_ceidg_form_autogenerated
else := {
    "matched": true,
    "rule_id": "jdg.p24.i1.r3",
    "package": "jdg.p24.innovations",
    "priority": 210003,
    "pit_form": "CEIDG-AKT",
    "_routing": "AUTO_FILE",
    "_routing_reason": "I1: Wniosek CEIDG-AKT wygenerowany automatycznie",
    "_legal_basis": "Art. 14 ust. 1 ustawy o CEIDG",
    "_warnings": ["[P24-I1] Wniosek CEIDG-AKT wygenerowany automatycznie na podstawie wykrytych zmian. Sprawdź poprawność danych przed wysłaniem."]
} {
    object.get(input.jdg_entrepreneur, "ceidg_autofile_generated", false) == true
    object.get(input.jdg_entrepreneur, "ceidg_autofile_sent", false) == false
}

# jdg.p24.i1.r4: i1_ceidg_deadline_reminder
else := {
    "matched": true,
    "rule_id": "jdg.p24.i1.r4",
    "package": "jdg.p24.innovations",
    "priority": 210004,
    "_routing": "BLOCK_AND_ALERT",
    "_routing_reason": "I1: Zbliża się termin 7 dni na zgłoszenie zmiany — pozostało 2 dni!",
    "_legal_basis": "Art. 14 ust. 1 ustawy o CEIDG",
    "_warnings": ["[P24-I1] UWAGA! Zostały 2 DNI na zgłoszenie zmiany w CEIDG! Po terminie kara porządkowa 700 zł."]
} {
    object.get(input.jdg_entrepreneur, "ceidg_change_days_elapsed", 0) >= 5
    object.get(input.jdg_entrepreneur, "ceidg_change_reported", false) == false
}

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  I2 — Lump Sum Rate Semantic Matcher (8 reguł)                              ║
# ║  AI dopasowujące stawkę ryczałtu do symbolu PKWiU/PKD                        ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# jdg.p24.i2.r1: i2_rate_3pct_it_services
decide := {
    "matched": true,
    "rule_id": "jdg.p24.i2.r1",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210010,
    "pit_rate": "0.03",
    "_routing_reason": "I2: Stawka ryczałtu 3% — usługi IT (PKWiU 62.01.1, 62.02)",
    "_legal_basis": "Art. 12 ust. 1 pkt 2b ustawy o ryczałcie",
    "_warnings": ["[P24-I2] Stawka ryczałtu 3%: programowanie, analiza systemów, projektowanie IT (PKWiU 62.01-62.03). Wyłączenie: doradztwo IT (8,5%)."]
} {
    object.get(input.jdg_entrepreneur, "tax_form", "") == "RYCZALT"
    object.get(input.jdg_entrepreneur, "pkd_main", "") in {"62.01.Z", "62.02.Z"}
}

# jdg.p24.i2.r2: i2_rate_5_5pct_manufacturing
else := {
    "matched": true,
    "rule_id": "jdg.p24.i2.r2",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210011,
    "pit_rate": "0.055",
    "_routing_reason": "I2: Stawka ryczałtu 5,5% — produkcja, budownictwo",
    "_legal_basis": "Art. 12 ust. 1 pkt 4 ustawy o ryczałcie",
    "_warnings": ["[P24-I2] Stawka ryczałtu 5,5%: produkcja, budownictwo z materiałami (PKD 41-43). Spójne z modułem budownictwo (VAT 8% osobno)."]
} {
    object.get(input.jdg_entrepreneur, "tax_form", "") == "RYCZALT"
    object.get(input.jdg_entrepreneur, "pkd_main", "") in {"41.10.Z", "41.20.Z", "42.11.Z", "43.11.Z", "43.31.Z"}
}

# jdg.p24.i2.r3: i2_rate_8_5pct_services
else := {
    "matched": true,
    "rule_id": "jdg.p24.i2.r3",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210012,
    "pit_rate": "0.085",
    "_routing_reason": "I2: Stawka ryczałtu 8,5% — usługi, handel, najem do 100k",
    "_legal_basis": "Art. 12 ust. 1 pkt 5 lit. a ustawy o ryczałcie",
    "_warnings": ["[P24-I2] Stawka ryczałtu 8,5%: pozostałe usługi, handel, najem do 100 000 zł. Dla najmu powyżej 100k: 12,5% (I2.r5)."]
} {
    object.get(input.jdg_entrepreneur, "tax_form", "") == "RYCZALT"
    object.get(input.jdg_entrepreneur, "ryczalt_rate_category", "") == "SERVICES"
}

# jdg.p24.i2.r4: i2_rate_12_5pct_freelance
else := {
    "matched": true,
    "rule_id": "jdg.p24.i2.r4",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210013,
    "pit_rate": "0.125",
    "_routing_reason": "I2: Stawka ryczałtu 12,5% — wolne zawody, leasing",
    "_legal_basis": "Art. 12 ust. 1 pkt 1-2 ustawy o ryczałcie",
    "_warnings": ["[P24-I2] Stawka ryczałtu 12,5%: wolne zawody (doradcy podatkowi, księgowi), leasing, niektóre usługi IT z doradztwem."]
} {
    object.get(input.jdg_entrepreneur, "tax_form", "") == "RYCZALT"
    object.get(input.jdg_entrepreneur, "ryczalt_rate_category", "") == "FREELANCE"
}

# jdg.p24.i2.r5: i2_rate_15pct_transport
else := {
    "matched": true,
    "rule_id": "jdg.p24.i2.r5",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210014,
    "pit_rate": "0.15",
    "_routing_reason": "I2: Stawka ryczałtu 15% — transport, rolnictwo, leśnictwo",
    "_legal_basis": "Art. 12 ust. 1 pkt 3 ustawy o ryczałcie",
    "_warnings": ["[P24-I2] Stawka ryczałtu 15%: transport drogowy, rolnictwo. Spójne z modułem transport (licencje) i plan33_tax_trans (podatek od środków)."]
} {
    object.get(input.jdg_entrepreneur, "tax_form", "") == "RYCZALT"
    object.get(input.jdg_entrepreneur, "ryczalt_rate_category", "") == "TRANSPORT"
}

# jdg.p24.i2.r6: i2_rate_17pct_domestic_services
else := {
    "matched": true,
    "rule_id": "jdg.p24.i2.r6",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210015,
    "pit_rate": "0.17",
    "_routing_reason": "I2: Stawka ryczałtu 17% — usługi dla gospodarstw domowych",
    "_legal_basis": "Art. 12 ust. 1 pkt 2 ustawy o ryczałcie",
    "_warnings": ["[P24-I2] Stawka ryczałtu 17%: usługi dla ludności, gospodarstw domowych. Limit: nie więcej niż 4 zatrudnionych."]
} {
    object.get(input.jdg_entrepreneur, "tax_form", "") == "RYCZALT"
    object.get(input.jdg_entrepreneur, "ryczalt_rate_category", "") == "DOMESTIC"
}

# jdg.p24.i2.r7: i2_rate_20pct_healthcare
else := {
    "matched": true,
    "rule_id": "jdg.p24.i2.r7",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210016,
    "pit_rate": "0.20",
    "_routing_reason": "I2: Stawka ryczałtu 20% — wolne zawody medyczne",
    "_legal_basis": "Art. 12 ust. 1 pkt 7 ustawy o ryczałcie",
    "_warnings": ["[P24-I2] Stawka ryczałtu 20%: lekarze, stomatolodzy, weterynarze. Najwyższa stawka ryczałtu."]
} {
    object.get(input.jdg_entrepreneur, "tax_form", "") == "RYCZALT"
    object.get(input.jdg_entrepreneur, "ryczalt_rate_category", "") == "HEALTHCARE"
}

# jdg.p24.i2.r8: i2_pkwiu_auto_mapper
else := {
    "matched": true,
    "rule_id": "jdg.p24.i2.r8",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210017,
    "_routing_reason": "I2: Mapowanie semantyczne PKD → stawka ryczałtu (auto-classifier)",
    "_legal_basis": "Art. 12 ustawy o ryczałcie — tabela PKWiU → stawka",
    "_warnings": ["[P24-I2] Mapowanie automatyczne: na podstawie symbolu PKD i opisu działalności przypisano stawkę ryczałtu. Zweryfikuj poprawność z tabelą PKWiU 2015."]
} {
    object.get(input.jdg_entrepreneur, "ryczalt_auto_classification_requested", false) == true
    object.get(input.jdg_entrepreneur, "tax_form", "") == "RYCZALT"
}

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  I4 — Construction Tax Auto-Calculator (5 reguł)                            ║
# ║  Kalkulator podatkowy budownictwa: VAT 8% vs 23%, RC, PCC, KSeF             ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# jdg.p24.i4.r1: i4_construction_vat_calculator
decide := {
    "matched": true,
    "rule_id": "jdg.p24.i4.r1",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210030,
    "vat_rate": "0.08",
    "_routing_reason": "I4: Budownictwo mieszkaniowe <= 300 m2 → VAT 8%",
    "_legal_basis": "Art. 41 ust. 12 VAT",
    "_warnings": ["[P24-I4] Kalkulator budowlany: usługa dla budynku mieszkalnego <= 300 m2 = VAT 8%. Weź pod uwagę usługę kompleksową (materiały + robocizna)."]
} {
    object.get(input.invoice, "service_category", "") == "CONSTRUCTION"
    object.get(input.invoice, "building_type", "") == "RESIDENTIAL"
    object.get(input.invoice, "usable_area_m2", 999999) <= 300
}

# jdg.p24.i4.r2: i4_construction_vat23_non_residential
else := {
    "matched": true,
    "rule_id": "jdg.p24.i4.r2",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210031,
    "vat_rate": "0.23",
    "_routing_reason": "I4: Budynek niemieszkalny → VAT 23%",
    "_legal_basis": "Art. 41 ust. 1 VAT",
    "_warnings": ["[P24-I4] Kalkulator budowlany: budynek niemieszkalny = VAT 23%. Sprawdź, czy nie ma reverse charge (I4.r3)."]
} {
    object.get(input.invoice, "service_category", "") == "CONSTRUCTION"
    object.get(input.invoice, "building_type", "") != "RESIDENTIAL"
}

# jdg.p24.i4.r3: i4_construction_reverse_charge_check
else := {
    "matched": true,
    "rule_id": "jdg.p24.i4.r3",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210032,
    "vat_rate": "0.00",
    "_routing_reason": "I4: B2B usługa budowlana → reverse charge (nabywca rozlicza VAT)",
    "_legal_basis": "Art. 17 ust. 1 pkt 8 VAT",
    "_warnings": ["[P24-I4] Reverse charge budowlany: między czynnymi podatnikami VAT. Faktura z adnotacją 'odwrotne obciążenie'. Spójne z budownictwo.a2."]
} {
    object.get(input.invoice, "service_category", "") == "CONSTRUCTION"
    object.get(input.counterparty, "is_vat_payer", false) == true
    input.jdg_entrepreneur.is_vat_payer == true
}

# jdg.p24.i4.r4: i4_construction_pcc_contract
else := {
    "matched": true,
    "rule_id": "jdg.p24.i4.r4",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210033,
    "_routing_reason": "I4: Umowa o roboty budowlane — PCC 1% od wartości (jeśli > 1000 zł i poza VAT)",
    "_legal_basis": "Art. 1 ust. 1 pkt 1 lit. a ustawy o PCC",
    "_warnings": ["[P24-I4] PCC od umowy budowlanej: jeśli umowa > 1000 zł i nie podlega VAT (np. z osobą prywatną), PCC 1% w ciągu 14 dni od zawarcia."]
} {
    object.get(input.contract, "construction_agreement_value", 0) > 1000
    object.get(input.contract, "vat_exempt", false) == true
    object.get(input.invoice, "pcc_paid", false) == false
}

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  I10 — Construction VAT Rate Auto-Classifier (4 reguły)                     ║
# ║  Klasyfikacja 8% vs 23% per rodzaj usługi budowlanej                        ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# jdg.p24.i10.r1: i10_classify_residential_renovation
decide := {
    "matched": true,
    "rule_id": "jdg.p24.i10.r1",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210050,
    "vat_rate": "0.08",
    "_routing_reason": "I10: Remont budynku mieszkalnego → VAT 8%",
    "_legal_basis": "Art. 41 ust. 12 VAT — remont mieszkaniowy",
    "_warnings": ["[P24-I10] Auto-klasyfikator: REMONT budynku mieszkalnego (<= 300 m2) = VAT 8%. Usługa kompleksowa (materiały + robocizna = 8%)."]
} {
    object.get(input.invoice, "service_scope", "") == "RENOVATION"
    object.get(input.invoice, "building_type", "") == "RESIDENTIAL"
}

# jdg.p24.i10.r2: i10_classify_modernization_check_area
else := {
    "matched": true,
    "rule_id": "jdg.p24.i10.r2",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210051,
    "vat_rate": "0.08",
    "_routing_reason": "I10: Modernizacja budynku mieszkalnego do 300 m2 → VAT 8%",
    "_legal_basis": "Art. 41 ust. 12 VAT",
    "_warnings": ["[P24-I10] Auto-klasyfikator: MODERNIZACJA budynku mieszkalnego <= 300 m2 = VAT 8%. Powyżej limitu = 23% (I10.r3)."]
} {
    object.get(input.invoice, "service_scope", "") == "MODERNIZATION"
    object.get(input.invoice, "building_type", "") == "RESIDENTIAL"
    object.get(input.invoice, "usable_area_m2", 999999) <= 300
}

# jdg.p24.i10.r3: i10_classify_over_limit
else := {
    "matched": true,
    "rule_id": "jdg.p24.i10.r3",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210052,
    "vat_rate": "0.23",
    "_routing_reason": "I10: Powierzchnia > 300 m2 → VAT 23% (utrata 8%)",
    "_legal_basis": "Art. 41 ust. 12b VAT — limit 300 m2",
    "_warnings": ["[P24-I10] Auto-klasyfikator: powierzchnia PRZEKRACZA 300 m2! Stawka 8% NIE ma zastosowania. Całość = VAT 23%."]
} {
    object.get(input.invoice, "building_type", "") == "RESIDENTIAL"
    object.get(input.invoice, "usable_area_m2", 0) > 300
}

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  I3 — Succession Readiness Scorecard (5 reguł)                              ║
# ║  Scoring gotowości sukcesyjnej JDG 0-100                                     ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# jdg.p24.i3.r1: i3_succession_scorecard_baseline
decide := {
    "matched": true,
    "rule_id": "jdg.p24.i3.r1",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210020,
    "succession_score": 0,
    "_routing_reason": "I3: Scoring sukcesyjny — wycena bazowa 0 pkt. Dodawaj punkty za poszczególne przygotowania.",
    "_legal_basis": "Ustawa o zarządzie sukcesyjnym (2018)",
    "_warnings": ["[P24-I3] Sukcesja Scorecard: Twoja gotowość sukcesyjna jest oceniana. Wynik 0-100. <30 = KRYTYCZNE, 30-60 = ŚREDNIE, >60 = DOBRE."]
} {
    object.get(input.jdg_entrepreneur, "succession_check_requested", false) == true
}

# jdg.p24.i3.r2: i3_succession_scorecard_will
else := {
    "matched": true,
    "rule_id": "jdg.p24.i3.r2",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210021,
    "succession_score_add": 30,
    "_routing_reason": "I3: Testament sporządzony → +30 pkt",
    "_legal_basis": "Art. 941-959 KC",
    "_warnings": ["[P24-I3] +30 pkt: Testament sporządzony. Dobrze! Zadbaj by był przechowywany w bezpiecznym miejscu."]
} {
    object.get(input.jdg_entrepreneur, "will_prepared", false) == true
}

# jdg.p24.i3.r3: i3_succession_scorecard_manager
else := {
    "matched": true,
    "rule_id": "jdg.p24.i3.r3",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210022,
    "succession_score_add": 25,
    "_routing_reason": "I3: Zarządca sukcesyjny wyznaczony → +25 pkt",
    "_legal_basis": "Art. 3 ustawy o zarządzie sukcesyjnym",
    "_warnings": ["[P24-I3] +25 pkt: Zarządca sukcesyjny wyznaczony. Upewnij się że osoba wyraziła zgodę na piśmie."]
} {
    object.get(input.jdg_entrepreneur, "succession_manager_nominated", false) == true
}

# jdg.p24.i3.r4: i3_succession_scorecard_insurance
else := {
    "matched": true,
    "rule_id": "jdg.p24.i3.r4",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210023,
    "succession_score_add": 15,
    "_routing_reason": "I3: Ubezpieczenie na życie / firmowe → +15 pkt",
    "_legal_basis": "Art. 808-821 KC — ubezpieczenia",
    "_warnings": ["[P24-I3] +15 pkt: Polisa na życie / ubezpieczenie firmy. Ważne dla płynności w okresie przejściowym."]
} {
    object.get(input.jdg_entrepreneur, "life_insurance_active", false) == true
}

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  I7 — Lump Sum vs Scale Decision Engine (5 reguł)                           ║
# ║  Silnik decyzyjny: porównanie obciążeń, rekomendacja formy opodatkowania    ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# jdg.p24.i7.r1: i7_recommend_lump_sum_low_costs
decide := {
    "matched": true,
    "rule_id": "jdg.p24.i7.r1",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210060,
    "recommended_tax_form": "RYCZALT",
    "_routing_reason": "I7: Rekomendacja RYCZAŁT — niskie koszty, wysoki przychód, stawka < 12%",
    "_legal_basis": "Art. 2, 6, 12 ustawy o ryczałcie",
    "_warnings": ["[P24-I7] DECYZJA: Ryczałt! Twoje koszty są niskie (<30% przychodu), a stawka ryczałtu (3-8,5%) niższa niż efektywna stawka na skali. Oszczędność: ~15% podatku."]
} {
    object.get(input.jdg_entrepreneur, "cost_to_revenue_ratio", 1.0) < 0.30
    object.get(input.jdg_entrepreneur, "ryczalt_effective_rate", 1.0) < 0.12
}

# jdg.p24.i7.r2: i7_recommend_scale_high_costs
else := {
    "matched": true,
    "rule_id": "jdg.p24.i7.r2",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210061,
    "recommended_tax_form": "SKALA",
    "_routing_reason": "I7: Rekomendacja SKALA PODATKOWA — wysokie koszty, ulgi, odliczenia",
    "_legal_basis": "Art. 26-27 ustawy o PIT",
    "_warnings": ["[P24-I7] DECYZJA: Skala podatkowa! Twoje koszty są wysokie (>60% przychodu), co daje niską podstawę opodatkowania. Dodatkowo możesz skorzystać z ulg (internet, rehabilitacja, termo)."]
} {
    object.get(input.jdg_entrepreneur, "cost_to_revenue_ratio", 0.0) > 0.60
}

# jdg.p24.i7.r3: i7_recommend_estonian_cit_reinvestment
else := {
    "matched": true,
    "rule_id": "jdg.p24.i7.r3",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210062,
    "recommended_tax_form": "ESTONSKI_CIT",
    "_routing_reason": "I7: Rekomendacja ESTOŃSKI CIT — wysoka reinwestycja zysku",
    "_legal_basis": "Art. 28c-28t CIT (estoński CIT dla JDG od 2024)",
    "_warnings": ["[P24-I7] DECYZJA: Estoński CIT! Planujesz reinwestować >80% zysku. Brak podatku od zatrzymanego zysku. PIT dopiero przy dystrybucji (dywidendzie)."]
} {
    object.get(input.jdg_entrepreneur, "reinvestment_ratio", 0.0) > 0.80
    object.get(input.jdg_entrepreneur, "employees_count", 0) >= 3
}

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  I8 — Unregistered Activity Detector (4 reguły)                             ║
# ║  Wykrywanie działalności nieewidencjonowanej (a5 PP)                         ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# jdg.p24.i8.r1: i8_unregistered_detector_limit_check
decide := {
    "matched": true,
    "rule_id": "jdg.p24.i8.r1",
    "_routing": "",
    "package": "jdg.p24.innovations",
    "priority": 210070,
    "_routing_reason": "I8: Monitorowanie limitu działalności nieewidencjonowanej (75% płacy min.)",
    "tiny_activity_limit_pln": 3499.50,
    "tiny_activity_min_wage_ratio": 0.75,
    "_legal_basis": "Art. 5 ustawy — Prawo przedsiębiorców",
    "_warnings": ["[P24-I8] Monitor nieewidencjonowanej: limit 75% płacy minimalnej = ~3 499,50 zł/mies. (2025). Wartość aktualizowana rocznie wraz ze zmianą płacy minimalnej."]
} {
    object.get(input.jdg_entrepreneur, "tiny_activity_active", false) == true
}

# jdg.p24.i8.r2: i8_unregistered_detector_warning_80pct
else := {
    "matched": true,
    "rule_id": "jdg.p24.i8.r2",
    "package": "jdg.p24.innovations",
    "priority": 210071,
    "_routing": "BLOCK_AND_ALERT",
    "_routing_reason": "I8: OSTRZEŻENIE — osiągnięto 80% limitu nieewidencjonowanej",
    "_legal_basis": "Art. 5 ust. 1 ustawy — Prawo przedsiębiorców",
    "_warnings": ["[P24-I8] UWAGA: Osiągasz 80% limitu działalności nieewidencjonowanej! Przy przekroczeniu 75% płacy minimalnej MUSISZ zarejestrować się w CEIDG."]
} {
    object.get(input.jdg_entrepreneur, "monthly_revenue_pln", 0) > 2799.60
    object.get(input.jdg_entrepreneur, "monthly_revenue_pln", 0) <= 3499.50
}

# jdg.p24.i8.r3: i8_unregistered_detector_limit_exceeded
else := {
    "matched": true,
    "rule_id": "jdg.p24.i8.r3",
    "package": "jdg.p24.innovations",
    "priority": 210072,
    "_routing": "BLOCK_AND_ALERT",
    "_routing_reason": "I8: PRZEKROCZENIE limitu nieewidencjonowanej — obowiązek wpisu CEIDG!",
    "_legal_basis": "Art. 5 ust. 2 ustawy — Prawo przedsiębiorców",
    "_warnings": ["[P24-I8] ALARM: Przekroczyłeś limit 75% płacy minimalnej! NATYCHMIAST złóż wniosek CEIDG-1. Prowadzenie działalności bez wpisu = wykroczenie KKS (kara do 5 000 zł)."]
} {
    object.get(input.jdg_entrepreneur, "monthly_revenue_pln", 0) > 3499.50
    object.get(input.jdg_entrepreneur, "tiny_activity_active", false) == true
    object.get(input.jdg_entrepreneur, "ceidg_registered", false) == false
}
