// Katalog produktow - chemia gospodarcza
// Ikony rysowane sa we frontendzie (SVG), tu definiujemy typ i kolor.
// ceny w PLN (liczby - NIGDY nie ufamy cenie z klienta, liczona tez po stronie serwera)

export const KATEGORIE = [
  { id: "wszystkie", nazwa: "Wszystkie" },
  { id: "pranie", nazwa: "Pranie" },
  { id: "naczynia", nazwa: "Naczynia" },
  { id: "powierzchnie", nazwa: "Powierzchnie" },
  { id: "lazienka", nazwa: "Łazienka" },
  { id: "dezynfekcja", nazwa: "Dezynfekcja" },
  { id: "akcesoria", nazwa: "Akcesoria" },
];

export const PRODUKTY = [
  {
    id: "p01",
    nazwa: "Mydło w płynie Czysta Dłoń 500 ml",
    kategoria: "dezynfekcja",
    cena: 7.99,
    ikonka: "pompka",
    kolor: "#4fc3f7",
    opis: "Delikatne mydło antybakteryjne z gliceryną.",
  },
  {
    id: "p02",
    nazwa: "Płyn do naczyń BąbelEkspert cytryna 900 ml",
    kategoria: "naczynia",
    cena: 9.49,
    ikonka: "butelka",
    kolor: "#ffd54f",
    opis: "Skutecznie odtłuszcza, wydajna formuła.",
  },
  {
    id: "p03",
    nazwa: "Proszek do prania Biel Aktywna 3 kg",
    kategoria: "pranie",
    cena: 24.99,
    ikonka: "kartonik",
    kolor: "#90a4ae",
    opis: "Białe pranie już od 30°C, 60 prań.",
  },
  {
    id: "p04",
    nazwa: "Płyn do płukania Miękki Puch lawenda 1,5 L",
    kategoria: "pranie",
    cena: 12.99,
    ikonka: "butelka",
    kolor: "#b39ddb",
    opis: "Trwały zapach i miękkość tkanin.",
  },
  {
    id: "p05",
    nazwa: "Płyn do podłóg Lśniący Dom 1 L",
    kategoria: "powierzchnie",
    cena: 8.99,
    ikonka: "kanister",
    kolor: "#81c784",
    opis: "Do paneli, płytek i parkietu. Bez smug.",
  },
  {
    id: "p06",
    nazwa: "Płyn do szyb KrystalView 500 ml",
    kategoria: "powierzchnie",
    cena: 6.49,
    ikonka: "spray",
    kolor: "#4dd0e1",
    opis: "Szybkie odparowanie, lustrzany połysk.",
  },
  {
    id: "p07",
    nazwa: "Wybielacz Biała Siła 1 L",
    kategoria: "dezynfekcja",
    cena: 5.99,
    ikonka: "kanister",
    kolor: "#e0e0e0",
    opis: "Usuwa plamy i bakterie. Uwaga: środki ochrony.",
  },
  {
    id: "p08",
    nazwa: "Płyn do WC Moc Żelu 750 ml",
    kategoria: "lazienka",
    cena: 7.49,
    ikonka: "butelka",
    kolor: "#4db6ac",
    opis: "Gęsty żel, usuwa kamień i osady.",
  },
  {
    id: "p09",
    nazwa: "Ściereczki uniwersalne 3 szt.",
    kategoria: "akcesoria",
    cena: 4.99,
    ikonka: "chusteczki",
    kolor: "#f48fb1",
    opis: "Microfibra - bez smug na każdej powierzchni.",
  },
  {
    id: "p10",
    nazwa: "Gąbki do naczyń 5 szt.",
    kategoria: "akcesoria",
    cena: 3.99,
    ikonka: "gabka",
    kolor: "#ff8a65",
    opis: "Warstwa szorująca, długo zachowują formę.",
  },
  {
    id: "p11",
    nazwa: "Płyn dezynfekujący do rąk 300 ml",
    kategoria: "dezynfekcja",
    cena: 8.49,
    ikonka: "pompka",
    kolor: "#a5d6a7",
    opis: "70% alkoholu, z pantenolem.",
  },
  {
    id: "p12",
    nazwa: "Kapsuły do prania Max Kolor 30 szt.",
    kategoria: "pranie",
    cena: 29.99,
    ikonka: "kapsula",
    kolor: "#7986cb",
    opis: "3 w 1: pranie, plamy, świeżość.",
  },
  {
    id: "p13",
    nazwa: "Odświeżacz powietrza Aero Fresh 300 ml",
    kategoria: "lazienka",
    cena: 9.99,
    ikonka: "spray",
    kolor: "#ce93d8",
    opis: "Natychmiastowa świeżość, neutralizuje zapachy.",
  },
  {
    id: "p14",
    nazwa: "Zestaw Start: płyn + gąbki + ściereczki",
    kategoria: "naczynia",
    cena: 15.99,
    ikonka: "kartonik",
    kolor: "#ffb74d",
    opis: "Pakiet ekonomiczny na start.",
  },
];

export const MAPA_PRODUKTOW = new Map(PRODUKTY.map((p) => [p.id, p]));
