# ═══════════════════════════════════════════════════════════════════════════════
# NexusAI JDG Policies — Corrections: Korekty faktur i deklaracji (R0420-R0435)
# Doc 28a Enterprise — 16 reguł kanonicznych
# ═══════════════════════════════════════════════════════════════════════════════
package jdg.corrections
import data.jdg.helpers
default decide := {"matched":false,"rule_id":"jdg.corrections.no_match","package":"jdg.corrections","priority":439}

# R0420: correction_invoice_in_minus — Faktura korygująca in minus
decide := {"matched":true,"rule_id":"jdg.corrections.invoice_in_minus","package":"jdg.corrections","priority":420,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","correction_type":"IN_MINUS","correction_period":"BUYER_RECEIPT_DATE","_routing":"","_routing_reason":"","_legal_basis":"Art. 106j VAT","_warnings":["KOREKTA IN MINUS — ujmij w okresie otrzymania potwierdzenia odbioru przez nabywcę. Sprzedawca: zmniejszenie podstawy. Nabywca: zmniejszenie odliczenia."]} { input.invoice.document_type == "CORRECTION_INVOICE"; input.invoice.correction_direction == "DECREASE" }

# R0421: correction_invoice_in_plus — Faktura korygująca in plus
else := {"matched":true,"rule_id":"jdg.corrections.invoice_in_plus","package":"jdg.corrections","priority":421,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","correction_type":"IN_PLUS","correction_period":"ORIGINAL_INVOICE_PERIOD","_routing":"","_routing_reason":"","_legal_basis":"Art. 106j VAT","_warnings":["KOREKTA IN PLUS — ujmij wstecznie w okresie pierwotnej faktury (jeśli przyczyna istniała w dniu wystawienia). W przeciwnym razie: bieżący okres."]} { input.invoice.document_type == "CORRECTION_INVOICE"; input.invoice.correction_direction == "INCREASE" }

# R0422: correction_vat_declaration_period — Korekta deklaracji VAT
else := {"matched":true,"rule_id":"jdg.corrections.vat_declaration_period","package":"jdg.corrections","priority":422,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","correction_declaration":"VAT","correction_file":"JPK_V7K","_routing":"","_routing_reason":"","_legal_basis":"Art. 81 OrdPU","_warnings":["KOREKTA DEKLARACJI VAT — złóż JPK_V7K z korektą. Dopłata: + odsetki od pierwotnego terminu. Nadpłata: zwrot w 45 dni."]} { input.invoice.is_declaration_correction == true; input.invoice.tax_type == "VAT" }

# R0423: correction_jpk_v7_storno — Storno w JPK_V7
else := {"matched":true,"rule_id":"jdg.corrections.jpk_v7_storno","package":"jdg.corrections","priority":423,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","correction_method":"STORNO","jpk_field":"KOREKTA_PODSTAWY_OPODATKOWANIA","_routing":"","_routing_reason":"","_legal_basis":"Art. 109 ust. 3b VAT","_warnings":["KOREKTA JPK_V7 — storno w polu K_15/K_16 (zmniejszenie) lub K_17/K_18 (zwiększenie). Oznacz przyczynę korekty."]} { input.invoice.is_jpk_correction == true }

# R0424: correction_statute_limitations — Przedawnienie korekty
else := {"matched":true,"rule_id":"jdg.corrections.statute_limitations","package":"jdg.corrections","priority":424,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","correction_deadline_years":5,"correction_allowed":within_limits,"_routing":routing_flag,"_routing_reason":routing_reason,"_legal_basis":"Art. 70, 81 OrdPU","_warnings":[sprintf("PRZEDAWNIENIE KOREKTY — %s. Zobowiązanie z %s: termin korekty upływa %s. Po terminie: korekta niedopuszczalna!",[limit_info, tax_year, deadline])]} { input.invoice.is_correction == true; tax_year:=object.get(input.invoice,"tax_year","");tax_year!="";deadline:=sprintf("%d-12-31",[to_number(tax_year)+5]);is_overdue:=deadline<"2026-12-31";within_limits=not is_overdue;routing_flag=""{within_limits==true};routing_flag="BLOCK_AND_ALERT"{within_limits==false};routing_reason=""{within_limits==true};routing_reason="Przedawnienie — korekta NIEDOPUSZCZALNA"{within_limits==false};limit_info="W terminie (do "+deadline+")"{within_limits==true};limit_info="PO TERMINIE — przedawnione!"{within_limits==false} }

# R0425: correction_interest_calculation — Odsetki od korekty
else := {"matched":true,"rule_id":"jdg.corrections.interest_calculation","package":"jdg.corrections","priority":425,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","correction_interest_due":true,"correction_interest_rate_pct":interest_pct,"_routing":"TRIAGE_QUEUE","_routing_reason":"Korekta + odsetki — dopłata po terminie","_legal_basis":"Art. 53-56 OrdPU","_warnings":[sprintf("ODSETKI OD KOREKTY — %.2f PLN × %.1f%% × %d dni = %.2f PLN. Nalicz od pierwotnego terminu płatności do dnia wpłaty.",[amount,interest_pct,days_late,interest_amount])]} { input.invoice.is_correction_in_plus==true;input.invoice.payment_overdue==true;days_late:=object.get(input.invoice,"days_overdue",0);days_late>0;amount:=object.get(input.invoice,"amount_net",0);interest_pct:=object.get(object.get(object.get(data.thresholds,"jdg",{}),"bounds",{}),"tax_interest_rate",14.5);interest_amount:=floor(amount*interest_pct/100*days_late/365*100)/100 }

# R0426: correction_pit_advance — Korekta zaliczki PIT
else := {"matched":true,"rule_id":"jdg.corrections.pit_advance","package":"jdg.corrections","priority":426,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","correction_type":"PIT_ADVANCE","correction_method":"AMEND_PREVIOUS_MONTHS","_routing":"","_routing_reason":"","_legal_basis":"Art. 44 PIT","_warnings":["KOREKTA ZALICZKI PIT — skoryguj zaliczki za poprzednie miesiące w zeznaniu rocznym. Nie składaj korekt miesięcznych — rozlicz wszystko w PIT-36/PIT-36L/PIT-28."]} { input.invoice.tax_type=="PIT";input.invoice.is_advance_correction==true }

# R0427: correction_zus_base — Korekta podstawy ZUS
else := {"matched":true,"rule_id":"jdg.corrections.zus_base","package":"jdg.corrections","priority":427,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","correction_type":"ZUS_BASE","correction_document":"DRA_KOREKTA","_routing":"TRIAGE_QUEUE","_routing_reason":"Korekta podstawy ZUS — złóż DRA korygującą","_legal_basis":"Art. 47 SUS","_warnings":["KOREKTA ZUS — skoryguj deklarację DRA. Dopłata składek: + odsetki. Nadpłata: wniosek o zwrot do ZUS (ZUS nie zwraca automatycznie!)."]} { input.invoice.is_zus_correction==true }

# R0428: correction_invoice_numbering — Ciągłość numeracji korekt
else := {"matched":true,"rule_id":"jdg.corrections.invoice_numbering","package":"jdg.corrections","priority":428,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","numbering_continuity":true,"expected_next":expected,"actual":actual,"_routing":"BLOCK_AND_ALERT","_routing_reason":"Numeracja faktur — brak ciągłości","_legal_basis":"Art. 106e ust. 1 pkt 2 VAT","_warnings":[sprintf("CIĄGŁOŚĆ NUMERACJI — oczekiwano %s, otrzymano %s. Luka w numeracji faktur! Sprawdź czy nie brakuje faktury.",[expected,actual])]} { input.invoice.document_type=="CORRECTION_INVOICE";expected:=object.get(input.invoice,"expected_invoice_number","");actual:=object.get(input.invoice,"invoice_number","");expected!=actual;expected!="" }

# R0429-R0435: Korekty zbiorcze i szczególne
else := {"matched":true,"rule_id":"jdg.corrections.collective_correction","package":"jdg.corrections","priority":429,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","collective_correction":true,"_routing":"","_routing_reason":"","_legal_basis":"Art. 106j ust. 3 VAT","_warnings":["KOREKTA ZBIORCZA — dopuszczalna dla wielu faktur. Zawieraj: okres, którego dotyczy + łączną kwotę korekty + przyczynę."]} { input.invoice.is_collective_correction==true }

else := {"matched":true,"rule_id":"jdg.corrections.bad_debt_correction","package":"jdg.corrections","priority":430,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","bad_debt_correction":true,"creditor_correction":"VAT_DECREASE","debtor_correction":"VAT_INCREASE","_routing":"TRIAGE_QUEUE","_routing_reason":"Korekta złe długi — ulga + obowiązek","_legal_basis":"Art. 89a-89b VAT","_warnings":["KOREKTA ZŁE DŁUGI — wierzyciel: zmniejszenie VAT po 90 dniach. Dłużnik: OBOWIĄZEK zwiększenia VAT po 90 dniach (30% sankcji za brak!)."]} { input.invoice.is_bad_debt_correction==true }

else := {"matched":true,"rule_id":"jdg.corrections.annual_correction","package":"jdg.corrections","priority":431,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","annual_vat_correction":true,"correction_type":"PROPORTION_UPDATE","_routing":"","_routing_reason":"","_legal_basis":"Art. 91 VAT","_warnings":["KOREKTA ROCZNA VAT — aktualizacja proporcji odliczeń. Rzeczywista proporcja ≠ szacunkowa >2pp → korekta w JPK_V7 za styczeń."]} { input.invoice.is_annual_proportion_correction==true }

else := {"matched":true,"rule_id":"jdg.corrections.fixed_asset_correction","package":"jdg.corrections","priority":432,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","fixed_asset_correction":true,"correction_period_years":correction_years,"_routing":"","_routing_reason":"","_legal_basis":"Art. 91 ust. 2 VAT","_warnings":[sprintf("KOREKTA ŚRODKÓW TRWAŁYCH — %d-letni okres korekty (nieruchomości: 10 lat, ruchomości >15k: 5 lat). Coroczna korekta 1/%d VAT.",[correction_years,correction_years])]} { input.invoice.is_fixed_asset_correction==true;asset_type:=object.get(input.invoice,"asset_type","");correction_years=10{asset_type=="REAL_ESTATE"};correction_years=5{asset_type!="REAL_ESTATE"} }

else := {"matched":true,"rule_id":"jdg.corrections.cross_border_correction","package":"jdg.corrections","priority":433,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","cross_border_correction":true,"_routing":"TRIAGE_QUEUE","_routing_reason":"Korekta VAT-UE / WNT/WDT","_legal_basis":"Art. 103 VAT","_warnings":["KOREKTA TRANSGRANICZNA — skoryguj VAT-UE w ciągu 14 dni od faktury korygującej. Dotyczy WNT, WDT, usług UE."]} { input.invoice.is_cross_border_correction==true }

else := {"matched":true,"rule_id":"jdg.corrections.correction_overpayment","package":"jdg.corrections","priority":434,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","overpayment_detected":true,"overpayment_refund_days":45,"_routing":"","_routing_reason":"","_legal_basis":"Art. 78 OrdPU","_warnings":[sprintf("NADPŁATA — %.2f PLN. US zwraca w 45 dni (+ odsetki po terminie). Możesz zaliczyć na przyszłe zobowiązania.",[overpayment_amount])]} { overpayment_amount:=object.get(input.invoice,"overpayment_amount",0);overpayment_amount>0 }

else := {"matched":true,"rule_id":"jdg.corrections.correction_underpayment","package":"jdg.corrections","priority":435,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","underpayment_detected":true,"underpayment_interest":interest_due,"_routing":"BLOCK_AND_ALERT","_routing_reason":"Niedopłata — ureguluj natychmiast!","_legal_basis":"Art. 53 OrdPU","_warnings":[sprintf("NIEDOPŁATA — %.2f PLN + odsetki %.2f PLN. Zapłać natychmiast! Każdy dzień zwłoki zwiększa odsetki.",[underpayment_amount,interest_due])]} { underpayment_amount:=object.get(input.invoice,"underpayment_amount",0);underpayment_amount>0;days_late := object.get(input.invoice, "days_overdue", 0); interest_rate := object.get(object.get(object.get(data.thresholds, "jdg", {}), "bounds", {}), "tax_interest_rate", 14.5); interest_due := floor(underpayment_amount * interest_rate / 100 * days_late / 365 * 100) / 100 }

# P180: correction_lock_during_audit — Zakaz korekty w trakcie kontroli (Doc 35)
else := {"matched":true,"rule_id":"jdg.corrections.lock_during_audit","package":"jdg.corrections","priority":180,"vat_rate":"","rounding_level":"","gtu_code":"","pit_form":"","pit_rate":"","pit_bracket":"","pit_annual_return_type":"","kus_qualification":"","kus_percent":0,"zus_social_base_type":"","zus_health_rate":"","business_status":"","correction_blocked":true,"block_reason":"TAX_AUDIT_IN_PROGRESS","_routing":"BLOCK_AND_ALERT","_routing_reason":"Korekta zablokowana — trwa kontrola podatkowa","_legal_basis":"Art. 81b § 1 Ordynacji podatkowej","_warnings":["KOREKTA ZABLOKOWANA — trwa kontrola celno-skarbowa. Korekta deklaracji NIEDOPUSZCZALNA do czasu zakończenia kontroli."]} { object.get(input.jdg_entrepreneur,"tax_audit_in_progress",false)==true; input.invoice.is_correction==true }
